tools/bwa/index/main.nf, tools/bwa/index/meta.yml, tools/bwa/index/test/main.nf, tools/bwa/index/test/nextflow.config, tools/gatk/dict/main.nf, tools/gatk/dict/meta.yml, tools/gatk/dict/test/main.nf, tools/gatk/dict/test/nextflow.config, tools/htslib/tabix/main.nf, tools/htslib/tabix/meta.yml, tools/htslib/tabix/test/main.nf, tools/htslib/tabix/test/nextflow.config, tools/samtools/faidx/main.nf, tools/samtools/faidx/meta.yml, tools/samtools/faidx/test/main.nf, tools/samtools/faidx/test/nextflow.config, tools/samtools/index/main.nf, tools/samtools/index/meta.yml
- Add bwa index
- Add gatk dict
- Add htslib tabix
- Add samtools faidx
- Fix samtools index
=> Add some modules

README.md
See above changes to readme :_)
=> Propose module organization

tools/shovill/main.nf, tools/shovill/meta.yml, tools/shovill/test/main.nf, tools/shovill/test/nextflow.config
Added module for shovill.
Suggested test dataset: https://www.ebi.ac.uk/ena/browser/view/SRR3609257
=> initial commit of shovill

.github/workflows/tcoffee.yml, tools/tcoffee/main.nf, tools/tcoffee/meta.yml, tools/tcoffee/test/main.nf, tools/tcoffee/test/nextflow.config
=> Adding tcoffee submodule

tools/fastq_screen/main.nf, tools/fastq_screen/meta.yml, tools/fastq_screen/test/main.nf, tools/fastq_screen/test/nextflow.config
Needs some work, and a test workflow.
=> Added FastQ Screen module

tools/fastqc/main.nf, tools/fastqc/meta.yml, tools/fastqc/test/main.nf, tools/fastqc/test/nextflow.config
Updated the FastQC module to work with passing over several arguments from the workflow to the (atomic) module. All seems to be working and publishing fine.
=> FastQC module is working and now accepting arguments

.github/workflows/fastqc.yml, software/fastqc/test/main.nf
Added a method to expand unit testing by validating the output of the Nextflow module process
=> add FastQC output validation and md5 checksum hash checks

.github/workflows/bwa_index.yml, .github/workflows/bwa_mem.yml, .github/workflows/fastqc.yml, .github/workflows/multiqc.yml, .github/workflows/picard_collectmultiplemetrics.yml, .github/workflows/picard_markduplicates.yml, .github/workflows/picard_mergesamfiles.yml, .github/workflows/samtools_flagstat.yml, .github/workflows/samtools_idxstats.yml, .github/workflows/samtools_index.yml, .github/workflows/samtools_sort.yml, .github/workflows/samtools_stats.yml, .github/workflows/trimgalore.yml
=> Support multiple nextflow versions in CI

.github/workflows/phantompeakqualtools.yml, tests/software/phantompeakqualtools/main.nf, tests/software/phantompeakqualtools/test.yml
I've updated the testing (workflow/main.nf/test.yml) for the Phantompeakqualtools module to follow the pytest-workflow format - this addresses #98.
Please let me know if there is anything which needs to be fixed!
=> Add testing for Phantompeakqualtools 

.github/workflows/ucsc_bedgraphtobigwig.yml, tests/software/ucsc/main.nf, tests/software/ucsc/test.yml
Added testing for UCSC module - the input files are loaded from https://github.com/igvteam/igv.js/.
Closes #107 
@Emiller88
=> Added testing for UCSC_BEDGRAPHTOBIGWIG

.github/workflows/gffread.yml, tests/data/gff/a.gff3, tests/software/gffread/main.nf, tests/software/gffread/test.yml
Completed testing for gffread - changes other than the necessary testing files include a new input file and folder (a.gff3, converted from a.bed using rtracklayer). Please let me know if the input file needs to be changed or taken from another repository (similar to the preseq test).
Closes #94 
@Emiller88
=> Add testing for gffread 

.github/workflows/star_align.yml, .github/workflows/star_genomegenerate.yml, software/star/align/main.nf, software/star/align/meta.yml, software/star/genomegenerate/meta.yml, tests/software/star/main.nf, tests/software/star/test.yml
Adding tests and `meta.yml` files for `star align` and `star genomegenerate` processes #103 
Some things to note:
I've added new test data, because no GTF was available and I couldn't find a GTF that works with the available genomes and reads. The data I added is unfortunately a bit on the bigger side (~10MB all in all I think). Am happy to use different datasets if you can point me to some.
Unfortunately, with the current set of data, STAR also doesn't align anything. I don't think this makes the tests any less valid but it would of course be nice to have a few aligned reads.
As discussed in Slack, I adapted the `star_align` process to emit BAM files by default. I had to do a few more adjustments:
To add BAM output as default but keep this still as an option, I've added the following …
=> Adding test for STAR

.github/workflows/bowtie2_align.yml, .github/workflows/bowtie2_build.yml, tests/software/bowtie2/test.yml
Adding missing github actions workflow yml missing in the previous PR as discussed [here](https://github.com/nf-core/modules/pull/127#issuecomment-770212266)
=> Bowtie2 viralrecon 2

.github/workflows/fastp.yml, software/fastp/functions.nf, software/fastp/main.nf, software/fastp/meta.yml, tests/software/fastp/main.nf, tests/software/fastp/test.yml
=> Adding fastp module

software/bwa/index/main.nf
Use container from quay.io.
This `biocontainers/bwa:v0.7.17_cv1` is not working for me.
=> Update bwa/index container

README.md
@KevinMenden I'll let you add how to use all of your `nf-core modules` tools when they get merged.
=> Add documentation for Testing

README.md
Follow up to #152 because it got merged before I woke up.
=> docs: Update README with minor edits

.github/filters.yml, software/gunzip/functions.nf, software/gunzip/main.nf, software/gunzip/meta.yml, tests/software/gunzip/main.nf, tests/software/gunzip/test.yml
Adding `gunzip` module as discussed [here](https://github.com/nf-core/viralrecon/issues/149)
=> Add gunzip module

.github/filters.yml, software/blast/makeblastdb/functions.nf, software/blast/makeblastdb/main.nf, software/blast/makeblastdb/meta.yml, tests/software/blast/makeblastdb/main.nf, tests/software/blast/makeblastdb/test.yml
Adding the `blast-makeblastdb` module as discussed [here](https://github.com/nf-core/viralrecon/issues/149)
=> Add blast makeblastdb module

.github/filters.yml, software/blast/blastn/functions.nf, software/blast/blastn/main.nf, software/blast/blastn/meta.yml, tests/software/blast/blastn/main.nf, tests/software/blast/blastn/test.yml
Adding the `blast-blastn` module as discussed [here](https://github.com/nf-core/viralrecon/issues/149)
=> Add blast blastn module

.github/filters.yml, software/bedtools/getfasta/functions.nf, software/bedtools/getfasta/main.nf, software/bedtools/getfasta/meta.yml, tests/software/bedtools/getfasta/main.nf, tests/software/bedtools/getfasta/test.yml, tests/software/bedtools/maskfasta/main.nf
Adding the `bedtools-getfasta` module as discussed [here](https://github.com/nf-core/viralrecon/issues/149)
=> Add bedtools getfasta module

software/bcftools/bgzip/main.nf, software/bcftools/filter/main.nf, software/bcftools/isec/main.nf, software/bcftools/stats/main.nf, software/bcftools/tabix/main.nf, software/blast/blastn/main.nf, software/blast/makeblastdb/main.nf
Some modules did not have the Conda build id as spotted by @drpatelh on https://github.com/nf-core/modules/pull/161
=> Add conda build id

.github/filters.yml, software/cat/fastq/functions.nf, software/cat/fastq/main.nf, software/cat/fastq/meta.yml, tests/software/cat/fastq/main.nf, tests/software/cat/fastq/test.yml
Tests (`pytest`) are not being launched maybe you can spot why.
=> Add cat fastq module

.github/filters.yml, software/mosdepth/functions.nf, software/mosdepth/main.nf, software/mosdepth/meta.yml, tests/software/mosdepth/main.nf, tests/software/mosdepth/test.yml
Add `mosdepth` module as mentioned [here](https://github.com/nf-core/viralrecon/issues/149)
=> Add mosdepth module

.github/filters.yml, software/samtools/faidx/functions.nf, software/samtools/faidx/main.nf, software/samtools/faidx/meta.yml, tests/software/samtools/faidx/main.nf, tests/software/samtools/faidx/test.yml
Continuation of https://github.com/nf-core/modules/pull/129 , this time as separate PRs
=> add samtools/faidx + tests

.github/filters.yml, software/qualimap/bamqc/functions.nf, software/qualimap/bamqc/main.nf, software/qualimap/bamqc/meta.yml, tests/software/qualimap/bamqc/main.nf, tests/software/qualimap/bamqc/test.yml
=> add qualimap/bamqc + test

.github/filters.yml, software/bismark/genome_preparation/functions.nf, software/bismark/genome_preparation/main.nf, software/bismark/genome_preparation/meta.yml, tests/software/bismark/genome_preparation/main.nf, tests/software/bismark/genome_preparation/test.yml
=> add bismark/genome_preparation + test

.github/filters.yml, software/gatk4/samtofastq/functions.nf, software/gatk4/samtofastq/main.nf, software/gatk4/samtofastq/meta.yml, tests/software/gatk4/samtofastq/main.nf, tests/software/gatk4/samtofastq/test.yml
Added `gatk4 SamToFastq` 
https://github.com/nf-core/modules/issues/226
=> added gatk4 SamToFastq

.github/filters.yml, software/gatk4/revertsam/functions.nf, software/gatk4/revertsam/main.nf, software/gatk4/revertsam/meta.yml, tests/software/gatk4/revertsam/main.nf, tests/software/gatk4/revertsam/test.yml
Adding the `gatk4 revertsam` module.
https://github.com/nf-core/modules/issues/233
=> Added GATK4 Revertsam

.github/filters.yml, software/bcftools/mpileup/functions.nf, software/bcftools/mpileup/main.nf, software/bcftools/mpileup/meta.yml, tests/software/bcftools/mpileup/main.nf, tests/software/bcftools/mpileup/test.yml
Add `bcftools_mpileup` module as listed [here](https://github.com/nf-core/viralrecon/issues/149).
=> Add bcftools mpileup module

software/bcftools/consensus/main.nf, software/bcftools/filter/main.nf, software/bcftools/isec/main.nf, software/bcftools/merge/main.nf, software/bcftools/merge/meta.yml, software/bcftools/mpileup/meta.yml, software/bcftools/stats/main.nf
Add resource `label` to `bcftools` processes and fix `yml`
=> Add missing requirements to bcftools modules

software/cutadapt/main.nf
Fix conda version declaration of cutadapt module
=> Fix conda version declaration of cutadapt module

software/ivar/consensus/main.nf, software/ivar/trim/main.nf, software/ivar/variants/main.nf
=> Update software version command for all iVar tools

tests/software/tiddit/sv/main.nf, tests/software/tiddit/sv/test.yml
=> fix tiddit_sv tests

software/bismark/deduplicate/main.nf, software/bismark/genome_preparation/main.nf, software/cat/fastq/main.nf, software/gffread/main.nf, software/gunzip/main.nf, software/hisat2/build/main.nf, software/hisat2/extractsplicesites/main.nf, software/samtools/flagstat/main.nf, software/samtools/idxstats/main.nf, software/samtools/index/main.nf, software/samtools/stats/main.nf, software/samtools/view/main.nf, software/tabix/bgzip/main.nf, software/untar/main.nf
=> Fix nf-core modules lint tests

software/dsh/filterbed/main.nf, software/dsh/splitbed/main.nf
=> Update dsh-bio to 2.0.3

software/spades/functions.nf, software/spades/main.nf, software/spades/meta.yml, tests/config/pytest_software.yml, tests/software/spades/main.nf, tests/software/spades/test.yml
Add spades module as a requirement of nfcore/viralrecon DSL2 implementation as listed [here](https://github.com/nf-core/viralrecon/issues/149)
=> Add spades module

.github/ISSUE_TEMPLATE/new_module.md, README.md
=> feature: add new issue template for creating new module

software/samtools/merge/functions.nf, software/samtools/merge/main.nf, tests/config/nextflow.config, tests/config/pytest_software.yml, tests/software/samtools/merge/main.nf, tests/software/samtools/merge/test.yml
Hi, I left out the md5sum of the output because for some reason it changes from one test run to another.
=> add samtools merge

software/unicycler/functions.nf, software/unicycler/main.nf, software/unicycler/meta.yml, tests/config/pytest_software.yml, tests/software/unicycler/main.nf, tests/software/unicycler/test.yml
Add unicycler module as a requirement of nfcore/viralrecon DSL2 implementation as listed [here](https://github.com/nf-core/viralrecon/issues/149)
=> Adding unicycler module

tests/software/tiddit/sv/main.nf
=> remove unnecessary call to module in tiddit_sv module

software/gatk4/fastqtosam/functions.nf, software/gatk4/fastqtosam/main.nf, software/gatk4/fastqtosam/meta.yml, tests/config/pytest_software.yml, tests/software/gatk4/fastqtosam/main.nf, tests/software/gatk4/fastqtosam/test.yml
=> add gatk4/fastqtosam #198

README.md
=> Add docs for running tests locally with pytest

software/samtools/fastq/main.nf, software/samtools/fastq/meta.yml, tests/software/samtools/fastq/test.yml
Modified the module samtools/fastq to get compressed fastq.gz output.
Closes #289 
Closes #316   
=> modified the samtools/fastq module

README.md, software/bowtie/build/main.nf, software/bowtie2/build/main.nf, software/bwa/index/main.nf, software/bwamem2/index/main.nf, software/bwameth/index/main.nf, software/hisat2/build/main.nf, software/rsem/preparereference/main.nf, software/salmon/index/main.nf, software/star/genomegenerate/main.nf, tests/software/bowtie/align/test.yml, tests/software/bowtie/build_test/test.yml, tests/software/bowtie2/align/test.yml, tests/software/bowtie2/build_test/test.yml, tests/software/bwa/index/test.yml, tests/software/bwamem2/index/test.yml, tests/software/bwameth/index/test.yml, tests/software/salmon/index/test.yml, tests/software/star/genomegenerate/test.yml
Update of [this](https://github.com/nf-core/modules/pull/328) PR
Closes #328
=> Add default output dir for modules that create indices, updated

software/vcftools/functions.nf, software/vcftools/main.nf, software/vcftools/meta.yml, tests/config/pytest_software.yml, tests/software/vcftools/main.nf, tests/software/vcftools/test.yml
Closes #214 
New PR for vcftools module after cleaning up conflicts.
=> add vcftools module

software/prokka/main.nf
I failed to add the appropriate label to the original model, updating it here.
=> Update Prokka modules - add process label 

README.md
This is just an update to the link in the README that points to the process descriptions
=> README - Fix link describing process labels

software/strelka/germline/functions.nf, software/strelka/germline/main.nf, software/strelka/germline/meta.yml, tests/config/pytest_software.yml, tests/software/strelka/germline/main.nf, tests/software/strelka/germline/test.yml
=> Strelka germline

tests/software/bedtools/complement/main.nf, tests/software/bedtools/genomecov/main.nf, tests/software/bedtools/getfasta/main.nf, tests/software/bedtools/intersect/main.nf, tests/software/bedtools/maskfasta/main.nf, tests/software/bedtools/merge/main.nf, tests/software/bedtools/slop/main.nf, tests/software/bedtools/sort/main.nf
=> Update bedtools modules with config logic

software/gatk4/variantfiltration/main.nf, tests/software/bcftools/consensus/main.nf, tests/software/bcftools/consensus/test.yml, tests/software/bcftools/filter/main.nf, tests/software/bcftools/filter/test.yml, tests/software/bcftools/isec/main.nf, tests/software/bcftools/isec/test.yml, tests/software/bcftools/merge/main.nf, tests/software/bcftools/merge/test.yml, tests/software/bcftools/mpileup/main.nf, tests/software/bcftools/mpileup/test.yml, tests/software/bcftools/stats/main.nf, tests/software/bcftools/stats/test.yml, tests/software/gatk4/variantfiltration/main.nf, tests/software/gatk4/variantfiltration/test.yml
Closes #XXX 
Updated assigned paths.
=> update test data paths

tests/software/samtools/faidx/main.nf, tests/software/samtools/faidx/test.yml, tests/software/samtools/fastq/main.nf, tests/software/samtools/fastq/test.yml, tests/software/samtools/flagstat/main.nf, tests/software/samtools/idxstats/main.nf, tests/software/samtools/index/main.nf, tests/software/samtools/index/test.yml, tests/software/samtools/merge/main.nf, tests/software/samtools/mpileup/main.nf, tests/software/samtools/sort/main.nf, tests/software/samtools/sort/test.yml, tests/software/samtools/stats/main.nf, tests/software/samtools/view/main.nf, tests/software/samtools/view/test.yml
=> Update samtools modules with config logic

tests/software/adapterremoval/main.nf, tests/software/dsh/filterbed/main.nf, tests/software/dsh/splitbed/main.nf
Tasks related to #363 
Updates test paths in
- adapterremoval
- dsh/splitbed
- dsh/filterbed
---
=> Update restructured paths

tests/software/picard/collectmultiplemetrics/main.nf, tests/software/picard/collectwgsmetrics/main.nf, tests/software/picard/markduplicates/main.nf, tests/software/picard/markduplicates/test.yml, tests/software/picard/mergesamfiles/main.nf, tests/software/picard/mergesamfiles/test.yml, tests/software/trimgalore/main.nf
Towards #363  
---
- ~~[ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)~~
- ~~[ ] Emit the `<SOFTWARE>.version.txt` file.~~
=> Fix a bunch of failing tests after switching to test config

tests/software/bowtie2/align/main.nf, tests/software/bowtie2/align/test.yml, tests/software/bowtie2/build_test/main.nf, tests/software/bowtie2/build_test/test.yml, tests/software/bwameth/align/main.nf, tests/software/bwameth/index/main.nf, tests/software/bwameth/index/test.yml, tests/software/multiqc/main.nf
Updates path to new test files for as assigned on #363 
`bwameth/index`
`bwameth/align`
`bowtie2/align`
`bowtie2/build_test` aka as the black sheep of the tests... 
`multiqc`
=> Fix some module test after adapting test config approach

tests/software/bismark/align/main.nf, tests/software/bismark/deduplicate/main.nf, tests/software/bismark/genomepreparation/main.nf, tests/software/bismark/genomepreparation/test.yml, tests/software/bismark/methylationextractor/main.nf, tests/software/bismark/report/main.nf, tests/software/vcftools/main.nf
Fixing vcftools and bismark tests
Some tests are still failing
=> Fixing vcftools and bismark tests

software/bwa/mem/main.nf, software/bwamem2/index/main.nf, software/bwamem2/mem/main.nf, tests/software/bwa/index/main.nf, tests/software/bwa/index/test.yml, tests/software/bwa/mem/main.nf, tests/software/bwa/mem/test.yml, tests/software/bwamem2/index/main.nf, tests/software/bwamem2/index/test.yml, tests/software/bwamem2/mem/main.nf, tests/software/bwamem2/mem/test.yml
=> Update test paths in bwa mappers

.github/workflows/pytest-workflow.yml
=> ci: Upload work directory on failure

software/subread/featurecounts/meta.yml, tests/config/pytest_software.yml, tests/software/subread/featurecounts/main.nf, tests/software/subread/featurecounts/test.yml
=> Add tests for subread #106

software/methyldackel/extract/main.nf, software/methyldackel/mbias/main.nf, tests/software/methyldackel/mbias/test.yml
=> MethylDackel: fix version scraping

software/pangolin/main.nf, software/rsem/preparereference/main.nf, software/spades/main.nf, software/spades/meta.yml, tests/software/pangolin/test.yml, tests/software/spades/main.nf, tests/software/spades/test.yml
=> Version bumps and minor module updates

software/tabix/bgzip/main.nf
=> Fix tabix/bgzip version command

software/rapidnj/functions.nf, software/rapidnj/main.nf, software/rapidnj/meta.yml, tests/config/pytest_software.yml, tests/software/rapidnj/main.nf, tests/software/rapidnj/test.yml
This PR adds a module for rapidnj - a rapd neighbour-joining phylogeny-building software
=> add rapidnj module

software/mash/sketch/functions.nf, software/mash/sketch/main.nf, software/mash/sketch/meta.yml, tests/config/pytest_software.yml, tests/software/mash/sketch/main.nf, tests/software/mash/sketch/test.yml
⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️
=> 🏋️‍♀️ new submodule mash/sketch🕺

software/rasusa/main.nf, software/rasusa/meta.yml, tests/software/rasusa/main.nf
- Changed genome size input position
=> 🧸  Updated rasusa

software/deeptools/computematrix/meta.yml, software/deeptools/plotfingerprint/meta.yml, software/deeptools/plotheatmap/meta.yml, software/deeptools/plotprofile/meta.yml, tests/config/pytest_software.yml, tests/config/test_data.config, tests/software/deeptools/computematrix/main.nf, tests/software/deeptools/computematrix/test.yml, tests/software/deeptools/plotfingerprint/main.nf, tests/software/deeptools/plotfingerprint/test.yml, tests/software/deeptools/plotheatmap/main.nf, tests/software/deeptools/plotheatmap/test.yml, tests/software/deeptools/plotprofile/main.nf, tests/software/deeptools/plotprofile/test.yml
This PR add test and metadata for the `deeptools` modules:
*  `computematrix`
*  `plotheatmap`
*  `plotfingerprint`
*  `plotprofile`
(As listed on https://github.com/nf-core/modules/issues/430)
=> Finish deeptools modules

software/abacas/meta.yml
Add output description for abacas in `meta.yml`
Closes #444
=> Fixing abacas meta.yml file

software/fastp/meta.yml
Correct very minor typo in meta.yml
=> minor typo

tests/config/nextflow.config
This should fix the issue described here: https://github.com/nf-core/tools/issues/1021
=> change process.time for tests to 2h

software/plasmidid/main.nf, tests/software/plasmidid/test.yml
Update to 1.6.5 for important bug fixes and updates.
=> Bump plasmidid version

software/kallistobustools/ref/main.nf, tests/software/kallistobustools/ref/main.nf, tests/software/kallistobustools/ref/test.yml
Closes #XXX 
This PR updates the version of kb-python, modifies test data to use the params.test_data option with homo_sapiens data and finally fixes the workflow definitions for tests lamanno and nucleus.
=> Update kallistobustools/ref module

tests/config/test_data.config
Adds gvcf index files to the config generate in https://github.com/nf-core/test-datasets/pull/246 (Wait for merge until 246 is merged)
Closes #XXX 
=> Add gvcf index files

software/qcat/functions.nf, software/qcat/main.nf, software/qcat/meta.yml, tests/config/pytest_software.yml, tests/config/test_data.config, tests/software/qcat/main.nf, tests/software/qcat/test.yml
I am using the non-demultiplexed file from nanoseq's test-dataset for the qcat test. Please merge this PR after other nanoseq module PRs are merged. Thanks!
=> add qcat module (from nanoseq modules)

tests/config/test_data.config
Adds test data paths for new data
=> updated paths to test data

software/nextclade/functions.nf, software/nextclade/main.nf, software/nextclade/meta.yml, software/pangolin/main.nf, tests/config/pytest_software.yml, tests/software/nextclade/main.nf, tests/software/nextclade/test.yml, tests/software/pangolin/test.yml
* Bumped Pangolin version to latest
=> Add Nextclade module

software/artic/minion/functions.nf, software/artic/minion/main.nf, software/artic/minion/meta.yml, tests/config/pytest_software.yml, tests/config/test_data.config, tests/software/artic/minion/main.nf, tests/software/artic/minion/test.yml
Add `artic/minion` module as a [requirement](https://github.com/nf-core/viralrecon/issues/149) of `nfcore/viralrecon` DSL2 implementation.
Closes #454 
=> Add artic minion

software/ucsc/bigwigaverageoverbed/functions.nf, software/ucsc/bigwigaverageoverbed/main.nf, software/ucsc/bigwigaverageoverbed/meta.yml, software/ucsc/wigtobigwig/functions.nf, software/ucsc/wigtobigwig/main.nf, software/ucsc/wigtobigwig/meta.yml, tests/config/pytest_software.yml, tests/software/ucsc/bigwigaverageoverbed/main.nf, tests/software/ucsc/bigwigaverageoverbed/test.yml, tests/software/ucsc/wigtobigwig/main.nf, tests/software/ucsc/wigtobigwig/test.yml
- [ x ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ x ] If necessary, include test data in your PR.
- [ x ] Remove all TODO statements.
- [ x ] Emit the `<SOFTWARE>.version.txt` file.
- [ x ] Follow the naming conventions.
- [ x ] Follow the parameters requirements.
- [ x ] Follow the input/output options guidelines.
- [ x ] Add a resource `label`
- [ x ] Use BioConda and BioContainers if possible to fulfil software requirements.
- [ x ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd`
- [ x ] `PROFILE=conda pytest --tag <MODULE> --symlink …
=> add additional ucsc tools

software/pairix/functions.nf, software/pairix/main.nf, software/pairix/meta.yml, tests/config/pytest_software.yml, tests/software/pairix/main.nf, tests/software/pairix/test.yml
- [ x ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ x ] If necessary, include test data in your PR.
- [ x ] Remove all TODO statements.
- [ x ] Emit the `<SOFTWARE>.version.txt` file.
- [ x ] Follow the naming conventions.
- [ x ] Follow the parameters requirements.
- [ x ] Follow the input/output options guidelines.
- [ x ] Add a resource `label`
- [ x ] Use BioConda and BioContainers if possible to fulfil software requirements.
- [ x ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd`
- [ x ] `PROFILE=conda pytest --tag <MODULE> --symlink …
=> add software/pairix

software/last/mafconvert/functions.nf, software/last/mafconvert/main.nf, software/last/mafconvert/meta.yml, tests/config/pytest_software.yml, tests/software/last/mafconvert/main.nf, tests/software/last/mafconvert/test.yml
The `maf-convert` tool distributed with [LAST](https://gitlab.com/mcfrith/last) reads alignments in [MAF](https://genome-asia.ucsc.edu/FAQ/FAQformat.html#format5) format and converts them in another format (axt, blast, blasttab, chain, gff, html, psl, sam, tab).
This new module is part of the work described in Issue #464. During this development, we fix the version of LAST to 1219 to ensure consistency. We will upgrade it later.
Closes #XXX 
=> New last/mafconvert module to convert MAF alignments.

software/pangolin/main.nf, tests/software/pangolin/test.yml
Update Pangoling version to 3.0.5 
=> Pangolin bump new version (3.0.5)

software/nextclade/main.nf, tests/software/nextclade/test.yml
Update Nextclade version to 0.14.4
=>  Nextclade bump new version (0.14.4)

software/last/dotplot/main.nf, software/last/dotplot/meta.yml, software/last/lastal/functions.nf, software/last/lastal/main.nf, software/last/lastdb/main.nf, software/last/mafconvert/main.nf, software/last/mafconvert/meta.yml, software/last/mafswap/functions.nf, software/last/mafswap/main.nf, software/last/mafswap/meta.yml, software/last/postmask/functions.nf, software/last/postmask/main.nf, software/last/postmask/meta.yml, software/last/split/functions.nf, software/last/split/main.nf, software/last/train/functions.nf, software/last/train/main.nf, tests/software/last/dotplot/main.nf, tests/software/last/dotplot/test.yml, tests/software/last/lastal/test.yml, tests/software/last/lastdb/test.yml, tests/software/last/mafconvert/main.nf
This is the final PR before closing Issue #464 ! Here are a couple of updates and corrections.
- Update LAST to version 1238 and MD5 checksums when needed.
- Update functions.nf to the latest devel version.
- Make a portable use of `zcat` for MacOS X.
- Allow input alignments to be uncompressed when possible.
- Correct how LAST index name was guessed.
- Use value input channel to chose output file format.
- Use optional output channels to handle variable file formats. 
Each commit corresponds roughly to one of these items.
Closes #464
=> Update last module

software/metaphlan3/functions.nf, software/metaphlan3/main.nf, software/metaphlan3/meta.yml, tests/config/pytest_software.yml, tests/software/metaphlan3/main.nf, tests/software/metaphlan3/test.yml
=> Add metaphlan3 module

software/tabix/bgziptabix/functions.nf, software/tabix/bgziptabix/main.nf, software/tabix/bgziptabix/meta.yml, tests/config/pytest_software.yml, tests/software/tabix/bgziptabix/main.nf, tests/software/tabix/bgziptabix/test.yml
=> Add modules bgziptabix

software/damageprofiler/functions.nf, software/damageprofiler/main.nf, software/damageprofiler/meta.yml, tests/config/pytest_software.yml, tests/software/damageprofiler/main.nf, tests/software/damageprofiler/test.yml
This adds the module for DamageProfiler
Closes #285 
=> damageprofiler

software/lofreq/filter/functions.nf, software/lofreq/filter/main.nf, software/lofreq/filter/meta.yml, tests/config/pytest_software.yml, tests/software/lofreq/filter/main.nf, tests/software/lofreq/filter/test.yml
=> Lofreq filter

software/lofreq/callparallel/functions.nf, software/lofreq/callparallel/main.nf, software/lofreq/callparallel/meta.yml, tests/config/pytest_software.yml, tests/software/lofreq/callparallel/main.nf, tests/software/lofreq/callparallel/test.yml
=> Pull request for module: lofreq/callparallel

software/lofreq/call/functions.nf, software/lofreq/call/main.nf, software/lofreq/call/meta.yml, tests/config/pytest_software.yml, tests/software/lofreq/call/main.nf, tests/software/lofreq/call/test.yml
Adding Lofreq call module for low frequency variant calling.
Resolves #561.
=> Lofreq call

modules/gatk4/samtofastq/main.nf
=> fix: update to gatk4.2.0.0

modules/seqkit/split2/main.nf
=> fix: update seqkit to 0.16.0

modules/samtools/merge/main.nf, tests/modules/samtools/merge/main.nf
Just don't want the merged file to be have the `_merged` suffix by default.
That can go to conf/modules.config
Closes #XXX 
=> fix: update samtools_merge

modules/hifiasm/functions.nf, modules/hifiasm/main.nf, modules/hifiasm/meta.yml, tests/config/pytest_modules.yml, tests/config/test_data.config, tests/modules/hifiasm/main.nf, tests/modules/hifiasm/test.yml
Replacement for https://github.com/nf-core/modules/pull/574
=> Add hifiasm module

README.md
Based on discussion https://nfcore.slack.com/archives/CJRH30T6V/p1626858274293800
Updates best practice of optional input file to use empty lists rather than dummy files.
=> Updated optional input definition

modules/picard/sortsam/functions.nf, modules/picard/sortsam/main.nf, modules/picard/sortsam/meta.yml, tests/config/pytest_modules.yml, tests/modules/picard/sortsam/main.nf, tests/modules/picard/sortsam/test.yml
Add picard SortSam module
Closes #600 
=> module: picard sortsam

modules/picard/filtersamreads/main.nf, tests/modules/picard/filtersamreads/main.nf
=> fix: picard filtersamreads input

modules/fastp/main.nf, modules/fastp/meta.yml, tests/modules/fastp/main.nf, tests/modules/fastp/test.yml
=> enhance module fastp: add `save_merged` (#598)

modules/dshbio/filterbed/main.nf, modules/dshbio/filtergff3/main.nf, modules/dshbio/splitbed/main.nf, modules/dshbio/splitgff3/main.nf
=> Update dsh-bio to 2.0.5

modules/star/align/main.nf, tests/modules/star/align/main.nf, tests/modules/star/align/test.yml
Added Platform (PL) tag in the RG line of STAR/Align command.
This is necessary for the downstream analysis especially for GATK to process the bam files.
=> Added PL tag in read group information of STAR/Align

modules/bcftools/concat/functions.nf, modules/bcftools/concat/main.nf, modules/bcftools/concat/meta.yml, tests/config/pytest_modules.yml, tests/modules/bcftools/concat/main.nf, tests/modules/bcftools/concat/test.yml
=> Add bcftools/concat module.

modules/dragonflye/functions.nf, modules/dragonflye/main.nf, modules/dragonflye/meta.yml, tests/config/pytest_modules.yml, tests/modules/dragonflye/main.nf, tests/modules/dragonflye/test.yml
This PR adds a module for [Dragonflye](https://github.com/rpetit3/dragonflye) a fork of Shovill that supports ONT reads.
Closes #632 
=> add module for dragonflye

modules/cooler/digest/main.nf
=> update typos. change quote from ' to ".

modules/bcftools/norm/functions.nf, modules/bcftools/norm/main.nf, modules/bcftools/norm/meta.yml, tests/config/pytest_modules.yml, tests/modules/bcftools/norm/main.nf, tests/modules/bcftools/norm/test.yml
=> Add bcftools/norm module

modules/expansionhunter/functions.nf, modules/expansionhunter/main.nf, modules/expansionhunter/meta.yml, tests/config/pytest_modules.yml, tests/config/test_data.config, tests/modules/expansionhunter/main.nf, tests/modules/expansionhunter/test.yml
Here is the PR for a expansionhunter module. 
Closes #663  
=> Expansionhunter

tests/modules/malt/run/test.yml
=> Remove sneaky leftover TODO in MALT test

modules/dshbio/exportsegments/functions.nf, modules/dshbio/exportsegments/main.nf, modules/dshbio/exportsegments/meta.yml, tests/config/pytest_modules.yml, tests/modules/dshbio/exportsegments/main.nf, tests/modules/dshbio/exportsegments/test.yml
=> Add dsh-bio export-segments module

modules/bedtools/makewindows/functions.nf, modules/bedtools/makewindows/main.nf, modules/bedtools/makewindows/meta.yml, tests/config/pytest_modules.yml, tests/modules/bedtools/makewindows/main.nf, tests/modules/bedtools/makewindows/test.yml
Closes #657
Added new module for bedtools/makewindows
=> Add bedtools/makewindows module

README.md
Hi nf-core/modules maintainers.
I tried to run the commands written in the README, but it did not work as expected.
Updated the command.
Other parts of the README may need to be updated as well. 
This is just a suggestion to fix some of them. 
So if it is not approved, feel free to close the pull request.
Thank you!
=> Update the commands in the Using existing modules section

modules/bcftools/view/functions.nf, modules/bcftools/view/main.nf, modules/bcftools/view/meta.yml, tests/config/pytest_modules.yml, tests/config/test_data.config, tests/modules/bcftools/view/main.nf, tests/modules/bcftools/view/test.yml
This PR adds `bcftools/view` module.
=> Add bcftools view module

modules/gatk4/getpileupsummaries/functions.nf, modules/gatk4/getpileupsummaries/main.nf, modules/gatk4/getpileupsummaries/meta.yml, tests/config/pytest_modules.yml, tests/modules/gatk4/getpileupsummaries/main.nf, tests/modules/gatk4/getpileupsummaries/test.yml
Closes #195 
Added new module Gatk4/GetPileupSummaries, along with appropriate tests. No new test data needed for the module.
=> Getpileupsummaries

modules/bcftools/query/functions.nf, modules/bcftools/query/main.nf, modules/bcftools/query/meta.yml, tests/config/pytest_modules.yml, tests/modules/bcftools/query/main.nf, tests/modules/bcftools/query/test.yml
This PR adds support for the bcftools/query module.
=> Add bcftools/query module

modules/pangolin/main.nf, tests/modules/pangolin/test.yml
=> Update pangolin to 3.1.11

modules/cat/cat/main.nf, modules/cat/cat/meta.yml, tests/modules/cat/cat/main.nf, tests/modules/cat/cat/test.yml
Follow up PR to https://github.com/nf-core/modules/pull/722
=> Refactor cat/cat module

modules/agrvate/main.nf
The new version of agrvate fixes an issue where sample names with a `.` (dot) in their names caused the name to be truncated
https://github.com/VishnuRaghuram94/AgrVATE/releases/tag/v1.0.1
Closes https://github.com/nf-core/modules/issues/727 
=> Update agrvate to v1.0.1

tests/test_versions_yml.py
Better error message for the `versions.yml` tests.
=> Better error message for FileNotFoundErrors

modules/subread/featurecounts/main.nf, tests/modules/subread/featurecounts/test.yml, tests/modules/yara/mapper/main.nf
- Fix featurecounts
- whitespace change to trigger CI on yara/mapper
Didn't manage more today...
=> fix more ver yml

modules/custom/dumpsoftwareversions/main.nf
As discussed in https://github.com/nf-core/tools/pull/1278#discussion_r718694075
=> Dump version for /custom/dumpsoftwareversions module itself

modules/bbmap/bbsplit/functions.nf, modules/bbmap/bbsplit/main.nf, modules/bbmap/bbsplit/meta.yml, tests/config/pytest_modules.yml, tests/modules/bbmap/bbsplit/main.nf, tests/modules/bbmap/bbsplit/test.yml
=> Add bbmap/bbsplit module

modules/sortmerna/main.nf
Partly addresses https://github.com/nf-core/rnaseq/issues/570
=> Update SortMeRNA to 4.3.4

modules/sortmerna/main.nf
Fix sortmerna docker container pointer.
=> Fix sortmerna

tests/modules/freebayes/test.yml
=> fix freebayes tests by removing md5sum check

modules/bwameth/align/main.nf
See https://github.com/nf-core/methylseq/pull/217 for context where this fix was added into the DSL1 methylseq pipeline.
x-ref https://github.com/nf-core/methylseq/pull/222/files#r743244912
Closes #XXX 
=> bwameth: Add touch command to fix problem with bwameth rejecting older files

modules/samtools/index/main.nf, modules/samtools/index/meta.yml, tests/modules/samtools/index/main.nf, tests/modules/samtools/index/test.yml
=> Add CRAM to samtools/index

tests/modules/gatk4/markduplicates/main.nf, tests/modules/gatk4/markduplicates/test.yml
Test was actually done only for input file.
The second was never considered as the channel was not set up properly
Closes #XXX 
=> fix: actually do the tests for multiple files

modules/fargene/functions.nf, modules/fargene/main.nf, modules/fargene/meta.yml, tests/config/pytest_modules.yml, tests/modules/fargene/main.nf, tests/modules/fargene/test.yml
Closes #XXX 
- [x ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [x ] Follow the naming conventions.
- [x ] Follow the parameters requirements.
- [x ] Follow the input/output options guidelines.
- [x ] Add a resource `label`
- [x ] Use BioConda and BioContainers if possible to fulfil software requirements.
- [x ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd`
=> new module fargene

modules/gatk4/getpileupsummaries/main.nf, modules/gatk4/getpileupsummaries/meta.yml, modules/gatk4/mutect2/main.nf, modules/gatk4/mutect2/meta.yml, tests/modules/gatk4/getpileupsummaries/main.nf, tests/modules/gatk4/mutect2/main.nf
=> Rename all _idx to _tbi

modules/gatk4/applybqsr/main.nf, modules/gatk4/applybqsr/meta.yml, modules/gatk4/baserecalibrator/main.nf, modules/gatk4/baserecalibrator/meta.yml, modules/gatk4/createsomaticpanelofnormals/main.nf, modules/gatk4/createsomaticpanelofnormals/meta.yml, modules/gatk4/filtermutectcalls/main.nf, modules/gatk4/filtermutectcalls/meta.yml, modules/gatk4/mutect2/main.nf, modules/gatk4/mutect2/meta.yml, subworkflows/nf-core/gatk_create_som_pon/main.nf, subworkflows/nf-core/gatk_create_som_pon/meta.yml, tests/modules/gatk4/filtermutectcalls/main.nf, tests/modules/gatk4/mutect2/main.nf, tests/subworkflows/nf-core/gatk_create_som_pon/main.nf
=> Rename all fastaidx to fai

modules/dshbio/exportsegments/main.nf, modules/dshbio/filterbed/main.nf, modules/dshbio/filtergff3/main.nf, modules/dshbio/splitbed/main.nf, modules/dshbio/splitgff3/main.nf
=> Update dsh-bio to 2.0.6

main.nf
Allows for launching of subworkflows
=> feat: Add main.nf

.github/workflows/nf-core-linting.yml, subworkflows/nf-core/gatk_create_som_pon/main.nf, tests/config/pytest_modules.yml
Closes #XXX 
The current implementation of `pytest_modules.yml` isn't valid YAML according to `pyyaml` (others are ok with it). This PR attempts to make it valid so play nicely with `nf-core/tools`, specifically the `modules create` command
=> use underscores in anchors and references

modules/gatk4/variantfiltration/main.nf, modules/gatk4/variantfiltration/meta.yml, tests/modules/gatk4/variantfiltration/main.nf, tests/modules/gatk4/variantfiltration/test.yml
Added vcf_index to vcf tuple; output to vcf.gz format.
- [] If you've fixed a bug or added code that should be tested, add tests!
- [x ] Emit the `versions.yml` file.
=> Update in GATK4 variantfiltration: Added vcf_index to vcf tuple; output to vcf.gz format.

modules/fastp/meta.yml
Fixed html pattern typo:
Before: pattern: "*.thml"
After fix: pattern: "*.html"
Closes #XXX 
=> Update meta.yml by fixing html pattern expected

modules/tabix/bgziptabix/main.nf
=> TABIX/BGZTABIX: emited channel should be gz_tbi and not only tbi

modules/seqkit/split2/main.nf, tests/modules/seqkit/split2/test.yml
=> Update version & prefix

modules/ensemblvep/main.nf, modules/snpeff/main.nf
=> feat: add meta.id tag

modules/ensemblvep/main.nf, modules/snpeff/main.nf, tests/modules/ensemblvep/nextflow.config, tests/modules/snpeff/nextflow.config
=> greatly simplify syntax

modules/gatk4/applybqsr/main.nf, modules/gatk4/baserecalibrator/main.nf, modules/gatk4/bedtointervallist/main.nf, modules/gatk4/calculatecontamination/main.nf, modules/gatk4/createsequencedictionary/main.nf, modules/gatk4/createsomaticpanelofnormals/main.nf, modules/gatk4/estimatelibrarycomplexity/main.nf, modules/gatk4/fastqtosam/main.nf, modules/gatk4/filtermutectcalls/main.nf, modules/gatk4/genomicsdbimport/main.nf, modules/gatk4/genotypegvcfs/main.nf, modules/gatk4/getpileupsummaries/main.nf, modules/gatk4/indexfeaturefile/main.nf, modules/gatk4/intervallisttools/main.nf, modules/gatk4/learnreadorientationmodel/main.nf, modules/gatk4/markduplicates/main.nf, modules/gatk4/mergebamalignment/main.nf, modules/gatk4/mergevcfs/main.nf, modules/gatk4/mutect2/main.nf, modules/gatk4/revertsam/main.nf, modules/gatk4/samtofastq/main.nf, modules/gatk4/splitncigarreads/main.nf, modules/gatk4/variantfiltration/main.nf
=> Add memory stuff to all gatk4 modules

modules/bwa/mem/main.nf, modules/bwa/mem/meta.yml, modules/bwamem2/mem/main.nf, modules/bwamem2/mem/meta.yml, tests/modules/bwa/mem/main.nf, tests/modules/bwa/mem/nextflow.config, tests/modules/bwa/mem/test.yml, tests/modules/bwamem2/mem/main.nf, tests/modules/bwamem2/mem/nextflow.config, tests/modules/bwamem2/mem/test.yml
=> Add new boolean sort_bam as input to be able to chose between sort and view in bwamem and bwamem2mem

modules/dragmap/align/main.nf, tests/modules/dragmap/align/main.nf, tests/modules/dragmap/align/nextflow.config, tests/modules/dragmap/align/test.yml
=> feat: update dragmap to follow new bwa/mem + bwamem2/mem logic

modules/gatk4/gatherbqsrreports/main.nf, modules/gatk4/gatherbqsrreports/meta.yml, tests/config/pytest_modules.yml, tests/modules/gatk4/gatherbqsrreports/main.nf, tests/modules/gatk4/gatherbqsrreports/nextflow.config, tests/modules/gatk4/gatherbqsrreports/test.yml
=> add gatk4/gatherbqsr

modules/seqwish/induce/main.nf
=> Update seqwish to version 0.7.2

modules/hmmcopy/generatemap/main.nf, modules/rseqc/tin/main.nf, modules/rseqc/tin/meta.yml, tests/config/pytest_modules.yml, tests/modules/rseqc/tin/main.nf, tests/modules/rseqc/tin/nextflow.config, tests/modules/rseqc/tin/test.yml
x-ref: https://github.com/nf-core/rnaseq/issues/728
=> Add RSeqC tin.py module

modules/lima/main.nf
This commit remove the old suffix option and check if input and output filenames are not the same.
=> Uppdate `Lima` module: remove old suffix option

modules/mash/dist/main.nf, modules/mash/dist/meta.yml, tests/config/pytest_modules.yml, tests/modules/mash/dist/main.nf, tests/modules/mash/dist/nextflow.config, tests/modules/mash/dist/test.yml
Closes https://github.com/nf-core/modules/issues/1192 
=> add module for mash dist

modules/ucsc/wigtobigwig/main.nf, modules/ucsc/wigtobigwig/meta.yml, tests/modules/ucsc/wigtobigwig/main.nf, tests/modules/ucsc/wigtobigwig/test.yml
This PR adds meta map to ucsc/wigtobigwig module to standardize with all other modules that hold meta values.
=> ucsc/wigtobigwig: add meta map

modules/samtools/view/main.nf
=> samtools subsampling

modules/dshbio/exportsegments/main.nf, modules/dshbio/exportsegments/meta.yml, modules/dshbio/filterbed/main.nf, modules/dshbio/filtergff3/main.nf, modules/dshbio/splitbed/main.nf, modules/dshbio/splitgff3/main.nf, tests/config/test_data.config, tests/modules/dshbio/exportsegments/main.nf, tests/modules/dshbio/exportsegments/test.yml
=> Update dsh-bio to version 2.0.7, add support for compressed GFA 1.0 format

modules/deepvariant/main.nf, modules/deepvariant/meta.yml, tests/modules/deepvariant/main.nf, tests/modules/deepvariant/nextflow.config, tests/modules/deepvariant/test.yml
=> Update version & add intervals usage

modules/chromap/index/main.nf, tests/modules/chromap/index/test.yml
Bump `chromap/index` version to 0.1.5
Closes #XXX 
=> Bump chromap index version

modules/deeparg/predict/main.nf
After the merge tweaked from something @mashehu noticed later
=> fix: remove left-over unnecessary code

.gitpod.yml
Updates Gitpod config to use the nf-core gitpod image, and recommended extensions.
=> Update gitpod config to use nf-core gitpod image and include extensions.

modules/prodigal/meta.yml
Quick fix to get the module parsing up and running again.
=> fix yml formatting

modules/msisensorpro/msi_somatic/main.nf, modules/msisensorpro/msi_somatic/meta.yml, modules/msisensorpro/scan/main.nf, modules/msisensorpro/scan/meta.yml, tests/config/pytest_modules.yml, tests/modules/msisensorpro/msi_somatic/main.nf, tests/modules/msisensorpro/msi_somatic/nextflow.config, tests/modules/msisensorpro/msi_somatic/test.yml, tests/modules/msisensorpro/scan/main.nf, tests/modules/msisensorpro/scan/nextflow.config, tests/modules/msisensorpro/scan/test.yml
=> Add msisensorpro

modules/manta/germline/main.nf
=> feat: nicer syntax

modules/gatk4/intervallisttobed/main.nf, modules/gatk4/intervallisttobed/meta.yml, tests/config/pytest_modules.yml, tests/modules/gatk4/intervallisttobed/main.nf, tests/modules/gatk4/intervallisttobed/nextflow.config, tests/modules/gatk4/intervallisttobed/test.yml
=> intervallisttobed

modules/gatk4/mergemutectstats/main.nf, modules/gatk4/mergemutectstats/meta.yml, tests/config/pytest_modules.yml, tests/modules/gatk4/mergemutectstats/main.nf, tests/modules/gatk4/mergemutectstats/nextflow.config, tests/modules/gatk4/mergemutectstats/test.yml
=> add mergemutectstats

modules/artic/minion/main.nf, modules/artic/minion/meta.yml, modules/ivar/variants/main.nf, modules/ivar/variants/meta.yml, tests/modules/artic/minion/main.nf, tests/modules/ivar/variants/main.nf
Fixes https://github.com/nf-core/viralrecon/issues/281
=> Patch fix artic/minion and ivar/variants modules

modules/rgi/main/main.nf, modules/rgi/main/meta.yml, tests/config/pytest_modules.yml, tests/modules/rgi/main/main.nf, tests/modules/rgi/main/nextflow.config, tests/modules/rgi/main/test.yml
Closes https://github.com/nf-core/modules/issues/1159 
WIP - Tests were failing on my system, wanting to see if its my system acting up
=> add module for rgi

modules/sistr/main.nf, modules/sistr/meta.yml, tests/config/pytest_modules.yml, tests/modules/sistr/main.nf, tests/modules/sistr/nextflow.config, tests/modules/sistr/test.yml
Closes https://github.com/nf-core/modules/issues/1322 
=> add module for sistr

modules/legsta/main.nf, modules/legsta/meta.yml, tests/config/pytest_modules.yml, tests/modules/legsta/main.nf, tests/modules/legsta/nextflow.config, tests/modules/legsta/test.yml
Closes https://github.com/nf-core/modules/issues/1318 
This is going to need a new build on the Bioconda side before it works, see: https://github.com/bioconda/bioconda-recipes/pull/33246
=> add module for legsta

modules/picard/fixmateinformation/main.nf, modules/picard/fixmateinformation/meta.yml, tests/config/pytest_modules.yml, tests/modules/picard/fixmateinformation/main.nf, tests/modules/picard/fixmateinformation/nextflow.config, tests/modules/picard/fixmateinformation/test.yml
=> Picard fixmateinformation

modules/picard/cleansam/main.nf, modules/picard/cleansam/meta.yml, tests/config/pytest_modules.yml, tests/modules/picard/cleansam/main.nf, tests/modules/picard/cleansam/nextflow.config, tests/modules/picard/cleansam/test.yml
=> Picard cleansam

modules/rseqc/tin/main.nf
See https://github.com/nf-core/rnaseq/issues/769
=> Change label for rseqc/tin to process_high

modules/hmmer/hmmsearch/main.nf, modules/hmmer/hmmsearch/meta.yml, tests/config/pytest_modules.yml, tests/modules/hmmer/hmmsearch/main.nf, tests/modules/hmmer/hmmsearch/nextflow.config, tests/modules/hmmer/hmmsearch/test.yml
=> feat: add hmmsearch module and tests

modules/gatk4/selectvariants/main.nf, modules/gatk4/selectvariants/meta.yml, tests/config/pytest_modules.yml, tests/modules/gatk4/selectvariants/main.nf, tests/modules/gatk4/selectvariants/nextflow.config, tests/modules/gatk4/selectvariants/test.yml
=> Gatk4 selectvariants

modules/seqkit/pair/main.nf, modules/seqkit/pair/meta.yml, tests/config/pytest_modules.yml, tests/modules/seqkit/pair/main.nf, tests/modules/seqkit/pair/nextflow.config, tests/modules/seqkit/pair/test.yml
=> Seqkit pair

modules/picard/cleansam/main.nf, modules/picard/cleansam/meta.yml, tests/modules/picard/cleansam/test.yml
Changes: 
- module reads and outputs bam files now (all other picard modules work with bam files and is mostly used format)
-  `--VALIDATION_STRINGENCY` param moved to args
=> update args & convert to bam

modules/hpsuissero/main.nf, modules/hpsuissero/meta.yml, tests/config/pytest_modules.yml, tests/modules/hpsuissero/main.nf, tests/modules/hpsuissero/nextflow.config, tests/modules/hpsuissero/test.yml
Closes https://github.com/nf-core/modules/issues/1330 
=> add module for hpsuisero

modules/ssuissero/main.nf, modules/ssuissero/meta.yml, tests/config/pytest_modules.yml, tests/modules/ssuissero/main.nf, tests/modules/ssuissero/nextflow.config, tests/modules/ssuissero/test.yml
Closes  https://github.com/nf-core/modules/issues/1328 
=> add module for ssuisero

modules/mafft/main.nf, modules/mafft/meta.yml, tests/config/pytest_modules.yml, tests/modules/mafft/main.nf, tests/modules/mafft/nextflow.config, tests/modules/mafft/test.yml
Adds a module for the multiple sequence alignment (MSA) program [MAFFT](https://bioconda.github.io/recipes/mafft/README.html). I use multiple alignment a lot in my pipelines, and prefer MAFFT.
Closes #1350 
=> Add MAFFT module

modules/samtools/ampliconclip/main.nf, modules/samtools/bam2fq/main.nf, modules/samtools/depth/main.nf, modules/samtools/faidx/main.nf, modules/samtools/fastq/main.nf, modules/samtools/fixmate/main.nf, modules/samtools/flagstat/main.nf, modules/samtools/idxstats/main.nf, modules/samtools/index/main.nf, modules/samtools/merge/main.nf, modules/samtools/mpileup/main.nf, modules/samtools/sort/main.nf, modules/samtools/stats/main.nf, modules/samtools/view/main.nf, tests/modules/samtools/ampliconclip/test.yml, tests/modules/samtools/bam2fq/test.yml, tests/modules/samtools/faidx/test.yml, tests/modules/samtools/fastq/test.yml, tests/modules/samtools/fixmate/test.yml, tests/modules/samtools/index/test.yml, tests/modules/samtools/sort/test.yml, tests/modules/samtools/stats/test.yml
=> update samtools version to 1.15

modules/controlfreec/main.nf, modules/controlfreec/meta.yml, tests/config/pytest_modules.yml, tests/config/test_data.config, tests/modules/controlfreec/main.nf, tests/modules/controlfreec/nextflow.config, tests/modules/controlfreec/test.yml
=> add controlfreec

modules/bwa/mem/main.nf, modules/bwa/sampe/main.nf, modules/bwa/samse/main.nf, modules/bwamem2/mem/main.nf, modules/custom/getchromsizes/main.nf, modules/qualimap/bamqccram/main.nf, tests/modules/bwa/sampe/test.yml, tests/modules/bwa/samse/test.yml
=> Update samtools version

modules/stranger/main.nf, modules/stranger/meta.yml, tests/config/pytest_modules.yml, tests/modules/stranger/main.nf, tests/modules/stranger/nextflow.config, tests/modules/stranger/test.yml
Adding stranger which annotatates output vcf files from ExpansionHunter with pathologic implications of the repeat sizes. 
Closes #1248 
=> Add stranger

modules/faqcs/main.nf, modules/faqcs/meta.yml, tests/modules/faqcs/test.yml
=> Faqcs patch

modules/deepvariant/main.nf
=> separate gvcf and vcf in output channels

modules/malt/run/main.nf, modules/malt/run/meta.yml, tests/modules/malt/run/main.nf
Re-adds meta to `malt/run` after further thought (also with the ability to supply empty meta with simply `[]`)
Closes #XXX 
=> Add meta to MALT/RUN

modules/picard/sortvcf/main.nf, modules/picard/sortvcf/meta.yml, tests/config/pytest_modules.yml, tests/modules/picard/sortvcf/main.nf, tests/modules/picard/sortvcf/nextflow.config, tests/modules/picard/sortvcf/test.yml
Adds sortvcf from picard
- [] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd`
=> Add picard/sortvcf

modules/yara/mapper/main.nf, modules/yara/mapper/meta.yml, tests/modules/yara/mapper/test.yml
=> Add samtools index to yara_mapper module

modules/seqkit/replace/main.nf, modules/seqkit/replace/meta.yml, tests/config/pytest_modules.yml, tests/modules/seqkit/replace/main.nf, tests/modules/seqkit/replace/nextflow.config, tests/modules/seqkit/replace/test.yml
=> added module seqkit replace

modules/controlfreec/meta.yml
=> fix controlfreek's meta.yml: fix indent error, avoiding html tag confusion

modules/optitype/main.nf, modules/optitype/meta.yml, tests/config/test_data.config, tests/modules/optitype/main.nf, tests/modules/optitype/test.yml
=> Add BAM indexes as input for optitype module

modules/ascat/main.nf, modules/ascat/meta.yml, tests/modules/ascat/test.yml
Closes #XXX 
This is a minor change to make sure the markdown in the `meta.yml` renders correctly. Thanks for noticing @mashehu
=> round the < to ( to make markdown work for meta.yml

tests/modules/roary/test.yml
Closes https://github.com/nf-core/modules/issues/1418 
=> Update test.yml for Roary module

modules/adapterremovalfixprefix/main.nf, modules/adapterremovalfixprefix/meta.yml, tests/config/pytest_modules.yml, tests/modules/adapterremovalfixprefix/main.nf, tests/modules/adapterremovalfixprefix/nextflow.config, tests/modules/adapterremovalfixprefix/test.yml
=> Add AdapterRemovalFixPrefix

modules/bracken/bracken/main.nf, modules/bracken/bracken/meta.yml, tests/config/pytest_modules.yml, tests/config/test_data.config, tests/modules/bracken/bracken/main.nf, tests/modules/bracken/bracken/nextflow.config, tests/modules/bracken/bracken/test.yml
Add bracken to the modules which is a post-processing tool for kraken2 output. This is wanted in [taxprofiler](https://github.com/nf-core/taxprofiler/issues/12).
=> Add bracken

README.md
=> [FIX/DOC] Broken Adding modules link

modules/dragonflye/main.nf
Closes #XXX 
Alot of features have been added to dragonflye since v1.0.4
=> Update dragonflye to latest version

modules/bbmap/pileup/main.nf, modules/bbmap/pileup/meta.yml, tests/config/pytest_modules.yml, tests/modules/bbmap/pileup/main.nf, tests/modules/bbmap/pileup/nextflow.config, tests/modules/bbmap/pileup/test.yml
=> feat(bbmap): Initialize pileup module

modules/samtools/mpileup/main.nf, modules/samtools/mpileup/meta.yml, tests/modules/samtools/mpileup/main.nf, tests/modules/samtools/mpileup/test.yml
=> Mpileup also likes intervals

modules/dragmap/align/main.nf
=> feat: add readgroup info + reorder samtools command line to mimic bwamem

modules/homer/pos2bed/main.nf, modules/homer/pos2bed/meta.yml, tests/config/pytest_modules.yml, tests/modules/homer/pos2bed/main.nf, tests/modules/homer/pos2bed/nextflow.config, tests/modules/homer/pos2bed/test.yml
=> feat(homer): Add pos2bed module

modules/preseq/ccurve/main.nf, modules/preseq/ccurve/meta.yml, modules/preseq/lcextrap/main.nf, modules/preseq/lcextrap/meta.yml, tests/config/pytest_modules.yml, tests/modules/preseq/ccurve/main.nf, tests/modules/preseq/ccurve/nextflow.config, tests/modules/preseq/ccurve/test.yml, tests/modules/preseq/lcextrap/test.yml
Split them into two separate processes, and use correct name in lcextrap.
=> Split preseq lcextrap and ccurve

modules/homer/maketagdirectory/main.nf, modules/homer/maketagdirectory/meta.yml, tests/modules/homer/maketagdirectory/main.nf, tests/modules/homer/maketagdirectory/nextflow.config, tests/modules/homer/maketagdirectory/test.yml
=> Add samtools to homer/maketagdirectory to use bam files

modules/controlfreec/freec/main.nf
=> Fix typo in args map

modules/svdb/merge/main.nf, modules/svdb/query/main.nf
This PR updates svdb to version from 2.5.2 to 2.6.0
=> Update svdb to 2.6.0

modules/seqkit/stats/main.nf, modules/seqkit/stats/meta.yml, tests/config/pytest_modules.yml, tests/modules/seqkit/stats/main.nf, tests/modules/seqkit/stats/nextflow.config, tests/modules/seqkit/stats/test.yml
Basic implementation of the `seqkit stats` command.
=> feat: add module for seqkit stats

modules/cnvpytor/callcnvs/main.nf, modules/cnvpytor/histogram/main.nf, modules/cnvpytor/importreaddepth/main.nf, modules/cnvpytor/partition/main.nf
This PR fixes the links for cnvpytor's singularity images
=> Update cnvpytor links

modules/adapterremoval/main.nf, modules/adapterremoval/meta.yml, tests/modules/adapterremoval/test.yml
Insert the missing `.fastq` file extension so that other tools can recognize the file type.
=> Refactor adapterremoval

modules/biobambam/bammarkduplicates2/main.nf, tests/modules/biobambam/bammarkduplicates2/test.yml
=> Update: biobambam/bammarkduplicates2 to v2.0.183

modules/snapaligner/index/main.nf, modules/snapaligner/index/meta.yml, tests/config/pytest_modules.yml, tests/modules/snapaligner/index/main.nf, tests/modules/snapaligner/index/nextflow.config, tests/modules/snapaligner/index/test.yml
=> new tool snap-aligner/index

modules/dshbio/exportsegments/main.nf, modules/dshbio/filterbed/main.nf, modules/dshbio/filtergff3/main.nf, modules/dshbio/splitbed/main.nf, modules/dshbio/splitgff3/main.nf
=> Update dsh-bio to version 2.0.8

modules/bwa/mem/main.nf, modules/bwamem2/mem/main.nf, modules/dragmap/align/main.nf
=> feat: remove read_group which should be set up with task.ext.args

modules/kaiju/kaiju/main.nf, modules/kaiju/kaiju/meta.yml, tests/modules/kaiju/kaiju/main.nf
=> Update kaiju_kaiju module

tests/config/pytest_modules.yml
=> update gatk4 yml for spark

modules/samtools/collatefastq/main.nf, modules/samtools/collatefastq/meta.yml, tests/config/pytest_modules.yml, tests/modules/samtools/collatefastq/main.nf, tests/modules/samtools/collatefastq/nextflow.config, tests/modules/samtools/collatefastq/test.yml
Following ideas from https://github.com/nf-core/modules/issues/1179
I'm proposing this collate|fastq module
Closes #XXX 
=> Add samtools/collatefastq module

modules/tabix/bgzip/main.nf, modules/tabix/bgzip/meta.yml, tests/config/test_data.config, tests/modules/tabix/bgzip/main.nf, tests/modules/tabix/bgzip/test.yml
=> add decompress possibilities to bgzip

modules/trimgalore/main.nf, modules/trimgalore/meta.yml
x-ref: https://github.com/nf-core/rnaseq/issues/799
=> Add Trimgalore output for unpaired reads

modules/gatk4/splitncigarreads/main.nf, modules/gatk4/splitncigarreads/meta.yml, tests/modules/gatk4/splitncigarreads/main.nf, tests/modules/gatk4/splitncigarreads/test.yml
=> add intervals possibilities to gatk4/splitncigarreads

modules/rsem/calculateexpression/main.nf, modules/rsem/preparereference/main.nf, tests/config/test_data.config, tests/modules/rsem/calculateexpression/test.yml
Bumped in https://github.com/BioContainers/multi-package-containers/pull/2152
=> Bump STAR version to 2.7.10a for RSEM modules

modules/krona/ktimporttext/main.nf, modules/krona/ktimporttext/meta.yml, tests/config/pytest_modules.yml, tests/config/test_data.config, tests/modules/krona/ktimporttext/main.nf, tests/modules/krona/ktimporttext/nextflow.config, tests/modules/krona/ktimporttext/test.yml
=> add kimporttext module

modules/picard/collectwgsmetrics/main.nf, tests/modules/picard/collectwgsmetrics/main.nf
* Make picard stop complaining about it's changing command line syntax
* drop unused bai input
=> picard CollectWgsMetrics: update to new cli args

modules/picard/addorreplacereadgroups/main.nf, modules/picard/cleansam/main.nf, modules/picard/collecthsmetrics/main.nf, modules/picard/collectmultiplemetrics/main.nf, modules/picard/collectwgsmetrics/main.nf, modules/picard/createsequencedictionary/main.nf, modules/picard/crosscheckfingerprints/main.nf, modules/picard/filtersamreads/main.nf, modules/picard/fixmateinformation/main.nf, modules/picard/liftovervcf/main.nf, modules/picard/markduplicates/main.nf, modules/picard/mergesamfiles/main.nf, modules/picard/sortsam/main.nf, modules/picard/sortvcf/main.nf, tests/modules/picard/addorreplacereadgroups/test.yml, tests/modules/picard/cleansam/test.yml, tests/modules/picard/createsequencedictionary/test.yml, tests/modules/picard/fixmateinformation/test.yml, tests/modules/picard/liftovervcf/nextflow.config, tests/modules/picard/markduplicates/nextflow.config
I know this isn't the most friendly way to do this, but it's the fastest 🤷🏻‍♂️  
Feel free to close if you don't like it!
=> bump picard version across the board

modules/gatk4/mergebamalignment/main.nf, modules/gatk4/mutect2/main.nf, modules/gatk4/revertsam/main.nf, modules/gatk4/samtofastq/main.nf, modules/samtools/view/main.nf, tests/modules/gatk4/mergebamalignment/main.nf, tests/modules/gatk4/mergebamalignment/test.yml, tests/modules/gatk4/mutect2/main.nf, tests/modules/gatk4/mutect2/test.yml, tests/modules/gatk4/revertsam/main.nf, tests/modules/gatk4/revertsam/test.yml, tests/modules/gatk4/samtofastq/main.nf, tests/modules/gatk4/samtofastq/test.yml, tests/modules/samtools/view/main.nf, tests/modules/samtools/view/test.yml
=> feat added stub to modules gatk4_mergebamalignment_mutect2_revertsam_samtofastq, samtools_view

modules/slimfastq/main.nf, modules/slimfastq/meta.yml, tests/config/pytest_modules.yml, tests/modules/slimfastq/main.nf, tests/modules/slimfastq/nextflow.config, tests/modules/slimfastq/test.yml
I know that nf-core generally works with gzipped FASTQ files but I'm going to use slimfastq for its lossless high compression capabilities. Maybe it helps someone else 🤷🏼 
=> feat: add module for slimfastq

modules/vardictjava/main.nf, tests/modules/vardictjava/main.nf
=> Small update to vardict-java

modules/svdb/merge/main.nf, modules/svdb/query/main.nf
This PR update svdb from version 2.6.0 to 2.6.1
=> update svdb version

modules/meryl/histogram/main.nf, modules/meryl/histogram/meta.yml, tests/config/pytest_modules.yml, tests/modules/meryl/histogram/main.nf, tests/modules/meryl/histogram/nextflow.config, tests/modules/meryl/histogram/test.yml
Adds the module Meryl Histogram which creates a histogram from a Meryl k-mer database.
Closes #1635  
=> Add meryl histogram

modules/rtgtools/vcfeval/main.nf
=> Added memory allocation to VCFeval

modules/gatk4/splitintervals/main.nf, modules/gatk4/splitintervals/meta.yml, tests/config/pytest_modules.yml, tests/modules/gatk4/splitintervals/main.nf, tests/modules/gatk4/splitintervals/nextflow.config, tests/modules/gatk4/splitintervals/test.yml
=> new module: gatk4/splitintervals

modules/bowtie2/align/main.nf, modules/bowtie2/align/meta.yml, tests/modules/bowtie2/align/main.nf, tests/modules/bowtie2/align/test.yml
add samtools sort option cfr bwa/bwa-mem2
Closes #XXX 
=> Bowtie2: add sort option

modules/bedtools/split/main.nf, modules/bedtools/split/meta.yml, tests/config/pytest_modules.yml, tests/modules/bedtools/split/main.nf, tests/modules/bedtools/split/nextflow.config, tests/modules/bedtools/split/test.yml
=> new module: bedtools split

modules/mash/screen/main.nf, modules/mash/screen/meta.yml, tests/config/pytest_modules.yml, tests/modules/mash/screen/main.nf, tests/modules/mash/screen/nextflow.config, tests/modules/mash/screen/test.yml
Adds the tool Mash Screen
Closes #1681  
=> Add mash screen

modules/gatk4/cnnscorevariants/main.nf, modules/gatk4/cnnscorevariants/meta.yml, modules/gatk4/filtervarianttranches/main.nf, modules/gatk4/filtervarianttranches/meta.yml, tests/config/pytest_modules.yml, tests/config/test_data.config, tests/modules/gatk4/cnnscorevariants/main.nf, tests/modules/gatk4/cnnscorevariants/test.yml, tests/modules/gatk4/filtervarianttranches/main.nf, tests/modules/gatk4/filtervarianttranches/nextflow.config, tests/modules/gatk4/filtervarianttranches/test.yml
=> Gatk filtervarianttranches

modules/cnvkit/antitarget/main.nf, modules/cnvkit/antitarget/meta.yml, tests/config/pytest_modules.yml, tests/modules/cnvkit/antitarget/main.nf, tests/modules/cnvkit/antitarget/nextflow.config, tests/modules/cnvkit/antitarget/test.yml
This PR closes #1661 and can be used in `nf-core/sarek` in `tumor_only mode` when no `reference.cnn` is available and has to be created to run the cnvkit pipeline. 
=> Added module cnvkit/antitarget

modules/cnvkit/batch/main.nf, modules/cnvkit/batch/meta.yml, tests/modules/cnvkit/batch/main.nf, tests/modules/cnvkit/batch/test.yml
This PR improves the runtime of `cnvkit/batch` when `cram` files are used as input. It relies on a new biocontainer that has `samtools` and `cnvkit` in order to convert `cram` to `bam` before running `cnvkit`. I've also added a new test for `cram` input in `tumor_only mode`.
=> Modified cnvkit/batch module: cram2bam conversion

modules/cnvkit/reference/main.nf, modules/cnvkit/reference/meta.yml, tests/config/pytest_modules.yml, tests/config/test_data.config, tests/modules/cnvkit/reference/main.nf, tests/modules/cnvkit/reference/nextflow.config, tests/modules/cnvkit/reference/test.yml
Closes #1662  and can be used in `nf-core/sarek` in `tumor_only mode` when no `reference.cnn` is available and has to be created to run the cnvkit pipeline.
=> Add cnvkit/reference module

modules/umitools/dedup/main.nf, modules/umitools/dedup/meta.yml, tests/modules/umitools/dedup/main.nf, tests/modules/umitools/dedup/nextflow.config, tests/modules/umitools/dedup/test.yml
x-ref: https://github.com/nf-core/rnaseq/issues/827
=> Update umitools/dedup module to make --output-stats optional

modules/cnvkit/reference/main.nf
=> Changed tag of module

modules/mosdepth/main.nf, modules/mosdepth/meta.yml, tests/modules/mosdepth/main.nf, tests/modules/mosdepth/nextflow.config, tests/modules/mosdepth/test.yml
- Add fasta input for cram compatibility
- fix meta.yaml
- add new tests
-   <b>dropped</b>  `window` input, this can be set through `ext.args` 
Closes #XXX 
=> mosdepth: cram compatiblility

modules/cnvkit/reference/main.nf, tests/modules/cnvkit/reference/test.yml
Added prefix to cnvkit/reference
=> Add prefix to cnvkit/reference

modules/bcftools/concat/main.nf, modules/bcftools/concat/meta.yml, tests/modules/bcftools/concat/main.nf, tests/modules/bcftools/concat/test.yml
=> Added optional input of index files to bcftools/concat

modules/gatk4/calibratedragstrmodel/main.nf, modules/gatk4/calibratedragstrmodel/meta.yml, tests/config/pytest_modules.yml, tests/config/test_data.config, tests/modules/gatk4/calibratedragstrmodel/main.nf, tests/modules/gatk4/calibratedragstrmodel/nextflow.config, tests/modules/gatk4/calibratedragstrmodel/test.yml
=> new module gatk4/calibratedragstrmodel

modules/ensemblvep/Dockerfile, modules/ensemblvep/build.sh, modules/ensemblvep/environment.yml
=> update VEP version + cache

modules/gatk4/calibratedragstrmodel/main.nf, modules/gatk4/calibratedragstrmodel/meta.yml, tests/modules/gatk4/calibratedragstrmodel/main.nf, tests/modules/gatk4/calibratedragstrmodel/test.yml
=> add intervals to gatk4/calibratedragstrmodel

modules/gatk/unifiedgenotyper/main.nf, modules/gatk/unifiedgenotyper/meta.yml, tests/config/pytest_modules.yml, tests/modules/gatk/unifiedgenotyper/main.nf, tests/modules/gatk/unifiedgenotyper/nextflow.config, tests/modules/gatk/unifiedgenotyper/test.yml
Note: specifying here GATK 3.5 (rather than the last GATK 3 version of 3.8), because I need specifically the GATK 3.5 UnifiedGenotyper VCF format for a downstream tool used in nf-core/eager (don't ask grimacing).
Originally started by @ilight1542 last year but I've copied over the relevant parts into the latest module structure.
Closes #844 
=> Add gatk/unifiedgenotyper

modules/gatk4/calibratedragstrmodel/main.nf, tests/modules/gatk4/calibratedragstrmodel/test.yml
=> add threads to calibratedragstrmodel

modules/multiqc/main.nf, modules/multiqc/meta.yml, tests/modules/multiqc/main.nf, tests/modules/multiqc/nextflow.config, tests/modules/multiqc/test.yml
=> multiqc: possible fix for name collisions

modules/gatk4/reblockgvcf/main.nf, modules/gatk4/reblockgvcf/meta.yml, tests/config/pytest_modules.yml, tests/modules/gatk4/reblockgvcf/main.nf, tests/modules/gatk4/reblockgvcf/nextflow.config, tests/modules/gatk4/reblockgvcf/test.yml
=> new module gatk4/reblockgvcf

modules/gatk4/applybqsrspark/main.nf, modules/gatk4/baserecalibratorspark/main.nf, modules/gatk4/markduplicatesspark/main.nf, tests/modules/gatk4/applybqsrspark/test.yml, tests/modules/gatk4/markduplicatesspark/test.yml
=> gatk4 version update to 4.2.6.1

modules/cellranger/Dockerfile, modules/cellranger/count/main.nf, modules/cellranger/mkfastq/Dockerfile, modules/cellranger/mkfastq/main.nf, modules/cellranger/mkgtf/main.nf, modules/cellranger/mkref/main.nf, tests/modules/cellranger/count/test.yml, tests/modules/cellranger/mkfastq/test.yml, tests/modules/cellranger/mkgtf/test.yml, tests/modules/cellranger/mkref/test.yml
Updates CellRanger recipe to 7.0.0
Closes #XXX 
=> CellRanger 7.0.0

tests/test_versions_yml.py
=> Allow Git commit SHA's as version numbers

modules/manta/convertinversion/main.nf, modules/manta/convertinversion/meta.yml, tests/config/pytest_modules.yml, tests/modules/manta/convertinversion/main.nf, tests/modules/manta/convertinversion/nextflow.config, tests/modules/manta/convertinversion/test.yml
=> add manta conversion script

modules/samtools/mpileup/main.nf, tests/modules/samtools/mpileup/test.yml
This PR is in response to [this sarek issue](https://github.com/nf-core/sarek/issues/579) and adds a bgzip command to the samtools/mpileup module to reduce output file size.
Closes #XXX 
=> Bgzip samtools/mpileup files

tests/modules/busco/test.yml
=> Change busco multi-fasta test md5sum to contains

modules/tiddit/sv/main.nf, tests/modules/tiddit/sv/main.nf, tests/modules/tiddit/sv/nextflow.config, tests/modules/tiddit/sv/test.yml
=> TIDDIT - add --skip_assembly when no bwa specified

modules/krakentools/kreport2krona/main.nf, modules/krakentools/kreport2krona/meta.yml, tests/config/pytest_modules.yml, tests/modules/krakentools/kreport2krona/main.nf, tests/modules/krakentools/kreport2krona/nextflow.config, tests/modules/krakentools/kreport2krona/test.yml
This module adds support for [KrakenTools](https://github.com/jenniferlu717/KrakenTools)' `kreport2krona` utility.
Closes #1741 
=> New module: krakentools/kreport2krona

modules/rtgtools/pedfilter/main.nf, modules/rtgtools/pedfilter/meta.yml, tests/config/pytest_modules.yml, tests/modules/rtgtools/pedfilter/main.nf, tests/modules/rtgtools/pedfilter/nextflow.config, tests/modules/rtgtools/pedfilter/test.yml
=> new module rtgtools/pedfilter

modules/fastk/histex/main.nf, modules/fastk/histex/meta.yml, tests/config/pytest_modules.yml, tests/modules/fastk/histex/main.nf, tests/modules/fastk/histex/nextflow.config, tests/modules/fastk/histex/test.yml
Adds the tool Fastk/Histex which allows making histograms for GenoScopeFK.
Closes #1763  
=> Add FastK/Histex

modules/merquryfk/merquryfk/main.nf, modules/merquryfk/merquryfk/meta.yml, tests/config/pytest_modules.yml, tests/modules/merquryfk/merquryfk/main.nf, tests/modules/merquryfk/merquryfk/nextflow.config, tests/modules/merquryfk/merquryfk/test.yml
Adds the tool MerquryFK for doing assembly evaluation from a FastK kmer database.
Closes #1765  
=> Add MerquryFK

modules/genescopefk/main.nf, modules/genescopefk/meta.yml, tests/config/pytest_modules.yml, tests/modules/genescopefk/main.nf, tests/modules/genescopefk/nextflow.config, tests/modules/genescopefk/test.yml
Adds the tool GeneScopeFK, a modification of GenomeScope 2.0 to work with Fastk databases
Closes #1764  
=> Add GeneScopeFK

modules/merquryfk/ploidyplot/main.nf, modules/merquryfk/ploidyplot/meta.yml, tests/config/pytest_modules.yml, tests/modules/merquryfk/ploidyplot/main.nf, tests/modules/merquryfk/ploidyplot/nextflow.config, tests/modules/merquryfk/ploidyplot/test.yml
Adds the tool PloidyPlot, an enhanced version of Smudgeplot calculated using a Fastk database.
Closes #1770  
=> Add MerquryFK PloidyPlot

modules/tabix/bgziptabix/main.nf, tests/modules/tabix/bgziptabix/test.yml
=> fix bgziptabix extension

modules/samtools/flagstat/main.nf, modules/samtools/idxstats/main.nf, modules/samtools/stats/main.nf, tests/modules/samtools/flagstat/test.yml, tests/modules/samtools/idxstats/test.yml, tests/modules/samtools/stats/test.yml
=> samtools/*stats*: use prefix for outputs

modules/ensemblvep/main.nf
=> Same version on conda and in the dockerfile

modules/trimmomatic/main.nf, modules/trimmomatic/meta.yml, tests/config/pytest_modules.yml, tests/modules/trimmomatic/main.nf, tests/modules/trimmomatic/nextflow.config, tests/modules/trimmomatic/test.yml
=> Trimmomatic

modules/merquryfk/katcomp/main.nf, modules/merquryfk/katcomp/meta.yml, tests/config/pytest_modules.yml, tests/modules/merquryfk/katcomp/main.nf, tests/modules/merquryfk/katcomp/nextflow.config, tests/modules/merquryfk/katcomp/test.yml
Adds the module Merqury / KatComp which plots a k-mer comparison of two sequencing libraries.
=> Add MerquryFK KatComp

modules/gecco/run/main.nf, modules/gecco/run/meta.yml, tests/config/pytest_modules.yml, tests/modules/gecco/run/main.nf, tests/modules/gecco/run/nextflow.config, tests/modules/gecco/run/test.yml
=> Add gecco/run module

modules/cellranger/count/main.nf
A simple change just to make the module also output the meta map.
=> make module output meta map

modules/merquryfk/katgc/main.nf, modules/merquryfk/katgc/meta.yml, tests/config/pytest_modules.yml, tests/modules/merquryfk/katgc/main.nf, tests/modules/merquryfk/katgc/nextflow.config, tests/modules/merquryfk/katgc/test.yml
Adds the tool KatGC to plot GC content from the MerquryFK package designed to work with FastK databases. 
=> Add MerquryFK KatGC

modules/bclconvert/main.nf, modules/bclconvert/meta.yml, tests/modules/bclconvert/test.yml
Pending update of `nfcore/bclconvert` docker image
Closes #XXX 
=> bump bclconvert version

modules/vcfanno/main.nf, tests/modules/vcfanno/main.nf, tests/modules/vcfanno/test.yml
=> small changes to vcfanno

modules/bclconvert/Dockerfile, modules/bclconvert/main.nf
=> bclconvert: Update Dockerfile

modules/bcftools/norm/main.nf, modules/bcftools/norm/meta.yml, modules/cellranger/count/main.nf, tests/modules/bcftools/norm/main.nf, tests/modules/bcftools/norm/test.yml
=> added an optional vcf index to bcftools/norm

modules/snapaligner/align/main.nf, modules/snapaligner/align/meta.yml, tests/modules/snapaligner/align/main.nf, tests/modules/snapaligner/align/nextflow.config, tests/modules/snapaligner/align/test.yml
=> add extra output from snap aligner

modules/fastk/merge/main.nf, modules/fastk/merge/meta.yml, tests/config/pytest_modules.yml, tests/modules/fastk/fastk/test.yml, tests/modules/fastk/merge/main.nf, tests/modules/fastk/merge/nextflow.config, tests/modules/fastk/merge/test.yml
Adds the tool Fastmerge from the Fastk toolkit, and fixes the capture of a missing hidden file from FASTK_FASTK.
Closes #XXX 
=> Add FastK/Merge

modules/snapaligner/align/main.nf, modules/snapaligner/index/main.nf
=> snapaligner: fix quotes

modules/snapaligner/align/main.nf, tests/modules/snapaligner/align/test.yml
=> snapaligner: improve index detection

modules/khmer/uniquekmers/main.nf, modules/khmer/uniquekmers/meta.yml, tests/config/pytest_modules.yml, tests/modules/khmer/uniquekmers/main.nf, tests/modules/khmer/uniquekmers/nextflow.config, tests/modules/khmer/uniquekmers/test.yml
Add khmer unique-kmers.py module
=> Add khmer unique-kmers.py module

modules/umitools/dedup/main.nf
=> Set randomseed for UMI tools if not otherwise set

modules/gunzip/main.nf
Add stub run to gunzip module, needed for testing purposes of the nf-core/proteinfold pipeline.
=> Add stub run to gunzip module

modules/megan/daa2info/main.nf, modules/megan/daa2info/meta.yml, tests/config/pytest_modules.yml, tests/modules/megan/daa2info/main.nf, tests/modules/megan/daa2info/nextflow.config, tests/modules/megan/daa2info/test.yml
Closes #1847 
Basically a clone of MEGAN/RMA2INFO but with daa files as input
=> Add MEGAN/DAA2INFO

modules/cnvpytor/callcnvs/main.nf, modules/cnvpytor/histogram/main.nf, modules/cnvpytor/importreaddepth/main.nf, modules/cnvpytor/partition/main.nf, modules/cnvpytor/view/main.nf
Just removed some extra ) from the version string in all of the cnvpytor modules :)
=> removed extra ) in the version strings

modules/multiqc/main.nf
As discussed with @SusiJo on slack, bugfix to also have conda use 1.13a
Closes #XXX 
=> Fix MultiQC conda

modules/fgbio/fastqtobam/main.nf
This PR updates the fgbio container version to get rid of a snappyjava error.
=> This updates the fgbio container version

.editorconfig, CITATION.cff
Added a `CITATION.cff` file for the `nf-core` publication. This was suggested in https://github.com/nf-core/tools/issues/361.
Closes #XXX 
=> Add CITATION.cff file for the nf-core publication

modules/kallistobustools/count/main.nf, tests/modules/kallistobustools/count/test.yml
Kallisto was being told to ask for the same amount of memory as it was said for nextflow to limit.
So, when kallisto tried to use it, nextflow was killing it. Thus, diminishing it per 1 GB solved the issue.
=> diminish memory demand

modules/porechop/main.nf, modules/porechop/meta.yml, tests/modules/porechop/test.yml
This will be useful for reporting statistics in a MultiQC module
=> Update PORECHOP module to output log file

modules/ensemblvep/Dockerfile, modules/ensemblvep/build.sh, modules/ensemblvep/environment.yml, modules/ensemblvep/main.nf, tests/modules/ensemblvep/main.nf, tests/modules/ensemblvep/nextflow.config
=> update ensemblvep to 106.1 and cache to 106

modules/snpeff/Dockerfile, modules/snpeff/build.sh, modules/snpeff/environment.yml, modules/snpeff/main.nf, tests/modules/snpeff/main.nf, tests/modules/snpeff/nextflow.config, tests/modules/snpeff/test.yml
=> update snpeff to 5.1 and cache up to 105

modules/samtools/stats/main.nf
=> more generic name because of multiple extension

modules/kallistobustools/count/main.nf, tests/modules/kallistobustools/count/test.yml
=> Improved kbtools/count

tests/modules/entrezdirect/esummary/test.yml
The test is otherwise failing the MD5 checksums is wrong.
=> Fixed the MD5 checksum

modules/bcftools/stats/main.nf, modules/bcftools/stats/meta.yml, tests/modules/bcftools/stats/main.nf
Adds a target_bed file to mandatory inputs for WES and correctly spreads the command over multiple lines. 
=> Update bcftools/stats for WES

modules/biobambam/bamsormadup/main.nf, tests/modules/biobambam/bamsormadup/main.nf, tests/modules/biobambam/bamsormadup/test.yml
=> bamsormadup: add extra test case, fix single file input

modules/bcftools/convert/main.nf, modules/bcftools/convert/meta.yml, tests/config/pytest_modules.yml, tests/modules/bcftools/convert/main.nf, tests/modules/bcftools/convert/nextflow.config, tests/modules/bcftools/convert/test.yml
=> added bcftools convert

modules/hamronization/abricate/main.nf, modules/hamronization/abricate/meta.yml, tests/config/pytest_modules.yml, tests/config/test_data.config, tests/modules/hamronization/abricate/main.nf, tests/modules/hamronization/abricate/nextflow.config, tests/modules/hamronization/abricate/test.yml, tests/modules/hamronization/deeparg/main.nf
Adding another AMR module to the hamronization summary module. Required test data is in a [separate PR](https://github.com/nf-core/test-datasets/pull/578) in the test-datasets repository.
Closes #XXX 
=> Add module `hamronization/abricate`

modules/entrezdirect/esummary/main.nf, modules/entrezdirect/esummary/meta.yml, tests/modules/entrezdirect/esummary/main.nf, tests/modules/entrezdirect/esummary/nextflow.config, tests/modules/entrezdirect/esummary/test.yml
=> renamed output in entrezdirect/esummary: xml

modules/entrezdirect/xtract/main.nf, modules/entrezdirect/xtract/meta.yml, tests/config/pytest_modules.yml, tests/modules/entrezdirect/xtract/main.nf, tests/modules/entrezdirect/xtract/nextflow.config, tests/modules/entrezdirect/xtract/test.yml
=> new (fixed) module: entrezdirect/xtract

modules/entrezdirect/esearch/main.nf, modules/entrezdirect/esearch/meta.yml, tests/config/pytest_modules.yml, tests/modules/entrezdirect/esearch/main.nf, tests/modules/entrezdirect/esearch/nextflow.config, tests/modules/entrezdirect/esearch/test.yml
=> new (fixed) module: entrezdirect/esearch

modules/samtools/dict/main.nf, modules/samtools/dict/meta.yml, tests/config/pytest_modules.yml, tests/modules/samtools/dict/main.nf, tests/modules/samtools/dict/nextflow.config, tests/modules/samtools/dict/test.yml
Adds a module for samtools/dict
Closes #1918
=> Added the samtools/dict module

modules/centrifuge/kreport/main.nf, modules/centrifuge/kreport/meta.yml, tests/modules/centrifuge/kreport/test.yml
=> Update module: Use report insted of results for centrifuge/kreport

modules/gecco/run/main.nf, modules/gecco/run/meta.yml
=> Update module: Gecco fix to no file generated if no hits found

modules/cat/fastq/main.nf, tests/modules/cat/fastq/test.yml
add stub for cat/fastq
Closes #XXX 
=> add stub for cat/fastq

modules/kallisto/index/main.nf, tests/modules/kallisto/index/test.yml
=> add stub for kallisto/index

modules/picard/collectwgsmetrics/main.nf, tests/modules/picard/collectwgsmetrics/test.yml
add stub for picard/collectwgsmtrics
=> add stub for picard/collectwgsmtrics

modules/star/align/main.nf, modules/star/genomegenerate/main.nf, tests/modules/star/align/test.yml, tests/modules/star/genomegenerate/test.yml
=> Add stub star align genomegenerate

modules/stringtie/merge/main.nf, modules/stringtie/stringtie/main.nf, tests/modules/stringtie/merge/test.yml, tests/modules/stringtie/stringtie/test.yml
=> add stub for stringtie

modules/genmod/annotate/main.nf, modules/genmod/annotate/meta.yml, modules/genmod/compound/main.nf, modules/genmod/compound/meta.yml, modules/genmod/models/main.nf, modules/genmod/models/meta.yml, modules/genmod/score/main.nf, modules/genmod/score/meta.yml, tests/config/pytest_modules.yml, tests/config/test_data.config, tests/modules/genmod/annotate/main.nf, tests/modules/genmod/annotate/nextflow.config, tests/modules/genmod/annotate/test.yml, tests/modules/genmod/compound/main.nf, tests/modules/genmod/compound/nextflow.config, tests/modules/genmod/compound/test.yml, tests/modules/genmod/models/main.nf, tests/modules/genmod/models/nextflow.config, tests/modules/genmod/models/test.yml, tests/modules/genmod/score/main.nf, tests/modules/genmod/score/nextflow.config, tests/modules/genmod/score/test.yml
This PR adds annotate, model, score and compound functionalities of genmod
=> Add genmod

modules/ncbigenomedownload/main.nf
The container referenced in the current module has a broken `/etc/resolv.conf` that prevents the software from downloading anything.
```
Command executed:
ncbi-genome-download \
-A GCF_000013425.1 --formats genbank,fasta,assembly-stats bacteria \
\
--output-folder ./ \
--flat-output
cat <<-END_VERSIONS > versions.yml
"test_ncbigenomedownload:NCBIGENOMEDOWNLOAD":
ncbigenomedownload: $( ncbi-genome-download --version )
END_VERSIONS
Command exit status:
75
Command output:
(empty)
Command error:
WARNING: While bind mounting '/lustre/scratch123/tol/teams/tolit/users/mm49/nextflow/pytest_workflow_8vyyn1d4/ncbigenomedownload_test_ncbigenomedownload/work/51/2e68040123c4cbb1ed41a875f3bff5:/lustre/scratch123/tol/teams/tolit/users/mm49/nextflow/pytest_workflow_8vyyn1d4/ncbigenomedownload_test_ncbigen …
```
=> Use a newer container version because the previous one is broken

modules/fq/lint/main.nf, modules/fq/lint/meta.yml, tests/config/pytest_modules.yml, tests/modules/fq/lint/main.nf, tests/modules/fq/lint/nextflow.config, tests/modules/fq/lint/test.yml
Additions:
- fq/lint module, which checks paired end FASTQ files and confirms they
are valid.
Relates to #1967
Closes #XXX 
=> Added fq/lint module

modules/bwamem2/index/meta.yml
=> typo in bwamem2 index meta.yml

modules/picard/addorreplacereadgroups/main.nf
=> Included args option in picard AddOrReplaceReadGroups

modules/samtools/stats/main.nf, tests/modules/samtools/stats/test.yml
=> fix samtools stats thread usage

modules/pints/caller/main.nf, modules/pints/caller/meta.yml, tests/config/pytest_modules.yml, tests/modules/pints/caller/main.nf, tests/modules/pints/caller/nextflow.config, tests/modules/pints/caller/test.yml
=> feat(pints): Add initial caller module

modules/delly/call/main.nf, tests/modules/delly/call/main.nf, tests/modules/delly/call/test.yml
=> Update delly/call version

modules/whamg/main.nf, modules/whamg/meta.yml, tests/config/pytest_modules.yml, tests/modules/whamg/main.nf, tests/modules/whamg/nextflow.config, tests/modules/whamg/test.yml
=> New module: Whamg

modules/bakta/main.nf
Updates bakta to latest version with pseudogene support
Closes #XXX 
=> [update] bump Bakta to 1.5.0

modules/delly/call/main.nf, modules/delly/call/meta.yml, tests/modules/delly/call/main.nf, tests/modules/delly/call/test.yml
=> Update for the delly/call module

modules/delly/call/main.nf, tests/modules/delly/call/main.nf
=> Another update to delly/call

modules/deepbgc/download/main.nf, modules/deepbgc/download/meta.yml, tests/config/pytest_modules.yml, tests/modules/deepbgc/download/main.nf, tests/modules/deepbgc/download/nextflow.config, tests/modules/deepbgc/download/test.yml
Closes #2007 
- [x ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [x ] Emit the `versions.yml` file.
- [x ] Follow the naming conventions.
- [x ] Follow the parameters requirements.
- [x ] Follow the input/output options guidelines.
- [x ] Add a resource `label`
- [x ] Use BioConda and BioContainers if possible to fulfil software requirements.
- [ x] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
=> Deepbgcdownload

modules/krakentools/combinekreports/main.nf, modules/krakentools/combinekreports/meta.yml, tests/config/pytest_modules.yml, tests/modules/krakentools/combinekreports/main.nf, tests/modules/krakentools/combinekreports/nextflow.config, tests/modules/krakentools/combinekreports/test.yml
=> Add krakentools/combinekreports

modules/bracken/combinebrackenoutputs/main.nf, modules/bracken/combinebrackenoutputs/meta.yml, tests/config/pytest_modules.yml, tests/modules/bracken/combinebrackenoutputs/main.nf, tests/modules/bracken/combinebrackenoutputs/nextflow.config, tests/modules/bracken/combinebrackenoutputs/test.yml
Closes https://github.com/nf-core/modules/issues/2020
=> Add bracken/combinebrackenoutputs

modules/bcftools/stats/main.nf, modules/custom/dumpsoftwareversions/main.nf, modules/manta/germline/main.nf, modules/manta/somatic/main.nf, modules/manta/tumoronly/main.nf, modules/samtools/convert/main.nf, modules/samtools/faidx/main.nf, modules/samtools/mpileup/main.nf, modules/samtools/view/main.nf, modules/strelka/germline/main.nf, modules/strelka/somatic/main.nf, modules/tabix/bgzip/main.nf, modules/tabix/bgziptabix/main.nf, modules/tabix/tabix/main.nf, modules/untar/main.nf, modules/unzip/main.nf, modules/vcftools/main.nf
=> Reduce resource requests

modules/pints/caller/main.nf
=> fix(pints): Remove update check

modules/multiqc/main.nf, modules/multiqc/meta.yml, tests/modules/multiqc/main.nf, tests/modules/multiqc/test.yml
Remove MultiQC logo from input channel (has to be specified within the config, not via a specific command line parameter, so the file can just be mixed as the other MultiQC input files)
See: https://nfcore.slack.com/archives/CE5LG7WMB/p1662624779370559?thread_ts=1662617706.279959&cid=CE5LG7WMB
Closes #XXX 
=> Multiqc sep logo

modules/svtk/standardize/main.nf, modules/svtk/standardize/meta.yml, tests/config/pytest_modules.yml, tests/modules/svtk/standardize/main.nf, tests/modules/svtk/standardize/nextflow.config, tests/modules/svtk/standardize/test.yml
=> new module: svtk/standardize

modules/ucsc/bedtobigbed/main.nf, modules/ucsc/bedtobigbed/meta.yml, tests/config/test_data.config, tests/modules/ucsc/bedgraphtobigwig/test.yml, tests/modules/ucsc/bedtobigbed/main.nf, tests/modules/ucsc/bedtobigbed/nextflow.config, tests/modules/ucsc/bedtobigbed/test.yml
Added support for the (optional) `-as` option in `bedToBigBed`
Closes #XXX 
=> bedToBigBed AutoSql option

modules/gatk4/collectsvevidence/main.nf, modules/gatk4/collectsvevidence/meta.yml, tests/config/pytest_modules.yml, tests/modules/gatk4/collectsvevidence/main.nf, tests/modules/gatk4/collectsvevidence/nextflow.config, tests/modules/gatk4/collectsvevidence/test.yml
=> new module gatk4/collectsvevidence

modules/multiqc/main.nf
Just wanted to update the module myself, but @robsyme was faster 🚀
=> Multiqc v1.13 release update (by @robsyme)

modules/eido/convert/main.nf, modules/eido/convert/meta.yml, tests/config/pytest_modules.yml, tests/modules/eido/convert/main.nf, tests/modules/eido/convert/nextflow.config, tests/modules/eido/convert/test.yml
This PR adds EIDO/VALIDATE command that will be used for integrating PEP format with `nf-core` pipelines. Changes:
- Introduced EIDO/CONVERT as a module
- Added unittests
Closes #2016 
=> Add eido/convert module

modules/picard/addorreplacereadgroups/main.nf, tests/modules/picard/addorreplacereadgroups/test.yml
This PR adds stub section to picard/addorreplacereadgroups module
=> add stub to picard/addorreplacereadgroups

modules/eido/validate/main.nf
This PR bumps the version of container for eido including newest bugfix
=> Update container version

modules/untar/main.nf, tests/modules/untar/test.yml
=> Fix for nested directories in tar archive

modules/ucsc/wigtobigwig/main.nf, tests/modules/ucsc/wigtobigwig/test.yml
This PR adds version line to the stub section of ucsc/wigtobigwig
=> Update stub for ucsc/wigtobigwig

modules/svdb/merge/main.nf, tests/modules/svdb/merge/test.yml
=> update stub for svdb/merge

modules/bases2fastq/main.nf, modules/bases2fastq/meta.yml, tests/config/pytest_modules.yml, tests/modules/bases2fastq/main.nf, tests/modules/bases2fastq/nextflow.config, tests/modules/bases2fastq/test.yml
Adds a basic module for element biosciences bases2fastq
=> Add bases2fastq

modules/eido/convert/main.nf, modules/eido/convert/meta.yml, tests/modules/eido/convert/main.nf, tests/modules/eido/convert/test.yml
I had to provide the path to pep_input_base_dir because the tests were failing for local files.
=> Update eido/convert module

modules/eido/validate/main.nf, modules/eido/validate/meta.yml, tests/modules/eido/validate/main.nf
I had to provide the path to `pep_input_base_dir` because the tests were failing for local files.
=> Update eido/validate module

modules/hmmer/eslreformat/main.nf, modules/hmmer/eslreformat/meta.yml, tests/modules/hmmer/eslreformat/main.nf, tests/modules/hmmer/eslreformat/nextflow.config, tests/modules/hmmer/eslreformat/test.yml
Update the module to use the last argument which specifies output format as suffix.
(I wouldn't mind a tip for how I could make the output statement more specific by including the calculated suffix.)
=> eslreformat: descriptive suffix

modules/samtools/merge/main.nf, modules/samtools/merge/meta.yml, modules/samtools/sort/main.nf, modules/samtools/sort/meta.yml, modules/samtools/view/main.nf, modules/samtools/view/meta.yml
The samtools subcommands `view`, `sort` and `merge` can optionally generate the bam index on the fly, by passing the argument `--write-index`. This PR adds an optional output for the BAM index, for when `--write-index` is passed to `ext.args`.
Closes #XXX 
=> [samtools] add optional csi output

modules/samtools/collate/main.nf, modules/samtools/collate/meta.yml, tests/config/pytest_modules.yml, tests/modules/samtools/collate/main.nf, tests/modules/samtools/collate/nextflow.config, tests/modules/samtools/collate/test.yml
Creates a stand alone samtools collate module. Needed for samtools markdup.
Closes #XXX 
- [ x] This comment contains a description of changes (with reason).
- [x ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [x ] If necessary, include test data in your PR.
- [x ] Follow the naming conventions.
- [x ] Follow the input/output options guidelines.
- [ x] Add a resource `label`
- [ x] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the …
=> samtools collate module

modules/samtools/markdup/main.nf, modules/samtools/markdup/meta.yml, tests/config/pytest_modules.yml, tests/modules/samtools/markdup/main.nf, tests/modules/samtools/markdup/nextflow.config, tests/modules/samtools/markdup/test.yml
Samtools markdup module
Closes #XXX 
- [x ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ x] Add a resource `label`
- [ x] Use BioConda and BioContainers if possible to fulfil software requirements.
- [ x] …
=> samtools markdup module

modules/gappa/examineheattree/main.nf, modules/gappa/examineheattree/meta.yml, tests/config/pytest_modules.yml, tests/modules/gappa/examineheattree/main.nf, tests/modules/gappa/examineheattree/nextflow.config, tests/modules/gappa/examineheattree/test.yml
This adds a module for the `gappa examine heat-tree` program call.
=> Adding gappa/examineheattree

modules/samtools/view/main.nf, modules/samtools/view/meta.yml, tests/modules/samtools/view/main.nf, tests/modules/samtools/view/nextflow.config, tests/modules/samtools/view/test.yml
- Adds functionality to convert from bam to cram and vice versa
- Adds test to check cram to bam
- Removes csi output
Closes #XXX 
- [x ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
=> Update samtools view

modules/goat/taxonsearch/main.nf, tests/modules/goat/taxonsearch/main.nf, tests/modules/goat/taxonsearch/test.yml
=> 2012 bug related to species input in goattaxonsearch module

modules/dshbio/exportsegments/main.nf, modules/dshbio/filterbed/main.nf, modules/dshbio/filtergff3/main.nf, modules/dshbio/splitbed/main.nf, modules/dshbio/splitgff3/main.nf
=> Update dsh-bio to 2.1

modules/delly/call/main.nf, tests/modules/delly/call/test.yml
=> updated the version of delly

modules/deepvariant/main.nf
simplify deepvariant container call
Closes #XXX 
=> Deepvariant - Update main.nf

modules/samtools/getrg/main.nf, modules/samtools/getrg/meta.yml, tests/config/pytest_modules.yml, tests/modules/samtools/getrg/main.nf, tests/modules/samtools/getrg/nextflow.config, tests/modules/samtools/getrg/test.yml
Add module to get RG info from bam/cram files
Closes #XXX 
=> new module: samtools/getrg

modules/deepvariant/main.nf, modules/ensemblvep/main.nf, tests/modules/ensemblvep/main.nf, tests/modules/ensemblvep/nextflow.config, tests/modules/ensemblvep/test.yml
This PR adds a stub section, the option to get compress output, and relevant tests
=> add stub and the option to compress output for vep

modules/checkm/lineagewf/main.nf, modules/checkm/lineagewf/meta.yml, tests/modules/checkm/lineagewf/main.nf
Note I cannot test the new functionality, as the CI tests they are already taking too long due to the database downloading/singularity image size and the database is too large for packaging test-datasets.
=> Update checkM version and add support for pre-defined database

modules/trimgalore/main.nf
=> Update cores specification in TrimGalore module

modules/samtools/fasta/main.nf, modules/samtools/fasta/meta.yml, tests/config/pytest_modules.yml, tests/modules/samtools/fasta/main.nf, tests/modules/samtools/fasta/nextflow.config, tests/modules/samtools/fasta/test.yml
`samtools/fasta` module -- very similar to [`samtools/fastq`](https://github.com/nf-core/modules/blob/master/modules/samtools/fastq)
- [ x] This comment contains a description of changes (with reason).
- [ x] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ x] Add a resource `label`
- [ x] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test …
=> samtools fasta module

modules/nf-core/yara/index/main.nf, modules/nf-core/yara/mapper/main.nf, tests/modules/nf-core/yara/index/main.nf, tests/modules/nf-core/yara/index/test.yml, tests/modules/nf-core/yara/mapper/main.nf, tests/modules/nf-core/yara/mapper/test.yml
This 
- updates the `yara index` module and adds `meta` to the process
- adapts the tests
- adapts the `yara mapper` and tests accordingly.
=> Update yara index and yara mapper

modules/nf-core/wgsim/main.nf, modules/nf-core/wgsim/meta.yml, tests/config/pytest_modules.yml, tests/modules/nf-core/wgsim/main.nf, tests/modules/nf-core/wgsim/nextflow.config, tests/modules/nf-core/wgsim/test.yml
New module for software `wgsim` to simulate short read from genome fasta
Closes #XXX 
- [ x] This comment contains a description of changes (with reason).
- [ x] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ x] If necessary, include test data in your PR.
- [ x] Remove all TODO statements.
- [ x] Add a resource `label`
- [ x] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test …
=> New module: wgsim

tests/config/pytest_modules.yml, tests/subworkflows/nf-core/align_bowtie2/test.yml, tests/subworkflows/nf-core/annotation/ensemblvep/test.yml, tests/subworkflows/nf-core/annotation/snpeff/test.yml, tests/subworkflows/nf-core/bam_qc_picard/test.yml, tests/subworkflows/nf-core/bam_sort_samtools/test.yml, tests/subworkflows/nf-core/bam_stats_samtools/test.yml, tests/subworkflows/nf-core/fgbio_create_umi_consensus/test.yml, tests/subworkflows/nf-core/gatk_create_som_pon/test.yml, tests/subworkflows/nf-core/gatk_tumor_normal_somatic_variant_calling/test.yml, tests/subworkflows/nf-core/gatk_tumor_only_somatic_variant_calling/test.yml, tests/subworkflows/nf-core/homer/groseq/test.yml, tests/subworkflows/nf-core/srafastq/test.yml
This updates the tags for subworkflows, so the tests get triggered.
=> Add tags to test subworkflows

tests/modules/nf-core/ncbigenomedownload/test.yml
=> fix_md5sum_error (checked output)

modules/nf-core/picard/renamesampleinvcf/main.nf, modules/nf-core/picard/renamesampleinvcf/meta.yml, tests/config/pytest_modules.yml, tests/modules/nf-core/picard/renamesampleinvcf/main.nf, tests/modules/nf-core/picard/renamesampleinvcf/nextflow.config, tests/modules/nf-core/picard/renamesampleinvcf/test.yml
=> Picard rename sample in vcf

tests/subworkflows/nf-core/fastq_align_dna/test.yml
=> fix subwf ci

subworkflows/nf-core/align_bowtie2/main.nf, subworkflows/nf-core/gatk_create_som_pon/main.nf, subworkflows/nf-core/gatk_tumor_normal_somatic_variant_calling/main.nf, subworkflows/nf-core/gatk_tumor_only_somatic_variant_calling/main.nf, tests/modules/nf-core/amplify/predict/main.nf, tests/modules/nf-core/maxquant/lfq/main.nf, tests/subworkflows/nf-core/align_bowtie2/main.nf, tests/subworkflows/nf-core/bam_qc_picard/main.nf, tests/subworkflows/nf-core/gatk_create_som_pon/main.nf, tests/subworkflows/nf-core/gatk_tumor_normal_somatic_variant_calling/main.nf, tests/subworkflows/nf-core/gatk_tumor_only_somatic_variant_calling/main.nf
=> chore: Remove addParams

modules/nf-core/picard/markduplicates/main.nf, modules/nf-core/picard/markduplicates/meta.yml, tests/modules/nf-core/picard/markduplicates/main.nf, tests/modules/nf-core/picard/markduplicates/nextflow.config, tests/modules/nf-core/picard/markduplicates/test.yml
Closes #[2245](https://github.com/nf-core/modules/issues/2245) 
=> Markduplicates

.github/workflows/code-linting.yml, .github/workflows/fix-linting.yml, .github/workflows/issues.yml, .github/workflows/nf-core-linting.yml, .github/workflows/pytest-workflow.yml
=> Move modules to run on self-hosted for now

modules/nf-core/msisensor2/msi/meta.yml, subworkflows/nf-core/fastq_align_hisat2/main.nf, subworkflows/nf-core/fastq_align_hisat2/meta.yml, tests/config/pytest_modules.yml, tests/subworkflows/nf-core/fastq_align_hisat2/main.nf, tests/subworkflows/nf-core/fastq_align_hisat2/nextflow.config, tests/subworkflows/nf-core/fastq_align_hisat2/test.yml
Closes #2264  
- [ x] This comment contains a description of changes (with reason).
- [x ] If necessary, include test data in your PR.
- [ x] Remove all TODO statements.
- [ x] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
=> Fastq align hisat2

subworkflows/nf-core/bam_markduplicates_picard/main.nf, subworkflows/nf-core/bam_markduplicates_picard/meta.yml, tests/config/pytest_modules.yml, tests/subworkflows/nf-core/bam_markduplicates_picard/main.nf, tests/subworkflows/nf-core/bam_markduplicates_picard/nextflow.config, tests/subworkflows/nf-core/bam_markduplicates_picard/test.yml
=> add subworkflow bam_markduplicates_picard

.github/workflows/code-linting.yml, .github/workflows/fix-linting.yml, .github/workflows/issues.yml, .github/workflows/nf-core-linting.yml, .github/workflows/pytest-workflow.yml
=> Revert "Move modules to run on self-hosted for now"

.github/ISSUE_TEMPLATE/new_subworkflow.yml
=> chore: Add a "New subworkflow" issue template

modules/nf-core/aria2/meta.yml
=> Fix typo in meta yml

modules/nf-core/samtools/view/main.nf
=> feat added args2 to samtools view

modules/nf-core/bowtie2/align/main.nf, modules/nf-core/bowtie2/align/meta.yml, modules/nf-core/bowtie2/build/main.nf, modules/nf-core/bowtie2/build/meta.yml, subworkflows/nf-core/fastq_align_dna/README.md, tests/modules/nf-core/bowtie2/align/main.nf, tests/modules/nf-core/bowtie2/align/nextflow.config, tests/modules/nf-core/bowtie2/align/test.yml, tests/modules/nf-core/bowtie2/build_test/main.nf, tests/modules/nf-core/bowtie2/build_test/test.yml, tests/subworkflows/nf-core/fastq_align_bowtie2/main.nf, tests/subworkflows/nf-core/fastq_align_bowtie2/nextflow.config, tests/subworkflows/nf-core/fastq_align_bowtie2/test.yml, tests/subworkflows/nf-core/fastq_align_dna/main.nf
=> add meta to bowtie2 index

modules/nf-core/dragmap/align/main.nf, modules/nf-core/dragmap/align/meta.yml, modules/nf-core/dragmap/hashtable/main.nf, modules/nf-core/dragmap/hashtable/meta.yml, tests/modules/nf-core/dragmap/align/main.nf, tests/modules/nf-core/dragmap/hashtable/main.nf, tests/subworkflows/nf-core/fastq_align_dna/main.nf
=> add meta to dragmap hashtable

subworkflows/nf-core/homer/groseq/main.nf
Fixes https://github.com/nf-core/nascent/pull/75
=> fix(homer): Update module include paths

modules/nf-core/gatk4/svcluster/main.nf, modules/nf-core/gatk4/svcluster/meta.yml, tests/config/pytest_modules.yml, tests/modules/nf-core/gatk4/svcluster/main.nf, tests/modules/nf-core/gatk4/svcluster/nextflow.config, tests/modules/nf-core/gatk4/svcluster/test.yml
=> new module gatk4/svcluster

modules/nf-core/gatk4/condensedepthevidence/main.nf, modules/nf-core/gatk4/condensedepthevidence/meta.yml, tests/config/pytest_modules.yml, tests/modules/nf-core/gatk4/condensedepthevidence/main.nf, tests/modules/nf-core/gatk4/condensedepthevidence/nextflow.config, tests/modules/nf-core/gatk4/condensedepthevidence/test.yml
=> new module gatk4/condensedepthevidence

modules/nf-core/svtk/vcf2bed/main.nf, modules/nf-core/svtk/vcf2bed/meta.yml, tests/config/pytest_modules.yml, tests/modules/nf-core/svtk/vcf2bed/main.nf, tests/modules/nf-core/svtk/vcf2bed/nextflow.config, tests/modules/nf-core/svtk/vcf2bed/test.yml
=> new module svtk/vcf2bed

modules/nf-core/bedtools/closest/main.nf, modules/nf-core/bedtools/closest/meta.yml, tests/config/pytest_modules.yml, tests/modules/nf-core/bedtools/closest/main.nf, tests/modules/nf-core/bedtools/closest/nextflow.config, tests/modules/nf-core/bedtools/closest/test.yml
=> new module bedtools/closest

modules/nf-core/gatk4/svannotate/main.nf, modules/nf-core/gatk4/svannotate/meta.yml, tests/config/pytest_modules.yml, tests/modules/nf-core/gatk4/svannotate/main.nf, tests/modules/nf-core/gatk4/svannotate/nextflow.config, tests/modules/nf-core/gatk4/svannotate/test.yml
=> new module gatk4/svannotate

modules/nf-core/odgi/sort/main.nf, modules/nf-core/odgi/sort/meta.yml, tests/config/pytest_modules.yml, tests/modules/nf-core/odgi/sort/main.nf, tests/modules/nf-core/odgi/sort/nextflow.config, tests/modules/nf-core/odgi/sort/test.yml
This PR progresses https://github.com/nf-core/pangenome/issues/70.
=> add module odgi/sort

modules/nf-core/samtools/collatefastq/main.nf, modules/nf-core/samtools/collatefastq/meta.yml, tests/modules/nf-core/samtools/collatefastq/main.nf, tests/modules/nf-core/samtools/collatefastq/test.yml
- Add fasta input for crams
- Add `interleave` option for interleaved output
- Add support for SE input/output
Closes #XXX 
=> samtools/collatefastq: cram compatibility, interleaved option, SE inputs

modules/nf-core/odgi/unchop/main.nf, modules/nf-core/odgi/unchop/meta.yml, tests/config/pytest_modules.yml, tests/modules/nf-core/odgi/unchop/main.nf, tests/modules/nf-core/odgi/unchop/nextflow.config, tests/modules/nf-core/odgi/unchop/test.yml
This PR progresses https://github.com/nf-core/pangenome/issues/70.
=> new module odgi/unchop

modules/nf-core/odgi/view/main.nf, modules/nf-core/odgi/view/meta.yml, tests/config/pytest_modules.yml, tests/modules/nf-core/odgi/view/main.nf, tests/modules/nf-core/odgi/view/nextflow.config, tests/modules/nf-core/odgi/view/test.yml
This PR progresses https://github.com/nf-core/pangenome/issues/70.
=> add module odgi/view

modules/nf-core/svtk/countsvtypes/main.nf, modules/nf-core/svtk/countsvtypes/meta.yml, tests/config/pytest_modules.yml, tests/modules/nf-core/svtk/countsvtypes/main.nf, tests/modules/nf-core/svtk/countsvtypes/nextflow.config, tests/modules/nf-core/svtk/countsvtypes/test.yml
=> new module svtk/countsvtypes

modules/nf-core/bwa/index/main.nf
=> fixed spaces

modules/nf-core/mageck/mle/main.nf, modules/nf-core/mageck/mle/meta.yml, tests/config/pytest_modules.yml, tests/modules/nf-core/mageck/mle/main.nf, tests/modules/nf-core/mageck/mle/nextflow.config, tests/modules/nf-core/mageck/mle/test.yml
=> New module subcommand : mageck mle

modules/nf-core/concoct/concoct/main.nf, modules/nf-core/concoct/concoct/meta.yml, tests/config/pytest_modules.yml, tests/modules/nf-core/concoct/concoct/main.nf, tests/modules/nf-core/concoct/concoct/nextflow.config, tests/modules/nf-core/concoct/concoct/test.yml
=> New module: CONCOCT_CONCOCT

modules/nf-core/concoct/mergecutupclustering/main.nf, modules/nf-core/concoct/mergecutupclustering/meta.yml, tests/config/pytest_modules.yml, tests/modules/nf-core/concoct/mergecutupclustering/main.nf, tests/modules/nf-core/concoct/mergecutupclustering/nextflow.config, tests/modules/nf-core/concoct/mergecutupclustering/test.yml
=> Add CONCOCT/MERGECUTUPCLUSTERING

modules/nf-core/concoct/extractfastabins/main.nf, modules/nf-core/concoct/extractfastabins/meta.yml, subworkflows/nf-core/fasta_index_dna/main.nf, tests/config/pytest_modules.yml, tests/modules/nf-core/concoct/concoct/main.nf, tests/modules/nf-core/concoct/extractfastabins/main.nf, tests/modules/nf-core/concoct/extractfastabins/nextflow.config, tests/modules/nf-core/concoct/extractfastabins/test.yml, tests/modules/nf-core/gatk/indelrealigner/main.nf, tests/modules/nf-core/krakentools/combinekreports/main.nf, tests/modules/nf-core/multivcfanalyzer/main.nf
Closes #2122
And removes a bunch of dumps (mostly in other of my modules...) 
=> New module: concoct/extractfastabins

.github/workflows/code-linting.yml, .github/workflows/nf-core-linting.yml
https://github.com/nf-core/tools/pull/1981
=> ci: Cancel linting if a newer run is started

modules/nf-core/deseq2/differential/main.nf
Tiny little fix- the general pattern is not to have the meta on the versions channel, so I'd like to match this to convention so we don't have to remove the meta before `mix()`ing with the versions of other modules in workflows.
=> DESeq2: Version doesn't need a meta

modules/nf-core/pints/caller/main.nf, tests/modules/nf-core/pints/caller/main.nf, tests/modules/nf-core/pints/caller/test.yml
https://github.com/hyulab/PINTS/issues/12
=> chore(pints): Bump version

modules/nf-core/bedtools/bamtobed/main.nf
x-ref: https://github.com/nf-core/cutandrun/issues/166
=> Change label for BEDTOOLS_BAMTOBED

modules/nf-core/gatk4/variantfiltration/main.nf, tests/modules/nf-core/gatk4/variantfiltration/test.yml
=> feat added stubs

modules/nf-core/bedtools/split/main.nf, modules/nf-core/bedtools/split/meta.yml, tests/modules/nf-core/bedtools/split/main.nf, tests/modules/nf-core/bedtools/split/nextflow.config, tests/modules/nf-core/bedtools/split/test.yml
=> update bedtools split

modules/nf-core/checkm/lineagewf/main.nf
by staging input bins
Closes #XXX 
=> Update CheckM: Fix occasional error to due to input file names and directory clash 

modules/nf-core/gatk4/splitcram/main.nf, modules/nf-core/gatk4/splitcram/meta.yml, tests/config/pytest_modules.yml, tests/modules/nf-core/gatk4/splitcram/main.nf, tests/modules/nf-core/gatk4/splitcram/nextflow.config, tests/modules/nf-core/gatk4/splitcram/test.yml
=> new module gatk4/splitcram

modules/nf-core/gatk4/splitintervals/main.nf, tests/modules/nf-core/gatk4/splitintervals/test.yml
=> add stub to gatk4/splitintervals

modules/nf-core/gatk4/selectvariants/main.nf, modules/nf-core/gatk4/selectvariants/meta.yml, tests/modules/nf-core/gatk4/selectvariants/main.nf, tests/modules/nf-core/gatk4/selectvariants/test.yml
This PR adds stub section to gatk4/selectvariants and the option to pass in an interval file. 
=> Add stub to gatk4/selectvariants

modules/nf-core/bcftools/concat/main.nf, tests/modules/nf-core/bcftools/concat/test.yml
=> Add stub to bcftools concat

modules/nf-core/deepvariant/main.nf, tests/modules/nf-core/deepvariant/test.yml
=> bump deepvariant version

modules/nf-core/bcftools/annotate/main.nf, modules/nf-core/bcftools/concat/main.nf, modules/nf-core/bcftools/consensus/main.nf, modules/nf-core/bcftools/convert/main.nf, modules/nf-core/bcftools/filter/main.nf, modules/nf-core/bcftools/index/main.nf, modules/nf-core/bcftools/isec/main.nf, modules/nf-core/bcftools/merge/main.nf, modules/nf-core/bcftools/norm/main.nf, modules/nf-core/bcftools/query/main.nf, modules/nf-core/bcftools/reheader/main.nf, modules/nf-core/bcftools/roh/main.nf, modules/nf-core/bcftools/sort/main.nf, modules/nf-core/bcftools/stats/main.nf, modules/nf-core/bcftools/view/main.nf, tests/modules/nf-core/bcftools/annotate/test.yml, tests/modules/nf-core/bcftools/concat/test.yml, tests/modules/nf-core/bcftools/filter/test.yml, tests/modules/nf-core/bcftools/isec/test.yml, tests/modules/nf-core/bcftools/sort/test.yml, tests/modules/nf-core/bcftools/view/test.yml
=> update bcftools version

modules/nf-core/porechop/abi/main.nf, modules/nf-core/porechop/abi/meta.yml, tests/config/pytest_modules.yml, tests/modules/nf-core/porechop/abi/main.nf, tests/modules/nf-core/porechop/abi/nextflow.config, tests/modules/nf-core/porechop/abi/test.yml
Closes [#2325 ](https://github.com/nf-core/modules/issues/2325)
Closes #XXX 
=> Add porechop_abi module

modules/nf-core/freebayes/main.nf, tests/modules/nf-core/freebayes/test.yml
=> bump freebayes version

modules/nf-core/bcftools/mpileup/main.nf
=> code polishing

modules/nf-core/fcs/fcsgx/main.nf, modules/nf-core/fcs/fcsgx/meta.yml, tests/config/pytest_modules.yml, tests/modules/nf-core/fcs/fcsgx/main.nf, tests/modules/nf-core/fcs/fcsgx/nextflow.config, tests/modules/nf-core/fcs/fcsgx/test.yml
Adds NCBI's FCS-GX, a genomic contamination screening software for genome assemblies.
This module can be used if assemblies are supposed to be uploaded to ncbi and tags contains of the assembly as contaminant or ambiguous, if they are not in line with the given taxid.
The tool needs a rather large database of around 500 GB, they provided a testdb with 5GB which is included in the test and pulled from the ftp ncbi server. Both databases are linked in the meta.yml of the module for future use in pipelines/or dedicated download module.
Unfortunately the tool is not available in condo and only available as prebuild singularity or docker container. (The same issue for fcs/fcsadapter module).
=> ncbi's fcs-gx module 

modules/nf-core/shigeifinder/main.nf, modules/nf-core/shigeifinder/meta.yml, tests/config/pytest_modules.yml, tests/modules/nf-core/shigeifinder/main.nf, tests/modules/nf-core/shigeifinder/nextflow.config, tests/modules/nf-core/shigeifinder/test.yml
Closes https://github.com/nf-core/modules/issues/2522 
=> add module for shigeifinder

subworkflows/nf-core/vcf_annotate_snpeff/main.nf, subworkflows/nf-core/vcf_annotate_snpeff/meta.yml, tests/config/pytest_modules.yml, tests/subworkflows/nf-core/vcf_annotate_snpeff/main.nf, tests/subworkflows/nf-core/vcf_annotate_snpeff/nextflow.config, tests/subworkflows/nf-core/vcf_annotate_snpeff/test.yml
=> add vcf_annotate_snpeff suborkflow and tests

modules/nf-core/genmod/annotate/main.nf, modules/nf-core/genmod/compound/main.nf, modules/nf-core/genmod/models/main.nf, modules/nf-core/genmod/score/main.nf, modules/nf-core/haplocheck/main.nf
=> fix version capture statement for genmod & haplocheck

subworkflows/nf-core/vcf_annotate_ensemblvep/main.nf, subworkflows/nf-core/vcf_annotate_ensemblvep/meta.yml, subworkflows/nf-core/vcf_annotate_snpeff/meta.yml, tests/config/pytest_modules.yml, tests/subworkflows/nf-core/vcf_annotate_ensemblvep/main.nf, tests/subworkflows/nf-core/vcf_annotate_ensemblvep/nextflow.config, tests/subworkflows/nf-core/vcf_annotate_ensemblvep/test.yml
- fix author
- add vcf_annotate_ensemblvep + tests
Closes #XXX 
=> add vcf_annotate_ensemblvep

modules/nf-core/agat/convertspgff2gtf/main.nf, modules/nf-core/agat/convertspgff2gtf/meta.yml, modules/nf-core/agat/convertspgxf2gxf/main.nf, modules/nf-core/agat/convertspgxf2gxf/meta.yml, tests/config/pytest_modules.yml, tests/modules/nf-core/agat/convertspgff2gtf/main.nf, tests/modules/nf-core/agat/convertspgff2gtf/nextflow.config, tests/modules/nf-core/agat/convertspgff2gtf/test.yml, tests/modules/nf-core/agat/convertspgxf2gxf/main.nf, tests/modules/nf-core/agat/convertspgxf2gxf/nextflow.config, tests/modules/nf-core/agat/convertspgxf2gxf/test.yml
This basically adds two tools for conversion of GFF and GTF formats
=> Two new modules: agat convertspgxf2gxf and convertspgff2gtf. Issue  #2527

modules/nf-core/artic/guppyplex/main.nf, modules/nf-core/artic/minion/main.nf, tests/modules/nf-core/artic/minion/test.yml
Closes #XXX 
Bumping version of `artic` to 1.2.3, which should allow to use the latest medaka models (otherwise only relatively old models can be used).
=> update version of artic

modules/nf-core/fastqc/main.nf, tests/modules/nf-core/fastqc/main.nf, tests/modules/nf-core/fastqc/test.yml, tests/subworkflows/nf-core/fastq_fastqc_umitools_trimgalore/main.nf, tests/subworkflows/nf-core/fastq_fastqc_umitools_trimgalore/test.yml
Renames file based on prefix instead of prefixing filename to fix https://nfcore.slack.com/archives/CJRH30T6V/p1669393822497519
=> Suggest naming fix

modules/nf-core/cnvkit/genemetrics/main.nf, modules/nf-core/cnvkit/genemetrics/meta.yml, tests/config/pytest_modules.yml, tests/config/test_data.config, tests/modules/nf-core/cnvkit/genemetrics/main.nf, tests/modules/nf-core/cnvkit/genemetrics/nextflow.config, tests/modules/nf-core/cnvkit/genemetrics/test.yml
Add `genemetrics` functionality to `cnvkit`.
Closes #2558
=> 2558 new module cnvkitgenemetrics

modules/nf-core/ensemblvep/main.nf
remove stageAs as not necessary in this context
Closes #XXX 
=> remove stageAs from ensemblvep

tests/config/pytest_modules.yml
When reviewing code I found a few issues in pytest_modules.yml:
- wrong paths / tool names
- tools that already exist (as subtools under the tool named "deeptools")
=> Misc. fixes in pytest_modules.yml

modules/nf-core/bowtie2/align/main.nf
=> replace double quotes by single

modules/nf-core/picard/bedtointervallist/main.nf, modules/nf-core/picard/bedtointervallist/meta.yml, tests/config/pytest_modules.yml, tests/modules/nf-core/picard/bedtointervallist/main.nf, tests/modules/nf-core/picard/bedtointervallist/nextflow.config, tests/modules/nf-core/picard/bedtointervallist/test.yml
=> New module: picard/bedtointervallist

modules/nf-core/purgedups/calcuts/main.nf, modules/nf-core/purgedups/calcuts/meta.yml, tests/config/pytest_modules.yml, tests/modules/nf-core/purgedups/calcuts/main.nf, tests/modules/nf-core/purgedups/calcuts/nextflow.config, tests/modules/nf-core/purgedups/calcuts/test.yml
Adds the module to calculate cutoffs for purge dups
Closes #2579  
=> Purgedups calcuts

modules/nf-core/picard/collecthsmetrics/main.nf, modules/nf-core/picard/collectmultiplemetrics/main.nf, modules/nf-core/picard/collectwgsmetrics/main.nf, modules/nf-core/samtools/idxstats/main.nf
Set selector to `process_single` for single core QC processes
Closes #XXX 
=> Set several QC processes to "single"

modules/nf-core/custom/tabulartogseagct/meta.yml
Late-coming fixes from https://github.com/nf-core/modules/pull/2603#pullrequestreview-1208933101
=> fix docs for custom/tabulartogseagct

modules/nf-core/mmseqs/tsv2exprofiledb/main.nf
Change module according to changes suggested in [https://github.com/nf-core/modules/pull/2600 review](https://github.com/nf-core/modules/pull/2609#discussion_r1038770109)
=> Fix module according to mmseqs createindex

.github/workflows/pytest-workflow.yml
=> Exclude tests that have no conda recipe in modules

modules/nf-core/samtools/fastq/main.nf, modules/nf-core/samtools/fastq/meta.yml, tests/modules/nf-core/samtools/fastq/main.nf, tests/modules/nf-core/samtools/fastq/test.yml
The current version of the `samtools_fastq` does not allow for interleaved file to be created. Added that functionality.
Closes #XXX 
=> samtools_fastq update

modules/nf-core/samtools/fasta/main.nf, modules/nf-core/samtools/fasta/meta.yml, tests/modules/nf-core/samtools/fasta/main.nf, tests/modules/nf-core/samtools/fasta/test.yml
The current version of the `samtools_fasta` does not allow for interleaved file to be created. Added that functionality.
Closes #XXX 
=> samtools_fasta update

modules/nf-core/bcftools/concat/main.nf
=> remove stageAs from bcftools/concat module

modules/nf-core/gappa/examineassign/main.nf, tests/modules/nf-core/gappa/examineassign/main.nf
=> Let GAPPA_EXAMINEASSIGN take all arguments in one structure

modules/nf-core/epang/place/main.nf, tests/modules/nf-core/epang/place/main.nf
=> Let EPANG_PLACE take all mandatory arguments in one structure

modules/nf-core/mosdepth/main.nf, modules/nf-core/mosdepth/meta.yml, tests/modules/nf-core/mosdepth/main.nf
=> add meta to mosdepth inputs

modules/nf-core/gsea/gsea/main.nf, modules/nf-core/gsea/gsea/meta.yml, tests/modules/nf-core/gsea/gsea/main.nf
This PR adds specification of the optional 'chip' file which can be used by GSEA to convert identifiers in expression matrices to those used in the gene set specifications. This is common in RNA-seq, where expression identifiers are routinely from Ensembl, and need conversion to match gene symbols in MSigDB.
=> GSEA: Add optional chip file specification

subworkflows/nf-core/fastq_subsample_fq_salmon/main.nf, subworkflows/nf-core/fastq_subsample_fq_salmon/meta.yml, tests/subworkflows/nf-core/fastq_subsample_fq_salmon/main.nf
x-ref: https://github.com/nf-core/rnaseq/issues/919
=> Add indexing step to fastq_subsample_fq_salmon subworkflow

modules/nf-core/gatk4/genomicsdbimport/main.nf
=> update label of genomicsdbimport

modules/nf-core/gsea/gsea/main.nf, tests/modules/nf-core/gsea/gsea/nextflow.config, tests/modules/nf-core/gsea/gsea/test.yml
This fixes file prefixing in the GSEA module to avoid file name clashes downstream, and removes awkward symlinking. 
The way I'd designed the GSEA output file handling has created problems for me in practice:
1. The prefix was used in such a way that it determined an output directory, but didn't prefix files themselves, making it difficult to work around file name clashes downstream. 
2. The symlinking I'd added to create predictable paths for use in CI for files otherwise containing a timestamp was creating issues with multiple matches in the output channels for certain patterns. 
I therefore propose this solution to do things differently:
1. Move files out of the results directory used by GSEA, and use the prefix at the file level.
2. Don't do the symlinking, but actually rename files, …
=> Simplify GSEA outputs, remove nasty symlinking, alow file-level prefixes

modules/nf-core/epang/split/main.nf, tests/modules/nf-core/epang/split/test.yml
=> EPANG_SPLIT: Add a period after prefix in output file names

modules/nf-core/multiqc/main.nf
=> bump multiqc to v1.14

subworkflows/nf-core/bam_split_by_region/nextflow.config
Small typo in config leftover from changes during preparation #2714
In one config the subwf was not renamed as it should have been, so the configuration did not apply properly when the config file was included in pipelines. 😓
=> Fix bam_split_by_region

modules/nf-core/shinyngs/staticdifferential/main.nf, modules/nf-core/shinyngs/staticexploratory/main.nf, modules/nf-core/shinyngs/validatefomcomponents/main.nf
With this trivial PR I make sure to quote the parameters passed to the underlying script to allow for the possibility of spaces.
=> Quote command line arguments in shinyngs modules

modules/nf-core/deseq2/differential/templates/deseq_de.R
This PR allows for spaces in sample metadata during differential analysis, by:
1. Using `scan()` to interpret quoted input parameter values (allowing use of quotes)
2. Sanitising variables that reference sample sheet columns, to match the the space-sanitised columns R creates when reading the sample metadata .
I did try passing the spaced variable all the way through, but I couldn't get DESeq2 to play ball, so it's simpler to just sanitise.
=> DESeq2: Allow for spaces in sample metadata columns

modules/nf-core/gatk4/gatherpileupsummaries/main.nf, modules/nf-core/gatk4/gatherpileupsummaries/meta.yml, tests/modules/nf-core/gatk4/gatherpileupsummaries/nextflow.config, tests/modules/nf-core/gatk4/gatherpileupsummaries/test.yml
=> Fix name in gatherpileupsummaries

modules/nf-core/snapaligner/align/main.nf, modules/nf-core/snapaligner/index/main.nf, tests/modules/nf-core/snapaligner/align/test.yml, tests/subworkflows/nf-core/fastq_align_dna/test.yml
=> bump snap version

modules/nf-core/bedtools/intersect/main.nf
=> add stub to bedtools intersect

modules/nf-core/dragmap/align/main.nf, tests/subworkflows/nf-core/fastq_align_dna/test.yml
https://github.com/Illumina/DRAGMAP/issues/47
=> fix(dragmap): Rollback to 1.2.1

modules/nf-core/biobambam/bamsormadup/main.nf, tests/modules/nf-core/biobambam/bamsormadup/test.yml
=> fix bamsormadup metrics

modules/nf-core/dastool/dastool/main.nf, modules/nf-core/dastool/fastatocontig2bin/main.nf, modules/nf-core/dastool/scaffolds2bin/main.nf, tests/modules/nf-core/dastool/dastool/test.yml, tests/modules/nf-core/dastool/fastatocontig2bin/test.yml, tests/modules/nf-core/dastool/scaffolds2bin/test.yml
=> Update: DAS_Tool to 1.1.6

tests/modules/nf-core/somalier/ancestry/main.nf
My suggestion [here](https://github.com/nf-core/modules/pull/2760#pullrequestreview-1267218616) was non-functional, just thought I'd do better and propose it edited, in functional form. 
=> Illustrate somalier/ancestry tidy-up

modules/nf-core/untar/main.nf
Closes https://github.com/nf-core/modules/issues/2771
=> untar: need a gnu grep to use -P, also use a consistent tar

modules/nf-core/glimpse/chunk/main.nf, tests/modules/nf-core/glimpse/chunk/main.nf, tests/modules/nf-core/glimpse/chunk/nextflow.config, tests/modules/nf-core/glimpse/chunk/test.yml
Update glimpse chunk for better parallelization and version control.
The value of the region that will need to be iterated is now present in the input tuple (better for parallelization has prescribed by @nvnieuwk in previous PR).
The version number of the tools is also now dynamically obtained.
=> Update glimpse chunk

modules/nf-core/seqwish/induce/main.nf
=> bump seqwish to v.0.7.8

modules/nf-core/odgi/squeeze/main.nf, modules/nf-core/odgi/squeeze/meta.yml, tests/config/pytest_modules.yml, tests/modules/nf-core/odgi/squeeze/main.nf, tests/modules/nf-core/odgi/squeeze/nextflow.config, tests/modules/nf-core/odgi/squeeze/test.yml
Closes #XXX 
This adds a new module `odgi squeeze` which is required for https://github.com/nf-core/pangenome.
=> Add new module `odgi squeeze`

modules/nf-core/odgi/build/main.nf, modules/nf-core/odgi/draw/main.nf, modules/nf-core/odgi/layout/main.nf, modules/nf-core/odgi/sort/main.nf, modules/nf-core/odgi/squeeze/main.nf, modules/nf-core/odgi/stats/main.nf, modules/nf-core/odgi/unchop/main.nf, modules/nf-core/odgi/view/main.nf, modules/nf-core/odgi/viz/main.nf
=> Update odgi modules to v0.8.2

tests/config/test_data.config
=> Fix sarek issues

modules/nf-core/shinyngs/validatefomcomponents/main.nf, modules/nf-core/shinyngs/validatefomcomponents/meta.yml, tests/modules/nf-core/shinyngs/validatefomcomponents/main.nf, tests/modules/nf-core/shinyngs/validatefomcomponents/test.yml
This PR makes the feature file an optional input to validator and splits the output into separate channels
Closes #XXX 
=> Shinyngs/validator: Make feature file optional

modules/nf-core/glimpse/ligate/main.nf, modules/nf-core/glimpse/ligate/meta.yml, tests/config/pytest_modules.yml, tests/modules/nf-core/glimpse/ligate/main.nf, tests/modules/nf-core/glimpse/ligate/nextflow.config, tests/modules/nf-core/glimpse/ligate/test.yml
Here is all the files needed for the new module for the glimpse imputation software: "Ligate"
=> New module: glimpse ligate

launch.sh, modules/nf-core/glimpse/phase/main.nf, modules/nf-core/glimpse/phase/meta.yml, tests/modules/nf-core/glimpse/phase/main.nf, tests/modules/nf-core/glimpse/phase/nextflow.config, tests/modules/nf-core/glimpse/phase/test.yml
This PR allows the choice of file format for the output (compressed, binary or not) by the use of a suffix argument.
=> Update Glimpse phase for compressed output

launch.sh, modules/nf-core/glimpse/chunk/meta.yml, modules/nf-core/glimpse/ligate/main.nf, modules/nf-core/glimpse/sample/main.nf, modules/nf-core/glimpse/sample/meta.yml, tests/modules/nf-core/glimpse/ligate/nextflow.config, tests/modules/nf-core/glimpse/ligate/test.yml, tests/modules/nf-core/glimpse/sample/main.nf, tests/modules/nf-core/glimpse/sample/nextflow.config, tests/modules/nf-core/glimpse/sample/test.yml
Here is the last module of the imputation software Glimpse (version 1).
There is also a couple of modifications in the linked modules for typos and compressed input/output.
=> New module Glimpse sample

modules/nf-core/cnvkit/antitarget/main.nf, modules/nf-core/cnvkit/batch/meta.yml, modules/nf-core/cnvkit/call/main.nf, modules/nf-core/cnvkit/call/meta.yml, modules/nf-core/cnvkit/genemetrics/main.nf, modules/nf-core/cnvkit/reference/main.nf, tests/config/pytest_modules.yml, tests/modules/nf-core/cnvkit/call/main.nf, tests/modules/nf-core/cnvkit/call/nextflow.config, tests/modules/nf-core/cnvkit/call/test.yml
Adds cnvkit/call module which can be used to call CNR from cnvkit/batch. 
Includes ability to use a VCF file for allele fractions.
=> new module: cnvkit/call

modules/nf-core/cnvkit/access/main.nf, modules/nf-core/cnvkit/access/meta.yml, tests/config/pytest_modules.yml, tests/modules/nf-core/cnvkit/access/main.nf, tests/modules/nf-core/cnvkit/access/nextflow.config, tests/modules/nf-core/cnvkit/access/test.yml
=> module: cnvkit/access

modules/nf-core/admixture/main.nf, modules/nf-core/admixture/meta.yml, modules/nf-core/antismash/antismashlitedownloaddatabases/main.nf, tests/config/pytest_modules.yml, tests/modules/nf-core/admixture/main.nf, tests/modules/nf-core/admixture/nextflow.config, tests/modules/nf-core/admixture/test.yml
=> New module: Admixture

modules/nf-core/cnvkit/target/main.nf, modules/nf-core/cnvkit/target/meta.yml, tests/config/pytest_modules.yml, tests/modules/nf-core/cnvkit/target/main.nf, tests/modules/nf-core/cnvkit/target/nextflow.config, tests/modules/nf-core/cnvkit/target/test.yml
=> module: cnvkit/target

modules/nf-core/shinyngs/staticdifferential/main.nf, modules/nf-core/shinyngs/staticexploratory/main.nf, modules/nf-core/shinyngs/validatefomcomponents/main.nf
This is just the module-level counterpart of https://github.com/bioconda/bioconda-recipes/pull/39135.
=> bump shinyngs in relevant modules

modules/nf-core/canu/main.nf, modules/nf-core/canu/meta.yml, tests/config/pytest_modules.yml, tests/modules/nf-core/canu/main.nf, tests/modules/nf-core/canu/nextflow.config, tests/modules/nf-core/canu/test.yml
Closes https://github.com/nf-core/modules/issues/823 
=> Added Canu module

modules/nf-core/bakta/baktadbdownload/meta.yml
Correct output name in meta.yml
Closes #XXX 
=> Update baktadbdownload: Correct output name

.pre-commit-config.yaml, .pre-commit-prettier-config.yaml
add pre-commit hook for prettier to modules repo
Closes #XXX 
=> add pre-commit hook for prettier to modules repo

modules/nf-core/taxpasta/standardise/main.nf, modules/nf-core/taxpasta/standardise/meta.yml, tests/config/pytest_modules.yml, tests/modules/nf-core/taxpasta/standardise/main.nf, tests/modules/nf-core/taxpasta/standardise/nextflow.config, tests/modules/nf-core/taxpasta/standardise/test.yml
=> Add taxpasta standardise

modules/nf-core/snpeff/download/main.nf, modules/nf-core/snpeff/download/meta.yml, modules/nf-core/snpeff/snpeff/main.nf, modules/nf-core/snpeff/snpeff/meta.yml, subworkflows/nf-core/vcf_annotate_snpeff/main.nf, tests/config/pytest_modules.yml, tests/modules/nf-core/snpeff/download/main.nf, tests/modules/nf-core/snpeff/download/nextflow.config, tests/modules/nf-core/snpeff/download/test.yml, tests/modules/nf-core/snpeff/snpeff/main.nf, tests/modules/nf-core/snpeff/snpeff/nextflow.config, tests/modules/nf-core/snpeff/snpeff/test.yml, tests/subworkflows/nf-core/vcf_annotate_snpeff/nextflow.config
=> New snpeff/download module

modules/nf-core/snpeff/download/main.nf, tests/modules/nf-core/snpeff/download/test.yml
=> SNPEFF_DOWNLOAD - change output folder

modules/nf-core/glimpse/ligate/main.nf, modules/nf-core/glimpse/ligate/meta.yml, modules/nf-core/glimpse/phase/main.nf, tests/modules/nf-core/glimpse/ligate/main.nf, tests/modules/nf-core/glimpse/ligate/test.yml, tests/modules/nf-core/glimpse/phase/test.yml
The input of glimpse ligate is improved and take also in account the modification made on glimpse_phase previously.
Glimpse_ligate take now a path channel as input and not a file containing the path to the files.
=> Glimpse_ligate input management

modules/nf-core/shapeit5/phasecommon/main.nf, modules/nf-core/shapeit5/phasecommon/meta.yml, tests/config/pytest_modules.yml, tests/modules/nf-core/shapeit5/phasecommon/main.nf, tests/modules/nf-core/shapeit5/phasecommon/nextflow.config, tests/modules/nf-core/shapeit5/phasecommon/test.yml
This PR add a new module SHAPEIT5 used for phasing haplotypes.
=> New module shapeit5 phase common

modules/nf-core/affy/justrma/main.nf, modules/nf-core/affy/justrma/templates/affy_justrma.R, tests/modules/nf-core/affy/justrma/nextflow.config, tests/modules/nf-core/affy/justrma/test.yml
This PR just adds the output prefixing for the results of affy/justrma, which I'd neglected to add prevoiusly.
=> Add output prefixing for affy/justrma

modules/nf-core/limma/differential/templates/limma_de.R, tests/modules/nf-core/limma/differential/main.nf
This PR just adds a couple of trivial fixes for limma/differential:
- Ignore null parameter overrides from the config
- Update channel for affy module output, reflecting updates to that module
- Correct gene_id to probe_id (the former being a copy/ paste artifact from deseq2/differential)
=> Minor limma fixes

modules/nf-core/smncopynumbercaller/main.nf
A stub section was added to this module after confirming the program works as intended.
=> add stub section to SMNcopynumbercaller

modules/nf-core/affy/justrma/templates/affy_justrma.R, modules/nf-core/limma/differential/templates/limma_de.R, tests/modules/nf-core/affy/justrma/test.yml
This PR:
-  corrects a typo for an option in affy/justrma
- prevents matrices getting their headers mangled on write by disabling check.names for both limma and affy
=> affy/justrma and limma/differential minor fixes

modules/nf-core/shinyngs/staticdifferential/main.nf, modules/nf-core/shinyngs/staticexploratory/main.nf, modules/nf-core/shinyngs/validatefomcomponents/main.nf
Bumps shinyngs modules for https://github.com/pinin4fjords/shinyngs/releases/tag/v1.5.6
=> bump shinyngs modules

modules/nf-core/happy/happy/main.nf, modules/nf-core/rtgtools/vcfeval/main.nf, tests/modules/nf-core/rtgtools/vcfeval/nextflow.config, tests/modules/nf-core/rtgtools/vcfeval/test.yml
=> Add stub to vcfeval and hap.py

modules/nf-core/tiara/tiara/main.nf, modules/nf-core/tiara/tiara/meta.yml, tests/config/pytest_modules.yml, tests/modules/nf-core/tiara/tiara/main.nf, tests/modules/nf-core/tiara/tiara/nextflow.config, tests/modules/nf-core/tiara/tiara/test.yml
Add Tiara module for domain-level classification of contigs. First module I'm submitting, so let me know if there's anything I've missed. 
Tiara does weird things with specific combinations of gzipped input and output, hence the clunky find commands to make sure everything is consistent.
=> New module Tiara

modules/nf-core/paragraph/idxdepth/main.nf, modules/nf-core/paragraph/idxdepth/meta.yml, tests/config/pytest_modules.yml, tests/modules/nf-core/paragraph/idxdepth/main.nf, tests/modules/nf-core/paragraph/idxdepth/nextflow.config, tests/modules/nf-core/paragraph/idxdepth/test.yml
=> new module paragraph/idxdepth

modules/nf-core/gatk4/splitintervals/meta.yml
=> Add description to gatk4/splitintervals

modules/nf-core/strelka/germline/main.nf, modules/nf-core/strelka/somatic/main.nf
see https://github.com/nf-core/sarek/issues/932! 
=> Removed strelka e-mailing ability

modules/nf-core/taxpasta/merge/main.nf
This PR updates taxpasta merge to version 0.2.0
=> Taxpasta version 0.2.0

modules/nf-core/bcftools/sort/main.nf, tests/modules/nf-core/bcftools/sort/test.yml
=> updated output of bcftools/sort

modules/nf-core/taxpasta/standardise/main.nf
This PR updates the taxpasta/standardise to version 0.2.0
=> Update taxpasta/standardise version 0.2.0

modules/nf-core/paragraph/multigrmpy/main.nf, tests/config/test_data.config, tests/modules/nf-core/paragraph/multigrmpy/main.nf, tests/modules/nf-core/paragraph/multigrmpy/test.yml
=> Update paragraph to work with no variant VCFs

modules/nf-core/jasminesv/main.nf, modules/nf-core/jasminesv/meta.yml, tests/config/pytest_modules.yml, tests/modules/nf-core/jasminesv/main.nf, tests/modules/nf-core/jasminesv/test.yml
=> Added bgzip support to jasminesv

modules/nf-core/bcftools/reheader/main.nf, modules/nf-core/bcftools/reheader/meta.yml, tests/modules/nf-core/bcftools/reheader/main.nf, tests/modules/nf-core/bcftools/reheader/nextflow.config, tests/modules/nf-core/bcftools/reheader/test.yml
The `bcftools reheader` command doesn't produce a compressed output. This PR pipes the output from `reheader` to `view` for compression. It also adds the option of producing non-compressed and bcf output. 
Closes #XXX 
=> compressing bcftools reheader output

modules/nf-core/fgbio/callmolecularconsensusreads/main.nf
=> Add threads to fgbio callmolecularconsensus module

modules/nf-core/paragraph/vcf2paragraph/main.nf, modules/nf-core/paragraph/vcf2paragraph/meta.yml, tests/config/pytest_modules.yml, tests/modules/nf-core/paragraph/vcf2paragraph/main.nf, tests/modules/nf-core/paragraph/vcf2paragraph/nextflow.config, tests/modules/nf-core/paragraph/vcf2paragraph/test.yml
=> new module paragraph/vcf2paragraph

modules/nf-core/shapeit5/switch/main.nf, modules/nf-core/shapeit5/switch/meta.yml, tests/config/pytest_modules.yml, tests/modules/nf-core/shapeit5/switch/main.nf, tests/modules/nf-core/shapeit5/switch/nextflow.config, tests/modules/nf-core/shapeit5/switch/test.yml
New module and last of the software SHAPEIT5.
The switch function allows to compare and detect the errors between the phasing estimate and the truth.
=> Shapeit5 switch

subworkflows/nf-core/vcf_annotate_ensemblvep/main.nf
DOCS: https://nextflow.io/docs/latest/operator.html#join
Closes #XXX 
=> Add sanity check for join

modules/nf-core/endorspy/main.nf, modules/nf-core/endorspy/meta.yml, modules/nf-core/taxpasta/merge/main.nf, tests/modules/nf-core/endorspy/main.nf, tests/modules/nf-core/endorspy/nextflow.config, tests/modules/nf-core/endorspy/test.yml
Updating the module for endorspy to be linked to the new version that calculates not only more versions of the percent on target but also clonality from samtools flagstats
=> Updating endorspy module

modules/nf-core/glimpse2/splitreference/main.nf, modules/nf-core/glimpse2/splitreference/meta.yml, tests/config/pytest_modules.yml, tests/modules/nf-core/glimpse2/splitreference/main.nf, tests/modules/nf-core/glimpse2/splitreference/nextflow.config, tests/modules/nf-core/glimpse2/splitreference/test.yml
Here is the next modules of GLIMPSE2 software.
This modules allow to split a reference panel in a bin format.
Preferably to use after GLIMPSE2_chunk.
=> Glimpse2 splitref

modules/nf-core/bakta/bakta/main.nf, modules/nf-core/bakta/baktadbdownload/main.nf, modules/nf-core/bakta/baktadbdownload/meta.yml, tests/modules/nf-core/bakta/baktadbdownload/main.nf, tests/modules/nf-core/bakta/baktadbdownload/nextflow.config, tests/modules/nf-core/bakta/baktadbdownload/test.yml
`bakta/bakta` and `bakta/baktadbdownload` are updated to 1.7.0.
=> Update bakta to 1.7.0

modules/nf-core/quast/meta.yml
Addresses Quast in from issue https://github.com/nf-core/modules/issues/2914
(Was going through the docs of the module on website and noticed the bug, later noticed the issue)
=> Updating missing description outputfiles from quast module 

modules/nf-core/unzip/main.nf
Hi, after fixing the last issue a new problem occurred. The [provided conda env](https://anaconda.org/bioconda/p7zip) cannot be built with the following error (at least for osx).
`PackagesNotFoundError: The following packages are not available from current channels:    
- bioconda::p7zip=15.09`
The respective package was last update on bioconda 4 years and 7 months ago.
I was able to fix the problem by switching to p7zip's [conda-forge package](https://anaconda.org/conda-forge/p7zip) which provides version 16.02.
Closes #XXX 
=> bioconda error fixed

modules/nf-core/plink/bcf/main.nf, modules/nf-core/plink/bcf/meta.yml, tests/config/pytest_modules.yml, tests/modules/nf-core/plink/bcf/main.nf, tests/modules/nf-core/plink/bcf/nextflow.config, tests/modules/nf-core/plink/bcf/test.yml
Closes #XXX 
This modules allows for conversion of bcf files into plink binary sets, among other utilities.
=> New module: Plink bcf

modules/nf-core/glimpse/phase/main.nf, modules/nf-core/glimpse/phase/meta.yml, subworkflows/nf-core/vcf_impute_glimpse/main.nf, tests/modules/nf-core/glimpse/concordance/main.nf, tests/modules/nf-core/glimpse/concordance/nextflow.config, tests/modules/nf-core/glimpse/concordance/test.yml, tests/modules/nf-core/glimpse/ligate/main.nf, tests/modules/nf-core/glimpse/ligate/nextflow.config, tests/modules/nf-core/glimpse/ligate/test.yml, tests/modules/nf-core/glimpse/phase/main.nf, tests/modules/nf-core/glimpse/phase/nextflow.config, tests/modules/nf-core/glimpse/phase/test.yml, tests/modules/nf-core/glimpse/sample/main.nf, tests/modules/nf-core/glimpse/sample/nextflow.config, tests/modules/nf-core/glimpse/sample/test.yml, tests/subworkflows/nf-core/vcf_impute_glimpse/main.nf, tests/subworkflows/nf-core/vcf_impute_glimpse/nextflow.config, tests/subworkflows/nf-core/vcf_impute_glimpse/test.yml
This PR change the way GLIMPSE_phase get its input files.
Everything is now inside one tuple for better parallelization.
All depending modules have been updated to reflect this change.
=> Glimpse phase input management

modules/nf-core/glimpse2/phase/main.nf, modules/nf-core/glimpse2/phase/meta.yml, tests/config/pytest_modules.yml, tests/modules/nf-core/glimpse2/phase/main.nf, tests/modules/nf-core/glimpse2/phase/nextflow.config, tests/modules/nf-core/glimpse2/phase/test.yml
Here are all the files necessary for the new module Glimpse2_phase.
This [PR](https://github.com/nf-core/test-datasets/pull/783) first need to be merged to have all necessary test data files.
=> New module Glimpse2 phase

modules/nf-core/plink/indep/main.nf, modules/nf-core/plink/indep/meta.yml, tests/config/pytest_modules.yml, tests/modules/nf-core/plink/indep/main.nf, tests/modules/nf-core/plink/indep/nextflow.config, tests/modules/nf-core/plink/indep/test.yml
Closes #XXX 
PLINK indep allows to subset of markers that are in approximate linkage equilibrium with each other.
=> Plink indep

subworkflows/nf-core/vcf_annotate_snpeff/main.nf, subworkflows/nf-core/vcf_annotate_snpeff/meta.yml
=> update vcf_annotate_snpeff to guidelines

modules/nf-core/fastp/main.nf, tests/modules/nf-core/fastp/test.yml
=> FASTP - Remove --stdout to not bloat log files

subworkflows/nf-core/bam_markduplicates_picard/main.nf, subworkflows/nf-core/bam_markduplicates_picard/meta.yml, tests/subworkflows/nf-core/bam_markduplicates_picard/test.yml
=> update bam markduplicates subwf to guidelines

subworkflows/nf-core/bam_stats_samtools/main.nf, subworkflows/nf-core/bam_stats_samtools/meta.yml
=> update bam stats samtools to guidelines

subworkflows/nf-core/vcf_extract_relate_somalier/main.nf, subworkflows/nf-core/vcf_extract_relate_somalier/meta.yml, tests/subworkflows/nf-core/vcf_extract_relate_somalier/main.nf
=> update vcf extract relate somalier to guidelines

modules/nf-core/cellranger/Dockerfile, modules/nf-core/cellranger/count/main.nf, modules/nf-core/cellranger/mkfastq/Dockerfile, modules/nf-core/cellranger/mkfastq/main.nf, modules/nf-core/cellranger/mkgtf/main.nf, modules/nf-core/cellranger/mkref/main.nf
=> Cellranger update

modules/nf-core/mapad/index/main.nf, modules/nf-core/mapad/index/meta.yml, tests/config/pytest_modules.yml, tests/modules/nf-core/mapad/index/main.nf, tests/modules/nf-core/mapad/index/nextflow.config, tests/modules/nf-core/mapad/index/test.yml
Adds mapAD/index module.
Closes #3021 
=> Add mapAD/index module

subworkflows/nf-core/fastq_align_bwaaln/main.nf, subworkflows/nf-core/fastq_align_bwaaln/meta.yml
=> update fastq align bwaaln to guidelines

modules/nf-core/taxpasta/merge/main.nf, modules/nf-core/taxpasta/standardise/main.nf
This PR updates taxpasta version 0.2.3
=> Taxpasta version 0.2.3

modules/nf-core/bbmap/bbnorm/main.nf, tests/modules/nf-core/bbmap/bbnorm/main.nf, tests/modules/nf-core/bbmap/bbnorm/test.yml
Closes #XXX 
I just added the .join(',') as now bbnorm is able to get multiple files in the same input
=> join input files

modules/nf-core/delly/call/main.nf, tests/modules/nf-core/delly/call/test.yml
=> Add tbi creation to delly

modules/nf-core/salmon/index/main.nf
Fixes https://github.com/nf-core/rnaseq/issues/878
=> Fix bug in salmon/index module when generating decoys

modules/nf-core/cnvkit/antitarget/meta.yml, modules/nf-core/cnvkit/reference/meta.yml, modules/nf-core/cnvkit/target/meta.yml, modules/nf-core/khmer/uniquekmers/meta.yml, modules/nf-core/phantompeakqualtools/meta.yml, modules/nf-core/rseqc/junctionannotation/meta.yml
(almost) finishes remaining items in https://github.com/nf-core/modules/issues/2914
fills in missing descriptions and keywords for multiple nf-core modules
=> fix missing descriptions and keywords in meta.yml

modules/nf-core/gffcompare/main.nf, modules/nf-core/gffcompare/meta.yml, tests/config/pytest_modules.yml, tests/modules/nf-core/gffcompare/main.nf, tests/modules/nf-core/gffcompare/nextflow.config, tests/modules/nf-core/gffcompare/test.yml
=> adding gffcompare

modules/nf-core/samtools/coverage/main.nf, modules/nf-core/samtools/coverage/meta.yml, tests/config/pytest_modules.yml, tests/modules/nf-core/samtools/coverage/main.nf, tests/modules/nf-core/samtools/coverage/nextflow.config, tests/modules/nf-core/samtools/coverage/test.yml
=> Add new samtools coverage

modules/nf-core/samtools/collatefastq/main.nf
=> Fix typo in args2 directive

modules/nf-core/bcftools/call/main.nf, modules/nf-core/bcftools/call/meta.yml, tests/config/pytest_modules.yml, tests/modules/nf-core/bcftools/call/main.nf, tests/modules/nf-core/bcftools/call/nextflow.config, tests/modules/nf-core/bcftools/call/test.yml
New module of bcftools : call.
It may be a replacement of bcftools view [(reference)](https://samtools.github.io/bcftools/bcftools.html#call)
=> New module bcftools call

subworkflows/nf-core/fastq_fastqc_umitools_fastp/main.nf, subworkflows/nf-core/fastq_fastqc_umitools_fastp/meta.yml, tests/config/pytest_modules.yml, tests/subworkflows/nf-core/fastq_fastqc_umitools_fastp/main.nf, tests/subworkflows/nf-core/fastq_fastqc_umitools_fastp/nextflow.config, tests/subworkflows/nf-core/fastq_fastqc_umitools_fastp/test.yml
=> New fastq_fastqc_umitools_fastp subworkflow

modules/nf-core/mosdepth/main.nf, tests/modules/nf-core/mosdepth/main.nf
=> Moved the bed input of mosdepth

modules/nf-core/shinyngs/staticdifferential/main.nf, modules/nf-core/shinyngs/staticexploratory/main.nf, modules/nf-core/shinyngs/validatefomcomponents/main.nf
Pulling in a bioconda update to address issues associated with https://github.com/nf-core/differentialabundance/issues/93.
=> Bump shinyngs in associated modules

modules/nf-core/bedtools/intersect/main.nf
=> fix a typo in bedtools/intersect

modules/nf-core/picard/addorreplacereadgroups/main.nf
=> update version extract regex for picard addorreplacereadgroups

modules/nf-core/deseq2/differential/main.nf, modules/nf-core/deseq2/differential/meta.yml, modules/nf-core/deseq2/differential/templates/deseq_de.R, tests/modules/nf-core/deseq2/differential/main.nf, tests/modules/nf-core/deseq2/differential/nextflow.config, tests/modules/nf-core/deseq2/differential/test.yml
This PR:
- [Updates the way in which non-file mandatory arguments are provided](https://github.com/nf-core/modules/pull/3092/commits/5195f3f4ac83308e8a266bed7b1440b630f3992e) to the DESeq2 module to agree with [the latest update to guidelines](https://github.com/nf-core/nf-co.re/pull/1596), including documentation of the components of the new value channel.
- [Allows the input matrix to be subsetted](https://github.com/nf-core/modules/pull/3092/commits/5ddaeee31b01ecb0ebf7efb9a6a41a6b09690a1f), either to contrast samples or using some other covariate, prior to its use in differential analysis, in  part fulfilment of https://github.com/nf-core/differentialabundance/issues/97
Other minor changes included:
- Replace 'treatment' with 'target' when referring to the non-reference side of the …
=> DESeq2: mandatory non-file args update, add subset options for differential analysis

modules/nf-core/limma/differential/main.nf, modules/nf-core/limma/differential/meta.yml, modules/nf-core/limma/differential/templates/limma_de.R, tests/modules/nf-core/limma/differential/main.nf, tests/modules/nf-core/limma/differential/nextflow.config, tests/modules/nf-core/limma/differential/test.yml
Closes https://github.com/nf-core/modules/issues/3096
=> Limma: mandatory non-file args update, add subset options for differential analysis

tests/config/test_data.config
=> Group all mus_musculus together

modules/nf-core/sourmash/compare/main.nf, modules/nf-core/sourmash/gather/main.nf, modules/nf-core/sourmash/sketch/main.nf
I've updated the versions for `sourmash` for the modules `compare`, `gather` and `sketch`.
=> Version update for sourmash modules

modules/nf-core/plink/indeppairwise/main.nf, modules/nf-core/plink/indeppairwise/meta.yml, tests/config/pytest_modules.yml, tests/modules/nf-core/plink/indeppairwise/main.nf, tests/modules/nf-core/plink/indeppairwise/nextflow.config, tests/modules/nf-core/plink/indeppairwise/test.yml
Closes [#3147](https://github.com/nf-core/modules/issues/3147) 
=> new module: indeppairwise

modules/nf-core/mapdamage2/main.nf
The current implementation does not emit the rescaled bam due to a typo in the emission path.
Closes #3186  
=> Update mapdage2 module

modules/nf-core/lofreq3/preprocessing/meta.yml
=> Add change meta.yml

modules/nf-core/survivor/filter/main.nf, modules/nf-core/survivor/filter/meta.yml, tests/config/pytest_modules.yml, tests/modules/nf-core/survivor/filter/main.nf, tests/modules/nf-core/survivor/filter/nextflow.config, tests/modules/nf-core/survivor/filter/test.yml
=> Addition of new module: Issue #3113 Survivor/filter

modules/nf-core/freyja/boot/main.nf
Previous label 'process_long' uses only one cpu, which is inefficient when multithreading is available
=> update appropriate label for freyja boot

modules/nf-core/snapaligner/align/main.nf, modules/nf-core/snapaligner/index/main.nf, tests/modules/nf-core/snapaligner/align/test.yml, tests/modules/nf-core/snapaligner/index/test.yml
=> bump snapaligner

modules/nf-core/shinyngs/app/main.nf, modules/nf-core/shinyngs/staticdifferential/main.nf, modules/nf-core/shinyngs/staticexploratory/main.nf, modules/nf-core/shinyngs/validatefomcomponents/main.nf, tests/modules/nf-core/shinyngs/app/main.nf, tests/modules/nf-core/shinyngs/app/test.yml
This PR bumps `r-shinyngs` is associated modules which also addresses a number of bugs that were present in the app generation/ deployment.
Closes #XXX 
=> Bump shinyngs versions, add minor fixes to shinyngs/app module

modules/nf-core/cellpose/main.nf, modules/nf-core/cellpose/meta.yml, tests/modules/nf-core/cellpose/main.nf
This PR fixes the problems mentioned in the issue:
- fixed the meta.yml statements
- added optional input file for user specified model
Closes #3237 
=> Cellpose fix metayml

modules/nf-core/mcquant/main.nf, tests/modules/nf-core/mcquant/nextflow.config, tests/modules/nf-core/mcquant/test.yml
This PR adds the $args variable to the mcquant main.nf and tests intensity_sum as an additional ext.args.
Closes #3251  
=> Added args to main.nf

modules/nf-core/cellpose/main.nf
Based on discussion with the biocontainer team, the base image for this container was changed to include procps: https://github.com/BioContainers/containers/pull/512
=> Changed container version

modules/nf-core/vsearch/sort/main.nf
=> fix output path glob in vsearch/sort

modules/nf-core/deepcell/mesmer/main.nf
Increase of release/container version to support compressed images using imagecodecs.
https://github.com/vanvalenlab/deepcell-applications/commit/0075eaa7f510a0da61f6b1c38023dace55d6eb79
=> Increased version of container to 0.4.1

modules/nf-core/shinyngs/app/main.nf, modules/nf-core/shinyngs/staticdifferential/main.nf, modules/nf-core/shinyngs/staticexploratory/main.nf, modules/nf-core/shinyngs/validatefomcomponents/main.nf, tests/modules/nf-core/shinyngs/app/test.yml, tests/modules/nf-core/shinyngs/staticdifferential/test.yml
Bumping conda and containers for recent r-shinyngs updates.
=> Bump shinyngs modules for contrasts, app UI fixes

modules/nf-core/samtools/view/meta.yml
=> SAMTOOLS_VIEW: make it clear csi file can be used for bam index file

modules/nf-core/manta/somatic/main.nf, modules/nf-core/manta/tumoronly/main.nf
=> Manta: remove --exome, should be set via config

modules/nf-core/ensemblvep/vep/main.nf, modules/nf-core/ensemblvep/vep/meta.yml, subworkflows/nf-core/vcf_annotate_ensemblvep/main.nf, subworkflows/nf-core/vcf_annotate_ensemblvep/meta.yml, tests/modules/nf-core/ensemblvep/vep/main.nf, tests/modules/nf-core/ensemblvep/vep/nextflow.config, tests/modules/nf-core/ensemblvep/vep/test.yml, tests/subworkflows/nf-core/vcf_annotate_ensemblvep/main.nf, tests/subworkflows/nf-core/vcf_annotate_ensemblvep/nextflow.config, tests/subworkflows/nf-core/vcf_annotate_ensemblvep/test.yml
=> FIX: #3262 custom files issues

subworkflows/nf-core/bam_create_som_pon_gatk/main.nf, subworkflows/nf-core/bam_create_som_pon_gatk/nextflow.config, tests/modules/nf-core/gatk4/applybqsr/test.yml, tests/modules/nf-core/gatk4/intervallisttools/test.yml, tests/modules/nf-core/gatk4/markduplicates/test.yml, tests/modules/nf-core/gatk4/samtofastq/test.yml, tests/modules/nf-core/gatk4/splitcram/test.yml, tests/modules/nf-core/gatk4/splitncigarreads/test.yml, tests/subworkflows/nf-core/bam_create_som_pon_gatk/main.nf, tests/subworkflows/nf-core/bam_create_som_pon_gatk/nextflow.config, tests/subworkflows/nf-core/bam_create_som_pon_gatk/test.yml
=> FIX: #3045 md5sum in gatk4 modules' update

modules/nf-core/tabix/bgziptabix/main.nf
=> update stub of tabix/bgziptabix

modules/nf-core/annotsv/annotsv/main.nf, modules/nf-core/annotsv/annotsv/meta.yml, tests/modules/nf-core/annotsv/annotsv/main.nf
=> move around the input of annotsv

modules/nf-core/seqwish/induce/main.nf
=> Update seqwish to v0.7.9

modules/nf-core/qualimap/bamqc/main.nf, modules/nf-core/qualimap/bamqccram/main.nf, modules/nf-core/qualimap/rnaseq/main.nf
Upstream update for https://github.com/nf-core/rnaseq/pull/1000
=> Make tmp dir if it doesn't exist for qualimap modules

modules/nf-core/bcftools/annotate/main.nf, tests/modules/nf-core/bcftools/annotate/main.nf, tests/modules/nf-core/bcftools/annotate/nextflow.config, tests/modules/nf-core/bcftools/annotate/test.yml
=> make header file sample dependent in bcftools/annotate

.github/workflows/pytest-workflow.yml, modules/nf-core/basicpy/main.nf, modules/nf-core/basicpy/meta.yml, tests/config/pytest_modules.yml, tests/modules/nf-core/basicpy/main.nf, tests/modules/nf-core/basicpy/nextflow.config, tests/modules/nf-core/basicpy/test.yml
Closes #3089  
This PR adds the new module Basicpy for illumination correction of images using python.
**test-datasets**: This module uses existing test data from the `imaging` folder.
=> New module: Basicpy

modules/nf-core/star/align/main.nf, modules/nf-core/star/align/meta.yml, tests/modules/nf-core/star/align/test.yml
=> feat added option of outputing wiggle and bedgraph

.github/workflows/nf-core-linting.yml
Linting should be stable enough now.
=> reset tools in CI to released version

modules/nf-core/bcftools/call/main.nf, modules/nf-core/bcftools/concat/main.nf, modules/nf-core/bcftools/consensus/main.nf, modules/nf-core/bcftools/convert/main.nf, modules/nf-core/bcftools/filter/main.nf, modules/nf-core/bcftools/index/main.nf, modules/nf-core/bcftools/isec/main.nf, modules/nf-core/bcftools/merge/main.nf, modules/nf-core/bcftools/mpileup/main.nf, modules/nf-core/bcftools/norm/main.nf, modules/nf-core/bcftools/query/main.nf, modules/nf-core/bcftools/reheader/main.nf, modules/nf-core/bcftools/roh/main.nf, modules/nf-core/bcftools/sort/main.nf, modules/nf-core/bcftools/split/main.nf, modules/nf-core/bcftools/stats/main.nf, modules/nf-core/bcftools/view/main.nf, tests/modules/nf-core/bcftools/mpileup/test.yml, tests/subworkflows/nf-core/bam_variant_calling_sort_freebayes_bcftools/test.yml
=> Update ALL bcftools modules

modules/nf-core/cat/fastq/main.nf, modules/nf-core/custom/tabulartogseacls/main.nf, modules/nf-core/custom/tabulartogseagct/main.nf, modules/nf-core/gnu/sort/main.nf, modules/nf-core/gunzip/main.nf, modules/nf-core/igv/js/main.nf, modules/nf-core/md5sum/main.nf, modules/nf-core/shasum/main.nf, modules/nf-core/untar/main.nf, modules/nf-core/untarfiles/main.nf
Fixes CI errors in https://github.com/nf-core/modules/actions/runs/4859920228/jobs/8663342740
See discussion in https://github.com/nf-core/tools/pull/2270#issuecomment-1531460193
=> Use long form docker.io address for Ubuntu

modules/nf-core/trinity/main.nf
ping @Joon-Klaps 
Closes #XXX 
=> Trinity: fix mem designation

modules/nf-core/gnu/sort/main.nf
=> Check that input and output names are different

modules/nf-core/trinity/main.nf, modules/nf-core/trinity/meta.yml, tests/modules/nf-core/trinity/test.yml
Trinity output was not gzipped
=> Compressing output of trinity

modules/nf-core/bcftools/query/main.nf
=> add stub to bcftools query

modules/nf-core/bcftools/pluginsplit/main.nf, modules/nf-core/bcftools/pluginsplit/meta.yml, modules/nf-core/bcftools/query/main.nf, tests/config/pytest_modules.yml, tests/modules/nf-core/bcftools/pluginsplit/main.nf, tests/modules/nf-core/bcftools/pluginsplit/nextflow.config, tests/modules/nf-core/bcftools/pluginsplit/test.yml
=> new module bcftools/pluginsplit

modules/nf-core/hlala/typing/main.nf
The label "process_single" was added accidentally. "process_high" is necessary.
Closes #XXX 
=> hlala typing process label fixed

modules/nf-core/fastp/main.nf, tests/modules/nf-core/fastp/test.yml, tests/subworkflows/nf-core/fastq_fastqc_umitools_fastp/test.yml
=> Bump fastp

modules/nf-core/sratools/fasterqdump/main.nf, modules/nf-core/sratools/fasterqdump/meta.yml, modules/nf-core/sratools/prefetch/main.nf, modules/nf-core/sratools/prefetch/meta.yml, subworkflows/nf-core/fastq_download_prefetch_fasterqdump_sratools/main.nf, subworkflows/nf-core/fastq_download_prefetch_fasterqdump_sratools/meta.yml, tests/modules/nf-core/sratools/fasterqdump/main.nf, tests/modules/nf-core/sratools/prefetch/main.nf, tests/subworkflows/nf-core/fastq_download_prefetch_fasterqdump_sratools/main.nf
See https://github.com/nf-core/fetchngs/issues/138 https://github.com/nf-core/fetchngs/pull/152
=> Update sratools modules/subworkflows to take jwt cart file as input

modules/nf-core/deepvariant/main.nf, tests/modules/nf-core/deepvariant/main.nf, tests/modules/nf-core/deepvariant/test.yml
=> Bump DeepVariant

modules/nf-core/samtools/view/main.nf, modules/nf-core/samtools/view/meta.yml, subworkflows/nf-core/bam_split_by_region/main.nf, subworkflows/nf-core/fastq_create_umi_consensus_fgbio/main.nf, tests/modules/nf-core/samtools/view/main.nf
Updates input parameters for samtools view
=> update input parameters

.github/workflows/pytest-workflow.yml, modules/nf-core/sentieon/varcal/main.nf, modules/nf-core/sentieon/varcal/meta.yml, tests/config/pytest_modules.yml, tests/modules/nf-core/sentieon/varcal/main.nf, tests/modules/nf-core/sentieon/varcal/nextflow.config, tests/modules/nf-core/sentieon/varcal/test.yml
nf-module for Sentieon's VarCal.
@maxulysse : How do you like this one?
Closes #XXX 
=> Sentieon VarCal

modules/nf-core/expansionhunter/meta.yml, modules/nf-core/expansionhunterdenovo/merge/main.nf, modules/nf-core/expansionhunterdenovo/merge/meta.yml, modules/nf-core/expansionhunterdenovo/profile/main.nf, modules/nf-core/expansionhunterdenovo/profile/meta.yml, modules/nf-core/stranger/main.nf, modules/nf-core/stranger/meta.yml, tests/modules/nf-core/expansionhunterdenovo/merge/main.nf, tests/modules/nf-core/expansionhunterdenovo/profile/main.nf, tests/modules/nf-core/stranger/main.nf, tests/modules/nf-core/stranger/nextflow.config, tests/modules/nf-core/stranger/test.yml
This PR updates the input parameters for expansionhunter, expansionhunterdenovo, and stranger. 
=> update input parameters for expansionhunter and stranger

.github/workflows/pytest-workflow.yml, modules/nf-core/sentieon/applyvarcal/main.nf, modules/nf-core/sentieon/applyvarcal/meta.yml, tests/config/pytest_modules.yml, tests/modules/nf-core/sentieon/applyvarcal/main.nf, tests/modules/nf-core/sentieon/applyvarcal/nextflow.config, tests/modules/nf-core/sentieon/applyvarcal/test.yml
=> Sentieon applyvarcal module

modules/nf-core/kmcp/merge/main.nf, modules/nf-core/kmcp/merge/meta.yml, tests/modules/nf-core/kmcp/merge/main.nf, tests/modules/nf-core/kmcp/merge/nextflow.config, tests/modules/nf-core/kmcp/merge/test.yml
=> Kmcp merge module

modules/nf-core/phispy/main.nf, modules/nf-core/phispy/meta.yml, tests/config/pytest_modules.yml, tests/modules/nf-core/phispy/main.nf, tests/modules/nf-core/phispy/nextflow.config, tests/modules/nf-core/phispy/test.yml
Adds a module for running [PhiSpy](https://github.com/linsalrob/PhiSpy), a tool for predicting phage sequences in bacterial genomes.
Closes #3452
=> add module: PhiSpy

modules/nf-core/maltextract/meta.yml, tests/modules/nf-core/amps/main.nf, tests/modules/nf-core/amps/nextflow.config, tests/modules/nf-core/maltextract/main.nf, tests/modules/nf-core/maltextract/nextflow.config
=> Fix wrong pattern in meta.yml for MaltExtract

modules/nf-core/hmtnote/annotate/main.nf, modules/nf-core/hmtnote/annotate/meta.yml
=> feat update environment hmtnote

modules/nf-core/samtools/faidx/main.nf, tests/modules/nf-core/samtools/faidx/main.nf, tests/modules/nf-core/samtools/faidx/nextflow.config, tests/modules/nf-core/samtools/faidx/test.yml
=> update stubs for samtools faidx

subworkflows/nf-core/fastq_fastqc_umitools_fastp/main.nf
Fixes https://github.com/nf-core/rnaseq/issues/1011
=> Fix bug in FASTQ_FASTQC_UMITOOLS_FASTP subworkflow

modules/nf-core/picard/scatterintervalsbyns/main.nf, modules/nf-core/picard/scatterintervalsbyns/meta.yml, tests/config/pytest_modules.yml, tests/modules/nf-core/picard/scatterintervalsbyns/main.nf, tests/modules/nf-core/picard/scatterintervalsbyns/nextflow.config, tests/modules/nf-core/picard/scatterintervalsbyns/test.yml
=> Scatterintervalsbyns

modules/nf-core/samtools/sort/main.nf, tests/modules/nf-core/samtools/sort/test.yml, tests/subworkflows/nf-core/fastq_create_umi_consensus_fgbio/test.yml
As it's creating lots of issues
=> FIX: remove mem assignement for SAMTOOLS_SORT

modules/nf-core/fcs/fcsgx/main.nf
=> add docker.io

modules/nf-core/bacphlip/main.nf, modules/nf-core/bacphlip/meta.yml, tests/config/pytest_modules.yml, tests/modules/nf-core/bacphlip/main.nf, tests/modules/nf-core/bacphlip/nextflow.config, tests/modules/nf-core/bacphlip/test.yml
=> New module: BACPHLIP

modules/nf-core/cutadapt/main.nf, tests/modules/nf-core/cutadapt/test.yml
Closes #XXX 
Added missing stub option in `cutadapt`.
=> Cutadapt missing stub

modules/nf-core/mmseqs/databases/main.nf, modules/nf-core/mmseqs/databases/meta.yml, tests/config/pytest_modules.yml, tests/modules/nf-core/mmseqs/databases/main.nf, tests/modules/nf-core/mmseqs/databases/nextflow.config, tests/modules/nf-core/mmseqs/databases/test.yml
Adds MMSEQS_DATABASES, which downloads and formats a protein database for use with mmseqs or metaeuk.
As the source databases are moving targets (and there is no way to specify versions), the test just checks for the existence of the correct output files.
=> New module: mmseqs_databases

modules/nf-core/cdhit/cdhit/main.nf
Variable `$args` was missing in script block. Also included the same memory check for picard, gatk4, ... (https://github.com/nf-core/modules/issues/258)
=> add args and memory for cdhit

modules/nf-core/gatk4/asereadcounter/main.nf, modules/nf-core/gatk4/composestrtablefile/main.nf, modules/nf-core/gatk4/composestrtablefile/meta.yml, modules/nf-core/gatk4/createsequencedictionary/main.nf, modules/nf-core/gatk4/filtervarianttranches/main.nf, modules/nf-core/gatk4/filtervarianttranches/meta.yml, modules/nf-core/gatk4/leftalignandtrimvariants/main.nf, modules/nf-core/gatk4/markduplicatesspark/main.nf, modules/nf-core/gatk4/printreads/main.nf, modules/nf-core/gatk4/printsvevidence/main.nf, modules/nf-core/gatk4/printsvevidence/meta.yml, modules/nf-core/gatk4/selectvariants/main.nf, modules/nf-core/gatk4/shiftfasta/main.nf, modules/nf-core/gatk4/splitcram/main.nf, modules/nf-core/gatk4/splitcram/meta.yml, modules/nf-core/gatk4/splitintervals/main.nf, modules/nf-core/gatk4/svannotate/main.nf, modules/nf-core/gatk4/svcluster/main.nf, modules/nf-core/gatk4/svcluster/meta.yml, tests/modules/nf-core/gatk4/svannotate/main.nf, tests/modules/nf-core/gatk4/svcluster/main.nf
=> FIX: Fix memory issue with some gatk4 modules

modules/nf-core/sentieon/applyvarcal/main.nf, modules/nf-core/sentieon/bwaindex/main.nf, modules/nf-core/sentieon/bwamem/main.nf, modules/nf-core/sentieon/dedup/main.nf, modules/nf-core/sentieon/gvcftyper/main.nf, modules/nf-core/sentieon/haplotyper/main.nf, modules/nf-core/sentieon/setup.md, modules/nf-core/sentieon/varcal/main.nf
=> update sentieon/modules to use quay.io

modules/nf-core/ganon/classify/main.nf, modules/nf-core/ganon/classify/meta.yml, tests/modules/nf-core/ganon/classify/test.yml
As I realised the console output could be used for MultiQC
Closes #XXX 
=> Update ganon/classify to include a log file

modules/nf-core/metaeuk/easypredict/main.nf, modules/nf-core/metaeuk/easypredict/meta.yml, tests/config/pytest_modules.yml, tests/modules/nf-core/metaeuk/easypredict/main.nf, tests/modules/nf-core/metaeuk/easypredict/nextflow.config, tests/modules/nf-core/metaeuk/easypredict/test.yml
Adds metaeuk easypredict for quick annotation of eukaryotic metagenomes
Closes #XXX 
=> New module: MetaEuk easypredict

modules/nf-core/lofreq/somatic/main.nf, modules/nf-core/lofreq/somatic/meta.yml
Fixed author name and use of quotation marks from lofreq_somatic module.
=> Minor fixes.

modules/nf-core/gatk4/markduplicates/main.nf, modules/nf-core/gatk4/markduplicatesspark/main.nf
waiting for update of mulled container: https://github.com/BioContainers/multi-package-containers/pull/2638
Closes #XXX 
=> Speed up GATK4 MD with CRAM & fix MDSpark version

modules/nf-core/art/illumina/meta.yml, modules/nf-core/backsub/meta.yml, modules/nf-core/bcftools/split/meta.yml, modules/nf-core/crisprcleanr/normalize/meta.yml, modules/nf-core/freyja/boot/meta.yml, modules/nf-core/freyja/demix/meta.yml, modules/nf-core/freyja/update/meta.yml, modules/nf-core/freyja/variants/meta.yml, modules/nf-core/gatk4/applybqsr/meta.yml, modules/nf-core/goleft/indexsplit/meta.yml, modules/nf-core/hlala/preparegraph/meta.yml, modules/nf-core/hlala/typing/meta.yml, modules/nf-core/interproscan/meta.yml, modules/nf-core/mapad/index/meta.yml, modules/nf-core/metaphlan/makedb/meta.yml, modules/nf-core/mindagap/mindagap/meta.yml, modules/nf-core/parabricks/applybqsr/meta.yml, modules/nf-core/parabricks/fq2bam/meta.yml, modules/nf-core/paragraph/multigrmpy/meta.yml, modules/nf-core/paragraph/vcf2paragraph/meta.yml, modules/nf-core/picard/collectinsertsizemetrics/meta.yml, modules/nf-core/pilon/meta.yml, modules/nf-core/sambamba/flagstat/meta.yml, modules/nf-core/snpsift/annotate/meta.yml, modules/nf-core/survivor/filter/meta.yml, modules/nf-core/svtyper/svtyper/meta.yml, modules/nf-core/ucsc/bedclip/meta.yml, modules/yaml-schema.json
More fixed meta.yml's to make them easier parse-able.
=> fix errors according to schema

modules/nf-core/spaceranger/count/main.nf, modules/nf-core/spaceranger/mkgtf/main.nf, modules/nf-core/spaceranger/mkref/main.nf, tests/modules/nf-core/spaceranger/count/nextflow.config
Cleanup outdated comments and remove a test configuration that is not necessary anymore. 
Closes #XXX 
=> Spaceranger: Cleanup outdated comments

modules/nf-core/eklipse/main.nf, modules/nf-core/eklipse/meta.yml, tests/config/pytest_modules.yml, tests/config/test_data.config, tests/modules/nf-core/eklipse/main.nf, tests/modules/nf-core/eklipse/nextflow.config, tests/modules/nf-core/eklipse/test.yml
=> eklipse module

modules/nf-core/upd/main.nf, tests/modules/nf-core/upd/nextflow.config, tests/modules/nf-core/upd/test.yml
This PR adds stubs to upd module
=> Add stubs to upd

modules/nf-core/bcftools/merge/main.nf, tests/modules/nf-core/bcftools/merge/main.nf
=> Bcftools merge update

modules/nf-core/ensemblvep/download/main.nf, modules/nf-core/ensemblvep/download/meta.yml, modules/nf-core/ensemblvep/vep/main.nf
=> MODULES: update VEP based modules

modules/nf-core/cdhit/cdhitest/main.nf, modules/nf-core/cdhit/cdhitest/meta.yml, tests/config/pytest_modules.yml, tests/modules/nf-core/cdhit/cdhitest/main.nf, tests/modules/nf-core/cdhit/cdhitest/nextflow.config, tests/modules/nf-core/cdhit/cdhitest/test.yml
Cdhit, a tool for clustering and comparing protein or nucleotide sequences has a subtool `cd-hit-est`, specifically for nucleotide sequences. The default `cd-hit` is for protein sequences. 
=> New module cdhit/cdhitest

modules/nf-core/vrhyme/extractunbinned/main.nf, modules/nf-core/vrhyme/extractunbinned/meta.yml, modules/nf-core/vrhyme/linkbins/main.nf, modules/nf-core/vrhyme/linkbins/meta.yml, modules/nf-core/vrhyme/vrhyme/main.nf, modules/nf-core/vrhyme/vrhyme/meta.yml, tests/config/pytest_modules.yml, tests/modules/nf-core/vrhyme/extractunbinned/main.nf, tests/modules/nf-core/vrhyme/extractunbinned/nextflow.config, tests/modules/nf-core/vrhyme/extractunbinned/test.yml, tests/modules/nf-core/vrhyme/linkbins/main.nf, tests/modules/nf-core/vrhyme/linkbins/nextflow.config, tests/modules/nf-core/vrhyme/linkbins/test.yml, tests/modules/nf-core/vrhyme/vrhyme/main.nf, tests/modules/nf-core/vrhyme/vrhyme/nextflow.config, tests/modules/nf-core/vrhyme/vrhyme/test.yml
=> Added a new module: vRhyme (binning of viral assemblies)

modules/nf-core/bbmap/bbsplit/main.nf, modules/nf-core/wfmash/main.nf, modules/nf-core/wfmash/meta.yml
Closes #XXX 
This updates `wfmash` to v0.10.4.  See https://github.com/waveygang/wfmash/releases/tag/v0.10.4 for the changelog.
=> update wfmash v0.10.4

tests/config/test_data.config
=> Add link to README

modules/nf-core/taxpasta/merge/main.nf, modules/nf-core/taxpasta/standardise/main.nf
=> Bump taxpasta version

modules/nf-core/hlala/preparegraph/meta.yml, modules/nf-core/hlala/typing/meta.yml
Forgot to change the authorship.
Just to make sure not the wrong people get pinged for questions.
Closes #XXX 
=> change authorship

modules/nf-core/mmseqs/createdb/main.nf, modules/nf-core/mmseqs/createdb/meta.yml, tests/config/pytest_modules.yml, tests/modules/nf-core/mmseqs/createdb/main.nf, tests/modules/nf-core/mmseqs/createdb/nextflow.config, tests/modules/nf-core/mmseqs/createdb/test.yml
Closes https://github.com/nf-core/modules/issues/3599
=> new module:  mmseqs2/createdb

modules/nf-core/metaphlan/metaphlan/main.nf, tests/modules/nf-core/metaphlan/metaphlan/main.nf
=> Metaphlan4 update: add --index

modules/nf-core/mmseqs/cluster/main.nf, modules/nf-core/mmseqs/cluster/meta.yml, tests/config/pytest_modules.yml, tests/modules/nf-core/mmseqs/cluster/main.nf, tests/modules/nf-core/mmseqs/cluster/nextflow.config, tests/modules/nf-core/mmseqs/cluster/test.yml
MMseqs module for clustering a mmseqs database
Closes https://github.com/nf-core/modules/issues/3597
=> New module: mmseqs/cluster

modules/nf-core/mmseqs/createtsv/main.nf, modules/nf-core/mmseqs/createtsv/meta.yml, tests/config/pytest_modules.yml, tests/modules/nf-core/mmseqs/createtsv/main.nf, tests/modules/nf-core/mmseqs/createtsv/nextflow.config, tests/modules/nf-core/mmseqs/createtsv/test.yml
Create a summary tsv file of a query target and result MMseqs database
=> New module:  mmseqs/createtsv

subworkflows/nf-core/bam_markduplicates_samtools/main.nf, subworkflows/nf-core/bam_markduplicates_samtools/meta.yml, tests/config/pytest_modules.yml, tests/subworkflows/nf-core/bam_markduplicates_samtools/main.nf, tests/subworkflows/nf-core/bam_markduplicates_samtools/nextflow.config, tests/subworkflows/nf-core/bam_markduplicates_samtools/test.yml
Markduplicate subworkflow with samtools markdup and modules to format data with collate, fixate and sort.
=> bam_markduplicates_samtools

modules/nf-core/mapad/map/main.nf, modules/nf-core/mapad/map/meta.yml, tests/config/pytest_modules.yml, tests/modules/nf-core/mapad/map/main.nf, tests/modules/nf-core/mapad/map/nextflow.config, tests/modules/nf-core/mapad/map/test.yml
=> Add mapAD/map

modules/nf-core/manta/somatic/main.nf, modules/nf-core/manta/tumoronly/main.nf
=> Update manta modules

modules/nf-core/simpleaf/index/main.nf, modules/nf-core/simpleaf/index/meta.yml, modules/nf-core/simpleaf/quant/main.nf, modules/nf-core/simpleaf/quant/meta.yml, tests/config/pytest_modules.yml, tests/modules/nf-core/simpleaf/index/main.nf, tests/modules/nf-core/simpleaf/index/nextflow.config, tests/modules/nf-core/simpleaf/index/test.yml, tests/modules/nf-core/simpleaf/quant/main.nf, tests/modules/nf-core/simpleaf/quant/nextflow.config, tests/modules/nf-core/simpleaf/quant/test.yml
In this PR I'm centralising the good work done with `simpleaf` in #scrnaseq. However I've made a few tweaks to fix things, and for better standards compliance, including:
- Update simpleaf version used
- Fix the distinct file sets needed in different modes of simpleaf/index
- Removed excess argument handling from simpleaf/quant - let the tool handle failures if particular combinations of parameters don't work.
- Remove assumptions on `meta` in simpleaf/quant - assume that any run-wise params will be passed via conf/modules.config at the workflow level.
- Don't save supplied whitelists to alevin output dir. Seems like a hack and it can be re-used from the inputs at the workflow level as required. 
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite …
=> Adding modules from #scrnaseq for simpleaf

modules/nf-core/icountmini/metagene/main.nf
module currently fails, i've fixed the error in icount-mini so now by bumping the version here we fix the issue (old matplotlib syntax)
Closes #XXX 
=> update icount mini version

modules/nf-core/taxpasta/merge/main.nf, modules/nf-core/taxpasta/standardise/main.nf
=> Bump taxpasta version (biocontainer not yet available)

modules/nf-core/samtools/import/main.nf, modules/nf-core/samtools/import/meta.yml, tests/config/pytest_modules.yml, tests/modules/nf-core/samtools/import/main.nf, tests/modules/nf-core/samtools/import/nextflow.config, tests/modules/nf-core/samtools/import/test.yml
=> new module: samtools/import

modules/nf-core/metaphlan/metaphlan/main.nf
=> update metaphlan module

modules/nf-core/gatk4/determinegermlinecontigploidy/main.nf, modules/nf-core/gatk4/germlinecnvcaller/main.nf, modules/nf-core/gatk4/postprocessgermlinecnvcalls/main.nf
Removes quay.io from GATK4 container
Closes #3668
=> Fix invalid GATK container

modules/nf-core/sentieon/applyvarcal/main.nf, modules/nf-core/sentieon/bwaindex/main.nf, modules/nf-core/sentieon/bwamem/main.nf, modules/nf-core/sentieon/dedup/main.nf, modules/nf-core/sentieon/gvcftyper/main.nf, modules/nf-core/sentieon/haplotyper/main.nf, modules/nf-core/sentieon/varcal/main.nf
Issue #3683 (This is the third batch of modules.)
1) Moving conda-check to script-section and stub-section.
2) Replacing `exit 1` with `error()`.
I'll do these updates 5-10 modules per PR in order to ease the reviews and handling of failing tests. 
This time I'm updating "my own" sentieon-modules, so all tests pass 😆 🥳
N.B. This PR is done from the nf-core/modules (and not a fork) because that is necessary for using the GitHub-secrets for runnning the tests of the Sentieon-modules.
Closes #XXX 
=> Move conda-checks (third batch)

modules/nf-core/multiqc/main.nf
Updating multiqc to v1.15 😃
Closes #XXX 
=> Updating multiqc to v1.15

modules/nf-core/gatk4/applyvqsr/main.nf, modules/nf-core/gatk4/variantrecalibrator/main.nf
=> add stub tests for two stubborn modules

modules/nf-core/mmseqs/easysearch/main.nf, modules/nf-core/mmseqs/easysearch/meta.yml, tests/config/pytest_modules.yml, tests/modules/nf-core/mmseqs/easysearch/main.nf, tests/modules/nf-core/mmseqs/easysearch/nextflow.config, tests/modules/nf-core/mmseqs/easysearch/test.yml
Add module mmseqs easysearch
Gets as input a fasta file and a database. 
Outputs a tsv file with the summary of the matches. 
Closes https://github.com/nf-core/modules/issues/3698
=> Add module mmseqs easysearch

.github/workflows/test.yml, modules/nf-core/sentieon/datametrics/main.nf, modules/nf-core/sentieon/datametrics/meta.yml, tests/config/pytest_modules.yml, tests/modules/nf-core/sentieon/datametrics/main.nf, tests/modules/nf-core/sentieon/datametrics/nextflow.config, tests/modules/nf-core/sentieon/datametrics/test.yml
=> Add sentieon datametrics

modules/nf-core/concoct/concoctcoveragetable/main.nf, modules/nf-core/concoct/cutupfasta/main.nf, modules/nf-core/concoct/extractfastabins/main.nf, modules/nf-core/concoct/mergecutupclustering/main.nf
Following https://github.com/nf-core/modules/pull/3669 - forgot to update the container version in the other concoct modules
Closes #XXX 
=> Update other concoct containers

.github/workflows/test.yml, modules/nf-core/sentieon/dnascope/main.nf, modules/nf-core/sentieon/dnascope/meta.yml, tests/config/pytest_modules.yml, tests/modules/nf-core/sentieon/dnascope/main.nf, tests/modules/nf-core/sentieon/dnascope/nextflow.config, tests/modules/nf-core/sentieon/dnascope/test.yml
=> Add sentieon dnascope

modules/nf-core/bcftools/stats/main.nf, modules/nf-core/bcftools/stats/meta.yml, tests/modules/nf-core/bcftools/stats/main.nf, tests/modules/nf-core/bcftools/stats/test.yml
This PR adds two additional input channels for the `--exons` and `--reference` input files, and adds a meta to each input channel.
Closes #3695 
=> Update bcftools stats

modules/nf-core/sentieon/datametrics/meta.yml, modules/nf-core/sentieon/dnascope/main.nf, modules/nf-core/sentieon/dnascope/meta.yml, tests/modules/nf-core/sentieon/dnascope/main.nf
This PR fixes a typo in meta.yml for datametrics module, and add meta for ml_model file in dnascope module.
=> update sentieon recipes

.github/workflows/test.yml, modules/nf-core/sentieon/dnamodelapply/main.nf, modules/nf-core/sentieon/dnamodelapply/meta.yml, tests/config/pytest_modules.yml, tests/modules/nf-core/sentieon/dnamodelapply/main.nf, tests/modules/nf-core/sentieon/dnamodelapply/nextflow.config, tests/modules/nf-core/sentieon/dnamodelapply/test.yml
=> Add sentieon dnamodelapply

modules/nf-core/mafft/main.nf, modules/nf-core/mafft/meta.yml, tests/modules/nf-core/mafft/test.yml, tests/subworkflows/nf-core/fasta_newick_epang_gappa/test.yml
Here I update the version of Mafft and add the module- and subworkflow-specific config files into the tests.
I also update the subworkflow's test tags so that only the relevant modules are tested.
Closes #XXX 
=> Mafft version update

modules/nf-core/bedtools/groupby/main.nf, modules/nf-core/bedtools/groupby/meta.yml, tests/config/pytest_modules.yml, tests/modules/nf-core/bedtools/groupby/main.nf, tests/modules/nf-core/bedtools/groupby/nextflow.config, tests/modules/nf-core/bedtools/groupby/test.yml
Closes #3749
- [c] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
=> add bedtools groupby

modules/nf-core/ensemblvep/filtervep/main.nf, modules/nf-core/ensemblvep/filtervep/meta.yml, tests/config/pytest_modules.yml, tests/modules/nf-core/ensemblvep/filtervep/main.nf, tests/modules/nf-core/ensemblvep/filtervep/nextflow.config, tests/modules/nf-core/ensemblvep/filtervep/test.yml
=> Add filter_vep

modules/nf-core/vsearch/cluster/main.nf
=> Fixed bug raised in issue #3747

modules/nf-core/quast/main.nf, modules/nf-core/quast/meta.yml, tests/modules/nf-core/quast/main.nf, tests/modules/nf-core/quast/test.yml
Quast was not up to nf-core guideline standards for modules. Mostly, the output filename was hardcoded and additional arguments were redundant. 
=> Module quast update to meet guidelines again

modules/nf-core/gfaffix/main.nf, tests/modules/nf-core/gfaffix/test.yml
Closes #XXX 
This updates module gfaffix to v0.1.5.
=> update gfaffix to 0.1.5

.github/workflows/test.yml, modules/nf-core/sentieon/tnscope/main.nf, modules/nf-core/sentieon/tnscope/meta.yml, tests/config/pytest_modules.yml, tests/modules/nf-core/sentieon/tnscope/main.nf, tests/modules/nf-core/sentieon/tnscope/nextflow.config, tests/modules/nf-core/sentieon/tnscope/test.yml
=> Add sentieon tnscope

modules/nf-core/smoothxg/main.nf
Closes #XXX 
Update `smoothxg` to v0.7.1.
=> update smoothxg to v0.7.1

modules/nf-core/kallisto/index/main.nf, modules/nf-core/kallisto/index/meta.yml, tests/modules/nf-core/kallisto/index/main.nf, tests/modules/nf-core/kallisto/index/test.yml
=> kallisto: add meta information for references

modules/nf-core/taxpasta/merge/main.nf, modules/nf-core/taxpasta/standardise/main.nf
This PR updates taxpasta to 0.5.0
=> Update taxpasta 0.5.0

modules/nf-core/bakta/bakta/main.nf, modules/nf-core/bakta/baktadbdownload/main.nf
Updating both bakta modules to version 1.8.2. There should be no changes in parameters.
=> Update bakta to v1.8.2

modules/nf-core/wfmash/main.nf
=> bump wfmash to v0.10.5

modules/nf-core/odgi/build/main.nf, modules/nf-core/odgi/draw/main.nf, modules/nf-core/odgi/layout/main.nf, modules/nf-core/odgi/sort/main.nf, modules/nf-core/odgi/squeeze/main.nf, modules/nf-core/odgi/squeeze/meta.yml, modules/nf-core/odgi/stats/main.nf, modules/nf-core/odgi/unchop/main.nf, modules/nf-core/odgi/view/main.nf, modules/nf-core/odgi/viz/main.nf
=> bump odgi modules to v0.8.3

modules/nf-core/csvtk/join/main.nf, modules/nf-core/csvtk/join/meta.yml, tests/config/pytest_modules.yml, tests/modules/nf-core/csvtk/join/main.nf, tests/modules/nf-core/csvtk/join/nextflow.config, tests/modules/nf-core/csvtk/join/test.yml
Joined new module csvtk/join
Closes #3705 
=> Added new module csvtk/join
