nf-core/modules

- .gitignore
- tools/bwa/mem/Dockerfile
- tools/bwa/mem/environment.yml
- tools/bwa/mem/main.nf
- tools/bwa/mem/meta.yml
- tools/bwa/mem/test/main.nf
- tools/bwa/mem/test/nextflow.config
I stuck to the standard alignment process format, where a single reference is assumed. However, I was a bit conflicted as to whether a multi-reference approach would be more appropriate, as this would be less intuitive, but more general. I envision doing this by making the process accept a single tuple containing (read id, fastq read files, index prefix, index files) as input. For the multi-reference case, read_ch.combine(index_ch) can then be implemented as an input to the module.  This would also allow  individual samples to be aligned to different references. 
I bundled alignment with samtools indexing, as the two steps are usually performed together. This requires a custom container with both tools. A dockerfile of the container I used has been attached. I have also included the …
> Added the bwa short alignment (bwa mem) module

- tools/trim_galore/main.nf
- tools/trim_galore/meta.yml
- tools/trim_galore/test/main.nf
- tools/trim_galore/test/nextflow.config
Adapted the Trim Galore module we use at Babraham to work in the NF-Core structure. Looking quite good!
> Added functional Trim Galore module

- tools/multiqc/main.nf
- tools/multiqc/meta.yml
- tools/multiqc/test/main.nf
- tools/multiqc/test/nextflow.config
This module uses the output of a simple ChIPseq pipeline, namely:
`FastQC`->`FastQ_Screen`->`Trim Galore`->`FastQC`->`Bowtie2`
The module accepts additional parameters in the usual way to customise the MultiQC experience (e.g.: `--multiqc_args="-o custom_output_dirname --title custom_report_title"`)
The files that are being fed to the MultiQC channel are:
```
test_R1_fastqc.zip
test_R2_fastqc.zip
test_R1.fastq.gz_trimming_report.txt
test_R2.fastq.gz_trimming_report.txt
test_R1_screen.txt
test_R1_val_1_fastqc.zip
test_R2_val_2_fastqc.zip
test_GRCm38_bowtie2_stats.txt
```
> Added DSL2 module for MultiQC

- tools/bowtie2/main.nf
- tools/bowtie2/meta.yml
- tools/bowtie2/test/main.nf
- tools/bowtie2/test/nextflow.config
Added is a functional module for `Bowtie2`.
The test requires the following command:
`./main.nf --genome E_coli`
The E. coli genome path is currently hard-coded, and needs to be adapted to a more final state. I have also generated a test dataset of 10,000 test reads (paired-end) with Sherman and the following command:
`Sherman -l 100 -n 10000 --genome /bi/scratch/Genomes/E_coli/ --paired -cr 0`. The data is available in the modules/test-data/tools/bowtie2/input (and output).
> Added Bowtie2 module and test workflow

- tools/bowtie2/main.nf
- tools/bowtie2/meta.yml
- tools/bowtie2/test/main.nf
- tools/bowtie2/test/nextflow.config
- tools/hisat2/main.nf
- tools/hisat2/meta.yml
- tools/hisat2/test/main.nf
- tools/hisat2/test/nextflow.config
Input data is the same E. coli test DNA data which is also used for Bowtie2. 
E. coli has to my knowledge no splice sites file, but the module handles `--known_splice_sites <file>` if this is supplied. 
Another comment: the output file is getting piped to `samtools view`. Not exactly sure whether this is an acceptable dependency, or how we are supposed to handle that. I suppose it is alright, as other tools also have dependencies...
> Added HISAT2 module and test workflow

- software/bowtie2/main.nf
- software/bwa/index/main.nf
- software/bwa/mem/main.nf
- software/cutadapt/main.nf
- software/fastq_screen/main.nf
- software/gatk/dict/main.nf
- software/hisat2/main.nf
- software/htslib/tabix/main.nf
- software/multiqc/main.nf
- software/samtools/faidx/main.nf
- software/samtools/index/main.nf
- software/samtools/sort/main.nf
- software/shovill/main.nf
- software/tcoffee/main.nf
- software/trim_galore/main.nf
This commit provides a minor refactoring with som
Nextflow code style improvments:
- Replaces `.toGiga()` with `.giga`
- Replaces `tag { foo }` with `tag "$foo"`
- Move publishDir before input declarations. Directives should be
before the first input. Tho this is not enforced, it may be in
future versions.
- Replaces input `file` with `path`
- Remove unnecessary parentheses
> Minor style improvements

- software/SOFTWARE/TOOL/functions.nf
- software/bwa/index/functions.nf
- software/bwa/mem/functions.nf
- software/deeptools/computematrix/functions.nf
- software/deeptools/plotfingerprint/functions.nf
- software/deeptools/plotheatmap/functions.nf
- software/deeptools/plotprofile/functions.nf
- software/fastqc/functions.nf
- software/homer/annotatepeaks/functions.nf
- software/lib/functions.nf
- software/macs2/callpeak/functions.nf
- software/phantompeakqualtools/functions.nf
- software/picard/collectmultiplemetrics/functions.nf
- software/picard/markduplicates/functions.nf
- software/picard/mergesamfiles/functions.nf
- software/preseq/lcextrap/functions.nf
- software/samtools/flagstat/functions.nf
- software/samtools/idxstats/functions.nf
- software/samtools/index/functions.nf
- software/samtools/sort/functions.nf
- software/samtools/stats/functions.nf
- software/subread/featurecounts/functions.nf
- software/trimgalore/functions.nf
- software/ucsc/bedgraphtobigwig/functions.nf
In the original code, if `args.publish_files = [:]` , then `args.publish_files?` is negative, and `options.publish_files=null`. The desired behavior is for `options.publish_files=[:]`, which should result in no files being published, rather than all of them. This is done by keeping `options.publish_files = args.publish_files` whenever `args.publish_files` is a Map.
> Changed options.publish_files definition in functions.nf/initOptions

- .github/workflows/cutadapt.yml
- software/cutadapt/functions.nf
- software/cutadapt/main.nf
- software/cutadapt/meta.yml
- tests/software/cutadapt/main.nf
- tests/software/cutadapt/test.yml
This PR adds the cutadapt module, modified from https://github.com/drpatelh/nf-core-viralrecon/blob/dsl2/modules/local/cutadapt.nf
I have adapted the module to be more flexible, i.e. I have removed 
`def paired   = meta.single_end ? "-a file:adapters.sub.fa"   : "-a file:adapters.sub.fa -A file:adapters.sub.fa"`
and thus the possibility of handing over a channel with adapters to the process. Cutadapt is highly flexible and can do all kinds of different trimming options. The code above, for instance, only allows to trim the same 3'-adapters from both mates. So in this version, the user has to specify the adapter files in the `modules.config`
I think this is reasonable as the adapters shouldn't change for different samples in the same pipeline run and it goes along the nf-core/modules …
> Added cutadapt module

- .github/filters.yml
- .github/workflows/pytest-workflow.yml
- tests/config/nextflow.config
- tests/software/bowtie/align/test.yml
- tests/software/bowtie/build/test.yml
- tests/software/bowtie2/build/test.yml
Should fix issues with singularity builds #145 and "fixes" the `bowtie*_build` tags not running.
> Get Singularity CI tests working

- .github/workflows/pytest-workflow.yml
Had to change tmp dir to ~ for singularity but didn't update where the log upload was looking for logs
> ci: Fix artifact path

- tests/config/nextflow.config
I think it's a good practice to have that especially to limit resources for our CI tests here with GitHub actions
cf #177
> Add cpus, memory and time requirements to limit resource consumption

- tests/software/TOOL/SUBTOOL/test.yml
- tests/software/bwa/mem/test.yml
- tests/software/bwamem2/mem/test.yml
- tests/software/fastp/test.yml
- tests/software/pangolin/test.yml
- tests/software/samtools/sort/test.yml
- tests/software/star/align/test.yml
- tests/software/star/genomegenerate/test.yml
- tests/software/stringtie/test.yml
follow up on #182
From @drpatelh 
> We need to fix all of the tests that are failing here for Docker / Singularity. It's fine to ignore the ones failing for Conda. Maybe the test files were generated relative to Conda and now that we have removed the pinned build the Docker / Singularity tests are failing? Don't know but I need to find a bed. Someone fancy fixing these in a follow up PR?
> 
> ```
> bcftools_filter
> bcftools_stats
> bwa_mem
> bwamem2_mem
> fastp
> pangolin
> salmon
> samtools_sort
> star_align
> star_genomegenerate
> stringtie
> tool_subtool
> ```
Managed to fix all tests, it was indeed just issue with `md5sum`, and some filename for `sringtie`
But couldn't find any issue for `bcftools_filter` and `bcftools_stats`
> fix: update checksum or filename

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/pytest-workflow.yml
- README.md
This avoids a race condition on the conda cache.
> Only use one thread for pytest-workflow

- tests/software/tiddit/sv/test.yml
Conda tests of the module `tiddit-sv` were not working since the resulting `vcf` file included a line tagged as `##TIDDITcmd` that differed between `Conda` and the `Singularity` or `Docker` execution (the reason is that the binary is placed in a different and hence the command is not the same). 
Now the tests just checks whether the `test.vcf` file exists.
> Fix tiddit sv tests

- tests/config/nextflow.config
This exits nicely if you are running any module tests with `nf-core modules create-test-yml` and are running with an older version of Nextflow.
> Check for minimum NF version

- software/methyldackel/extract/main.nf
- software/methyldackel/mbias/main.nf
Previously,  MethylDackel was pinned to `0.5.0` because it had some `htslib` related issue that caused segfaults.
The issue is fixed in the latest version `0.5.2`, so let's use it.
> update methyldackel version

- .github/PULL_REQUEST_TEMPLATE.md
Encourages PR submitters to link the corresponding issue - and trigger closing it automatically when the PR is merged.
> Add link to issue in pull request template

- README.md
Add instructions on how to build a bespoke multi-tool Docker container and Singularity image
> multi-tool instructions

- software/bwameth/align/main.nf
- software/bwameth/index/main.nf
The container was not matching the latest conda package version, but used a rather old version of bwameth instead.
Closes #XXX 
> bwameth: fix container not matching conda version

- software/bismark/report/main.nf
- software/bismark/summary/main.nf
bismark2report does some autodetection of input data based on filenames if no explicit arguments are given.
This change makes the process more lenient if input data is partially missing by relying on this autodetection (explicit arguments can still be passed via `options.args`)
Additionally, the output channel glob no longer matches the .version.txt output which was leading to input filename collisions when used in downstream processes.
Closes #XXX 
> bismark/report: allow missing input data

- software/snpsites/main.nf
Currently the constant sites are emitted as a file. It would be useful to pass onwards as a string also
> output constant sites as a val so it can be passed into iqtree

- software/bowtie/build/main.nf
- software/bowtie2/build/main.nf
- software/bwa/index/main.nf
- software/bwamem2/index/main.nf
- software/bwameth/index/main.nf
- software/cat/fastq/main.nf
- software/hisat2/build/main.nf
- software/rsem/preparereference/main.nf
- software/salmon/index/main.nf
- software/star/genomegenerate/main.nf
- software/yara/index/main.nf
This was missed on the auto-update script I wrote yesterday but I noticed it when testing after re-installing all  nf-core/modules for the viralrecon pipeline [here](https://github.com/nf-core/viralrecon/pull/172).
> Add default publish_dir for index processes

- tests/software/plasmidid/test.yml
After changing `contigs.fasta` files on this [PR](https://github.com/nf-core/test-datasets/pull/234) the md5sum checks need to be updated.
Closes #433 
- [x ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd`
> FIx plasmidid tests for new contigs.fasta file

- tests/config/test_data.config
- tests/software/abacas/main.nf
- tests/software/plasmidid/main.nf
- tests/software/plasmidid/test.yml
Assembly files from sarscov2 are generated from Illumina reads and thus, it was somehow misleading to place them under `genome` folder. They were moved on [test-datasets](https://github.com/nf-core/test-datasets/pull/236).
> Move assembly test files from genome to illumina

- software/hisat2/build/main.nf
- software/preseq/lcextrap/main.nf
- software/preseq/lcextrap/meta.yml
- software/samtools/index/main.nf
- software/samtools/index/meta.yml
- software/star/genomegenerate/main.nf
- tests/software/preseq/lcextrap/test.yml
- tests/software/samtools/index/main.nf
- tests/software/samtools/index/test.yml
- tests/software/star/genomegenerate/main.nf
Udpdating modules required for the nf-core/rnaseq pipeline
* Fix memory options in hisat2/build module
* Bump Preseq version and added `meta.yml` to get lint tests passing
* Add ability to auto-detect `--genomeSAindexNbases` for smaller genomes in star/genomegenerate module
> Update modules required for rnaseq pipeline

- .gitignore
- software/hmmer/hmmalign/functions.nf
- software/hmmer/hmmalign/main.nf
- software/hmmer/hmmalign/meta.yml
- tests/config/pytest_software.yml
- tests/software/hmmer/hmmalign/main.nf
- tests/software/hmmer/hmmalign/test.yml
This PR adds a module, `hmmer/hmmalign`, that contains a function that calls `hmmalign` from the [HMMER](http://hmmer.org) package to make a multiple alignment of sequences from a fasta file to an hmm profile.
Tests pass with Docker using Nextflow 21.04.0-edge, haven't tried Singularity nor Conda.
> New module to use hmmalign from HMMER to align sequences

- software/raxmlng/main.nf
Just updating the process label to high
> raxml-ng is compute intensive - upgrade process label to high

- software/last/lastdb/functions.nf
- software/last/lastdb/main.nf
- software/last/lastdb/meta.yml
- tests/config/pytest_software.yml
- tests/software/last/lastdb/main.nf
- tests/software/last/lastdb/test.yml
The `lastdb` command creates a sequence index for the [LAST aligner](https://gitlab.com/mcfrith/last). Input can be in FASTA or FASTQ format, and compression is handled automagically.  DNA or protein sequences can be indexed.
The sequence index is a collection of files sharing the same basename. This module sets the basename to the sample identifier (`$meta.id`) and creates the index in a directory always called `lastdb`.  The module's output channel then conveys a copy of the metadata and the path to the `lastdb` directory.
Other modules will follow (see Issue #464).  The LAST aligner can align proteins to proteins, DNA to DNA and can translate DNA align to proteins.
Closes #XXX 
> New last/lastdb module to index sequences before alignment.

- .github/workflows/nf-core-linting.yml
- .github/workflows/pytest-workflow.yml
- README.md
- tests/config/nextflow.config
Recent stable release https://github.com/nextflow-io/nextflow/releases/tag/v21.04.0
Mainly to test the CI against it, and to open the discussion for whether we need to support the older edge version.
> build: Bump version to 21.04.0

- software/artic/minion/meta.yml
- tests/config/nextflow.config
The build time for `conda` build has been increased to `120 min`. The default time (20 min), see [here](https://www.nextflow.io/docs/latest/config.html#scope-conda), was not enough for many tools and the `conda` tests were repeatedly failing due to this reason.
Also, the description of the `meta.yml` file of the `artic/minion` module was missing. Updated.
> Increase conda build time

- software/bowtie/align/main.nf
- software/bowtie2/align/main.nf
- software/bwa/mem/main.nf
- software/bwamem2/mem/main.nf
- software/bwameth/align/main.nf
- tests/software/bwa/mem/test.yml
- tests/software/bwamem2/mem/test.yml
Split the number of CPUs in modules with two tools in a piped command and each of them with an explicit declaration of the CPUs to be used. See #498 
Closes #498
> Fix number of cpus for modules with piped tools

- README.md
Running pytest with `--tag fastqc_single_end` does not work (it runs zero tests), as it appears that the tag name was changed to `fastqc` during the transition from underscores to slashes.
> Update pytest tag name for fastqc in README's examples

- software/last/train/functions.nf
- software/last/train/main.nf
- software/last/train/meta.yml
- tests/config/pytest_software.yml
- tests/config/test_data.config
- tests/software/last/train/main.nf
- tests/software/last/train/test.yml
The last-train command creates a parameter file that will be used by last/lastal module for sequence alignment. It takes indexed sequences and query sequences as input and we use the metadata of both to create an id of the parameter output file.
Submission of the LAST modules is discussed in more details in the issue #464. For consistency, we use LAST version 1219 for this whole development and will upgrade later.
Closes #XXX 
> New last/train module to train alignment parameters.

- software/last/mafswap/functions.nf
- software/last/mafswap/main.nf
- software/last/mafswap/meta.yml
- tests/config/pytest_software.yml
- tests/config/test_data.config
- tests/software/last/mafswap/main.nf
- tests/software/last/mafswap/test.yml
The `maf-swap` tool distributed with [LAST](https://gitlab.com/mcfrith/last) reorders sequences in alignment files in [Multiple Alignment Format](https://genome-asia.ucsc.edu/FAQ/FAQformat.html#format5). When run without command-line arguments, it will swap the target and the query sequences.  This is useful when turning a many-to-many alignment into a many-to-one and then a one-to-one alignment in conjunction with the `last-split` command (split, swap, split and swap again).
The LAST aligner outputs MAF files, but other tools also use this format.  As MAF files can be very large (up to hundreds of gigabytes), the module expects its input to be compressed with gzip and will compress its output.
This new module is part of the work described in Issue #464.  During this development, we fix …
> New module last/mafswap to reorder sequences in alignments

- software/last/split/functions.nf
- software/last/split/main.nf
- software/last/split/meta.yml
- tests/config/pytest_software.yml
- tests/software/last/split/main.nf
- tests/software/last/split/test.yml
The `last-split` tool distributed with [LAST](https://gitlab.com/mcfrith/last) finds split (typically for DNA) or spliced (typically for RNA) alignments in a [MAF](https://genome-asia.ucsc.edu/FAQ/FAQformat.html#format5) file that is produced with, for example, LAST `lastal` or `maf-swap` command.
This new module is part of the work discribed in Issue #464. During this development, we fix the versiob of LAST to 1219 to ensure consistency. We will upgrade it later.
Closes #XXX 
> New last/split module to find split alignments.

- software/last/lastal/functions.nf
- software/last/lastal/main.nf
- software/last/lastal/meta.yml
- tests/config/pytest_software.yml
- tests/config/test_data.config
- tests/software/last/lastal/main.nf
- tests/software/last/lastal/test.yml
`lastal` is the main program of the [LAST](https://gitlab.com/mcfrith/last) suite.  It aligns query DNA sequences in FASTA or FASTQ format to a target index of DNA or protein sequences.  The index is produced by the `lastdb` program (module `last/lastdb`).  The score matrix for evaluating the alignment can be chosen among preset ones or computed iteratively by the `last-train` program (module `last/train`).  For this reason, the `last/lastal` module proposed here has one input channel containing an optional file, that has to be dummy when not used.
The LAST aligner outputs MAF files that can be very large (up to hundreds of gigabytes), therefore this module unconditionally compresses its output with gzip.
This new module is part of the work described in Issue #464.  During this …
> New last/lastal module to align query sequences on a target index

- tests/config/nextflow.config
> Remove docker.runOptions in favor of docker.userEmulation

- software/last/dotplot/functions.nf
- software/last/dotplot/main.nf
- software/last/dotplot/meta.yml
- tests/config/pytest_software.yml
- tests/software/last/dotplot/main.nf
- tests/software/last/dotplot/test.yml
The `last-dotplot` tool takes a pairwise alignment in [MAF](http://genome.ucsc.edu/FAQ/FAQformat.html#format5) format,
possibly compressed with gzip, or in a tabular format produced by the `maf-convert` tool, and produces a similarity dot-plot of the two sequences in one of the graphical formats supported by the Python Imaging Library.
A the tool guesses the output format by the file extension of the file, which is constructed by the module at run time, I have used the `args2` option to convey this information to the module.
This new module is part of the work described in Issue #464.  During this development, we fix the version of LAST to 1219 to ensure consistency (hence please ignore lint's version warning).
Closes #XXX 
- Ensure that the test works with either Docker / Singularity. …
> New last/dotplot module for pairwise similarity plots

- software/last/postmask/functions.nf
- software/last/postmask/main.nf
- software/last/postmask/meta.yml
- tests/config/pytest_software.yml
- tests/software/last/postmask/main.nf
- tests/software/last/postmask/test.yml
The `last-postmask` tool distributed with [LAST](https://gitlab.com/mcfrith/last) filters alignments in a MAF file to remove those with too many masked (lower-case) positions compared with their score.
As other filter modules like `last/split`, its output file risks to overwrite its input file as their names are constructed from the sample
ID when multiple filters are chained in the pipeline.  Following our discussion on Slack, I added a check that gives a clearer error message in this case.  Please let me know what you think about; I can add this test to the existing LAST modules as well.
This new module is part of the work described in Issue #464. During this development, we fix the version of LAST to 1219 to ensure consistency. We will upgrade it later.
- Ensure that the test works …
> New module last/postmask to filter alignment files

- software/salmon/quant/main.nf
- software/salmon/quant/meta.yml
- tests/software/salmon/quant/main.nf
- tests/software/salmon/quant/test.yml
An input `val` has been included in `salmon/quant` which enables to set the `--libType A option`. This option allows Salmon to automatically infer the library type.
Closes #535
> Update salmon/quant to provide '--libType A' option

- software/fastqc/main.nf
when using the suffix option in the fastqc module it gets added with a "." to the ${meta.id}, this leads to sample name clashing when passing the fastqc output of raw and processed files suffixed with "trim" or "clean" to multiqc.
I suggest to remove the "." this would also be more consistent with the prefix def in most of the other nf-core modules.
##' Ref:
https://nfcore.slack.com/archives/CJRH30T6V/p1625129138043900
Closes #XXX 
> do not add "." in prefix when suffix is set

- software/last/lastal/main.nf
- tests/software/last/lastal/main.nf
The `last/lastal` submodule aligns query sequences to  a target index, and optionally takes one set of alignment parameters (including a score matrix) computed by the `last/train` module for each of the sequences.
In the previous implementation the sequences and the alignment parameters were provided in different channels, but this was causing them to be sometimes desynchronised.
In the patched implementation, `last/lastal` takes a 3-tuple as input to ensure synchronicity.  To produce this tuple in a pipeline,
one can use the `join` command as in the following example.
LAST_TRAIN  ( query,
target )
LAST_LASTAL ( query.join(LAST_TRAIN.out.param_file),
target )
In case no parameter file is computed one can pass a dummy file to the module as follows:
LAST_LASTAL ( query.map { row -> [ …
> Input a triple (id, fasta, params) to last/lastal

- tests/modules/lofreq/call/test.yml
Lofreq output VCF contains the current day date therefore automated tests containing md5sum will fail when the date changes.
> fix: lofreq/call `test.yml` md5sum

- modules/lofreq/callparallel/main.nf
- modules/lofreq/callparallel/meta.yml
- tests/modules/lofreq/callparallel/test.yml
After using the `lofreq/callparallel` module I noticed that my arguments were not being passed to the process as it was missing `$options.args`.
In addition:
- changed the version file to only contain version number
- changed test to check if the output file contains a string
- as lofreq can output compressed based on suffix changed output to compressed vcf
> fix: lofreq/callparallel missing arg (#562)

- modules/samtools/ampliconclip/functions.nf
- modules/samtools/ampliconclip/main.nf
- modules/samtools/ampliconclip/meta.yml
- tests/config/pytest_modules.yml
- tests/modules/samtools/ampliconclip/main.nf
- tests/modules/samtools/ampliconclip/test.yml
I have added the module with some optional outputs that are passed as params similar as it is implemented currently in `ivar/variants`:
https://github.com/nf-core/modules/blob/0b40798d1b59a28bd86aa5b558a0793614be1efa/modules/ivar/variants/main.nf#L34-L35
I have also included the `param` value setting in the `test.yml` files, again as it is currently implemented in `ivar/variants`:
https://github.com/nf-core/modules/blob/0b40798d1b59a28bd86aa5b558a0793614be1efa/tests/modules/ivar/variants/main.nf#L7-L10
@drpatelh, following the explanation from you on slack let me know if you would prefer me to move it from `params` to `input` and remove the assignments to `params.save_cliprejects` and `params.save_clipstats`.   
- Ensure that the test works with either Docker / Singularity. Conda CI tests …
> Add samtools ampliconclip

- modules/fastp/main.nf
- tests/modules/fastp/main.nf
- tests/modules/fastp/test.yml
Current `fastp` module includes a `params` option which isn't allowed according to the nf-core module guidelines. This replaces the `params.save_trimmed_fail` with a input `value` channel
Note: I'm not sure if this is the most optimal implementation here, as it means it adds a _required_ input channel , and I'm not 100% of this parameter can be considered to be 'required as it requires the explicit creation of an extra channel for a parameter maybe irrelevant for some cases of `fastp`.
Closes #594 
> Replaced param with input val channel

- modules/star/align/main.nf
- modules/star/align/meta.yml
- tests/modules/star/align/main.nf
- tests/modules/star/align/test.yml
Added an optional output channel for getting chimeric junctions from STAR/align. This is required for the downstream analysis for fusion calling with STAR-fusion.
> Added an optional output junction channel in STAR

- modules/nextclade/main.nf
- modules/nextclade/meta.yml
- tests/modules/nextclade/main.nf
- tests/modules/nextclade/test.yml
This PR will fix https://github.com/nf-core/viralrecon/issues/226. I have thought about this a little and it is going to be too much hassle adding logic to check for multiple output formats in the module / pipeline. We can simply just publish whichever files with `publish_files` in `modules.config` and leave it up to the user to amend that via a `custom.config` if required. The files will be tiny and the `work/` directory will most likely be deleted after the run anyway.
> Update Nextclade to output all files by default

- modules/rseqc/bamstat/main.nf
- modules/rseqc/inferexperiment/main.nf
- modules/rseqc/innerdistance/main.nf
- modules/rseqc/junctionannotation/main.nf
- modules/rseqc/junctionsaturation/main.nf
- modules/rseqc/readdistribution/main.nf
- modules/rseqc/readduplication/main.nf
This is the prerequisite to close the following bug: nf-core/rnaseq#685 
This PR mainly enforces a working conda env with the appropriate R version needed by rseqc
> Require r-base>=3.5 for RSeqC Conda envs

- modules/gatk4/mutect2/main.nf
- modules/gatk4/mutect2/meta.yml
- tests/modules/gatk4/mutect2/test.yml
This pull request adds an output channel for the stats file generated by mutect2. File is necessary when running filtermutectcalls. Meta yml file updated to include new output. Tests.yml updated to expect the stats file as an output during testing.
> Update for mutect2: add output channel for stats file

- .github/workflows/code-linting.yml
- .github/workflows/nf-core-linting.yml
- .github/workflows/pytest-workflow.yml
Currently the CI runs twice unless the PR comes from a forked repository, see for instance #739
The suggested change makes the CI only run on pull requests, and if the changes actually get merged into the master branch.
> Run CI only on pull-requests and on the master-branch.

- tests/test_versions_yml.py
Cover case when processes have been imported under different name. 
See discussion on slack https://nfcore.slack.com/archives/CJRH30T6V/p1632487431023500.
> Fix test for integrity of `versions.yml`

- modules/chromap/chromap/main.nf
- modules/delly/call/main.nf
- modules/ensemblvep/main.nf
- modules/expansionhunter/main.nf
- modules/fgbio/callmolecularconsensusreads/main.nf
- modules/fgbio/sortbam/main.nf
- modules/glnexus/main.nf
- modules/kleborate/main.nf
- modules/minia/main.nf
- tests/config/test_data.config
- tests/modules/delly/call/test.yml
- tests/modules/hifiasm/main.nf
- Fixes `chromap/chromap`, `delly/call`, `ensemblevep`, `expansionhunter`, `fgbio/callmolecularconsensusreads`, `fgbio/sortbam`, `glnexus`, `kleborate`, `minia`
- For `minia` I changed how the input list is created due changes in indentation created by previous method
- had to do something similar with  `chromap`  
- `fgbio` had color codes in the version that had to be removed
- Added `hifi` to test_data.config to make `hifiasm` work again
> few version and test data config fixes

- modules/custom/dumpsoftwareversions/functions.nf
- modules/custom/dumpsoftwareversions/main.nf
- modules/custom/dumpsoftwareversions/meta.yml
- tests/config/pytest_modules.yml
- tests/modules/custom/dumpsoftwareversions/main.nf
- tests/modules/custom/dumpsoftwareversions/test.yml
* Updated version of (and closes) https://github.com/nf-core/modules/pull/368
* Since the Python code is self-contained within the module we don't have to worry about providing a separate executable for the module
* We can now install this module directly into the pipeline template
* Can't check for md5sums in the tests because the NF version outputted to the YAML will be subjective on where you run the tests
> Add custom/dumpsoftwareversions modules for nf-core pipeline template

- modules/bowtie/align/main.nf
- modules/bowtie2/align/main.nf
- modules/bwa/mem/main.nf
- modules/bwamem2/mem/main.nf
- modules/bwameth/align/main.nf
In case of modules with piped commands, currently, we are splitting the number of cpus assigned for that process equally between the two softwares. This is good idea in general, but when we have a combination of aligner and samtools (for converting the resulting output to bam), I think it is very inefficient to assign half the number of cpus to samtools when the rate limiting step here is the alignment.
These are the affected modules.
-  bowtie/align
-  bowtie2/align
-  bwa/mem
-  bwamem2/mem
-  bwameth/align
Based on the comments and discussion in the nf-core slack channel [here](https://nfcore.slack.com/archives/CJRH30T6V/p1632822976224200), [here](https://nfcore.slack.com/archives/CJRH30T6V/p1632822291214200), and [here](https://nfcore.slack.com/archives/CJRH30T6V/p1632822851221500), I …
> remove cpu restrictions for piped commands

- modules/csvtk/concat/main.nf
Closes #XXX 
@drpatelh haha as soon as you merged, I thought of something.
In the current implementation, you could theoretically get output files with random delimiter characters (e.g. if `out_format = '-'` the output file would be named `*.-` and thats an issue.
I think should make it either `tsv` or default to `csv`
> patch output extension in csvtk/concat

- modules/allelecounter/main.nf
- modules/allelecounter/meta.yml
- tests/modules/allelecounter/main.nf
- tests/modules/allelecounter/test.yml
Closes #1012
This PR adds support for CRAM files to the allelecounter module by adding an optional fasta input parameter
> Add cram support to Allelecounter module

- modules/bbmap/align/main.nf
- tests/modules/bbmap/align/test.yml
Closes #XXX 
Standard output from the command was not kept except in `.command.log`. I added this as an output channel.
MD5 sums from log files are not stable (probably because the time it took is recorded), so I didn't add them to `test.yml`.
> Add log to output from bbmap/align

- modules/gatk4/splitncigarreads/main.nf
- modules/gatk4/splitncigarreads/meta.yml
- tests/modules/gatk4/splitncigarreads/main.nf
fasta_fai_dict tuple channel has now been split into separate input channels as followed in other modules. It could be convenient way to pass inputs to module when used. 
> GATK4 SplitNCigarReads: fasta_fai_dict tuple is now split into separate input channels

- modules/picard/markduplicates/main.nf
- tests/modules/picard/markduplicates/main.nf
- tests/modules/picard/markduplicates/test.yml
The way options are set has in the script section has been updated to fit the new syntax `I= or INPUT=` instead of `-I`
Also, `test.yml` has been updated not to check md5sum and the `metrics.txt` is now checked for containing a given string. 
Closes #1071
> Fix picard markduplicates

- .github/workflows/pytest-workflow.yml
Currently adding entire `work` directory of CI tests to artifacts includes entire singularity images or ocnda environments which take a long time to upload and subsequently download when trying debug modules.
This excludes those specific folders to make the whole process faster, but also reduce our disk footprint
> fix: exclude conda/singularity images from pytest workflow output

- modules/rsem/preparereference/main.nf
Closes https://github.com/nf-core/rnaseq/issues/727
> Fix transcriptome staging issues on DNAnexus for rsem/prepareference

- modules/samtools/index/main.nf
- tests/modules/samtools/index/test.yml
Reverts https://github.com/nf-core/modules/pull/1147 to keep with `emit` a single output file per channel as per the nf-core/modules guidelines.
> Revert PR #1147

- .github/check_duplicate_md5s.py
Related to https://github.com/nf-core/tools/pull/1358 - quick script to make it easy to find instances of duplicate md5sums.
```console
❯ python .github/check_duplicate_md5s.py --help
Usage: check_duplicate_md5s.py [OPTIONS]
Find duplicate file MD5 sums in test YAML files.
Options:
--min_dups INTEGER  Minimum number of duplicates to report  [default: 5]
--search_dir TEXT   Glob directory pattern used to find test YAML files
[default: .github/../tests/**/test.yml]
--help              Show this message and exit.
```
This script is not currently run anywhere automatically (in any CI), so is only an undocumented helper script for maintainers.
> Add helper script to find duplicate test YAML md5s

- modules/hmmcopy/generatemap/main.nf
- modules/picard/collecthsmetrics/main.nf
- modules/picard/collectmultiplemetrics/main.nf
- modules/picard/collectwgsmetrics/main.nf
- modules/picard/filtersamreads/main.nf
- modules/picard/markduplicates/main.nf
- modules/picard/mergesamfiles/main.nf
- modules/picard/sortsam/main.nf
As bought to our attention in https://github.com/nf-core/rnaseq/issues/734
> Bump picard version from 2.25.7 to 2.26.7 for log4j vulnerability

- modules/kleborate/main.nf
- tests/modules/kleborate/test.yml
Closes #XXX 
Recipe only allowed `*.fasta`  files as inputs, this fixes it to use `$fastas`
> Fix kleborate inputs

- modules/gatk4/applybqsr/main.nf
- modules/gatk4/applybqsr/meta.yml
- modules/gatk4/baserecalibrator/main.nf
- modules/gatk4/baserecalibrator/meta.yml
- modules/gatk4/genotypegvcfs/main.nf
- modules/gatk4/genotypegvcfs/meta.yml
- modules/gatk4/haplotypecaller/main.nf
- modules/gatk4/haplotypecaller/meta.yml
- tests/modules/gatk4/applybqsr/main.nf
- tests/modules/gatk4/applybqsr/test.yml
- tests/modules/gatk4/baserecalibrator/main.nf
- tests/modules/gatk4/genotypegvcfs/main.nf
- tests/modules/gatk4/genotypegvcfs/test.yml
- tests/modules/gatk4/haplotypecaller/main.nf
In sarek we use these modules with multiple intervals per sample. So to make sure that all samples are run with all intervals, I propose to change the interval input to go along with the sample. 
Closes #XXX 
> Change intervals to be part of sample specific input

- modules/last/postmask/main.nf
- modules/plink/extract/main.nf
- modules/pmdtools/filter/main.nf
- modules/samblaster/main.nf
- modules/samtools/fixmate/main.nf
Fix several error messages that still were mentioning the deprecated `suffix` option. 
> Fix error messages mentioning suffix

- modules/ataqv/ataqv/main.nf
- modules/bcftools/index/main.nf
- modules/bowtie2/build/main.nf
- modules/cutadapt/main.nf
- modules/fgbio/fastqtobam/main.nf
- modules/gtdbtk/classifywf/main.nf
- modules/idr/main.nf
- modules/jupyternotebook/main.nf
- modules/krona/kronadb/main.nf
- modules/malt/run/main.nf
- modules/paraclu/main.nf
- modules/pirate/main.nf
- modules/porechop/main.nf
- modules/rmarkdownnotebook/main.nf
- modules/spatyper/main.nf
- tests/config/pytest_modules.yml
Fixed some of these whilst developing https://github.com/nf-core/tools/pull/1374
* Now properly allow for `input:` and `output:` not being specified in module
* Allow for containers from other biocontainers resource
* Allow for `stageAs` syntax as defined here: https://github.com/nf-core/modules/blob/cde237e7cec07798e5754b72aeca44efe89fc6db/modules/cat/fastq/main.nf#L11
* Fix mismatching container versions and replace `%3A` notation with `:`
* Add missing modules to `pytest_modules.yml`
* Fix modules using `version` instead of `versions` in `emit` statement
Most of the remaining lint warnings are for modules that needs a version bump and those that generate empty files.
> Fix modules warned or failed with nf-core modules lint

- modules/bcftools/sort/main.nf
- modules/bcftools/sort/meta.yml
- tests/config/pytest_modules.yml
- tests/modules/bcftools/sort/main.nf
- tests/modules/bcftools/sort/nextflow.config
- tests/modules/bcftools/sort/test.yml
Closes #915
This PR adds the bcftools/sort utility, which can be useful subworkflows manipulating VCFs.
> Bcftools sort new syntax

- modules/cat/cat/main.nf
- tests/modules/cat/cat/main.nf
- tests/modules/cat/cat/test.yml
The `cat/cat` module as is can't handle a single file. In a pipeline, if a previous step e.g. splits a fasta-file based on size and then `cat/cat` is run to gather the results it will work for more than one file, but it would be desirable if it also worked on a single file. Therefore I've edited the module to process single files as well as more than one file.
> Editing the CAT/CAT module to handle single files

- modules/artic/minion/main.nf
In order for nanopolish to be able handle the default compression for Mk1C Minions (vbz) it must be aware of where to find the plugin. Exporting the HDF5_PLUGIN_PATH found in the conda install (also used to make the biocontainer image) is the solution
See also
https://github.com/jts/nanopolish/issues/899#issuecomment-826920235
Closes #XXX 
> Add functionality to handle vbz compression

- modules/chromap/chromap/main.nf
- tests/modules/chromap/chromap/test.yml
- tests/modules/chromap/index/test.yml
The previous version of `chromap` was not producing `sam` files that were parsable by samtools. The version of  `chromap` and `samtools` have been updated to 0.1.5 and 1.14, respectively.
> Bump version 0.1.5 to chromap/chromap

- .github/workflows/pytest-workflow.yml
If nextflow fails within `pytest` it is relatively hard to figure out what's going on. At the moment it is necessary to download the artifacts and retrieve the log files from there. This PR prints out the logfiles to the github actions log in case of failure, which I find more convenient. 
If something goes wrong within a work directory, it will still be necessary to obtain the artifact. 
---
> CI: print out pytest logs on failure

- modules/nextclade/datasetget/main.nf
- modules/nextclade/run/main.nf
- tests/modules/nextclade/datasetget/main.nf
- tests/modules/nextclade/datasetget/test.yml
- tests/modules/nextclade/run/main.nf
- tests/modules/nextclade/run/test.yml
Factors in breaking changes introduced in [1.10.1](https://github.com/nextstrain/nextclade/releases/tag/1.10.0)
> Bump Nextclade version to 1.10.1

- .nf-core.yml
Add config `repository_type`, to be used by nf-core/tools after https://github.com/nf-core/tools/pull/1391 is merged.
> Add repository_type to .nf-core.yml

- modules/gatk4/genotypegvcfs/main.nf
- modules/gatk4/genotypegvcfs/meta.yml
In order to run the GATK `GenotypeGVCFs` tool with an interval file (such as a .bed file) you need to have the corresponding index file. Otherwise you get the following error message
```
A USER ERROR has occurred: An index is required but was not found for file genome.bed.gz: work/6c/541fce2dc670597f62a571c72288c6/genome.bed.gz. Support for unindexed block-compressed files has been temporarily disabled. Try running IndexFeatureFile on the input.
```
including the index file fixes this problem
> include intervals_index

- modules/seqtk/seq/main.nf
- tests/modules/seqtk/seq/test.yml
Fixes the indent levels in `versions.yml` for seqtk/seq module, making it compatible with custom/dumpsoftwareversions.
Closes #1383
- [NA] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
> Decrease indent in seqtk/seq versions.yml output

- modules/bwa/aln/meta.yml
I guess we should probably lint for proper `meta.yml` structure.
> Fix indentation in bwa/aln meta

- modules/panaroo/run/main.nf
- modules/panaroo/run/meta.yml
- modules/pirate/main.nf
- tests/config/pytest_modules.yml
- tests/modules/panaroo/run/main.nf
- tests/modules/panaroo/run/nextflow.config
- tests/modules/panaroo/run/test.yml
- tests/modules/pirate/test.yml
Closes https://github.com/nf-core/modules/issues/1443
I opted for `panaroo/run` because panaroo has a few other sub-commands that might be added in the future. I also cleaned up some lingering comments in the PIRATE test `main.nf`
> add module for panaroo, fix pirate tests

- modules/cat/cat/main.nf
- modules/cat/cat/meta.yml
- tests/modules/cat/cat/main.nf
- tests/modules/cat/cat/nextflow.config
- tests/modules/cat/cat/test.yml
The current cat module doesn't take in a meta map, ths would be helpful to have when concatenating i.e. sample specific files. 
Also, the output file name is currently specified as an input val, which is very different from the other modules. I would therefore propose that in general it should be supplied via `task.ext.prefix` and as a default option use the file ending of the `input` files
Closes #XXX 
> CAT: Use meta map and supply output file name via modules.config

- modules/homer/maketagdirectory/main.nf
- modules/homer/maketagdirectory/meta.yml
- tests/modules/homer/findpeaks/test.yml
- tests/modules/homer/maketagdirectory/test.yml
- tests/modules/homer/pos2bed/test.yml
This fixes the `maketagdirectory` caching. A follow-up to #1437.
> Fix homer/maketagdirectory output collision

- modules/chromap/chromap/main.nf
- modules/chromap/index/main.nf
- tests/modules/chromap/chromap/test.yml
- tests/modules/chromap/index/test.yml
Bump version 0.2.1 of `chromap`
> Bump chromap version 0.2.1

- modules/gstama/polyacleanup/main.nf
- modules/gstama/polyacleanup/meta.yml
- tests/config/pytest_modules.yml
- tests/modules/gstama/polyacleanup/main.nf
- tests/modules/gstama/polyacleanup/nextflow.config
- tests/modules/gstama/polyacleanup/test.yml
A module for TAMA's tama_flnc_polya_cleanup.py script (https://github.com/GenomeRIK/tama/wiki/TAMA-GO:-Sequence-Cleanup). This script is used to remove remaining polyA tails from Full Length Non Chimeric reads (isoseq 3). 
> New Module: `gstama/polyacleanup`

- modules/phantompeakqualtools/main.nf
- modules/phantompeakqualtools/meta.yml
- tests/config/pytest_modules.yml
- tests/modules/phantompeakqualtools/main.nf
- tests/modules/phantompeakqualtools/nextflow.config
- tests/modules/phantompeakqualtools/test.yml
As explained [here](https://github.com/nf-core/chipseq/issues/220), when the data set is too big the `phantompeakqualtools` throws an exception. Adding the option fixes the problem `--max-ppsize=500000`. On this PR, `task.ext.args` to the  `phantompeakqualtools` command and also, all the missing bits of the module were added (tests + meta.yml file)
> Add task.ext.args to phantompeakqualtools and finish the module

- modules/centrifuge/main.nf
- modules/centrifuge/meta.yml
- tests/modules/centrifuge/main.nf
- tests/modules/centrifuge/test.yml
Update centrifuge module so that the database is extracted using the untar module
Closes #XXX 
> Fix untar for centrifuge

- subworkflows/nf-core/homer/groseq/main.nf
- subworkflows/nf-core/homer/groseq/meta.yml
- tests/subworkflows/nf-core/homer/groseq/main.nf
- tests/subworkflows/nf-core/homer/groseq/nextflow.config
- tests/subworkflows/nf-core/homer/groseq/test.yml
Adding homer groseq subworkflow here, so it can be supported by tests more easily and because it's a pure nf-core subworkflow.
> feat(homer): Add groseq subworkflow

- tests/config/test_data.config
This PR updates the `test_data.config` file to include kaiju database directory in tar format.
> Update test_data.config to include kaiju.tar.gz

- modules/elprep/split/main.nf
- tests/modules/elprep/split/test.yml
Fix output glob and write outputs to subdir. This avoids globbing input data into the outputs.
> elprep/split: fix output glob

- modules/elprep/filter/main.nf
- tests/modules/elprep/filter/test.yml
This PR fixes the output glob for `elprep filter` to avoid globbing the input data into the outputs
> elprep/filter: fix output glob

- modules/cat/fastq/main.nf
- modules/gunzip/main.nf
- modules/untar/main.nf
x-ref: https://github.com/nf-core/rnaseq/issues/764
> Replace vanilla Linux Biocontainer with Ubuntu

- modules/phantompeakqualtools/main.nf
When running the dev version of the chipseq pipeline in my cluster with the test_full  dataset and it turned out that the process `phantompeakqualtools` was taking too long to run and being killed. If the the argument to set the number of cpus used by run_spp.R (i.e. -p=$task.cpus) from the [command in the process](https://github.com/nf-core/chipseq/blob/c1975ca9d9a6dbb53d1584ad27e6884b2c0228da/modules/nf-core/modules/phantompeakqualtools/main.nf#L29) section then the process speeds up to only 1h and something. So seems that the way multithreading is handled in the script is not efficient enough. Hence I disabled this option from the module and this option can be now pass as an optional parmeter, see below:
```
withName: 'PHANTOMPEAKQUALTOOLS' {
ext.args   = { "-p=$task.cpus" }
```
- …
> Remove task.cpus from the command of the phantompeakqualtools module

- tests/config/test_data.config
This PR adds the [GBFF test data](https://github.com/nf-core/test-datasets/blob/modules/data/genomics/prokaryotes/bacteroides_fragilis/genome/genome.gbff.gz) of the *Bacteroides fragilis* prokaryotic genome as present in the [test-datasets repo](https://github.com/nf-core/test-datasets/tree/modules/data/genomics/prokaryotes/bacteroides_fragilis/genome) to the test_data.config file. It is not apparent why this single file was missing (maybe got removed in the recent folder structure reshuffle).
> Add missing bacteroides_fragilis genome.gbff.gz

- modules/antismash/antismashlitedownloaddatabases/main.nf
- modules/antismash/antismashlitedownloaddatabases/meta.yml
- tests/modules/antismash/antismashlitedownloaddatabases/test.yml
Some folders, which are not present in the container (only created during the antiSMASH database download), but required for antismashlite to work, are now emitted as output channels of this module. They can then be mounted as additional volumes when using docker/singularity containers of the antismashlite module.
Closes #XXX 
> Add antismash download DB: missing container folders as output channels

- modules/custom/getchromsizes/main.nf
All SAMtools modules have been updated to 1.15 and this PR does the same for `custom/getchromsizes` so a single container is downloaded when running pipelines (if possible).
> Bump SAMtools version for custom/getchromsizes

- modules/gatk4/haplotypecaller/main.nf
When working with larger chromosomes (e.g. Chromosome 1 of _Monodelphis domestica_ has a size of 748055161bp), GATK HaplotypeCaller fails to create a TBI index for the VCF file. The current implementation of BAI and TBI in HTSLib is limited to 512Mb [doi: 10.1093/gigascience/giab007]. In such cases, we will have to turn off index creation (--create-output-variant-index false) to get the variant calls. So this PR is to make the *.tbi as an optional output to handle such large genomes for variant calling.
Closes #XXX 
> Changed tbi as optional output in GATK4 HaplotypeCaller

- modules/tiddit/sv/main.nf
- tests/modules/tiddit/sv/test.yml
`TIDDIT_SV` is currently broken as the input `fasta` option is ignored unless it's named "dummy_file.txt":
https://github.com/nf-core/modules/blob/68f1c27169946f931ea4318911de5681f88b2961/modules/tiddit/sv/main.nf#L27
This PR fixes that bug and adds md5sum's to the unit test VCF's that were previously missing.
> Fix tiddit/sv

- modules/minimap2/align/main.nf
There seems to be a small typo in minimap2/align (`sam_format` likely should be `bam_format`). This PR fixes the typo.
Closes #1585
> Fix a small typo in minimap2/align

- modules/gatk4/markduplicates/main.nf
Changed BAI as optional output in GATk4 MarkDuplicates module:
Two reasons:
- It does not create an index by default. So the module does not work unless you specify `--CREATE_INDEX true`
- For large genomes, BAI does not need to be generated, so we want the module to work even without an index file output.
Closes #XXX 
> Changed BAI as optional output

- modules/metaphlan3/main.nf
Metaphlan3 currently doesn't handle the case when the input gzipped fastq files have `fq.gz` file name suffix. This PR adds that feature to the module.
Closes #1599
> Add additional handling of fq.gz file name suffix

- modules/star/align/main.nf
- modules/star/genomegenerate/main.nf
- tests/modules/star/align/test.yml
Bumping here to be able to use default nf-core/module in rnaseq and a custom one for iGenomes. See https://github.com/nf-core/rnaseq/issues/834
> Bump container version for STAR to 2.7.10a

- modules/filtlong/main.nf
- tests/modules/filtlong/nextflow.config
- tests/modules/filtlong/test.yml
Now the tool runs properly, I realised that the module goes against the [module guidelines](https://nf-co.re/docs/contributing/modules#naming-conventions) in that it hardcodes it's 'own' file name (breaking taxprofiler's publishDir directive). 
This is is something that should be specified in `modules.config`. I've added a check for this accordingly.
Closes #XXX 
> Fix filtlong to remove hardcoded output names

- modules/deeptools/bamcoverage/main.nf
- modules/deeptools/bamcoverage/meta.yml
- tests/modules/deeptools/bamcoverage/main.nf
- tests/modules/deeptools/bamcoverage/test.yml
This PR uses a new container that first converts cram2bam before running `deeptools/bamcoverage`, as this was not working with real cram-input files. 
> Adjust deeptools/bamcoverage with new mulled container

- modules/untar/main.nf
- tests/config/test_data.config
- tests/modules/untar/main.nf
- tests/modules/untar/test.yml
Fix output when the tar archive has a different name than the tarred dir.
- added test
- no breaking change
Closes #XXX 
> fix untar output dir

- modules/mcroni/main.nf
- modules/mcroni/meta.yml
- tests/config/pytest_modules.yml
- tests/modules/mcroni/main.nf
- tests/modules/mcroni/nextflow.config
- tests/modules/mcroni/test.yml
Closes https://github.com/nf-core/modules/issues/1749
> add module for mcroni

- modules/gatk4/getpileupsummaries/main.nf
Explained here: https://gatk.broadinstitute.org/hc/en-us/community/posts/360074629231-GetPileupSummaries-following-Mutect2-what-inputs-are-suitable-for-intervals-L-
-L/--intervals is required and should be set to the variant site of no intervals are available
Closes #XXX 
> GATK/Getpileupsummaries: If no intervals use variants instead

- modules/vcf2maf/main.nf
- modules/vcf2maf/meta.yml
- tests/config/pytest_modules.yml
- tests/config/test_data.config
- tests/modules/vcf2maf/main.nf
- tests/modules/vcf2maf/nextflow.config
- tests/modules/vcf2maf/test.yml
This adds the vcf2maf module as per #490. To use, supply an uncompressed VCF, a FASTA file and an (optional) VEP cache. 
VEP is required for full functioning of vcf2maf. By default, a multi-package container is used which includes VEP. This does not include the VEP cache by default, so I've included a Dockerfile and shell script that is basically an exact copy of the one in the ensembl-vep module.
Tests are included for with and without VEP. Currently, only the Docker version works with the custom docker image because I can't get it to point to the correct cache. 
Closes #490 
_Note: Requires custom docker container_
> vcf2maf module with built in VEP

- modules/fastp/main.nf
- modules/fastp/meta.yml
- tests/modules/fastp/main.nf
- tests/modules/fastp/test.yml
Since FastP can be used for many operations, I find it slightly confusing that in the results folders of the pipeline fastp-modified reads even if not trimmed contain `.trim.` in the file name. Ideally, I would like to set this via the `modules.config`, but seem like `prefix` is taken for some softlinking. 
Instead, I propose to just add the toolname.
Closes #XXX 
> Proposal: Rename output from fastp module

- modules/multiqc/main.nf
This bumps MultiQC to v1.13a, the dev version of MultiQC that should fix issues for smrnaseq and also some other pipelines where DupRadar (I think rnaseq? @drpatelh FYI) was used and the HTML report contained duplicated sections. 
Can be used until there is a new proper V1.13 release as @ewels suggested 🥳 
Closes #XXX 
> Bump MultiQC to v1.13a (dev)

- modules/ngscheckmate/ncm/main.nf
NGSCheckMate doesn't generate a pdf showing how samples relate to each other if only one sample is included. This PR just makes the output pdf channel optional to stop failures in that case.
- [] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
> NGSCheckMate doesn't generate a pdf for only one sample, made optional output

- modules/antismash/antismashlite/main.nf
- modules/antismash/antismashlite/meta.yml
Adding the option to not supply GFF files as AntiSMASH input, thus enabling GBK support.
> antismashlite: Support GBK input

- modules/picard/collectmultiplemetrics/main.nf
- modules/picard/collectmultiplemetrics/meta.yml
- tests/modules/picard/collectmultiplemetrics/main.nf
- tests/modules/picard/collectmultiplemetrics/test.yml
Changes:
- Add .fai input to Picard CollectMultipleMetrics
- Now supports CRAM effectively.
- Will break existing pipelines!
- Added better testing which looks in all text files.
Fixes #1852
Closes #1852
> fix (1852): picard/collectmultiplemetrics supports CRAM

- modules/ataqv/ataqv/main.nf
- tests/modules/ataqv/ataqv/test.yml
> Bump ataqv version

- modules/artic/guppyplex/main.nf
- modules/artic/minion/main.nf
Looks like the version of `artic` was bumped after the latest release:
https://github.com/artic-network/fieldbioinformatics/compare/1.2.2...master
The Biocontainer would have been built relative to the code in the tagged version and not `master` which is why it is showing the incorrect version on the CLI:
```
$ docker run -it quay.io/biocontainers/artic:1.2.2--pyhdfd78af_0 bash
root@9e6ed8b35659:/# artic --version
artic 1.2.1
```
Don't think rebuilding the Bioconda recipe will fix this because the assets will be frozen relative to the 1.2.2 tagged release. The only solution right now is to manually define the version in the module.
> Add manual version definition for artic modules

- modules/filtlong/main.nf
- modules/filtlong/meta.yml
- tests/modules/filtlong/test.yml
This redirects the stderr which contains logging information into a log file. Potentially useful for MultiQC
Example:
Closes #XXX 
> Update filtlong module to output log file

- modules/motus/profile/main.nf
- modules/motus/profile/meta.yml
- tests/modules/motus/profile/test.yml
This redirects the stderr which contains logging information into a log file. Potentially useful for MultiQC
Example:
Closes #XXX 
> Update MOTUS/PROFILE  module to output log file

- modules/snpeff/main.nf
- modules/snpeff/meta.yml
- tests/modules/snpeff/test.yml
In the Sarek-pipeline, we need the snpEff-module to also output the genes-txt-file and the summary-html-file.
Concerning the test `/home/aspe/dev/fork_modules/tests/modules/snpeff/test.yml`, the test-vcf-file `test.ann.vcf` does contain some variants, but `test.genes.txt` doesn't contain any genes:
```
$ cat test.genes.txt
#GeneName	GeneId	TranscriptId	BioType
```
The `summary.html`-file indicate there there were 9 errors (and the vcf contains 9 variants):
Should those errors give raise to concern?
Closes #XXX 
> DRAFT: Extend output from snpeff

- modules/bwamem2/index/main.nf
- modules/bwamem2/index/meta.yml
- modules/bwamem2/mem/main.nf
- modules/bwamem2/mem/meta.yml
- tests/modules/bwamem2/index/main.nf
- tests/modules/bwamem2/mem/main.nf
I think bwamem2/index and minimap2/index should consider meta in their input and output. This would make it much easier to plug them in workflows (no need to do `.map { it[1] }`).
Closes #1917
> Added support for meta in bwamem2/index

- modules/samtools/faidx/main.nf
ext.args was not used in the actual command-line
Closes #XXX 
> Added support for ext.args in samtools/faidx

- modules/ucsc/bedtobigbed/main.nf
The previous one raises the warning
> WARNING: Skipping mount /path/to/singularity-v3.9.0/var/singularity/mnt/session/etc/resolv.conf [files]: /etc/resolv.conf doesn't exist in container
Closes #XXX 
> Newer container version because the previous one is misconfigured

- modules/kraken2/kraken2/main.nf
As per a request by @Midnighter 
- Previous classified_fastq output channel would include the unclassified and classifiedreads.txt files, this ensures they are not incorrectly picked up
- Also makes the FASTQ option  command injection variables clearer (distinguish from the atual pigz command)
Closes #XXX 
> Improves kraken2 output glob

- modules/msisensor2/msi/main.nf
- modules/msisensor2/msi/meta.yml
- modules/msisensor2/scan/main.nf
- modules/msisensor2/scan/meta.yml
- tests/config/pytest_modules.yml
- tests/modules/msisensor2/msi/main.nf
- tests/modules/msisensor2/msi/nextflow.config
- tests/modules/msisensor2/msi/test.yml
- tests/modules/msisensor2/scan/main.nf
- tests/modules/msisensor2/scan/nextflow.config
- tests/modules/msisensor2/scan/test.yml
Add `msisensor2` `scan` and `msi` modules.
Tests for `msi` in ML mode originate from `msisensor2` repository, because test data in the NF-Core test data repository doesn't seem compatible. 
To do:
- bioconda recipe needs to be built
- singularity image needs to be built
Closes #1976 
- [x Remove all TODO statements.
> 1976 msisensor2

- modules/multiqc/main.nf
- modules/multiqc/meta.yml
- tests/modules/multiqc/main.nf
- tests/modules/multiqc/test.yml
Given both the config file and logo are both optional, and not necessarily required together, this separates the two input channels to make the module more flexible re: input
I will also update the pipeline template accordingly
Closes #XXX 
> Modify MULTIQC: separate logo from config file 

- modules/minimap2/index/main.nf
- modules/minimap2/index/meta.yml
- tests/modules/minimap2/index/main.nf
Follow-up of #1921 and #1917; this time for `minimap2/index`
This PR brings support for the meta map into `minimap2/index`
> Added the meta map to minimap2/index

- modules/multiqc/main.nf
- modules/multiqc/meta.yml
- tests/modules/multiqc/main.nf
Otherwise the fancy `stageAs "?/*"` potentially changes the directory name where the logo file is staged every time, making it incompatible with multiqc_config file...
Closes #XXX 
> Update MultiQC to re-add staging logos as a separate input channel

- modules/samtools/faidx/main.nf
- modules/samtools/faidx/meta.yml
- tests/config/test_data.config
- tests/modules/samtools/faidx/main.nf
- tests/modules/samtools/faidx/test.yml
When the input is a compressed Fasta file (i.e. with bgzip), `samtools faidx` also creates the `.gzi` file to enable random access into the fasta file.
This PR registers an optional .gzi output in the `samtools/faidx` module
The test data are waiting to be merged, cf https://github.com/nf-core/test-datasets/pull/579
> Added the optional .gzi output of "samtools faidx"

- modules/epang/main.nf
- modules/epang/meta.yml
- tests/modules/epang/test.yml
The module did not adhere to the recommendation of outputting gzipped files because I didn't think that downstream tools would handle them easily. It turned out I was wrong. I've changed the module to output a gzipped file through the `jplace` output channel. 
I also changed it to output _copies_ of the jplace and log files with prefix from `$prefix` to the `jplace` and `log` output channels, in order to keep the original file names for anyone wanting to use the directory output channel.
> epang: Output gzipped jplace

- modules/custom/getchromsizes/main.nf
- modules/custom/getchromsizes/meta.yml
- tests/modules/custom/getchromsizes/main.nf
- tests/modules/custom/getchromsizes/test.yml
Similar to #1935 : output the gzi index since `samtools faidx` may create it.
I also added `meta` everywhere since it was missing !
Closes #XXX 
> Upgraded getchromsizes to support meta and output the gzi index

- modules/bakta/main.nf
The variable `prodigal_tf` was mistakenly spelled `prodigal_opt`.
Closes #XXX 
> Fix bakta: variable in main.nf

- modules/hmmer/eslreformat/main.nf
- tests/modules/hmmer/eslreformat/main.nf
- tests/modules/hmmer/eslreformat/nextflow.config
- tests/modules/hmmer/eslreformat/test.yml
I've added a `postprocessing` config file option to the module to allow e.g. removal of gap characters, see discussion in https://github.com/nf-core/modules/pull/2053.
I'm unaware of naming (and other) conventions for this type of thing so please correct me! :-S
> Add postprocessing option to hmmer/eslreformat

- modules/multiqc/main.nf
- modules/multiqc/meta.yml
- tests/modules/multiqc/main.nf
Adds ability to have one(!) other custom config to the MultiQC module.
This allows nf-core pipelines to have the default pipeline one, and then a user to modify sections by supplying their second config file, the contents of which [overrides anything common](https://multiqc.info/docs/#configuring-multiqc) with the pipeline base config file. 
Closes #XXX 
> Update MULTIQC for an additional custom config

- modules/hmmer/hmmalign/main.nf
- tests/modules/hmmer/hmmalign/main.nf
- tests/modules/hmmer/hmmalign/nextflow.config
- tests/modules/hmmer/hmmalign/test.yml
The module output was prefixed with `meta.id` not `prefix`, fixed that, with a test.
> Make hmmer/hmmalign output files with correct prefix

- modules/epang/main.nf
I had forgotten to add `.gz` to the output channel spec when changing the module to output gzipped files -- fixed.
> epang: Missing .gz in output spec

- modules/bakta/main.nf
- modules/deepbgc/download/main.nf
- modules/deepbgc/download/meta.yml
- modules/deepbgc/pipeline/meta.yml
Since I missed my chance to review both DeepBGC modules before merge, here are some tiny suggestions.
The tag in `main.nf` is not needed.
> DeepBGC: tiny revisiosn

- modules/epang/main.nf
The `jplace` output channel didn't output the `meta` map, changed that.
> Make epang output meta with the jplace channel

- modules/cat/fastq/main.nf
This patch fixes an issue where the script output is `null` when the number of files is equal to 1 (SE) or 2 (PE)
Closes #XXX 
> cat/fastq: update conditional

- modules/stringtie/merge/main.nf
I found that `$args` was missing from the command line, so I added it.
Also, I made using a reference annotation optional, i.e. the argument `-G` won't be used when passing an empty list to the `annotation_gtf` input.
Closes #XXX 
> Make stringtie/merge arguments configurable

- modules/samtools/ampliconclip/main.nf
- modules/samtools/depth/main.nf
- modules/samtools/idxstats/main.nf
- tests/modules/samtools/ampliconclip/test.yml
These three samtools commands are all multi-threaded, but it was not exposed in Nextflow
Following the convention of other samtools modules, there is a "minus 1" because of that description of the `--threads` option in the man page:
```
-@, --threads INT
Number of additional threads to use [0]
```
but I don't really know whether `--threads 1` will really make those commands use 2 CPUs
Closes #XXX 
> Multithreaded samtools commands

- modules/custom/dumpsoftwareversions/templates/dumpsoftwareversions.py
- tests/modules/custom/dumpsoftwareversions/main.nf
Otherwise `nf-core lint` complains that "Local copy of module does not match remote"
Closes #XXX 
> Updated dumpsoftwareversions.py to match the pipeline template

- modules/tabix/bgzip/main.nf
- modules/tabix/bgzip/meta.yml
- tests/modules/tabix/bgzip/main.nf
- tests/modules/tabix/bgzip/nextflow.config
- tests/modules/tabix/bgzip/test.yml
When bgzip is given the `-i` option, it creates an index (in gzi format). The index needs to be considered an output so that it can be published. This PR adds an optional output channel to capture the index.
The `-I` option is automatically injected to name the index according to the convention.
Closes #XXX 
> Added an output channel for the gzi index

- .github/workflows/fix-linting.yml
Workflow was copied from the pipeline template but the jinja2 template tags were still there
> Remove jinja tags from workflow

- modules/samtools/view/main.nf
- modules/samtools/view/meta.yml
- tests/modules/samtools/view/main.nf
- tests/modules/samtools/view/nextflow.config
- tests/modules/samtools/view/test.yml
`--qname` or `-N` flag with a read names list allows `samtools/view` to filter alignments
I could not figure out a test for the datasets available.
Closes #XXX 
- [x ] Follow the naming conventions.
- [x ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
> add qname feature to samtools/view

- modules/tabix/bgzip/main.nf
This is a fix for the issue I've mentioned on Slack (https://nfcore.slack.com/archives/CJRH30T6V/p1664528844937629)
The problem was that the `.gzi` file, when available, was flown through both output channels (`output` and `gzi`). I considered regular expressions as advised in the Slack thread, but it felt like it'd be a tricky regex to write.
Seeing the other discussion that I was referred to (about DeepVariant), I also had the idea of being more explicit about the file names I'm expecting, which is actually straightforward in the case of bgzip, since it simply removes the extension.
At the same time, I've added a few more valid bgzip extensions, cf https://github.com/samtools/htslib/blob/develop/bgzip.c#L82
I've tested locally that the output of the channels is correct. If you've got …
> Explicitly name the output files to avoid the gzi index being flown through the `output` channel

- modules/nf-core/stringtie/merge/meta.yml
- modules/nf-core/stringtie/stringtie/main.nf
- modules/nf-core/stringtie/stringtie/meta.yml
- tests/modules/nf-core/stringtie/stringtie/main.nf
- tests/modules/nf-core/stringtie/stringtie/test.yml
As done in #2049 for `stringtie/merge`, this PR makes the GTF input optional (enables passing an empty list `[]` to not use a reference annotation during assembly).
Also, made the variable name consistent between `stringtie/merge` and `stringtie/stringtie`, and updated the `meta.yml` to reflect the changes.
Closes #XXX 
> [stringtie/stringtie] make gtf input optional

- tests/config/nextflow.config
This is my proposal to address conda testing failures, with reference to https://github.com/nextflow-io/nextflow/pull/3073.
Motivate by failure discussed in https://nfcore.slack.com/archives/CJRH30T6V/p1665736973295039,  https://github.com/nf-core/modules/pull/2167.
In summary, the Conda profile is no longer driving Conda environment creation and usage, which was [noted previously](https://nfcore.slack.com/archives/C0415MQNW14/p1665485750441599), so I think we just need to set this param explicitly. 
> set conda.enabled=true to fix Conda testing 

- subworkflows/nf-core/bcl_demultiplex/main.nf
- subworkflows/nf-core/bcl_demultiplex/meta.yml
- tests/subworkflows/nf-core/bcl_demultiplex/main.nf
Allow tar archives as bcl dir.
Closes #XXX 
> subworkflow bcl_demultiplex: allow tarred inputs

- modules/nf-core/deseq2/differential/meta.yml
- modules/nf-core/deseq2/differential/templates/deseq_de.R
- tests/modules/nf-core/deseq2/differential/main.nf
- tests/modules/nf-core/deseq2/differential/nextflow.config
- tests/modules/nf-core/deseq2/differential/test.yml
This PR:
- Adds a basic method for being flexible with input files (CSV or TSV). There's a lot of inconsistency in what's used, and maybe it's better if the module is just flexible. This makes it respond to file extensions.
- Fixes a previous assumption about a comma-separated field in a comma-separated file. I think it's better if the blocking definition is semicolon-separated where multiple values are supplied, so that things don't break when that is stored in a CSV file like [the example](https://github.com/nf-core/test-datasets/blob/modules/data/genomics/mus_musculus/rnaseq_expression/SRP254919.contrasts.csv).
> Let DESeq2 module be flexible with CSV/ TSV, and use semicolons in blocking field

- modules/nf-core/deseq2/differential/templates/deseq_de.R
- tests/modules/nf-core/deseq2/differential/main.nf
- tests/modules/nf-core/deseq2/differential/nextflow.config
- tests/modules/nf-core/deseq2/differential/test.yml
As highlighted by @WackerO, we need to be able to pass some important options to e.g. `vst()` when running the DESeq2 module. I've added the passing of options, and a test to make sure VST works.
> Pass variance stabilisation options for DESeq2

- modules/nf-core/chromap/chromap/main.nf
- modules/nf-core/chromap/chromap/meta.yml
- modules/nf-core/chromap/index/main.nf
- modules/nf-core/chromap/index/meta.yml
- tests/modules/nf-core/chromap/chromap/main.nf
- tests/modules/nf-core/chromap/index/main.nf
As requested on #2414 add meta to reference channels of chromap modules.
> Add meta to fasta reference and index of chromap modules

- modules/nf-core/msisensor2/msi/main.nf
Some testing revealed msisensor2 doesn't scale well with resources. In fact it's pretty much the same with 1 or 2 cores and 1Gb of RAM! So I've reduced the memory usage down to `process_low`.
- x ] Follow the parameters requirements.
> msisensor2/msi reduced resource usage because it doesn't scale

- subworkflows/nf-core/fastq_align_chromap/meta.yml
<!--
Many thanks for contributing to nf-core/modules!
See this comment: https://github.com/nf-core/modules/pull/2426/files#r1012600269
By the moment I revert it to be consistent with the rest of subworkflows.
> Fix yml structure info in fastq_align_chromap subworkflow

- modules/nf-core/bismark/summary/main.nf
- modules/nf-core/bismark/summary/meta.yml
- tests/modules/nf-core/bismark/summary/main.nf
This bismark/summary module pulled in all BAM files to run. This staged them in the work directory and `bismark2summary` used these to guess the report filenames. That's all 😅  Quite an expensive strategy when staging files on the cloud.
Changed to instead accept a list of BAM _filenames_ instead, without staging the files.
Closes #XXX
> Bismark summary - BAM filenames, not files

- modules/nf-core/shinyngs/staticdifferential/main.nf
- modules/nf-core/shinyngs/staticdifferential/meta.yml
- modules/nf-core/shinyngs/staticexploratory/main.nf
- modules/nf-core/shinyngs/staticexploratory/meta.yml
This PR removes consideration of `_files` folders from the htmlwidgets-exported plots I generating from the shinyngs module. The exports are 'self contained', and while I thought the bug was in that self-containment such that folders would still be required, in fact the bug is just in deletion of the _files directories. 
TL;DR: I included some folders in the plot output which are only there due to an [upstream bug](https://github.com/ramnathv/htmlwidgets/issues/296), and can reliably be ignored. 
> _files directories not needed for plots in shinyngs modules

- modules/nf-core/ataqv/ataqv/main.nf
- modules/nf-core/ataqv/ataqv/meta.yml
- tests/modules/nf-core/ataqv/ataqv/main.nf
- tests/modules/nf-core/ataqv/mkarv/main.nf
This PR is required to fix an issue in nf-core/atacseq, detailed in https://github.com/nf-core/modules/issues/2502.
Essentially, we cannot rely on ext.args to supply the `--mitochondrial-reference-name` argument, as the parameter is often set *after* the ext.args are resolved.
This commit introduces the `mito_name` as a process input.
> Add mito_name to ATAQV_ATAQV inputs

- .github/workflows/pytest-workflow.yml
Also switch to apt-get
Fixes
```
Run sudo apt install bat > /dev/null
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/universe/r/rust-bat/bat_0.12.1-1ubuntu0.1_amd64.deb  404  Not Found [IP: 52.252.75.106 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Error: Process completed with exit code 100.
```
> ci: Add apt-get update

- subworkflows/nf-core/fastq_contam_seqtk_kraken/main.nf
When running the `KRAKEN_SCREEN` sub-workflow the output channels from it, `KRAKEN_SCREEN.out.reports` are all empty. Related to issue #2516 
I checked and the fix is having:
```groovy
ch_versions = ch_versions.mix(KRAKEN2.out.versions.first())
ch_reports  = ch_reports.mix(KRAKEN2.out.report)
```
Instead of:
https://github.com/nf-core/modules/blob/master/subworkflows/nf-core/fastq_contam_seqtk_kraken/main.nf#L40-L41
> Fix KRAKEN_SCREEN output channel definition

- modules/nf-core/nanoplot/main.nf
Nanoplot has a `--no-static` option which disables generation of the static png plots. In order to be able to use this with the nextflow module, `png` output needs to be marked as optional. 
Closes #XXX 
> Nanoplot: make png output optional to enable using --no-static

- modules/nf-core/deseq2/differential/templates/deseq_de.R
- tests/modules/nf-core/deseq2/differential/test.yml
When I wrote the DESeq2 module I applied some limitation to the decimal places used in certain tabular outputs, for consistency to make use of the CI easier. But that created some issues in that the outputs were strings, with NAs (for example) padded out. It's then a pain to parse these files and convert the strings back to numeric. 
This PR does that conversion back to numeric before the tables are written, including preservation of NA values.
> Enforce numeric on formatted tabular outputs from DESeq2

- .nf-core.yml
In anticipation of new tooling code add the `org_path` value to the `.nf-core.yml`.
This value defines the path under which modules/subworkflows are stored i.e. `modules/<org_path>` which here is `nf-core`
Closes #XXX 
> Add org path to .nf-core.yml

- modules/nf-core/malt/build/main.nf
- modules/nf-core/malt/build/meta.yml
- modules/nf-core/malt/run/main.nf
- modules/nf-core/malt/run/meta.yml
- tests/modules/nf-core/malt/build_test/main.nf
- tests/modules/nf-core/malt/build_test/nextflow.config
- tests/modules/nf-core/malt/build_test/test.yml
- tests/modules/nf-core/malt/run/main.nf
- tests/modules/nf-core/malt/run/nextflow.config
- tests/modules/nf-core/malt/run/test.yml
Joining these in one because they are required for each other.
This is reverting the version 'revert' I did a while ago, as the latest version fixes the bug in 0.53.
I've also removed a few `val` channels which are for mandatory parameters, but are non-files, as per the most recent guidelines
Closes #XXX 
> Bump MALT/RUN and MALT/BUILD to 0.61

- modules/nf-core/krakenuniq/preloadedkrakenuniq/main.nf
- modules/nf-core/krakenuniq/preloadedkrakenuniq/meta.yml
- tests/modules/nf-core/krakenuniq/preloadedkrakenuniq/main.nf
- tests/modules/nf-core/krakenuniq/preloadedkrakenuniq/test.yml
Improve prefix generation and split flows for single- and paired-end reads.
> fix: krakenuniq correctly handle read pairs

- modules/nf-core/rgi/main/main.nf
- modules/nf-core/rgi/main/meta.yml
- tests/modules/nf-core/rgi/main/test.yml
As `publishDir`  patterns can't exclude (or rather globs don't :().
Moves all files with `temp` in the name to a dedicated directory
Closes #XXX 
> Update: RGI_MAIN to ensure you can separate temp files from real output 

- subworkflows/nf-core/fastq_align_bwaaln/main.nf
- subworkflows/nf-core/fastq_align_bwaaln/meta.yml
- tests/config/pytest_modules.yml
- tests/subworkflows/nf-core/fastq_align_bwaaln/main.nf
- tests/subworkflows/nf-core/fastq_align_bwaaln/nextflow.config
- tests/subworkflows/nf-core/fastq_align_bwaaln/test.yml
Implements the bwa aln -> samse/sampe -> index workflow.
I've not modified the excisitng `fastq_align_bwa` to maybe the more 'correct' `fastq_align_bwamem`, but maybe this is something to consider @JoseEspinosa? I'm wondering if that should also be in guidelines (full module name, if subcommands exist?)
Note that _unlike_ other alignment subworkflows, I've explicitly _not_ included the stats here. I'm wary of doing this at this step given in some cases people (i.e., me) may actually want to map per run/lane/library separately, then merge the resulting BAM files after this (of a given sample/library), upon which you generte stats (so to get stats per library or sample rather than of each lane/run separately). This helps chunk up alignment steps of pipelines into smaller/'cluster-friendly' …
> New subworkflow: fastq_align_bwaaln

- tests/config/test_data.config
When making a new module, I realised that the layout of test_data.config was corrupted:
- it had some tabulations
- some hashes were wrongly indented
- some `=` were not aligned
This PR fixes all three issues.
Closes #XXX 
> Fixed the layout of the dictionary

- modules/nf-core/bwamem2/index/meta.yml
- modules/nf-core/minimap2/index/meta.yml
- modules/nf-core/miniprot/align/main.nf
- modules/nf-core/miniprot/align/meta.yml
- modules/nf-core/miniprot/index/main.nf
- modules/nf-core/miniprot/index/meta.yml
- tests/config/pytest_modules.yml
- tests/modules/nf-core/miniprot/align/main.nf
- tests/modules/nf-core/miniprot/align/nextflow.config
- tests/modules/nf-core/miniprot/align/test.yml
- tests/modules/nf-core/miniprot/index/main.nf
- tests/modules/nf-core/miniprot/index/nextflow.config
- tests/modules/nf-core/miniprot/index/test.yml
Miniprot is the latest aligner, which can align protein sequences against genomic sequences: https://github.com/lh3/miniprot
This PR adds support for the `index` and `align` modes. The modules are very close to the minimap2 ones (because the CLI is almost identical) and borrow the same interface, layout, nomenclature, etc.
I also found that one of the minimap2 output channel was wrong in meta.yaml
Closes #XXX 
- [/] If necessary, include test data in your PR.
> Miniprot index and align

- modules/nf-core/picard/collectwgsmetrics/main.nf
- modules/nf-core/picard/collectwgsmetrics/meta.yml
- subworkflows/nf-core/bam_qc_picard/main.nf
- subworkflows/nf-core/bam_qc_picard/meta.yml
- tests/modules/nf-core/picard/collectwgsmetrics/main.nf
Add fasta index to picard/collectWGSMetrics for cram compatibility
Closes #XXX 
> add fasta index to collectWGSmetrics

- tests/config/test_data.config
This adds RNA paired-end test data from chromosome 6 that can e.g. be used by HLA genotyping modules.
Closes #XXX 
> Add rna paired-end chr6 test data

- modules/nf-core/shinyngs/staticdifferential/main.nf
- modules/nf-core/shinyngs/staticexploratory/main.nf
- tests/modules/nf-core/shinyngs/staticdifferential/main.nf
- tests/modules/nf-core/shinyngs/staticdifferential/nextflow.config
- tests/modules/nf-core/shinyngs/staticdifferential/test.yml
- tests/modules/nf-core/shinyngs/staticexploratory/main.nf
- tests/modules/nf-core/shinyngs/staticexploratory/nextflow.config
- tests/modules/nf-core/shinyngs/staticexploratory/test.yml
This PR is basically pulling in https://github.com/pinin4fjords/shinyngs/pull/26, making HTML outputs optional (and by default off) for the shinyngs plotting scripts. 
I also added some missing 'contains' statements in a test.yml.
> Make html output optional for shinyngs static plots

- tests/modules/nf-core/antismash/antismashlitedownloaddatabases/main.nf
pin the versions to allow retro-active testing
as next version 6.1.1 needs updated TARs with different scripts
Closes #XXX 
> Update antismash-lite tests: pin the versions to allow retro-active testing

- modules/nf-core/cnvkit/batch/main.nf
this module did not create a PON even when specified - bug fixed.
Closes #2705
> fix: correct pon if statement, rm collect, set tumor_out to empty string

- modules/nf-core/trimgalore/main.nf
- modules/nf-core/trimgalore/meta.yml
- subworkflows/nf-core/fastq_fastqc_umitools_trimgalore/main.nf
Partially closes https://github.com/nf-core/rnaseq/issues/922
`*report.txt` aren't produced by TrimGalore when `--hardtrim 3` or `--hardtrim 5` are set which means we can't get the read stats info. So I had to refactor the logic that filters channels if the FastQ files are empty after trimming.
> Add --hardtrim* files as output for TrimGalore

- modules/nf-core/antismash/antismashlite/main.nf
- modules/nf-core/antismash/antismashlite/meta.yml
Add directory with MIBiG hits as separate output channel
Closes #XXX 
> Antismash: add output channel

- modules/nf-core/hmmcopy/gccounter/main.nf
- modules/nf-core/hmmcopy/gccounter/meta.yml
- modules/nf-core/hmmcopy/generatemap/main.nf
- modules/nf-core/hmmcopy/generatemap/meta.yml
- modules/nf-core/hmmcopy/mapcounter/main.nf
- modules/nf-core/hmmcopy/mapcounter/meta.yml
- tests/modules/nf-core/hmmcopy/gccounter/main.nf
- tests/modules/nf-core/hmmcopy/gccounter/test.yml
- tests/modules/nf-core/hmmcopy/generatemap/main.nf
- tests/modules/nf-core/hmmcopy/generatemap/test.yml
- tests/modules/nf-core/hmmcopy/mapcounter/main.nf
- tests/modules/nf-core/hmmcopy/mapcounter/test.yml
Update existing hmmcopy tools to match existing module tooling.
Changes:
- add meta map to all channels
- add prefix variable to all output filenames
- remove extra suffixes from file extensions (use prefix in place)
> Updates to hmmcopy module tools to match existing structure

- tests/modules/nf-core/seqtk/seq/test.yml
Under conda, the `.gz` files differ, but their uncompressed form is OK, so switching to `contains`
Closes #1416
> Use "contains" rather than the MD5 checksum (seqtk/seq)

- modules/nf-core/shinyngs/staticdifferential/main.nf
- modules/nf-core/shinyngs/staticexploratory/main.nf
- modules/nf-core/shinyngs/validatefomcomponents/main.nf
This PR incorporates upstream fixes for https://github.com/nf-core/differentialabundance/issues/56. 
There appears to be something going on with the singularity CI. The change should have got to the galaxy servers by now, but hasn't. Docker is fine.
I'll leave this overnight and see what happens then.
> Bump shinyngs to address palette issues

- modules/nf-core/gatk4/determinegermlinecontigploidy/main.nf
- modules/nf-core/graphtyper/genotype/main.nf
- modules/nf-core/platypus/main.nf
- modules/nf-core/plink/recode/main.nf
- modules/nf-core/smncopynumbercaller/main.nf
- modules/nf-core/trinity/main.nf
- tests/modules/nf-core/graphtyper/genotype/main.nf
- tests/modules/nf-core/platypus/test.yml
These modules were probably in progress when the overall of the conda syntax happened.
I also fixed the MD5s of the `platypus` tests, that somehow didn't match the current output.
Closes #XXX 
> Fixed the conda syntax because params.enable_conda is deprecated

- modules/nf-core/ataqv/mkarv/main.nf
Using the groovy join operator to explicitly print all json filenames can become extremely verbose when hundreds of json files are passed to the ATAQV_MKARV process. By staging all inputs into a known directory, we can use shell globs rather than writing all filenames.
> Stage inputs in directory for shorter script

- modules/nf-core/bclconvert/main.nf
- tests/modules/nf-core/bclconvert/test.yml
- tests/subworkflows/nf-core/bcl_demultiplex/test.yml
Apparently `bcl-convert` doesn't generate any InterOp reports for the NextSeq2000. This PR sets the output to optional.
Closes #XXX 
> fix bclconvert interop output

- modules/nf-core/gridss/gridss/main.nf
Soft link copy of files from the BWA index (would give an error if the index was on another file system)
> copy fix for gridss

- modules/nf-core/deseq2/differential/templates/deseq_de.R
This PR turns of R's default name checking, which can mangle some things (e.g. column names starting with numbers).
> Turn off name checking in DESeq2 script

- subworkflows/nf-core/bam_rseqc/meta.yml
Fix the indentation in `meta.yml` from `bam_rseqc` subworklfow
Closes #XXX 
> fix bam_rseqc meta indentation

- modules/nf-core/smncopynumbercaller/main.nf
The SMNcopynumbercaller stub gives an error when running stub tests, because prefix and version were not defined in the stubs section.
I had identified the problem wrongly in the previous PR, which I closed, but now I understand the real error. 
> Fix smncaller stub

- tests/config/pytest_modules.yml
Related to #2874 to make sure it doesn't break anything silently
> fix(#2874): Add untar requirement to demultiplexer tests

- modules/nf-core/smncopynumbercaller/main.nf
There is a problem in this module where using a newline character in the main.nf document `/n` causes the versions.yml file to not interpret END_VERSIONS correctly, and subsequently it includes the END_VERSIONS line into versions.yml. The changed code here uses an actual newline (by pressing enter in the code), and it now properly outputs the requested data in the correct format.
Problem:
With the new code:
> smncopynumbercaller change echo newline character

- modules/nf-core/deseq2/differential/templates/deseq_de.R
- modules/nf-core/limma/differential/templates/limma_de.R
This PR fixes issues caused by me getting carried away in https://github.com/nf-core/modules/pull/2911. We don't want to have `check.names` active on the input matrices, but it's actively helpful on the sample metadata table we use to construct models. 
This is actually breaking the full size tests on #differentialabundance, which has spaces in sample metadata columns.
> Fix variable sanitisation for differential modules

- modules/nf-core/tiara/tiara/main.nf
- modules/nf-core/tiara/tiara/meta.yml
- tests/modules/nf-core/tiara/tiara/test.yml
tiara/tiara was throwing a Groovy warning that I had put down to Gitpod playing up, due to a poorly escaped \ in the script:
`unknown recognition error type: groovyjarjarantlr4.v4.runtime.LexerNoViableAltException`
Fixed by using extended grep to avoid the backslash entirely. Also updated the output filenames so that they just take $prefix and don't have an arbitrary '.out'. in the filename.
Closes #XXX 
> Fix tiara/tiara

- modules/nf-core/cellranger/mkfastq/meta.yml
- modules/nf-core/cellranger/mkgtf/meta.yml
- modules/nf-core/cellranger/mkref/meta.yml
Fixes missing `cellranger` module metadata from #2914. Slightly harmonizes the text between `cellranger` submodules.
> update, unify cellranger module metadata

- modules/nf-core/goleft/indexsplit/main.nf
- modules/nf-core/goleft/indexsplit/meta.yml
- tests/config/pytest_modules.yml
- tests/modules/nf-core/goleft/indexsplit/main.nf
- tests/modules/nf-core/goleft/indexsplit/nextflow.config
- tests/modules/nf-core/goleft/indexsplit/test.yml
> add module goleft/indexsplit

- modules/nf-core/umitools/dedup/main.nf
- modules/nf-core/umitools/extract/main.nf
- tests/modules/nf-core/umitools/dedup/main.nf
- tests/modules/nf-core/umitools/dedup/test.yml
- tests/modules/nf-core/umitools/extract/test.yml
After almost two years without updates, [versions 1.13 and 1.14 of umi-tools were released early March 2023](https://github.com/CGATOxford/UMI-tools/releases). 
Those new versions comprise for example [a speed-up for read pair mate writing](https://github.com/CGATOxford/UMI-tools/pull/543). This improves performance for transcriptome alignments greatly (Time to run is reduced from 5 hours to 4 minutes) and is thus most anticipated for the RNA-seq pipeline.
Accordingly, I have also changed the process labels. Since `umi-tools` is not multithreaded, in particular _process medium_ seemed like a waste of CPU. 
Also, the new `--umi-separator` command to `umi-tools extract` will be beneficial. So far only available for `umi-tools dedup`, so we had to stick to underscores as separator, although …
> Bump version of umi-tools to 1.14

- modules/nf-core/blast/blastn/main.nf
- modules/nf-core/blast/makeblastdb/main.nf
- modules/nf-core/blast/tblastn/main.nf
- modules/nf-core/custom/dumpsoftwareversions/main.nf
- modules/nf-core/ivar/consensus/main.nf
- modules/nf-core/ivar/trim/main.nf
- modules/nf-core/ivar/variants/main.nf
- modules/nf-core/nextclade/datasetget/main.nf
- modules/nf-core/nextclade/run/main.nf
- modules/nf-core/pangolin/main.nf
- modules/nf-core/spades/main.nf
- modules/nf-core/unicycler/main.nf
- tests/modules/nf-core/blast/tblastn/test.yml
- tests/modules/nf-core/ivar/consensus/test.yml
- tests/modules/nf-core/ivar/trim/test.yml
- tests/modules/nf-core/ivar/variants/test.yml
- tests/modules/nf-core/nextclade/run/test.yml
- tests/modules/nf-core/pangolin/test.yml
blast: `2.12.0` -> `2.13.0`
ivar: `1.3.1` -> `1.4`
nextclade: `2.2.0` -> `2.12.0`
pangolin: `4.1.1` -> `4.2`
spades: `3.15.4` -> `3.15.5`
> Bump software versions for modules used in nf-core/viralrecon

- modules/nf-core/kraken2/kraken2/main.nf
When the `--output` option is not given to kraken2, it prints out information for every classified read. This makes both the `.command.out` and `.command.log` grow to several GBs in size (depending on input). We ignore this output by redirecting to `/dev/null`. If a user is interested in this information they presumably chose the option `save_reads_assignment` anyway.
Prompted by https://github.com/nf-core/taxprofiler/issues/268
> fix: redirect kraken2 output to /dev/null

- modules/nf-core/cnvkit/batch/main.nf
Running multi-threaded without indexed BAM files causes CNVkit to try indexing the same file at the same time. See https://github.com/nf-core/sarek/issues/920
Closes #XXX 
> Index BAM files before calling CNVkit

- modules/nf-core/sratools/prefetch/templates/retry_with_backoff.sh
- tests/modules/nf-core/sratools/prefetch/main.nf
- tests/modules/nf-core/sratools/prefetch/test.yml
Not all SRA runs are available in the "SRA Normalized" format. In cases
where only the "SRA Lite" format is available, the behavior or prefetch
changes - writing files in the current directory rather than a directory
named by the sample ID.
This update moves the ./${id}.sralite to ./${id}/${id}.sralite to match
the location when pulling a run where the "SRA Normalized" format is
available.
Closes #XXX 
> Add support for SRA Lite files in sratools/prefetch.

- tests/config/test_data.config
- tests/modules/nf-core/ilastik/multicut/main.nf
- tests/modules/nf-core/ilastik/pixelclassification/main.nf
Contributes to https://github.com/nf-core/test-datasets/issues/815 as requested in https://github.com/nf-core/test-datasets/pull/821#pullrequestreview-1360366283.
This PR renames the previous `spatialomics` test dataset directory to `imaging` for more consistency and clarity.
`tiff` and `ometiff` datasets added in  https://github.com/nf-core/test-datasets/pull/821 have also added
> Rename spatialomics to imaging in test_data.config

- tests/config/test_data.config
This PR contributes to https://github.com/nf-core/test-datasets/issues/822, in which we add and re-organise test datasets for imaging data
Existing test datasets are left in place to avoid causing issues for existing modules.
Module tests will be transitioned in separate PRs, so this PR should not break any modules.
> Add imaging test data in config

- modules/nf-core/bwa/sampe/main.nf
Closes https://github.com/nf-core/nf-co.re/issues/1053
Removes the -1 in the CPU size specification for the BWA module for samtools.
> Removed -1 in CPU size specification for samtools in BWA module

- modules/nf-core/tiddit/sv/main.nf
This module doesn't work when we pass the index and fasta from igenomes. 
Bwa index from igenomes also includes the fasta file, and this fasta file has the same name as the staged fasta file. So when the module tries to create a link for all the files in the bwaindex folder in the main work directory, it barfs because a file with a same name already exists. This PR attempts to fix that error. 
> fix tiddit sv

- modules/nf-core/windowmasker/mk_counts/main.nf
- modules/nf-core/windowmasker/ustat/main.nf
Closes ##3236
This pr addresses an issue with the version currently being pulled from windowmasker causing pipelines to crash. Currently, the version is `windowmasker : 1.0.0` rather than `1.0.0`
> Windowmasker version fix

- tests/modules/nf-core/delly/call/test.yml
I looked into this to cover the `delly/call` part of #2154 . All the tests are in fact now passing since #2909 but the MD5 checksums of the VCF and BCF outputs have been removed. Why ? As you can see here, the tests pass on Docker + Singularity + Conda
Closes #XXX 
> Added the MD5 checksums for the delly/call tests

- tests/modules/nf-core/bamcmp/main.nf
- tests/modules/nf-core/bamcmp/test.yml
Fixed the `bamcmp` module tests, as identified in #2154.
1. The module interface of `BWA_INDEX` had changed and now requires a meta map
2. The MD5 checksums were wrong
Closes #XXX 
> Fixed the `bamcmp`module tests

- tests/modules/nf-core/controlfreec/assesssignificance/test.yml
- tests/modules/nf-core/controlfreec/freec2bed/test.yml
- tests/modules/nf-core/controlfreec/freec2circos/test.yml
- tests/modules/nf-core/controlfreec/makegraph/test.yml
This comes from #2154 
I checked all `controlfreec` tests and updated the MD5 checksums. Just one issue: `controlfreec/assesssignificance` doesn't pass on Conda + GitHub, it complains of an installation issue, but it works locally (and the MD5s match).
Any idea what that could be ?
Closes #XXX 
> Updated the MD5 checksums of all controlfreec tests

- modules/nf-core/malt/build/meta.yml
- modules/nf-core/malt/run/meta.yml
- modules/nf-core/megan/daa2info/meta.yml
- modules/nf-core/megan/rma2info/meta.yml
- tests/modules/nf-core/amps/main.nf
- tests/modules/nf-core/amps/nextflow.config
The `amps` module test was identified as failing in #2154. This was caused by some changes in the interface of other modules (`malt/build` and `malt/extract`) that are used in the test.
This PR fixes those tests and also updates the URL of the Tübingen university, because the old one has an expired certificate that Nextflow complains about.
Closes #XXX 
> Fixed the `amps` test

- modules/nf-core/chromap/chromap/main.nf
- modules/nf-core/chromap/chromap/meta.yml
`meta2` was use both for the fasta and the index. Change to `meta3` for the index.
> Change meta2 to meta3 for the index

- .github/workflows/pytest-workflow.yml
- modules/nf-core/bcl2fastq/main.nf
- modules/nf-core/bcl2fastq/meta.yml
- modules/nf-core/bclconvert/main.nf
- modules/nf-core/bclconvert/meta.yml
- subworkflows/nf-core/bcl_demultiplex/main.nf
- tests/modules/nf-core/bcl2fastq/main.nf
- tests/modules/nf-core/bcl2fastq/nextflow.config
- tests/modules/nf-core/bcl2fastq/test.yml
- tests/modules/nf-core/bclconvert/main.nf
- tests/modules/nf-core/bclconvert/nextflow.config
- tests/modules/nf-core/bclconvert/test.yml
- tests/subworkflows/nf-core/bcl_demultiplex/main.nf
- tests/subworkflows/nf-core/bcl_demultiplex/nextflow.config
- tests/subworkflows/nf-core/bcl_demultiplex/test.yml
- include tar in bcl2fastq and bclconvert modules + remove untar from bcl_demultiplex subworkflow
Closes #XXX 
> FIX: include tar in bcl2fastq and bclconvert

- modules/nf-core/shinyngs/app/meta.yml
- modules/nf-core/shinyngs/staticdifferential/meta.yml
- modules/nf-core/shinyngs/staticexploratory/main.nf
- modules/nf-core/shinyngs/staticexploratory/meta.yml
- modules/nf-core/shinyngs/validatefomcomponents/meta.yml
In recent updates, Shinyngs will not attempt to output MAD plots for outlier detection if the replication number are too low (< 3). So the outputs need to be optional. 
> Make MAD plots optional in shinyngs

- modules/nf-core/sratools/fasterqdump/main.nf
- CHORES: update sratools/fasterqdump
Closes #XXX 
> update sratools/fasterqdump to handle 10X data

- modules/nf-core/shinyngs/app/main.nf
- modules/nf-core/shinyngs/staticdifferential/main.nf
- modules/nf-core/shinyngs/staticexploratory/main.nf
- modules/nf-core/shinyngs/validatefomcomponents/main.nf
Adds a missing space to address issues with `nf-core download` associated with these modules. 
Working to address https://github.com/nf-core/differentialabundance/issues/122
> Add space to fix singularity download error on shinyngs modules

- modules/nf-core/pilon/main.nf
- modules/nf-core/pilon/meta.yml
- tests/config/pytest_modules.yml
- tests/modules/nf-core/pilon/main.nf
- tests/modules/nf-core/pilon/nextflow.config
- tests/modules/nf-core/pilon/test.yml
> New module : Pilon

- modules/nf-core/cat/fastq/main.nf
- modules/nf-core/custom/tabulartogseacls/main.nf
- modules/nf-core/custom/tabulartogseagct/main.nf
- modules/nf-core/gunzip/main.nf
- modules/nf-core/igv/js/main.nf
- modules/nf-core/md5sum/main.nf
- modules/nf-core/shasum/main.nf
- modules/nf-core/untar/main.nf
- modules/nf-core/untarfiles/main.nf
Given the recent changes in https://github.com/nf-core/modules/pull/3380 and in nf-core/tools v.2.8 where we specify a default registry to `quay.io`, I have now created a mirror of the ubuntu base image in the nf-core quay.io account:
https://quay.io/repository/nf-core/ubuntu?tab=tags
This will make it easier to override `docker.registry` for all containers in the pipeline if we can slowly transition to copying all active containers in use on the nf-core Dockerhub account to quay.io instead.
> Use nf-core quay.io for ubuntu image

- modules/nf-core/gtdbtk/classifywf/main.nf
- modules/nf-core/gtdbtk/classifywf/meta.yml
Just noticed when looking at it on #mag.
Closes #XXX 
> Fix mismatch between conda and container versions for GTDBTK/CLASSIFY

- tests/modules/nf-core/kmcp/compute/nextflow.config
- tests/modules/nf-core/kmcp/compute/test.yml
This PR fixes a the output file in tests for kmcp/compute module.
> Fix output argument in test in kmcp/compute

- modules/nf-core/pyrodigal/main.nf
- modules/nf-core/pyrodigal/meta.yml
- tests/modules/nf-core/pyrodigal/main.nf
- tests/modules/nf-core/pyrodigal/test.yml
Update of the `Pyrodigal` module including `pigz` to unzip input and zip output files. This was done like before in the `Prodigal` module.
Closes #3395  
- [x ] Emit the `versions.yml` file.
- [x ] Follow the parameters requirements.
- [x ] Follow the input/output options guidelines.
- [x ] Add a resource `label`
- [x ] Use BioConda and BioContainers if possible to fulfil software requirements.
- [x ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd …
> zip pyrodigal output

- modules/nf-core/pyrodigal/main.nf
- modules/nf-core/pyrodigal/meta.yml
PR to fix the previous [PR](https://github.com/nf-core/modules/pull/3414): The uncompressed fasta file from pigz was not caught by pyrodigal.
And updated the meta.yml.
> Fix pyrodigal input

- modules/nf-core/bbmap/bbsplit/main.nf
- modules/nf-core/bbmap/bbsplit/meta.yml
- subworkflows/nf-core/bam_dedup_stats_samtools_umitools/main.nf
BBSplit fails intermittently in daily tests we run and retrying seems to fix the issue. Added a label by default to retry.
> Add default retry strategy to flaky bbsplit module

- tests/config/test_data.config
- tests/modules/nf-core/purecn/normaldb/main.nf
As discussed with @nvnieuwk , this PR completes https://github.com/nf-core/modules/pull/3129 addressing the absence of the new purecn/normaldb test in the config file. Additionally, it modifies the paths of the test data within the tests.
@lbeltrame
> Add purecn/normaldb test data to config and fix paths in tests

- modules/nf-core/kallistobustools/count/meta.yml
- tests/modules/nf-core/kallistobustools/count/main.nf
- tests/modules/nf-core/kallistobustools/count/test.yml
- tests/modules/nf-core/universc/main.nf
- tests/modules/nf-core/universc/test.yml
Closes https://github.com/nf-core/test-datasets/issues/917
tests for kallistobustools/count and universc were broken during a large reorganization of 10X Genomics data (https://github.com/nf-core/test-datasets/pull/878)
the original gene expression FASTQs were purged in favor of new data compatible with cellranger/multi
this PR fixes the broken tests by pointing to replacement 10X Genomics single cell gene expression FASTQs using the 3' version 3 chemistry
> fix tests for kallistobustools, universc

- modules/nf-core/bowtie2/build/main.nf
Closes #XXX 
Missing stub for the `bowtie2/build`
> fix: missing 'stub' option

- modules/nf-core/tabix/bgziptabix/main.nf
cf https://github.com/nf-core/modules/pull/3424
Closes #XXX 
> Remove quay.io

- modules/nf-core/bases2fastq/main.nf
- modules/nf-core/bcl2fastq/main.nf
- modules/nf-core/bclconvert/main.nf
- modules/nf-core/cellranger/count/main.nf
- modules/nf-core/cellranger/mkgtf/main.nf
- modules/nf-core/cellranger/mkref/main.nf
- modules/nf-core/cellranger/mkvdjref/main.nf
- modules/nf-core/cellranger/multi/main.nf
- modules/nf-core/cellranger/vdj/main.nf
- modules/nf-core/deepvariant/main.nf
- modules/nf-core/gatk4/applybqsrspark/main.nf
- modules/nf-core/gatk4/baserecalibratorspark/main.nf
- modules/nf-core/gatk4/cnnscorevariants/main.nf
- modules/nf-core/gatk4/determinegermlinecontigploidy/main.nf
- modules/nf-core/gatk4/germlinecnvcaller/main.nf
- modules/nf-core/gatk4/markduplicatesspark/main.nf
- modules/nf-core/gatk4/postprocessgermlinecnvcalls/main.nf
- modules/nf-core/universc/README.md
- modules/nf-core/universc/main.nf
- tests/modules/nf-core/universc/nextflow.config
I have pulled and pushed the containers in these modules to the nf-core `quay.io` account. Updating modules now, will re-install in the pipeline and create patch releases.
> Move containers for sarek, demultiplex and scrnaseq to quay.io

- modules/nf-core/kmcp/search/main.nf
- tests/modules/nf-core/kmcp/search/test.yml
This PR adds stub to [kmcp search module](https://github.com/nf-core/modules/tree/master/modules/nf-core/kmcp/search)
> Add stub for kmcp search module

- tests/modules/nf-core/kmcp/index/test.yml
This PR adds test for stub for [kmcp/index module](https://github.com/nf-core/modules/tree/master/modules/nf-core/kmcp/index)
> Add test for stub for kmcp index module

- modules/nf-core/ataqv/ataqv/main.nf
- modules/nf-core/ataqv/ataqv/meta.yml
- modules/nf-core/ataqv/mkarv/main.nf
- modules/nf-core/ataqv/mkarv/meta.yml
Bump `1.3.1` ataqv version in `ataqv/ataqv` and `ataqv/mkarv`.
> Update ataqv modules version

- modules/nf-core/mmseqs/databases/main.nf
Accidentally used single quotes so variable not expanded!
> Fix tag quotes in mmseqs_databases

- modules/nf-core/kmcp/profile/main.nf
- tests/modules/nf-core/kmcp/profile/test.yml
This PR adds stub for [kmcp profile module](https://github.com/nf-core/modules/tree/master/modules/nf-core/kmcp/profile).
> Add stub for kmcp profile

- modules/nf-core/gatk4/collectreadcounts/main.nf
- modules/nf-core/gatk4/collectreadcounts/meta.yml
- modules/nf-core/gatk4/determinegermlinecontigploidy/main.nf
- modules/nf-core/gatk4/determinegermlinecontigploidy/meta.yml
- modules/nf-core/gatk4/germlinecnvcaller/main.nf
- modules/nf-core/gatk4/germlinecnvcaller/meta.yml
- modules/nf-core/gatk4/postprocessgermlinecnvcalls/main.nf
- modules/nf-core/gatk4/postprocessgermlinecnvcalls/meta.yml
- tests/modules/nf-core/gatk4/collectreadcounts/main.nf
- tests/modules/nf-core/gatk4/determinegermlinecontigploidy/main.nf
- tests/modules/nf-core/gatk4/determinegermlinecontigploidy/test.yml
- tests/modules/nf-core/gatk4/germlinecnvcaller/main.nf
- tests/modules/nf-core/gatk4/germlinecnvcaller/test.yml
- tests/modules/nf-core/gatk4/postprocessgermlinecnvcalls/main.nf
- tests/modules/nf-core/gatk4/postprocessgermlinecnvcalls/nextflow.config
- tests/modules/nf-core/gatk4/postprocessgermlinecnvcalls/test.yml
This PR updates the following modules,
1. collectreadcounts
2. determinegermlinecontigploidy
3. germlinecnvcaller
4. postprocessgermlinecnvcalls
Major change here is the removal of tarred inputs and outputs for modules 2, 3, and 4. Reason being that the modules are used as a part of gatk's cnvcalling workflow, and compressing the output from one module only to uncompress it in the next step is a futile exercise.
> update modules in GATK's gcnvcaller pipeline

- modules/nf-core/pretextmap/main.nf
- tests/modules/nf-core/pretextmap/test.yml
Updated the container to samtools 1.17 and so that container and bioconda pretext versions now match.
md5sums updated in light of this.
> Updated pretext container 

- modules/nf-core/sentieon/setup.md
- tests/modules/nf-core/sentieon/license_message.py
Adding BSD 2-Clause license statement the sentieon script `tests/modules/nf-core/sentieon/license_message.py`.
Updating `modules/nf-core/sentieon/setup.md` with info on how to use the sentieon modules with a file-based sentieon license.
Closes #XXX 
> License on sentieon script

- modules/nf-core/gunzip/main.nf
Hello,
I've found out that `gunzip` creates the uncompress file under the same group ownership as the compressed file. This may cause some issues when the work directory is on a filesystem where this group doesn't have a quota. It also breaks the assumption that all the files created by Nextflow are under the primary group of the user (or the group of the holding directory if the setgid permission is used) and is painful to debug.
Here, I propose passing through the shell to get the file created to guarantee the group ownership follows the usual rules.
Closes #XXX 
> Use `gzip -cd` because `gunzip` preserves the group ownership

- modules/nf-core/ngmerge/main.nf
- modules/nf-core/ngmerge/meta.yml
- tests/config/pytest_modules.yml
- tests/modules/nf-core/ngmerge/main.nf
- tests/modules/nf-core/ngmerge/nextflow.config
- tests/modules/nf-core/ngmerge/test.yml
> Newmodule ngmerge

- modules/nf-core/pureclip/main.nf
- modules/nf-core/pureclip/meta.yml
- tests/config/pytest_modules.yml
- tests/modules/nf-core/pureclip/main.nf
- tests/modules/nf-core/pureclip/nextflow.config
- tests/modules/nf-core/pureclip/test.yml
> NEW MODULE: PURECLIP

- subworkflows/nf-core/fastq_fastqc_umitools_fastp/main.nf
- subworkflows/nf-core/fastq_trim_fastp_fastqc/main.nf
Very large fastqs can cause `num_reads` in the `fastq_fastqc_umitools_fastp` and `fastq_trim_fastp_fastqc` subworkflows to overflow and mistakenly skip samples.
I'm not sure how to test this. Probably a unit test of the `getFastpReadsAfterFiltering()` method would be best, but i'm not familiar enough with groovy to know how to do that.
Closes #XXX 
> fix integer overflow

- modules/nf-core/metaeuk/easypredict/main.nf
- tests/modules/nf-core/metaeuk/easypredict/main.nf
- tests/modules/nf-core/metaeuk/easypredict/test.yml
Fixes a bug with metaeuk_easypredict - when calling with an mmseqs2-formatted database, it turns out it also requires the file basename to be supplied, rather than just a directory, which I didn't realise 😅
Also adds a test to download the SwissProt DB (~80mb) and test the tool with this input type. As the DB is not versioned, the test just checks for the existence of the output files as the results are likely to change.
> Fix metaeuk_easypredict when using mmseqs database

- modules/nf-core/ngmerge/main.nf
- modules/nf-core/ngmerge/meta.yml
- tests/modules/nf-core/ngmerge/main.nf
- tests/modules/nf-core/ngmerge/test.yml
Closes #3630 
add -f option and emit unstitched read 1 and read 2 as output so they can be used by downstream processes if required
> 3630 add unstitched reads as emitted output of ngmerge

- modules/nf-core/hicexplorer/hicpca/main.nf
- modules/nf-core/hicexplorer/hicpca/meta.yml
- tests/config/pytest_modules.yml
- tests/modules/nf-core/hicexplorer/hicpca/main.nf
- tests/modules/nf-core/hicexplorer/hicpca/nextflow.config
- tests/modules/nf-core/hicexplorer/hicpca/test.yml
> Hicexplorer hicpca

- modules/nf-core/pyrodigal/main.nf
Added "--force" to pigz which should prevent errors reported on Slack ([link to thread](https://nfcore.slack.com/archives/C02K5GX2W93/p1688471831570479)).
I don't think we need to care about being more specific with the filename pattern when zipping the output like `pigz -nmf ${prefix}*`, since only the output files (not input fasta) should be present in the folder. And it worked like this before the symbolic link error came in ;)
> Fix bug in pyrodigal module

- modules/nf-core/hisat2/build/main.nf
- tests/modules/nf-core/hisat2/build_test/main.nf
- tests/modules/nf-core/hisat2/build_test/test.yml
Closes #3648 
I have adapted the existing module to only use these optional inputs if they are provided. Previously the `--exons` and `--ss` parameters were optional dependent on available memory. Simpler indices were constructed if the memory requirement was not satisfied. This PR makes it so that nf-core users can intentionally build these 'non-splice aware' indices if they so choose (example use case is where there is no splicing).
> Hisat2-build: index construction w/ truly optional inputs 

- modules/nf-core/tiddit/cov/main.nf
- modules/nf-core/tiddit/sv/main.nf
- tests/modules/nf-core/tiddit/sv/test.yml
Singularity-images https://depot.galaxyproject.org/singularity/tiddit:3.6.1--py38h24c8ff8_0 not expected to be available before 22/7, so the singularity-based test is going to failed before that.
Closes #XXX 
> Update tiddit to v3.6.1

- modules/nf-core/bwa/mem/main.nf
- tests/modules/nf-core/bwa/mem/main.nf
- tests/modules/nf-core/bwa/mem/test.yml
> Update stubs for bwa mem

- modules/nf-core/homer/annotatepeaks/main.nf
- modules/nf-core/homer/annotatepeaks/meta.yml
- tests/modules/nf-core/homer/annotatepeaks/nextflow.config
- tests/modules/nf-core/homer/annotatepeaks/test.yml
Closes #XXX 
- [ X] This comment contains a description of changes (with reason).
> Additional optional output to homer/annotatepeaks 

- modules/nf-core/hisat2/align/main.nf
- tests/modules/nf-core/hisat2/align/main.nf
- tests/modules/nf-core/hisat2/align/test.yml
Updated Hisat2 align to allow splice sites to actually be optional 
Changes involve the specification of the splice sites paramater being defined outside the command so that if it is empty (' ') then it will not throw an error. 
Closes #3653
> Hisat2 align splicesitesoptional

- modules/nf-core/proteus/readproteingroups/templates/proteus_readproteingroups.R
- modules/nf-core/shinyngs/app/main.nf
- modules/nf-core/shinyngs/staticdifferential/main.nf
- modules/nf-core/shinyngs/staticexploratory/main.nf
- modules/nf-core/shinyngs/validatefomcomponents/main.nf
- tests/modules/nf-core/proteus/readproteingroups/test.yml
- tests/modules/nf-core/shinyngs/app/test.yml
- tests/modules/nf-core/shinyngs/staticdifferential/test.yml
- tests/modules/nf-core/shinyngs/staticexploratory/main.nf
- tests/modules/nf-core/shinyngs/staticexploratory/nextflow.config
- tests/modules/nf-core/shinyngs/staticexploratory/test.yml
This PR updates the shinyngs containers to the latest version 1.8.1 and modifies the tests accordingly. It also removes the na.omit() call in proteus_readproteingroups as with the new shinyngs/static_exploratory, NAs do not throw an error anymore.
Closes #XXX 
> Update shinyngs, remove na.omit() from proteus

- modules/nf-core/sentieon/bwaindex/main.nf
With this update the output-prefix can be set with the `prefixtask.ext.prefix`.
Closes #XXX 
> Updating output-prefix for sentieon-bwaindex

- modules/nf-core/samtools/coverage/main.nf
I noticed while running the module that it produces an extra parenthesis in the version output. This is the cause.
Closes #XXX 
> Extra parenthesis removed and added stub

- modules/nf-core/sentieon/applyvarcal/main.nf
- modules/nf-core/sentieon/applyvarcal/meta.yml
- tests/modules/nf-core/sentieon/applyvarcal/main.nf
Adding extra meta-fields for fasta and fai in input section of sentieon/applyvarcal.
N.B. This PR is made directly from the nf-core/modules-repo as that is necessary in order for the sentieon-based CI-tests to have access to the GH-secrets.
Closes #XXX 
> Adding extra meta-fields for sentieon/applyvarcal

- modules/nf-core/famsa/align/main.nf
- modules/nf-core/famsa/align/meta.yml
- tests/config/pytest_modules.yml
- tests/modules/nf-core/famsa/align/main.nf
- tests/modules/nf-core/famsa/align/nextflow.config
- tests/modules/nf-core/famsa/align/test.yml
Add module: famsa/align 
Takes as input a fast file and optionally a tree in Newick format.
Outputs a multiple sequence alignment computed with famsa.
Closes https://github.com/nf-core/modules/issues/3696
> Add module famsa_align

- modules/nf-core/sentieon/bwamem/main.nf
- modules/nf-core/sentieon/bwamem/meta.yml
- tests/modules/nf-core/sentieon/bwamem/main.nf
Adding extra meta-fields for fasta and fai in input section of sentieon/bwamem.
Closes #XXX 
> Adding extra meta-fields for sentieon/bwamem

- modules/nf-core/snakemake/meta.yml
Snakemake inputs meta.yml was incorrect. This PR fixes it.
> fixup: Snakemake meta.yml was incorrect

- modules/nf-core/spaceranger/count/main.nf
- modules/nf-core/spaceranger/mkref/main.nf
- modules/nf-core/universc/main.nf
- modules/nf-core/unzip/main.nf
- modules/nf-core/unzip/meta.yml
- modules/nf-core/unzipfiles/main.nf
- modules/nf-core/unzipfiles/meta.yml
- subworkflows/nf-core/fasta_index_dna/main.nf
- subworkflows/nf-core/fastq_align_dna/main.nf
Issue #3683 (This is the seventh - and probably last - PR in this sad series.)
1) Moving conda-check to script-section and stub-section.
2) Replacing `exit 1` with `error()`.
------
The usual lint error for `spaceranger/count` and `spaceranger/mkref` : "Unable to connect ..." 403.
Closes #XXX 
> Move conda-checks (seventh batch)

- modules/nf-core/metabat2/metabat2/main.nf
- tests/modules/nf-core/metabat2/metabat2/test.yml
- mv operations were causing problems on certain filesystems.
- This commit removes the mv operations in favour of using the existing files directly.
- Uses Nextflow native output operators to locate output files
- Outputs of METABAT2_METABAT2 will appear in a subfolder `metabat2/` unless changed in the publishDir as part of the pipeline.
> METABAT2: reduced number of mv operations

- modules/nf-core/parabricks/fq2bam/main.nf
- modules/nf-core/parabricks/fq2bam/meta.yml
The parabricks/fq2bam module had hard copies from the previous working dir to the local working directory to remove the affect of symlinks. However, this will fail on a number of cases therefore this commit replaces them with the stageInDirective of Nextflow.
Would like to merge after #3738 is merged for tests.
> Parabricks use stageInMode to prevent unpredictable file operations while running

- modules/nf-core/mmseqs/cluster/meta.yml
- modules/nf-core/mmseqs/createdb/meta.yml
- modules/nf-core/mmseqs/search/meta.yml
- modules/nf-core/mmseqs/tsv2exprofiledb/meta.yml
As described in attached issue, this PR fixes the incorrect labelling of an output channel in mmseqs_createdb in documentation.
Closes #3739
> Mmseqs: Documentation fix  #3739

- .github/workflows/test.yml
- modules/nf-core/snakemake/main.nf
- tests/modules/nf-core/snakemake/main.nf.test
- tests/modules/nf-core/snakemake/main.nf.test.snap
I done messed up with the output channels in Snakemake.
- Correct filtering to avoid `.snakemake` output folder in main channel
- Corrects nf-test outputs (snap)
- pytest-workflow unaffected
> Fix Snakemake output channel

- modules/nf-core/cellranger/count/templates/cellranger_count.py
The filename check for consistency between R1 and R2 filename was a bit naive and led to false positives (e.g. on SRR12345 in the filename. It now uses a regex that is a bit cleverer. 
Closes #XXX 
> Fix filename check for cellranger count

- modules/nf-core/umitools/group/main.nf
- modules/nf-core/umitools/group/meta.yml
- tests/config/pytest_modules.yml
- tests/modules/nf-core/umitools/group/main.nf
- tests/modules/nf-core/umitools/group/nextflow.config
- tests/modules/nf-core/umitools/group/test.yml
Closes #3764
Adds a new module to group reads from a BAM file using `umi_tools group` . 
> New module: umitools/group

- modules/nf-core/glimpse2/concordance/main.nf
- modules/nf-core/glimpse2/concordance/meta.yml
- tests/modules/nf-core/glimpse2/concordance/main.nf
- tests/modules/nf-core/glimpse2/concordance/nextflow.config
- tests/modules/nf-core/glimpse2/concordance/test.yml
I added the optional output that is produced when using the flag --out_r2_per_site and modified the code for producing input.txt so that it can also be run in multiple chromosomes by providing a list of regions as input in val(region). This still allows for a single input.
Running on multiple regions is important to calculate aggregated MAF bin metrics for the whole genome for example.
I also removed the indentation from the version HEREDOCS since it is causing problems with dumpsoftwareversions.
> Added support for multiple regions and added per-site r^2 optional output

- modules/nf-core/sentieon/dnascope/main.nf
- modules/nf-core/sentieon/dnascope/meta.yml
- tests/modules/nf-core/sentieon/dnascope/main.nf
- tests/modules/nf-core/sentieon/dnascope/test.yml
Updating Sentieon Dnascope module to facilitate both vcf and gvcf output from one invocation.
Added option for `pcr_indel_model`.
Added some extra pytests.
Closes #XXX 
> Update sentieon dnascope

- modules/nf-core/bcftools/sort/main.nf
- tests/modules/nf-core/bcftools/sort/test.yml
Without `--temp-dir .` for bcftools-sort, I was getting
`mkdtemp(/home/ubuntu/nf_tmp/bcftools.PNwtq8) failed: Read-only file system`
from `BCFTOOLS_SORT` when running Sarek with singularity, that is,
```
nextflow run main.nf -profile test_cache,targeted,singularity --tools freebayes --outdir results
```
The hardcoding the tempdir to `.` in the BCFTOOLS_SORT-module corresponds to what we are doing in the GATK-modules.
Closes #XXX 
> Setting temp-dir for BCFTOOLS_SORT

- subworkflows/nf-core/fastq_trim_fastp_fastqc/main.nf
Closes #XXX 
Channels outputting `fastqc_raw*`  files are empty due to incorrect variable name assignment. This caused fastqc_raw channels emitted by the subworkflow to always be empty.
> fix empty channel assignment in FASTQ_TRIM_FASTP_FASTQC subworkflow

- subworkflows/nf-core/initialise/main.nf
> Flip order of operations in intialise so --help doesn't error if --input isn't provided

- subworkflows/nf-core/initialise/main.nf
- subworkflows/nf-core/initialise/meta.yml
- tests/subworkflows/nf-core/initialise/main.nf
- tests/subworkflows/nf-core/initialise/nextflow.config
- tests/subworkflows/nf-core/initialise/nextflow_schema.json
- INTIALISE suboworkflow uses take and emit for better modularity
Closes #XXX 
> INITIALISE uses take and emit

- modules/nf-core/bcl2fastq/main.nf
- modules/nf-core/bclconvert/main.nf
- tests/modules/nf-core/bcl2fastq/main.nf
- tests/modules/nf-core/bclconvert/main.nf
In a nutshell, the previous glob would miss files where the sample name ends with one of these letters `[Udeimnrt]`, see issue #3794 for more details.
This PR matches fastq files using their sample number instead, which will be 0 for Undetermined files and >1 for other files (see [bcl2fastq docs](https://support.illumina.com/content/dam/illumina-support/documents/documentation/software_documentation/bcl2fastq/bcl2fastq2-v2-20-software-guide-15051736-03.pdf), page 17).
I'm not sure about how to update the tests though... I guess I would need to update the samplesheet at https://github.com/nf-core/test-datasets/blob/modules/data/genomics/homo_sapiens/illumina/bcl/flowcell_samplesheet.csv but that would probably break a cascade of other tests I guess? Or is there a way to edit the …
> Fix output for bcl2fastq & bclconvert

- modules/nf-core/krakenuniq/build/main.nf
- modules/nf-core/krakenuniq/download/main.nf
- modules/nf-core/krakenuniq/preloadedkrakenuniq/main.nf
- modules/nf-core/krakenuniq/preloadedkrakenuniq/meta.yml
Update KrakenUniq version from v1.0.2 to v1.0.4
Closes https://github.com/nf-core/taxprofiler/issues/381
> update KrakenUniq version to the latest

- modules/nf-core/abritamr/run/main.nf
- modules/nf-core/abritamr/run/meta.yml
- tests/config/pytest_modules.yml
- tests/modules/nf-core/abritamr/run/main.nf
- tests/modules/nf-core/abritamr/run/nextflow.config
- tests/modules/nf-core/abritamr/run/test.yml
Closes https://github.com/nf-core/modules/issues/3724 
> add module for abritamr_run

- modules/nf-core/sratools/fasterqdump/main.nf
- modules/nf-core/sratools/prefetch/main.nf
- modules/nf-core/sratools/prefetch/templates/retry_with_backoff.sh
- tests/modules/nf-core/sratools/fasterqdump/test.yml
- tests/modules/nf-core/sratools/prefetch/test.yml
The SRA uses two file formats used to store the short read data: sra and sralite, and we want to support both formats.
When using `prefetch ID`, the behaviour of the resulting files differs depending on whether the format of `ID` stored at NCBI is sra or sralite. 
If the backend format is sra (using `ID=SRR6242565` as an example), the `prefetch $ID` command writes into a directory keyed by the ID:
```
SRR6242565
└── SRR6242565.sra
```
If the backend format is sralite (using `ID=SRR042042` as an example), the `prefetch $ID` command writes a single file to the current working directory:
```
SRR042042.sralite
```
Previously, we simply moved the sralite file into a new directory to match the sra format output, but this can break downstream tools. The most important is `fasterq-fetch` which …
> Different approach to handling sralite files when using prefetch.

- .gitignore
- modules/nf-core/fastqc/main.nf
- modules/nf-core/fastqc/tests/main.nf.test.snap
- [ x ] This comment contains a description of changes (with reason).
- [ x ] Use BioConda and BioContainers if possible to fulfil software requirements.
Use of deprecated Docker images can be a problem when using Docker repository proxies (some of them may not allow using deprecated docker images). Changed docker image (fastqc:0.11.9--0) was discovered to be deprecated, and has therefore been changed to the newest one (fastqc:0.12.1--hdfd78af_0), which is not deprecated.
Besides, deprecated Docker images won't be deployable in short time.
> Update deprecated fastqc image

- modules/yaml-schema.json
With this PR we make the DOI check less strict and allow the value "no DOI available" as an alternative.
> allow tools with no DOI available

- modules/nf-core/rmarkdownnotebook/main.nf
- tests/modules/nf-core/rmarkdownnotebook/test.yml
This PR suggests a change from native use of 'params' in the RMarkdown `render()` function, to rather edit the R Markdown document to substitute the params in the YAML-format header matter.
The main motivation for this is to produce a Markdown file which can be used an played with by users downstream, in addition to rendered HTML. I do not believe it's possible to simply 'render' a markdown file to another Rmarkdown file with variables resolved, though that would be a much neater solution.
> Output parameterised Rmd from RMARKDOWNNOTEBOOK

- modules/nf-core/metaphlan3/mergemetaphlantables/meta.yml
- tests/modules/nf-core/metaphlan3/mergemetaphlantables/main.nf
- tests/modules/nf-core/metaphlan3/mergemetaphlantables/nextflow.config
The test hasn't been updated when the `METAPHLAN3` module got renamed + a bit of linting.
Closes #XXX 
> Wrong module name in `metaphlan3` test

- tests/config/nf-test.config
Copying the settings from `tests/nextflow.config`
> fix ownership for nf-test

- tests/config/nextflow.config
- tests/config/nf-test.config
we added this trying to fix the AWS runners, but without success. now it seems to also break github runners so removing it again.
> fix `no locator available for file` error

- modules/nf-core/bcl2fastq/tests/main.nf.test
- modules/nf-core/bcl2fastq/tests/main.nf.test.snap
- modules/nf-core/bcl2fastq/tests/nextflow.config
- modules/nf-core/bcl2fastq/tests/tags.yml
- modules/nf-core/bclconvert/tests/main.nf.test
- modules/nf-core/bclconvert/tests/main.nf.test.snap
- modules/nf-core/bclconvert/tests/nextflow.config
- modules/nf-core/bclconvert/tests/tags.yml
- tests/config/pytest_modules.yml
This PR converts the bclconvert and bcl2fastq tests to nf-test.
NB: the `TODO` statements are imported from the old pytest tests
> Convert bclconvert and bcl2fastq modules to nf-test

- modules/nf-core/cellrangeratac/count/main.nf
- modules/nf-core/cellrangeratac/mkfastq/main.nf
- modules/nf-core/cellrangeratac/mkref/main.nf
- modules/nf-core/ganon/buildcustom/main.nf
- modules/nf-core/icountmini/segment/main.nf
- modules/nf-core/kmcp/index/main.nf
- modules/nf-core/kmcp/merge/main.nf
- modules/nf-core/mitohifi/mitohifi/main.nf
- modules/nf-core/purecn/coverage/main.nf
- modules/nf-core/purecn/normaldb/main.nf
1. @mahesh-panchal found an instance of `exit 1` in `mitohifi/mitohifi` after #4193 got merged. I found a few other instances across modules and decided to open a separate pull-request. I believe the rationale for using "error" instead of "exit 1" is expressed in #3683.
2. One of those modules was still using `quay.io/` as a container prefix, so I added another commit that removes the prefix from the few modules that still had it (see #3380).
Closes #XXX 
> Use "error" rather than "exit 1", and removed `quay.io/`

- modules/nf-core/mitohifi/mitohifi/environment.yml
- modules/nf-core/mitohifi/mitohifi/main.nf
- modules/nf-core/mitohifi/mitohifi/meta.yml
- tests/modules/nf-core/mitohifi/mitohifi/main.nf
- tests/modules/nf-core/mitohifi/mitohifi/nextflow.config
Changes to input according to 
https://github.com/nf-core/modules/pull/4193
https://github.com/nf-core/modules/pull/4248
by @muffato and @mahesh-panchal 
Closes #XXX 
> Mitohifi channel input

- tests/config/test_data.config
Adding the chr21 version of the NGSCheckMate bed file to the config so it can be used.
> Add ngscheckmate bed file to test_data config

- modules/nf-core/kraken2/kraken2/tests/main.nf.test
- modules/nf-core/kraken2/kraken2/tests/main.nf.test.snap
- modules/nf-core/kraken2/kraken2/tests/tags.yml
- tests/config/pytest_modules.yml
This PR converts the Kraken2 tests to nf-test.
> Convert Kraken2 tests to nf-test

- .github/workflows/test.yml
Opinions on the wording here? I don't love it currently, but I feel if we don't ask no one ever will.
Where's the docs? Do we have an issue to update the modules create?([Made one](https://github.com/nf-core/tools/issues/2484))
Closes #4055
> Add call to action comment on pytest-workflow runs

- modules/nf-core/nonpareil/curve/main.nf
- modules/nf-core/nonpareil/nonpareil/main.nf
- modules/nf-core/nonpareil/set/main.nf
I'm very confused why nf-core tools picked up two different types, and older ones at that... but now in sync to prevent multiple containers being downloaded in one pipeline run
Closes #XXX 
> Update: Nonpareil modules - latest biocontainer build for all modules

- .github/workflows/test.yml
Reverts nf-core/modules#4421
Because it makes paths-filer fail https://github.com/nf-core/modules/actions/runs/7006198435/job/19057567113?pr=4423
> Revert "run migration notice on pull_request_target"

- tests/modules/nf-core/bowtie2/build
- tests/modules/nf-core/hisat2/build
Removes some left over symlinks to folders that no longer exist, that were [breaking pytest](https://github.com/nf-core/modules/actions/runs/7095156771/job/19316099849).
> Remove leftover symlinks to build

- modules/nf-core/gffread/main.nf
- modules/nf-core/gffread/meta.yml
- modules/nf-core/gffread/tests/main.nf.test
- modules/nf-core/gffread/tests/main.nf.test.snap
- modules/nf-core/gffread/tests/nextflow.config
> Emit gffread_gff output channel when '-T' argument is absent

- modules/nf-core/cat/cat/main.nf
- modules/nf-core/cat/cat/tests/main.nf.test
> Now throwing an error if CAT_CAT prefix is not correctly configured

- modules/nf-core/gprofiler2/gost/main.nf
- modules/nf-core/gprofiler2/gost/templates/gprofiler2_gost.R
- tests/modules/nf-core/gprofiler2/gost/main.nf
- tests/modules/nf-core/gprofiler2/gost/test.yml
A little bug caused the empty output to be created only if no DE genes were input, not if the enrichment analysis itself failed, this is now fixed. Also changed the contrast params into a single prefix param
Closes #XXX 
> [Fix gprofiler] Empty output table is now always added

- modules/nf-core/cobs/compactconstruct/environment.yml
- modules/nf-core/cobs/compactconstruct/main.nf
- modules/nf-core/cobs/compactconstruct/meta.yml
- modules/nf-core/cobs/compactconstruct/tests/main.nf.test
- modules/nf-core/cobs/compactconstruct/tests/main.nf.test.snap
- modules/nf-core/cobs/compactconstruct/tests/tags.yml
Add cobs/compactconstruct module. This subtool is very similar to one previously merged (cobs/classicconstruct: https://github.com/nf-core/modules/pull/4586), but it builds a compact bloom filter instead of a classic one, which is the main innovation of this work. For cobs, see https://github.com/iqbal-lab-org/cobs and https://link.springer.com/chapter/10.1007/978-3-030-32686-9_21
Closes #XXX 
> Add cobs/compactconstruct module

- modules/nf-core/rseqc/bamstat/environment.yml
- modules/nf-core/rseqc/bamstat/main.nf
- modules/nf-core/rseqc/bamstat/tests/main.nf.test.snap
- modules/nf-core/rseqc/inferexperiment/environment.yml
- modules/nf-core/rseqc/inferexperiment/main.nf
- modules/nf-core/rseqc/inferexperiment/tests/main.nf.test.snap
- modules/nf-core/rseqc/innerdistance/environment.yml
- modules/nf-core/rseqc/innerdistance/main.nf
- modules/nf-core/rseqc/innerdistance/tests/main.nf.test.snap
- modules/nf-core/rseqc/junctionannotation/environment.yml
- modules/nf-core/rseqc/junctionannotation/main.nf
- modules/nf-core/rseqc/junctionannotation/tests/main.nf.test.snap
- modules/nf-core/rseqc/junctionsaturation/environment.yml
- modules/nf-core/rseqc/junctionsaturation/main.nf
- modules/nf-core/rseqc/junctionsaturation/tests/main.nf.test.snap
- modules/nf-core/rseqc/readdistribution/environment.yml
- modules/nf-core/rseqc/readdistribution/main.nf
- modules/nf-core/rseqc/readdistribution/tests/main.nf.test.snap
- modules/nf-core/rseqc/readduplication/environment.yml
- modules/nf-core/rseqc/readduplication/main.nf
- modules/nf-core/rseqc/readduplication/tests/main.nf.test.snap
- modules/nf-core/rseqc/tin/environment.yml
- modules/nf-core/rseqc/tin/main.nf
- modules/nf-core/rseqc/tin/tests/main.nf.test.snap
- subworkflows/nf-core/bam_rseqc/tests/main.nf.test.snap
In this PR I'm bumping all the RSeQC modules. This is mostly straightforward, the snapshot updates are pretty much just versions.
The unusual thing is: 
```
grep -v 'E::idx_find_and_load'
```
This is necessitated by [this issue](https://github.com/pysam-developers/pysam/issues/939), whereby pysam prints a particular warning to logs. It only does so with Conda, so I've just grep'd out the warning so that the Docker and Conda versions behave the same. 
See https://github.com/nf-core/rnaseq/issues/1140 for motivation.
Closes #XXX 
> Bump rseqc

- modules/nf-core/gprofiler2/gost/templates/gprofiler2_gost.R
Changed priority of token, organism, GMT to that order; the other two params can now override GMT
Closes #XXX 
> [Update gprofiler2] Changed priority of token, organism, GMT

- modules/nf-core/star/genomegenerate/environment.yml
- modules/nf-core/star/genomegenerate/main.nf
- modules/nf-core/star/genomegenerate/tests/main.nf.test
- modules/nf-core/star/genomegenerate/tests/main.nf.test.snap
> Made gtf input optional for star/genomegenerate

- .gitpod.yml
Removes installation of `icdiff` in favour of using `pdiff` installed in the nf-core Gitpod image (https://github.com/nf-core/tools/pull/2642). 
Closes #XXX 
> Remove icdiff in favour of pdiff in gitpod image

- modules/nf-core/samtools/fasta/main.nf
- tests/modules/nf-core/samtools/fasta/test.yml
The standard output of `samtools fasta` is _uncompressed_ Fasta. Need to add `gzip` to compress it
Closes #XXX 
> bugfix: the file was not compressed

- subworkflows/nf-core/fastq_fastqc_umitools_fastp/main.nf
- subworkflows/nf-core/fastq_fastqc_umitools_fastp/meta.yml
- subworkflows/nf-core/fastq_fastqc_umitools_fastp/tests/main.nf.test
- subworkflows/nf-core/fastq_fastqc_umitools_fastp/tests/main.nf.test.snap
This improves the FASTQ_FASTQC_UMITOOLS_FASTP subworkflow by adding in the output of detected adapter sequence(s) per sample. Needed in https://github.com/nf-core/smrnaseq/pull/303 to enable mirtrace to get the adapter sequence. I ditched the previously used subworkflow in favor of this one (thank you for making this already cover 95%!)
Closes #XXX 
> Improve FASTQC/FASTP/UMI subworkflow

- modules/nf-core/custom/sratoolsncbisettings/tests/main.nf.test
- modules/nf-core/sratools/fasterqdump/tests/main.nf.test
- modules/nf-core/sratools/prefetch/tests/main.nf.test
- modules/nf-core/untar/tests/main.nf.test
- tests/config/nf-test.config
- tests/modules/nf-core/bases2fastq/test.yml
Changes:
- Base path for test data is now replaced with a more logical form based on discussions on Slack
- from modules_test_data_base to testdata_base_path
- Should be more explicit and reduce confusion with 'database'
> Replace base path for test data with new form

- modules/nf-core/blast/blastn/main.nf
- modules/nf-core/blast/blastn/tests/main.nf.test
- modules/nf-core/blast/tblastn/main.nf
- modules/nf-core/blast/tblastn/tests/main.nf.test
Very large blast databases, like NT, are split in chunks, and only the individual chunks have `.nin` files.
```
$ wget https://ftp.ncbi.nlm.nih.gov/blast/db/nt.000.tar.gz
$ tar tvzf nt.000.tar.gz
-rw-r--r-- blastadm/blast  962 2024-01-06 03:06 nt.nal
-rw-r--r-- blastadm/blast 5712982016 2024-01-05 06:59 nt.ndb
-rw-r--r-- blastadm/blast 2283727932 2024-01-05 06:54 nt.nos
-rw-r--r-- blastadm/blast 1230513580 2024-01-05 07:00 nt.not
-rw-r--r-- blastadm/blast  189022208 2024-01-05 07:01 nt.ntf
-rw-r--r-- blastadm/blast  421142456 2024-01-05 07:00 nt.nto
-rw-rw-r-- blastadm/blast  164539268 2024-01-08 14:05 taxdb.btd
-rw-rw-r-- blastadm/blast   17292992 2024-01-08 14:05 taxdb.bti
-rw-rw-r-- blastadm/blast   78737408 2024-01-08 14:05 taxonomy4blast.sqlite3
-rw-r--r-- blastadm/blast   27374232 …
```
> Support large databases like NT

- modules/nf-core/cat/fastq/tests/main.nf.test.snap
In nf-test [v0.8.2](https://github.com/askimed/nf-test/releases/tag/v0.8.2), the way md5s are generated for `.gz` files has changed, such that it is now the equivalent of running `gunzip -c file.gz | md5sum` (as opposed to, `md5sum file.gz`). The snapshot in the nf-core modules `master` branch contains the md5s generated for the compressed merged FASTQ, as opposed to the uncompressed. This PR updates the test snapshot using nf-test v0.8.3 and the command `nf-test test --tag cat/fastq --update-snapshot`.
Closes #XXX
> cat/fastq: update snapshot using nf-test v0.8.3

- modules/nf-core/gtdbtk/classifywf/main.nf
Simple fix by adding double quotes to find command pattern in `gtdbtk/classifywf/main.nf`. 
Closes #4692
> Fix for #4692 added double quotes for find command in gtdbtk/classifywf

- modules/nf-core/hifiasm/main.nf
- modules/nf-core/hifiasm/meta.yml
This change outputs the stderr of hifiasm to a .log file, and adds it to the named emitted files. Log file is compatible with MultiQC, and this module can now be used with it.
> adding log to hifiasm outputs

- modules/nf-core/umicollapse/main.nf
The Java `-Xss` parameter was automatically derived from the amount of available / supplied memory to the task. However, this resulted in e.g. `-Xss6553M` which is larger than the allowed > 1GB limit that most Java systems allowed when running this in production, thus creating failures. 
This fixes this to the allowed maximum of Xss999M, which should be fine given that most people will run umicollapse with > 4GB of memory which will result in a default of `-Xmx3800M` that is still higher than 999M for Xss as it should be.
> Fix stack size for collapse tool

- modules/nf-core/custom/sratoolsncbisettings/main.nf
- modules/nf-core/custom/sratoolsncbisettings/tests/main.nf.test
- subworkflows/nf-core/fastq_download_prefetch_fasterqdump_sratools/main.nf
This is to prevent the `FASTQ_DOWNLOAD_PREFETCH_FASTERQDUMP_SRATOOLS:CUSTOM_SRATOOLSNCBISETTINGS` process from running unnecessarily when no sra ids are provided to the workflow. If the sra ids channel is empty that process will no longer be run.
> Update custom/sratoolsncbisettings to only run when sra ids are provided

- modules/nf-core/multiqc/tests/main.nf.test
- modules/nf-core/multiqc/tests/main.nf.test.snap
Replaces config based path with relative path in test data for MultiQC module.
> Use relative test data for multiqc module

- modules/nf-core/minimap2/align/main.nf
This pull-request removes an unnecessary use of `samtools view`. `samtools sort` is now able to do the conversion to BAM on its own.
At the same time, I added the ability to give it extra options through `ext.args2.
Closes #XXX 
> Use `samtools sort` to convert to BAM

- modules/nf-core/custom/tx2gene/environment.yml
- modules/nf-core/custom/tx2gene/main.nf
- modules/nf-core/custom/tx2gene/meta.yml
- modules/nf-core/custom/tx2gene/templates/tx2gene.py
- modules/nf-core/custom/tx2gene/tests/main.nf.test
- modules/nf-core/custom/tx2gene/tests/main.nf.test.snap
- modules/nf-core/custom/tx2gene/tests/tags.yml
- tests/config/test_data.config
https://github.com/nf-core/test-datasets/pull/1083 should be merged first, and appropriate adjustments made here.
> Add tx2gene module (formerly local to rnaseq)

- modules/nf-core/rsem/preparereference/tests/main.nf.test
Updates rsem/preparereference to use a relative path instead of config map.
> CHORES: rsem/preprarereference test path update

- modules/nf-core/sortmerna/main.nf
- modules/nf-core/sortmerna/tests/main.nf.test
- modules/nf-core/sortmerna/tests/main.nf.test.snap
- subworkflows/nf-core/preprocess_rnaseq/tests/main.nf.test
- subworkflows/nf-core/preprocess_rnaseq/tests/main.nf.test.snap
- Removes requirement for `meta.single_end` from meta map. Infers the information from the FASTQs directly
- Replace config map with relative paths in sortmerna tests.
> CHORES: Update sortmerna modules to use path rather than map

- subworkflows/nf-core/utils_nfcore_pipeline/main.nf
- subworkflows/nf-core/utils_nfcore_pipeline/meta.yml
- subworkflows/nf-core/utils_nfcore_pipeline/tests/main.function.nf.test
- subworkflows/nf-core/utils_nfcore_pipeline/tests/main.function.nf.test.snap
- subworkflows/nf-core/utils_nfcore_pipeline/tests/main.workflow.nf.test
Add `checkProfileProvided` to `utils_nfcore_pipeline` according to the changes in the pipeline template https://github.com/nf-core/tools/pull/2736
> add checkProfileProvided to utils_nfcore_pipeline

- modules/nf-core/star/align/tests/main.nf.test
- modules/nf-core/star/genomegenerate/tests/main.nf.test
- Adds a global set up so we only run STAR_INDEX once
- Changes to use relative file paths.
> Use global SETUP for making index for STAR_ALIGN tests

- modules/nf-core/rsem/calculateexpression/tests/main.nf.test
Updates rsem/calculateexpression to use a relative path instead of config map.
> CHORES: Update rsem/calculateexpression to use path rather than map

- subworkflows/nf-core/utils_nfcore_pipeline/main.nf
Change according to the nf-core pipeline template https://github.com/nf-core/tools/pull/2736
> Update utils-nfcore-pipeline: add multiqc report to completion email

- modules/nf-core/bwa/mem/environment.yml
- modules/nf-core/bwa/mem/main.nf
- modules/nf-core/bwa/mem/tests/main.nf.test.snap
- modules/nf-core/samblaster/environment.yml
- modules/nf-core/svdb/merge/environment.yml
- modules/nf-core/umicollapse/tests/main.nf.test.snap
Updating samtools to v1.19.2 in bwamem.
Also pinning version of htslib in `environment.yml` to v1.19.2 for modules `bwa/mem`, `samblaster` and `svdb/merge`.
> Updating samtools in bwamem

- modules/nf-core/umitools/prepareforrsem/main.nf
This module will currently quite happily write its output to the same path as the input. Let's prevent that.
- For modules:
> Stop UMItools prepare-for-rsem command writing to the input file

- modules/nf-core/ltrharvest/environment.yml
- modules/nf-core/ltrharvest/main.nf
- modules/nf-core/ltrharvest/meta.yml
- modules/nf-core/ltrharvest/tests/main.nf.test
- modules/nf-core/ltrharvest/tests/main.nf.test.snap
- modules/nf-core/ltrharvest/tests/tags.yml
> Added parallel version of ltrharvest

- modules/nf-core/minimap2/align/main.nf
- modules/nf-core/minimap2/align/tests/main.nf.test
- modules/nf-core/minimap2/align/tests/main.nf.test.snap
- modules/nf-core/minimap2/index/main.nf
Adds stubs for:
- `minimap2/align`
- `minimap2/index`
Updates `nf-test` tests for:
- `minimap2/align`
- For modules:
> Add stubs for minimap2 modules

- modules/nf-core/bakta/bakta/main.nf
- modules/nf-core/bakta/bakta/tests/main.nf.test.snap
- modules/nf-core/bakta/bakta/tests/nextflow.config
This fixes a crash of bakta when using the automatically downloaded database with bakta (reported [here](https://github.com/nf-core/modules/pull/4847#discussion_r1499767614)).
It does not seem to be a conda-only issue. I could reproduce it with singularity as well, that's why I execute the `amrfinder_update` line regard of the profile.
(The memory requirement in the config file was decreased only because GHA complained.)
- For modules:
> Fix bakta: amrfinder database issue

- modules/nf-core/preseq/lcextrap/main.nf
> fix annoying PRESEQ failure for methylseq

- modules/nf-core/cellranger/count/main.nf
- modules/nf-core/cellranger/count/meta.yml
- modules/nf-core/cellranger/count/tests/main.nf.test.snap
Update relates to requirement for PR in `nf-core/scrnaseq`: https://github.com/nf-core/scrnaseq/pull/301
> add paths in output directive in cellranger cout module

- modules/nf-core/kraken2/add/main.nf
- modules/nf-core/kraken2/add/tests/main.nf.test.snap
> rename taxonomy files in kraken2/add module

- modules/nf-core/ale/environment.yml
- modules/nf-core/ale/main.nf
- modules/nf-core/ale/meta.yml
- modules/nf-core/ale/tests/main.nf.test
- modules/nf-core/ale/tests/main.nf.test.snap
- modules/nf-core/ale/tests/tags.yml
> Added module ALE

- subworkflows/nf-core/fastq_align_mapad/main.nf
- subworkflows/nf-core/fastq_align_mapad/meta.yml
- subworkflows/nf-core/fastq_align_mapad/tests/main.nf.test
- subworkflows/nf-core/fastq_align_mapad/tests/main.nf.test.snap
- subworkflows/nf-core/fastq_align_mapad/tests/nextflow.config
- subworkflows/nf-core/fastq_align_mapad/tests/tags.yml
> Add subworkflow mapAD

- modules/nf-core/fastqc/main.nf
In v.0.12.0 FastQC implemented:
> Improved memory handling - default allocation is now 512MB and there
> is a --memory option which can increase the allocated memory without
> having to play with --threads
Changing `task.memory` does not change how much memory FastQC actually allocates, this PR fixes this. 
Otherwise, FastQC will not work/be very slow on longer reads.
Closes #XXX 
- For modules:
> Fix FastQC memory allocation

- subworkflows/nf-core/fastq_align_bowtie2/meta.yml
In the [fastq_align_bowtie2/meta.yml](subworkflows/nf-core/fastq_align_bowtie2/meta.yml) the sort_bam description was a duplicated from save_unaligned, I just replaced it with the description from the [bowtie2 module](https://nf-co.re/modules/bowtie2_align)
Closes #XXX 
- For modules:
> Fixed sort_bam description in meta.yml

- subworkflows/nf-core/bam_dedup_stats_samtools_umicollapse/main.nf
- subworkflows/nf-core/bam_dedup_stats_samtools_umicollapse/meta.yml
- subworkflows/nf-core/bam_dedup_stats_samtools_umicollapse/tests/main.nf.test
- subworkflows/nf-core/bam_dedup_stats_samtools_umicollapse/tests/main.nf.test.snap
- subworkflows/nf-core/bam_dedup_stats_samtools_umicollapse/tests/paired-end-umis.config
- subworkflows/nf-core/bam_dedup_stats_samtools_umicollapse/tests/tags.yml
This PR proposes the addition of the `bam_dedup_stats_samtools_umicollapse` subworkflow. It is closely modelled after the [`bam_dedup_stats_samtools_umitools`](https://nf-co.re/subworkflows/bam_dedup_stats_samtools_umitools) and essentially copies most if its code - minus one input channel, plus one additional output channel. 
It is meant as an alternative/drop-in replacement of the former to use the more performant tool `umicollapse` instead of `umi-tools`. 
Regarding the tests I am unfortunately in a Catch22 situation: nf-tests do not run on my local machine and also not on Gitpod. They seem to work on the Github runner, but I can't update the snapshot to reflect the latest changes.
Closes #5184
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite …
> New subworkflow: Bam dedup stats samtools umicollapse

- modules/nf-core/amrfinderplus/run/main.nf
This fixes the renaming of the AMRFinderPlus database folder. The `cp` command does not work as is (only as `cp -r`, but this copies the >220MB db folder within the work dir). It makes more sense to rename it instead.
Tested and works now as intended.
- For modules:
> Fix AMRFinderPlus

- modules/nf-core/repeatmodeler/builddatabase/environment.yml
- modules/nf-core/repeatmodeler/builddatabase/main.nf
- modules/nf-core/repeatmodeler/builddatabase/meta.yml
- modules/nf-core/repeatmodeler/builddatabase/tests/main.nf.test
- modules/nf-core/repeatmodeler/builddatabase/tests/main.nf.test.snap
- modules/nf-core/repeatmodeler/builddatabase/tests/tags.yml
> Added repeatmodeler/builddatabase

- modules/nf-core/sentieon/applyvarcal/environment.yml
- modules/nf-core/sentieon/applyvarcal/main.nf
- modules/nf-core/sentieon/bwaindex/environment.yml
- modules/nf-core/sentieon/bwaindex/main.nf
- modules/nf-core/sentieon/bwamem/environment.yml
- modules/nf-core/sentieon/bwamem/main.nf
- modules/nf-core/sentieon/datametrics/environment.yml
- modules/nf-core/sentieon/datametrics/main.nf
- modules/nf-core/sentieon/dedup/environment.yml
- modules/nf-core/sentieon/dedup/main.nf
- modules/nf-core/sentieon/dnamodelapply/environment.yml
- modules/nf-core/sentieon/dnamodelapply/main.nf
- modules/nf-core/sentieon/dnascope/environment.yml
- modules/nf-core/sentieon/dnascope/main.nf
- modules/nf-core/sentieon/gvcftyper/environment.yml
- modules/nf-core/sentieon/gvcftyper/main.nf
- modules/nf-core/sentieon/haplotyper/environment.yml
- modules/nf-core/sentieon/haplotyper/main.nf
- modules/nf-core/sentieon/readwriter/environment.yml
- modules/nf-core/sentieon/readwriter/main.nf
- modules/nf-core/sentieon/tnfilter/environment.yml
- modules/nf-core/sentieon/tnfilter/main.nf
- modules/nf-core/sentieon/tnhaplotyper2/environment.yml
- modules/nf-core/sentieon/tnhaplotyper2/main.nf
- modules/nf-core/sentieon/tnscope/environment.yml
- modules/nf-core/sentieon/tnscope/main.nf
- modules/nf-core/sentieon/varcal/environment.yml
- modules/nf-core/sentieon/varcal/main.nf
- modules/nf-core/sentieon/wgsmetrics/environment.yml
- modules/nf-core/sentieon/wgsmetrics/main.nf
Updating Sentieon to version 202308.02.
I don't expect that the CI-tests will run, since - as far as I know - nf-core's test-license server for sentieon is still down.
Closes #XXX 
- For modules:
> Updating sentieon to 202308.02

- modules/nf-core/ucsc/gtftogenepred/main.nf
The use of single quotes around `${meta.id}` prevents variable evaluation, outputting the literal string "${meta.id}". This is resolved by switching to double quotes, aligning the module with the other ucsc modules.
> Changed tag from single quotes to double quotes

- .github/workflows/test.yml
The CI test was activating when the master branch was updated, causing a wasted and failed nonsensical test. This PR removes that trigger.
> Do not trigger test on update of master branch

- modules/nf-core/openms/decoydatabase/environment.yml
- modules/nf-core/openms/decoydatabase/main.nf
- modules/nf-core/openms/decoydatabase/meta.yml
- modules/nf-core/openms/decoydatabase/tests/main.nf.test.snap
- modules/nf-core/openms/idfilter/meta.yml
- modules/nf-core/openms/idmerger/environment.yml
- modules/nf-core/openms/idmerger/main.nf
- modules/nf-core/openms/idmerger/meta.yml
- modules/nf-core/openms/idmerger/tests/main.nf.test.snap
- modules/nf-core/openms/idripper/meta.yml
- modules/nf-core/openms/idscoreswitcher/meta.yml
- modules/nf-core/openms/peakpickerhires/environment.yml
- modules/nf-core/openms/peakpickerhires/main.nf
- modules/nf-core/openms/peakpickerhires/meta.yml
- modules/nf-core/openms/peakpickerhires/tests/main.nf.test.snap
- modules/nf-core/openms/peptideindexer/meta.yml
> Bump OpenMS version

- modules/nf-core/gtdbtk/classifywf/environment.yml
- modules/nf-core/gtdbtk/classifywf/main.nf
gtdbtk was updated last month from 2.3.2 to 2.4.0+
- `FastANI` has been replaced by `skani` as the primary tool for computing Average Nucleotide Identity (ANI)
> Update `modules/gtdbtk_classifywf` to 2.4.0

- modules/nf-core/rgi/main/main.nf
The loop checks if files exist before moving them to temp/
Closes #376
> RGI_MAIN: Replace multiple ifs with a for loop

- modules/nf-core/bclconvert/main.nf
Replaces cp operation with native Nextflow output path handling. This should reduce the amount of storage required to run the bclconvert process.
Fixes https://github.com/nf-core/modules/issues/5644
Closes #5644 
- For modules:
> Remove cp operation from bclconvert with Nextflow output operation

- modules/nf-core/propr/propd/meta.yml
- modules/nf-core/propr/propd/templates/propd.R
- modules/nf-core/propr/propd/tests/main.nf.test.snap
> modify one_metric_df function and update meta.yml in propd

- modules/nf-core/fcs/fcsadaptor/tests/main.nf.test
- modules/nf-core/fcs/fcsadaptor/tests/main.nf.test.snap
> Added nf-test to explicitly check detection of PacBio adapters

- modules/nf-core/tximeta/tximport/main.nf
- modules/nf-core/tximeta/tximport/templates/tximport.r
- modules/nf-core/tximeta/tximport/tests/main.nf.test
- modules/nf-core/tximeta/tximport/tests/main.nf.test.snap
- subworkflows/nf-core/quantify_pseudo_alignment/main.nf
- subworkflows/nf-core/quantify_pseudo_alignment/tests/main.nf.test
- subworkflows/nf-core/quantify_pseudo_alignment/tests/main.nf.test.snap
Effectively undo https://github.com/nf-core/modules/pull/5619 and https://github.com/nf-core/modules/pull/5610. The abundance estimates of Salmon/ Kallisto are unaffected by tximport processing (unlike the counts) so there's no point writing them out multiple times.
Closes #XXX 
- For modules:
> Remove redundant tximport outputs

- modules/nf-core/annotsv/annotsv/environment.yml
- modules/nf-core/annotsv/annotsv/main.nf
- modules/nf-core/annotsv/annotsv/tests/main.nf.test.snap
- modules/nf-core/annotsv/installannotations/environment.yml
- modules/nf-core/annotsv/installannotations/main.nf
- modules/nf-core/annotsv/installannotations/tests/main.nf.test
- modules/nf-core/annotsv/installannotations/tests/main.nf.test.snap
The old `biocontainers` were having some permission errors that were bugging me for a long time. It seems the permissions do get set correctly by migrating to seqera containers
> Move annotsv containers to seqera containers

- modules/nf-core/segemehl/align/main.nf
- modules/nf-core/segemehl/align/meta.yml
- modules/nf-core/segemehl/align/tests/main.nf.test
- modules/nf-core/segemehl/align/tests/main.nf.test.snap
- modules/nf-core/segemehl/align/tests/split.config
- modules/nf-core/segemehl/align/tests/tags.yml
Currently, the output files of this module are all provided as a single channel containing the output directory.
This makes selecting individual files for further analysis inconvenient. 
This was not a problem before, as the only nf-core pipeline using this module (circrna) had a specific process for handling this. Recently, we switched to using the nf-core `GAWK` module, which makes it necessary to provide only the relevant file to the process.
- For modules:
> Make segemehl outputs more specific

- modules/nf-core/multiqc/environment.yml
- modules/nf-core/multiqc/main.nf
- modules/nf-core/multiqc/tests/main.nf.test.snap
- subworkflows/nf-core/bam_dedup_stats_samtools_umitools/main.nf
- subworkflows/nf-core/bam_dedup_stats_samtools_umitools/meta.yml
- subworkflows/nf-core/bam_dedup_stats_samtools_umitools/tests/main.nf.test
As of now, the subworkflow `bam_dedup_stats_samtools_umitools` does emit the UMI-tools deduplication logs. The output channel `UMITOOLS_DEDUP.out.log` of the module is ignored in the subworkflow, but it is needed to generate a summary of the deduplication rate with MultiQC inside a pipeline. Since MultiQC supports the tool, it would be a pity to omit the stats in the report in the future.
This PR thus makes sure that there is also an output channel on the subworkflow level, so the logs can be utilized in a pipeline's MultiQC report. In addition, I have also upgraded the MultiQC module to the latest version.
- For modules:
- [] `nf-core modules test <MODULE> --profile docker` (**MultiQC**)
- …
> Subworkflow: Publish UMI-tools dedup basic deduplication statistics in "Bam dedup stats samtools umitools"

- modules/nf-core/gnu/sort/environment.yml
- modules/nf-core/gnu/sort/main.nf
- modules/nf-core/gnu/sort/tests/main.nf.test.snap
The primary goal is to fix the upcoming problems with old docker images not being compatible with current docker versions. I took inspiration from [gnu_split](https://github.com/nf-core/modules/tree/master/modules/nf-core/gnu/split), which has the same dependencies.
> Update gnu_sort dependency versions

- subworkflows/nf-core/fastq_fastqc_umitools_fastp/main.nf
- subworkflows/nf-core/fastq_fastqc_umitools_fastp/tests/main.nf.test
- subworkflows/nf-core/fastq_fastqc_umitools_fastp/tests/main.nf.test.snap
> Added stub logic and test to fastq_fastqc_umitools_fastp

- modules/nf-core/mapad/index/main.nf
- modules/nf-core/mapad/index/tests/main.nf.test.snap
- modules/nf-core/mapad/map/main.nf
- modules/nf-core/mapad/map/tests/main.nf.test.snap
- subworkflows/nf-core/fastq_align_mapad/tests/main.nf.test.snap
Remove a stray parenthesis that was not correctly stripped off the version string.
> mapAD: fix `versions.yml` emission

- modules/nf-core/samtools/reheader/main.nf
Just a simple bug fix. When supplying a prefix to SAMTOOLS_REHEADER, this was not being used to evaluate if input/output files were the same to trigger the error message. 
Closes #XXX 
- For modules:
> samtools/reheader: Fix bug causing output name to be incorrectly evaluated

- modules/nf-core/last/dotplot/main.nf
- modules/nf-core/last/dotplot/meta.yml
- modules/nf-core/last/dotplot/tests/main.nf.test
- modules/nf-core/last/dotplot/tests/main.nf.test.snap
This adds the capacity to overlay annotations to the dot plots.  In the _pairgenomealign_ pipeline, we will use it to indicate genomic regions containing N stretches that typically mark contig boundaries in scaffold assemblies, like the pink lines in the following example:
The annotation of the target (plotted horizontally) genome is passed as a new channel.
The annotation of the query (plotted vertically) genome is passed as a new component of the first channel.
This is because this module typically loops on a list of alignments of various query genomes (from samplesheet) to a single target genome.
The annotation files are called `annot_a` and `annot_b` because they are passed to the `-a` and `-b` arguments of `last-dotplot`.
Closes #XXX 
- [ x] Use BioConda and BioContainers if possible …
> Pass annotation files to last-dotplot

- modules/nf-core/evigene/tr2aacds/environment.yml
- modules/nf-core/evigene/tr2aacds/main.nf
- modules/nf-core/evigene/tr2aacds/meta.yml
- modules/nf-core/evigene/tr2aacds/tests/main.nf.test
- modules/nf-core/evigene/tr2aacds/tests/main.nf.test.snap
> Added evigene/tr2aacds

- modules/nf-core/president/main.nf
- modules/nf-core/president/meta.yml
- modules/nf-core/president/tests/main.nf.test
- modules/nf-core/president/tests/main.nf.test.snap
I just fixed the path for the output files in the stub section. Nothing big, but important.
> correct president stub

- modules/nf-core/pbtk/pbindex/environment.yml
- modules/nf-core/pbtk/pbindex/main.nf
- modules/nf-core/pbtk/pbindex/meta.yml
- modules/nf-core/pbtk/pbindex/tests/main.nf.test
- modules/nf-core/pbtk/pbindex/tests/main.nf.test.snap
> Added pbtk/pbindex

- modules/nf-core/kallisto/index/main.nf
- modules/nf-core/kallisto/index/tests/main.nf.test
- modules/nf-core/kallisto/index/tests/main.nf.test.snap
- modules/nf-core/kallisto/quant/main.nf
- modules/nf-core/kallisto/quant/tests/main.nf.test
- modules/nf-core/kallisto/quant/tests/main.nf.test.snap
- subworkflows/nf-core/fastq_fastqc_umitools_fastp/tests/main.nf.test
- subworkflows/nf-core/fastq_fastqc_umitools_fastp/tests/main.nf.test.snap
- subworkflows/nf-core/fastq_fastqc_umitools_trimgalore/tests/main.nf.test
- subworkflows/nf-core/fastq_fastqc_umitools_trimgalore/tests/main.nf.test.snap
- subworkflows/nf-core/fastq_subsample_fq_salmon/tests/main.nf.test
- subworkflows/nf-core/fastq_subsample_fq_salmon/tests/main.nf.test.snap
- subworkflows/nf-core/quantify_pseudo_alignment/tests/main.nf.test
- subworkflows/nf-core/quantify_pseudo_alignment/tests/main.nf.test.snap
Continuing #5911 with:
- Fix stub for modules:
- `kallisto/index`
- `kallisto/quant`
- Add stub tests for subworkflows:
- `fastq_fastqc_umitools_fastp`
- `fastq_fastqc_umitools_trimgalore`
- `fastq_subsample_fq_salmon`
- `quantify_pseudo_alignment`
Closes #XXX 
- For modules:
> Add stubs for rnaseq subworkflows - part II

- modules/nf-core/vardictjava/environment.yml
- modules/nf-core/vardictjava/main.nf
- modules/nf-core/vardictjava/tests/main.nf.test.snap
> mulled biocontainer for vardict-java and htslib

- modules/nf-core/argnorm/environment.yml
- modules/nf-core/argnorm/main.nf
- modules/nf-core/argnorm/meta.yml
- modules/nf-core/argnorm/tests/argnorm_hamronized.config
- modules/nf-core/argnorm/tests/argnorm_raw.config
- modules/nf-core/argnorm/tests/main.nf.test
- modules/nf-core/argnorm/tests/main.nf.test.snap
- modules/nf-core/argnorm/tests/tags.yml
[argNorm](https://github.com/BigDataBiology/argNorm) is a tool to normalize antibiotic resistance genes (ARGs) by mapping them to the [antibiotic resistance ontology (ARO)](https://obofoundry.org/ontology/aro.html) created by the [CARD database](https://card.mcmaster.ca/).
argNorm also enhances antibiotic resistance gene annotations by providing drug categorization of the drugs that antibiotic resistance genes confer resistance to.
argNorm takes the outputs of the [hAMRonization](https://nf-co.re/modules/hamronization_abricate) module as well as ARG annotation tools (DeepARG, ARGs-OAP, ABRicate, ResFinder, and AMRFinderPlus) to normalize them to the antibiotic resistance ontology.
> ADD argNorm module

- .github/workflows/test.yml
- **ci: Remove setting secrets in pytest-workflow**
- **ci: Add a longer note about conditionals**
- **ci: Check for secrets in env**
This fixes issues where the CI fails if the PR is coming from a fork
Follow up to #5856
> Fix Sentieon CI

- modules/nf-core/dupradar/templates/dupradar.r
In the course of working on the upcoming rnaseq 3.15.0 release, we noticed that MultiQC renamed or otherwise changed keywords in the configuration. For compatibility with current and future versions of MultiQC, the module needs updating.
I wonder if there is a point in retaining the old version and enabling switching between the two?
(_This PR is not ready for merging, we might need to add more changes to it when testing is continued with a new MultiQC version._)
Closes #XXX 
- For modules:
> Update dupradar.r according to new MultiQC (>=v1.22) config values

- modules/nf-core/genmap/index/main.nf
- modules/nf-core/genmap/map/main.nf
- modules/nf-core/pairtools/dedup/main.nf
- modules/nf-core/pairtools/flip/main.nf
- modules/nf-core/pairtools/merge/main.nf
- modules/nf-core/pairtools/parse/main.nf
- modules/nf-core/pairtools/restrict/main.nf
- modules/nf-core/pairtools/select/main.nf
- modules/nf-core/pairtools/sort/main.nf
- modules/nf-core/pairtools/split/main.nf
- modules/nf-core/pairtools/stats/main.nf
> by remove the 2>&1 to avoid the warning message.

- modules/nf-core/custom/gtffilter/main.nf
Make the output definition more general, as the extension won't always be "gtf"
> Fix gtffilter output definition

- subworkflows/nf-core/fastq_qc_trim_filter_setstrandedness/main.nf
- subworkflows/nf-core/fastq_qc_trim_filter_setstrandedness/meta.yml
- subworkflows/nf-core/fastq_qc_trim_filter_setstrandedness/tests/main.nf.test
I'm porting some [improvements we made](https://github.com/nf-core/rnaseq/pull/1306) in rnaseq for strandedness determination to this subworkflow. This is basically defining our own logic and thresholds for setting strandedness, using Salmon statistics, rather than letting Salmon do it internally.
(Note, I'm [also moving the rnaseq logic to actually use this subworkflow](https://github.com/nf-core/rnaseq/pull/1342), after I previously factored the logic out for the riboseq workflow). 
Closes #XXX 
- For modules:
> Improve strandedness derivation in rnaseq preprocessing swf

- modules/nf-core/fgbio/collectduplexseqmetrics/environment.yml
- modules/nf-core/fgbio/collectduplexseqmetrics/main.nf
- modules/nf-core/fgbio/collectduplexseqmetrics/meta.yml
- modules/nf-core/fgbio/collectduplexseqmetrics/tests/main.nf.test
- modules/nf-core/fgbio/collectduplexseqmetrics/tests/main.nf.test.snap
- modules/nf-core/fgbio/collectduplexseqmetrics/tests/tags.yml
Closes #3257 
Add module fgbio/collectduplexseqmetrics
- For modules:
> Add module fgbio/collectduplexseqmetrics

- modules/nf-core/tabix/bgzip/environment.yml
- modules/nf-core/tabix/bgzip/main.nf
- modules/nf-core/tabix/bgzip/tests/main.nf.test.snap
- modules/nf-core/tabix/bgziptabix/environment.yml
- modules/nf-core/tabix/bgziptabix/main.nf
- modules/nf-core/tabix/bgziptabix/tests/main.nf.test.snap
- modules/nf-core/tabix/tabix/environment.yml
- modules/nf-core/tabix/tabix/main.nf
- modules/nf-core/tabix/tabix/tests/main.nf.test
- modules/nf-core/tabix/tabix/tests/main.nf.test.snap
> Update tabix and add threads

- modules/nf-core/ltrfinder/tests/main.nf.test
- modules/nf-core/ltrfinder/tests/main.nf.test.snap
- modules/nf-core/ltrfinder/tests/tags.yml
> ltrfinder: Added test to verify graceful handling of no ltr input

- modules/nf-core/stringtie/stringtie/tests/main.nf.test
- modules/nf-core/stringtie/stringtie/tests/nextflow.config
- subworkflows/nf-core/fastq_align_hisat2/tests/main.nf.test.snap
> Hotfix stringtie_stringtie

- modules/nf-core/bedops/convert2bed/tests/main.nf.test
- modules/nf-core/bedops/gtf2bed/tests/main.nf.test
- modules/nf-core/chewbbaca/createschema/tests/main.nf.test
- modules/nf-core/diamond/blastp/tests/main.nf.test
- modules/nf-core/diamond/blastp/tests/main.nf.test.snap
- modules/nf-core/diamond/blastx/tests/main.nf.test
- modules/nf-core/diamond/blastx/tests/main.nf.test.snap
- modules/nf-core/diamond/makedb/tests/main.nf.test
- modules/nf-core/diamond/makedb/tests/main.nf.test.snap
- modules/nf-core/narfmap/align/tests/main.nf.test
- modules/nf-core/narfmap/align/tests/main.nf.test.snap
- modules/nf-core/narfmap/hashtable/tests/main.nf.test
- modules/nf-core/tabix/bgziptabix/tests/main.nf.test
- modules/nf-core/tabix/tabix/tests/main.nf.test
> Updated test data base path batch 1

- modules/nf-core/porechop/abi/environment.yml
- modules/nf-core/porechop/abi/main.nf
- modules/nf-core/porechop/abi/meta.yml
- modules/nf-core/porechop/abi/tests/main.nf.test
- modules/nf-core/porechop/abi/tests/main.nf.test.snap
- modules/nf-core/porechop/abi/tests/tags.yml
- tests/config/pytest_modules.yml
Will be used in https://github.com/nf-core/taxprofiler/issues/145 
- For modules:
> Add nf-test to porechop_abi

- modules/nf-core/cutadapt/tests/main.nf.test
- modules/nf-core/gt/gff3/tests/main.nf.test
- modules/nf-core/gt/gff3validator/tests/main.nf.test
- modules/nf-core/gt/ltrharvest/tests/main.nf.test
- modules/nf-core/gt/ltrharvest/tests/main.nf.test.snap
- modules/nf-core/gt/stat/tests/main.nf.test
- modules/nf-core/gt/suffixerator/tests/main.nf.test
- modules/nf-core/oatk/tests/main.nf.test
- modules/nf-core/oatk/tests/main.nf.test.snap
- modules/nf-core/pycoqc/tests/main.nf.test
- modules/nf-core/trinity/main.nf
- modules/nf-core/trinity/tests/main.nf.test
- modules/nf-core/trinity/tests/main.nf.test.snap
- modules/nf-core/vcfanno/tests/main.nf.test
- tests/config/pytest_modules.yml
> Updated test data paths batch 6

- modules/nf-core/sentieon/qualcal/main.nf
- modules/nf-core/sentieon/qualcal/tests/main.nf.test
If generate_recalibrated_bams is false, sentieon/qualcal stubs would fail with an empty 'touch' command. This PR fixes that bug.
> Fix bug in sentieon/qualcal where stubs failed

- modules/nf-core/sentieon/haplotyper/main.nf
- modules/nf-core/sentieon/haplotyper/meta.yml
- modules/nf-core/sentieon/haplotyper/tests/main.nf.test
PR adds recalibration as part of the sample-specific input instead of a general input, since each sample has its own recalibration table generated upstream by sentieon/qualcal. 
Without the changes the recalibration table can't be matched to the sample.
> Sentieon/Haplotyper: Recal table is sample specific

- modules/nf-core/ampir/tests/main.nf.test
- modules/nf-core/bowtie2/align/tests/main.nf.test
- modules/nf-core/checkm2/predict/tests/main.nf.test
- modules/nf-core/fcs/fcsadaptor/tests/main.nf.test
- modules/nf-core/foldseek/createdb/tests/main.nf.test
- modules/nf-core/foldseek/easysearch/tests/main.nf.test
- modules/nf-core/isoseq3/tag/tests/main.nf.test
- modules/nf-core/mosdepth/tests/main.nf.test
- modules/nf-core/stringtie/merge/tests/main.nf.test
> Updated test data paths batch 8

- modules/nf-core/abacas/tests/main.nf.test
- modules/nf-core/abritamr/run/tests/main.nf.test
- modules/nf-core/fq/lint/meta.yml
- modules/nf-core/fq/lint/tests/main.nf.test
- modules/nf-core/freyja/boot/tests/main.nf.test
- modules/nf-core/freyja/demix/tests/main.nf.test
- modules/nf-core/freyja/variants/tests/main.nf.test
- modules/nf-core/quartonotebook/tests/main.nf.test
- subworkflows/nf-core/bam_variant_demix_boot_freyja/tests/main.nf.test
- subworkflows/nf-core/bam_variant_demix_boot_freyja/tests/nextflow.config
> Updated test data paths batch 11

- modules/nf-core/bedtools/genomecov/main.nf
- modules/nf-core/bedtools/genomecov/tests/tags.yml
`bedtools sort` uses a large amount of CPUs and memory, but when using it here it doesn't require the  additional genome based features of `bedtools`. Replacing it should speed up the process and make it many times more efficient.
First discovered by @pabloaledo 
- For modules:
> Replace bedtools sort with unix sort in BEDTOOLS_GENOMECOV

- modules/nf-core/sentieon/coveragemetrics/main.nf
I accidentally used `meta` twice which caused the `tag` to be null. This PR fixes it.
- For modules:
> Fix: Sentieon CoverageMetrics error in meta values

- modules/nf-core/sentieon/bwamem/main.nf
- modules/nf-core/sentieon/bwamem/meta.yml
- modules/nf-core/sentieon/bwamem/tests/tags.yml
- Sentieon uses an environment variable to estimate the maximum memory usage.
- This PR sets the environment variable to 90% of the task memory, which should be a safe value for most cases.
- This will speed up the Sentieon BWA mem throughput considerably.
- For modules:
> Maximises Sentieon BWA Mem memory usage

- .github/env-template.yml
- .github/workflows/test.yml
- modules/environment-schema.json
- subworkflows/nf-core/utils_nextflow_pipeline/main.nf
Structural changes to schema and other files for removing the `defaults` channel.
See https://github.com/nf-core/modules/issues/5829
> Conda remove defaults channel - structural changes

- modules/nf-core/sentieon/bwamem/main.nf
- modules/nf-core/sentieon/bwamem/tests/main.nf.test.snap
Sentieon bwamem always generates a bai file, even if `cram` is specified as output. In the output channel specification this means that both `bai` and `crai` are provided as indices breaking any downstream tool without further channel magic. Since the `bai` is not needed, if a `crai` exists, it is removed.
Closes #XXX 
- For modules:
> Sentieon/bwamem: Remove bai if cram is output

- modules/nf-core/ashlar/environment.yml
- modules/nf-core/ashlar/main.nf
- tests/modules/nf-core/ashlar/test.yml
Some microscope file formats will break if files are renamed, so we can't change the staged filenames to avoid collisions. Instead we will stage each input without renaming into its own unique subdirectory.
- For modules:
> Update ashlar to 1.18 and improve staging

- subworkflows/nf-core/utils_nextflow_pipeline/main.nf
Remove `defaults` channel for https://github.com/nf-core/tools/pull/3029 and https://github.com/nf-core/modules/issues/5829
> remove 'defaults' from conda channels

- modules/nf-core/lofreq/callparallel/main.nf
- modules/nf-core/lofreq/callparallel/meta.yml
- modules/nf-core/lofreq/callparallel/tests/main.nf.test
- modules/nf-core/lofreq/callparallel/tests/main.nf.test.snap
Closes #6426 
- For modules:
`tbi` index has been added as an output to `lofreq callparallel` since it is already generated in the variant calling process. It might (and probably will) used downstream in the pipelines. With this change it doesn't have to be generated again.
> Add tbi index as an output to lofreq callparallel

- modules/nf-core/tximeta/tximport/templates/tximport.r
This fixes an error introduced by https://github.com/nf-core/modules/pull/6466.
The row names of the gene info table do need to be null (which is what the original line was doing, unclearly). Otherwise we get errors like:
```
Error in SummarizedExperiment(assays = list(counts = counts, abundance = abundance,  : 
the rownames and colnames of the supplied assay(s) must be NULL or
identical to those of the SummarizedExperiment object (or derivative)
to construct
```
Closes #XXX 
- For modules:
> Fix gene table row naming in tximeta/tximport

- modules/nf-core/bcftools/pluginimputeinfo/meta.yml
This PR includes suggestions from the new module PR that were not incorporated prior to the merge into master
- For modules:
> Update bcftools/pluginimputeinfo meta.yml

- modules/nf-core/ltrfinder/tests/main.nf.test
- modules/nf-core/ltrretriever/ltrretriever/tests/main.nf.test
For a little while nf-test has been producing a warning for every test:
```
│ Warning: Module /workspace/modules/modules/nf-core/ltrfinder/tests/main.nf.test: Dependency '/workspace/modules/modules/nf-core/ltrfinder/tests/../../gunzip/main' not found.                   │
│ Warning: Module /workspace/modules/modules/nf-core/ltrretriever/ltrretriever/tests/main.nf.test: Dependency                                                                                     │
│ '/workspace/modules/modules/nf-core/ltrretriever/ltrretriever/tests/../../../gunzip/main' not found.        
```
This PR fixes this by providing full file paths to them modules.
> Stop nf-test complaining about missing dependency

- modules/nf-core/jvarkit/dict2bed/environment.yml
- modules/nf-core/jvarkit/dict2bed/main.nf
- modules/nf-core/jvarkit/dict2bed/meta.yml
- modules/nf-core/jvarkit/dict2bed/tests/main.nf.test
- modules/nf-core/jvarkit/dict2bed/tests/main.nf.test.snap
- modules/nf-core/jvarkit/dict2bed/tests/nextflow.config
- modules/nf-core/jvarkit/dict2bed/tests/tags.yml
this is a PR for jvarkit/vcf2table  which convert files containing a dictionary like cram/bam/dict/etc.. to bed: https://jvarkit.readthedocs.io/en/latest/DictToBed/
```
$ java -jar dist/jvarkit.jar dict2bed ~/src/jvarkit-git/src/test/resources/*.bam |  head | column -t
chrom  start  end        path                                                                         tid  buildName  AS  M5  SP  UR
chr1   0      248956422  /home/lindenb/src/jvarkit-git/src/test/resources/ENCFF331CGL.rnaseq.b38.bam  0    GRCh38     .   .   .   .
chr2   0      242193529  /home/lindenb/src/jvarkit-git/src/test/resources/ENCFF331CGL.rnaseq.b38.bam  1    GRCh38     .   .   .   .
chr3   0      198295559  /home/lindenb/src/jvarkit-git/src/test/resources/ENCFF331CGL.rnaseq.b38.bam  2    GRCh38     .   .   .   . …
```
> new module jvarkit/dict2bed

- modules/nf-core/samtools/ampliconclip/environment.yml
- modules/nf-core/samtools/bam2fq/environment.yml
- modules/nf-core/samtools/calmd/environment.yml
- modules/nf-core/samtools/cat/environment.yml
- modules/nf-core/samtools/collate/environment.yml
- modules/nf-core/samtools/collatefastq/environment.yml
- modules/nf-core/samtools/consensus/environment.yml
- modules/nf-core/samtools/convert/environment.yml
- modules/nf-core/samtools/coverage/environment.yml
- modules/nf-core/samtools/cramsize/environment.yml
- modules/nf-core/samtools/depth/environment.yml
- modules/nf-core/samtools/dict/environment.yml
- modules/nf-core/samtools/faidx/environment.yml
- modules/nf-core/samtools/fasta/environment.yml
- modules/nf-core/samtools/fastq/environment.yml
- modules/nf-core/samtools/fixmate/environment.yml
- modules/nf-core/samtools/flagstat/environment.yml
- modules/nf-core/samtools/getrg/environment.yml
- modules/nf-core/samtools/idxstats/environment.yml
- modules/nf-core/samtools/import/environment.yml
- modules/nf-core/samtools/index/environment.yml
- modules/nf-core/samtools/markdup/environment.yml
- modules/nf-core/samtools/merge/environment.yml
- modules/nf-core/samtools/mpileup/environment.yml
- modules/nf-core/samtools/reheader/environment.yml
- modules/nf-core/samtools/sormadup/environment.yml
- modules/nf-core/samtools/sort/environment.yml
- modules/nf-core/samtools/stats/environment.yml
- modules/nf-core/samtools/view/environment.yml
> restore samtools modules version bump

- modules/nf-core/phantompeakqualtools/main.nf
Do not use `oras` in `phantompeakqualtools` module.
- For modules:
> Switch from oras to https in phantompeakqualtools module

- modules/nf-core/vardictjava/main.nf
- modules/nf-core/vardictjava/meta.yml
- modules/nf-core/vardictjava/tests/main.nf.test
- modules/nf-core/vardictjava/tests/main.nf.test.snap
- modules/nf-core/vardictjava/tests/nextflow.config
> Don't use test scripts when the `-fisher` option has been given in vardictjava

- modules/nf-core/maxbin2/main.nf
- modules/nf-core/maxbin2/meta.yml
Currently this modules allows the input of only one abundance file with one abundance column. This adds a possibility to use multiple abundance files (each with the contig abundance of one sample).
Related to https://github.com/nf-core/mag/pull/690
Closes #XXX 
- For modules:
> Update MaxBin2: allow multiple abund files

- modules/nf-core/tar/main.nf
> Fix tar to always follow symlinks due to nxf staging in work dirs

- modules/nf-core/svdb/merge/main.nf
- modules/nf-core/svdb/merge/meta.yml
- modules/nf-core/svdb/merge/tests/main.nf.test
- modules/nf-core/svdb/merge/tests/main.nf.test.snap
- modules/nf-core/svdb/merge/tests/nextflow.config
This PR adds functionality for sorting the input files to SVDB. This allows the output to be snapshot when this module is included in a subworkflow, since the sample order in the output files will be fixed. The priority tags are sorted together with the VCFs, so the priority order is unchanged.
It also adds a check to make sure there are as many priority tags as input VCFs.
Tests should cover all usages.
Closes #XXX 
- For modules:
> Allow sorting inputs to SVDB

- modules/nf-core/fastqe/environment.yml
- modules/nf-core/fastqe/main.nf
- modules/nf-core/fastqe/meta.yml
- modules/nf-core/fastqe/tests/main.nf.test
- modules/nf-core/fastqe/tests/main.nf.test.snap
Adds FASTQE, arguably the most important module.
- For modules:
> Add FASTQE module

- modules/nf-core/cellranger/mkfastq/main.nf
Closes [mkfastq fails on AWS Batch #281](https://github.com/nf-core/demultiplex/issues/281)
`cellranger/mkfastq` process fails when running `nf-core/demultiplex` on AWS Batch with `-profile test_mkfastq,docker`. 
When running locally, the output folders are created (but without files) hence the process ends succesfully. When running on AWS Batch the process fails with the following error:
``` bash
Missing output file(s) `*_outs/outs/fastq_path/Reports` expected by process `NFCORE_DEMULTIPLEX:DEMULTIPLEX:MKFASTQ_DEMULTIPLEX:CELLRANGER_MKFASTQ (test_sample.1)`
```
Some explanation may come from the following [AWS doc](https://docs.aws.amazon.com/AmazonS3/latest/userguide/using-folders.html) explaining that S3 is a flat system where files are grouped by common prefixes to simulate folders. …
> Set mkfastq reports and stats outputs to optional

- modules/nf-core/krakenuniq/preloadedkrakenuniq/main.nf
- modules/nf-core/krakenuniq/preloadedkrakenuniq/meta.yml
- modules/nf-core/krakenuniq/preloadedkrakenuniq/tests/main.nf.test
- modules/nf-core/krakenuniq/preloadedkrakenuniq/tests/main.nf.test.snap
Updating the module will address the following bug in the taxprofiler pipeline https://github.com/nf-core/taxprofiler/issues/533 but requires that the pipeline be refactored to supply the new input.
> Expect input of prefixes to KrakenUniq

- .pre-commit-config.yaml
I thought we did this already... it's just too noisy with updates and we don't need to update the config that often.
> remove pre-commit config validator hook

- .github/workflows/wave.yml
Because it doesn't expose our tower workspace and tower token if it's from a fork.
https://github.com/nf-core/modules/pull/6917
> Skip wave if the PR is from a fork

- modules/nf-core/fgbio/callduplexconsensusreads/environment.yml
- modules/nf-core/fgbio/callduplexconsensusreads/main.nf
- modules/nf-core/fgbio/callduplexconsensusreads/tests/main.nf.test.snap
- modules/nf-core/fgbio/callmolecularconsensusreads/environment.yml
- modules/nf-core/fgbio/callmolecularconsensusreads/main.nf
- modules/nf-core/fgbio/callmolecularconsensusreads/tests/main.nf.test.snap
- modules/nf-core/fgbio/collectduplexseqmetrics/environment.yml
- modules/nf-core/fgbio/collectduplexseqmetrics/main.nf
- modules/nf-core/fgbio/collectduplexseqmetrics/tests/main.nf.test.snap
- modules/nf-core/fgbio/fastqtobam/environment.yml
- modules/nf-core/fgbio/fastqtobam/main.nf
- modules/nf-core/fgbio/fastqtobam/tests/main.nf.test.snap
- modules/nf-core/fgbio/filterconsensusreads/environment.yml
- modules/nf-core/fgbio/filterconsensusreads/main.nf
- modules/nf-core/fgbio/filterconsensusreads/tests/main.nf.test.snap
- modules/nf-core/fgbio/groupreadsbyumi/environment.yml
- modules/nf-core/fgbio/groupreadsbyumi/main.nf
- modules/nf-core/fgbio/groupreadsbyumi/tests/main.nf.test.snap
- modules/nf-core/fgbio/sortbam/environment.yml
- modules/nf-core/fgbio/sortbam/main.nf
- modules/nf-core/fgbio/sortbam/tests/main.nf.test.snap
- modules/nf-core/fgbio/zipperbams/environment.yml
- modules/nf-core/fgbio/zipperbams/main.nf
- modules/nf-core/fgbio/zipperbams/tests/main.nf.test.snap
This PR updates the version of fgbio used in all fgbio modules to version 2.4.0. It also switches from biocontainers to Seqera containers.
- For modules:
> chore: bump fgbio version

- .github/renovate.json5
No clue if this will work, it passed locally 🤷🏻 
Adds a regex to fix not finding the dependency if `::` and a channel is in the conda dependency.
> ci(renovate): Allow channels in environment.ymls

- .github/CODEOWNERS
- .github/workflows/wave.yml
- modules/nf-core/quartonotebook/Dockerfile
- modules/nf-core/wittyer/Dockerfile
- modules/nf-core/wittyer/environment.yml
For @matthdsm on #4935
Branched off from #4080
> Wave with Dockerfiles

- modules/nf-core/trgt/plot/environment.yml
- modules/nf-core/trgt/plot/main.nf
- modules/nf-core/trgt/plot/meta.yml
- modules/nf-core/trgt/plot/tests/main.nf.test
- modules/nf-core/trgt/plot/tests/main.nf.test.snap
- modules/nf-core/trgt/plot/tests/nextflow.config
(Partially) closes #6984  
- For modules:
> Added module trgt/plot

- subworkflows/nf-core/fastq_align_dedup_bismark/main.nf
- subworkflows/nf-core/fastq_align_dedup_bismark/meta.yml
- subworkflows/nf-core/fastq_align_dedup_bismark/tests/main.nf.test
- subworkflows/nf-core/fastq_align_dedup_bismark/tests/main.nf.test.snap
- subworkflows/nf-core/fastq_align_dedup_bismark/tests/nextflow.config
renaming emit channels as depending on whether `skip_deduplication` is used, the output is either aligned or dedup bam
> improve workflow logic for `fastq_align_dedup_bismark`

- .github/actions/nf-test-action/action.yml
- .github/renovate.json5
- .github/workflows/gpu-tests.yml
- .github/workflows/lint.yml
- .github/workflows/nf-test.yml
- .github/workflows/pytest-workflow.yml
- .github/workflows/wave.yml
- tests/config/nextflow.config
- tests/config/nf-test.config
Fixes #6664 
- **ci(renovate): Add custom VERSION updates in GitHub actions**
- **ci(#6664): Bump all Nextflow versions to 24.10.1**
- **ci: Add renovate comments to version in actions**
> Bump Nextflow Versions

- .github/workflows/nf-test.yml
Fixes errors seen in Github actions when running on an existing runner, e.g.: https://github.com/nf-core/modules/actions/runs/11932680093
Closes #XXX 
- For modules:
> Purge the workspace for the self-hosted runners

- modules/nf-core/samtools/view/main.nf
There were some weird non-printing characters in the Docker container name for samtools/view which caused a failure when running using Docker due to the name failing to resolve. 
samtools/view also uses a different container than the rest of the samtools modules, but I've left that unchanged here
Closes #XXX 
- For modules:
> fix special characters in samtools/view container

- modules/nf-core/quartonotebook/main.nf
See https://github.com/nf-core/modules/actions/runs/11974423411/job/33385468168 for an example of a broken test caused by this change.
This reverts the multi-line import introduced in https://github.com/nf-core/modules/pull/5561
We need to fix the detect-nf-test but for now this will keep us going.
- For modules:
> fix: quartonotebook imported over multiple lines which broke detect-nf-test-changes

- subworkflows/nf-core/utils_nfcore_pipeline/main.nf
New Nextflow language server throws a warning about these unused variables. Figured the easiest solution is to print them to the debug log.
Same as #7070 but a different subworkflow.
> nf-core utils: fix langserver warnings

- subworkflows/nf-core/utils_nextflow_pipeline/main.nf
New Nextflow language server throws a warning about these unused variables. Figured the easiest solution is to print them to the debug log.
> Utils Nextflow: Avoid unused variables

- modules/nf-core/fastqc/main.nf
New Nextflow language server throws a warning about this variable as it's unused. Prefixing with an underscore resolves this.
> FastQC: Avoid NXF langserver warning

- modules/nf-core/mafft/guidetree/main.nf
- modules/nf-core/mafft/guidetree/tests/main.nf.test.snap
There was a mistake in the version reporting - i only spotted it now!
- For modules:
> fix versions of mafft/guidetree

- modules/nf-core/spaceranger/Dockerfile
- modules/nf-core/spaceranger/README.md
- modules/nf-core/spaceranger/count/main.nf
- modules/nf-core/spaceranger/count/tests/main.nf.test
- modules/nf-core/spaceranger/count/tests/main.nf.test.snap
- modules/nf-core/spaceranger/mkgtf/main.nf
- modules/nf-core/spaceranger/mkgtf/tests/main.nf.test
- modules/nf-core/spaceranger/mkgtf/tests/main.nf.test.snap
- modules/nf-core/spaceranger/mkref/main.nf
- modules/nf-core/spaceranger/mkref/tests/main.nf.test
- modules/nf-core/spaceranger/mkref/tests/main.nf.test.snap
Bump version of spaceranger (in part, to be able to analyze visium hd data)
- For modules:
> spaceranger_bump_version

- modules/nf-core/nacho/normalize/meta.yml
- modules/nf-core/nacho/qc/meta.yml
Continues [NACHO_QC](https://github.com/nf-core/modules/pull/7100) and [NACHO_NORMALIZE](https://github.com/nf-core/modules/pull/7108)
- For modules:
Fix linting problems on meta.yml files.
**NOTE**: linting on this modules with `nf-core modules lint` did not thow errors. However, after applying them to Nanostring pipeline and running `nf-core pipelines lint`, it changed these two files. So, this changed the files there causing a mismatch with nf-core repository.
nf-core version used on pipeline: 3.0.2 (Gitpod session)
nf-core version used on modules: 3.0.3dev0 (Gitpod session)
> fix linting on meta.yml files

- modules/nf-core/rrnatranscripts/main.nf
Related to: https://github.com/nf-core/rnafusion/issues/563
Closes #XXX 
- For modules:
> Fix bug in `RRNATRANSCRIPTS` with harcoded gtf

- modules/nf-core/coptr/estimate/environment.yml
- modules/nf-core/coptr/estimate/main.nf
- modules/nf-core/coptr/estimate/meta.yml
- modules/nf-core/coptr/estimate/tests/main.nf.test
- modules/nf-core/coptr/estimate/tests/main.nf.test.snap
- modules/nf-core/coptr/extract/main.nf
- modules/nf-core/coptr/extract/tests/main.nf.test.snap
- modules/nf-core/coptr/merge/main.nf
- modules/nf-core/coptr/merge/tests/main.nf.test.snap
> New module: COPTR/ESTIMATE

- subworkflows/nf-core/utils_nfcore_pipeline/main.nf
- subworkflows/nf-core/utils_nfcore_pipeline/tests/main.function.nf.test
The use of the switch syntax is not yet supported by the LSP, so replacing it with if-else for the time being. Less elegant, but functionally identical.
I also added some tests to check that the function works as expected.
Closes #XXX 
- For modules:
> Replace switch with else-if in utils_nfcore_pipeline

- modules/nf-core/trimgalore/environment.yml
- modules/nf-core/trimgalore/main.nf
- modules/nf-core/trimgalore/tests/main.nf.test
- modules/nf-core/trimgalore/tests/main.nf.test.snap
- subworkflows/nf-core/fastq_fastqc_umitools_trimgalore/tests/main.nf.test.snap
- **feat: Add pigz to trimgalore**
- **style: Run lsp format**
This one shouldn't be controversial. It's documented that using pigz speeds up trimgalore. In the DSL2 transition the requirement got dropped because it was in mega environment.yml in methylseq, and atac-seq.
Closes https://github.com/nf-core/atacseq/issues/394 
> Added multi-threading support with the new option -j/--cores INT; many thanks to Frankie James for initiating this. Multi-threading support works effectively if Cutadapt is run with Python 3, and if parallel gzip (pigz) is installed: 
https://github.com/FelixKrueger/TrimGalore/blob/master/CHANGELOG.md#version-060-release-on-1-mar-2019
> Add pigz to trimgalore

- modules/nf-core/foldmason/createdb/environment.yml
- modules/nf-core/foldmason/createdb/main.nf
- modules/nf-core/foldmason/createdb/meta.yml
- modules/nf-core/foldmason/createdb/tests/main.nf.test
- modules/nf-core/foldmason/createdb/tests/main.nf.test.snap
- modules/nf-core/foldmason/easymsa/environment.yml
- modules/nf-core/foldmason/easymsa/main.nf
- modules/nf-core/foldmason/easymsa/tests/main.nf.test.snap
Add a module for creating the database by Foldmason 
Closes #7179 
- For modules:
> Add foldmason createdb

- modules/nf-core/megahit/main.nf
MEGAHIT only accepts comma separated list when there is n > 1 files into any given input flag
Closes #XXX 
- For modules:
> MEGAHIT: fix single-end input

- modules/nf-core/ngsbits/samplegender/environment.yml
- modules/nf-core/ngsbits/samplegender/main.nf
- modules/nf-core/ngsbits/samplegender/meta.yml
- modules/nf-core/ngsbits/samplegender/tests/main.nf.test
- modules/nf-core/ngsbits/samplegender/tests/main.nf.test.snap
> bump ngsbits

- modules/nf-core/clustalo/align/main.nf
Closes #XXX 
- For modules:
In profile mode, Clustal Omega sometimes writes warning messages to standard out which ruins the output file as it's not recognizable fasta any more. I fixed this by writing the output with `-o` instead of `>`.
I didn't add any test as it requires quite a bit of new test data. I did test the updated module on my own test case however.
> Correct non-gzipped output from clustalo/align

- modules/nf-core/busco/busco/main.nf
If BUSCO fails for all inputs, does not create `busco_sequences` directories.
Closes #XXX 
- For modules:
> Make busco/busco `seq_dir` output optional

- modules/nf-core/vcf2db/environment.yml
- modules/nf-core/vcf2db/main.nf
> fix vcf2db: add missing dependencies

- modules/nf-core/busco/busco/main.nf
- modules/nf-core/busco/busco/meta.yml
- modules/nf-core/busco/busco/tests/main.nf.test
- modules/nf-core/busco/busco/tests/main.nf.test.snap
- modules/nf-core/busco/generateplot/environment.yml
- modules/nf-core/busco/generateplot/main.nf
- modules/nf-core/busco/generateplot/tests/main.nf.test.snap
- subworkflows/nf-core/fasta_gxf_busco_plot/tests/main.nf.test.snap
This PR
- Adds downloaded BUSCO lineages as an output.
- Updates BUSCO version in busco/generateplot
- For modules:
> Add busco downloads as output

- subworkflows/nf-core/bam_dedup_stats_samtools_umitools/tests/main.nf.test.snap
- subworkflows/nf-core/fastq_qc_trim_filter_setstrandedness/main.nf
- subworkflows/nf-core/fastq_qc_trim_filter_setstrandedness/meta.yml
- subworkflows/nf-core/fastq_qc_trim_filter_setstrandedness/tests/main.nf.test
This fixes an issue in `fastq_qc_trim_filter_setstrandedness` inherited from its origin in nf-core/rnaseq. See https://github.com/nf-core/rnaseq/issues/1452 for detail.
Closes #XXX 
- For modules:
> Fix fastp merge issue with subworkflow

- modules/nf-core/trimgalore/main.nf
- modules/nf-core/trimgalore/meta.yml
- modules/nf-core/trimgalore/tests/main.nf.test
- modules/nf-core/trimgalore/tests/main.nf.test.snap
- modules/nf-core/trimgalore/tests/nextflow.config
In order to fix the linked issue, we need to constrain the output to the `reads` channel so that it can't also catch the 'unpaired'.
Note: thinking about it, I'm unsure if the catching of unpaired reads in the reads channel was intentional. I'll consult @FelixKrueger .
Closes #7268
- For modules:
> Fix unpaired outputs from trimgalore

- modules/nf-core/bcftools/consensus/main.nf
- modules/nf-core/bcftools/consensus/tests/main.nf.test.snap
This PR adds a stub section to the module (which is somehow missing from https://github.com/nf-core/modules/pull/6219) and updates the test snapshot.
- For modules:
> added stub section and updated test

- .github/workflows/lint.yml
This PR should fix those CI runs where it tries to lint the templates directory of a module:
https://github.com/nf-core/modules/actions/runs/12707914180/job/35423804348?pr=6907
https://github.com/nf-core/modules/actions/runs/12671121539/job/35312247763
https://github.com/nf-core/modules/actions/runs/12671121539/job/35312255127
Closes #XXX 
- For modules:
> fix linting of template directory

- .github/workflows/lint.yml
- .github/workflows/nf-test.yml
- .github/workflows/pytest-workflow.yml
Some CI jobs are sent to offline self-hosted runners. Switching to GitHub runners until the issue is solved
> run CI on github runners until self-hosted issues are solved 😢 

- modules/nf-core/seqkit/fx2tab/environment.yml
- modules/nf-core/seqkit/fx2tab/main.nf
- modules/nf-core/seqkit/fx2tab/tests/main.nf.test.snap
- modules/nf-core/seqkit/tab2fx/environment.yml
- modules/nf-core/seqkit/tab2fx/main.nf
- modules/nf-core/seqkit/tab2fx/tests/main.nf.test.snap
Note this only updates `seqkit` in modules I am author of; I will try to update the other ones separately.
Closes #XXX 
- For modules:
> Update seqkit to version 2.9.0

- modules/nf-core/mmseqs/cluster/environment.yml
- modules/nf-core/mmseqs/cluster/main.nf
- modules/nf-core/mmseqs/cluster/tests/main.nf.test.snap
- modules/nf-core/mmseqs/createdb/environment.yml
- modules/nf-core/mmseqs/createdb/main.nf
- modules/nf-core/mmseqs/createdb/tests/main.nf.test.snap
- modules/nf-core/mmseqs/createindex/environment.yml
- modules/nf-core/mmseqs/createindex/main.nf
- modules/nf-core/mmseqs/createindex/tests/main.nf.test.snap
- modules/nf-core/mmseqs/createtsv/environment.yml
- modules/nf-core/mmseqs/createtsv/main.nf
- modules/nf-core/mmseqs/createtsv/tests/main.nf.test.snap
- modules/nf-core/mmseqs/databases/environment.yml
- modules/nf-core/mmseqs/databases/main.nf
- modules/nf-core/mmseqs/databases/tests/main.nf.test.snap
- modules/nf-core/mmseqs/easysearch/environment.yml
- modules/nf-core/mmseqs/easysearch/main.nf
- modules/nf-core/mmseqs/easysearch/tests/main.nf.test.snap
- modules/nf-core/mmseqs/linclust/environment.yml
- modules/nf-core/mmseqs/linclust/main.nf
- modules/nf-core/mmseqs/linclust/tests/main.nf.test.snap
- modules/nf-core/mmseqs/search/environment.yml
- modules/nf-core/mmseqs/search/main.nf
- modules/nf-core/mmseqs/search/tests/main.nf.test.snap
- modules/nf-core/mmseqs/taxonomy/environment.yml
- modules/nf-core/mmseqs/taxonomy/main.nf
- modules/nf-core/mmseqs/taxonomy/tests/main.nf.test.snap
- modules/nf-core/mmseqs/tsv2exprofiledb/environment.yml
- modules/nf-core/mmseqs/tsv2exprofiledb/main.nf
- modules/nf-core/mmseqs/tsv2exprofiledb/tests/main.nf.test.snap
> Update all mmseqs modules to version 17

- modules/nf-core/vcfanno/environment.yml
- modules/nf-core/vcfanno/main.nf
- modules/nf-core/vcfanno/meta.yml
- modules/nf-core/vcfanno/tests/main.nf.test.snap
> update vcfanno output

- modules/nf-core/taxonkit/lineage/meta.yml
This should fix a catch 22 we're having with #metatdenovo.
- For modules:
> Run prettier on taxonkit/lineage/meta.yml

- .pre-commit-config.yaml
- **style: Add sort-simple-yaml**
- **style: Add yaml type**
- **style: Change comments to name of pre-commit hooks**
- **style: Add validation for environment.ymls**
Also validates our new GitHub action that lives in the repo.
> Add pre-commit hook to validate environment.ymls

- modules/nf-core/last/train/main.nf
- modules/nf-core/last/train/tests/main.nf.test.snap
Here is the long story:
Escape sequences for newline and tab in a shell `tr` command were not escaped in the script section of the module, causing them to be expanded in `.command.sh`.
This did not prevent `tr` from doing its job, but this caused the lines in the script to be indented, like this:
```
cat <<-END_VERSIONS > versions.yml
"NFCORE_PAIRGENOMEALIGN:PAIRGENOMEALIGN:PAIRALIGN_M2M:ALIGNMENT_TRAIN":
last: $(lastdb --version | sed 's/lastdb //')
END_VERSIONS
```
The indentation broke the herescript, but did not cause the module to fail.
Therefore, the `versions.yml` file contained one extra line with
`    END_VERSIONS` in it.  This crashes the pipelines that collect the
version numbers, but this was not noticed because `last/train` is always
used with other `last/` submodules, and I …
> Fix broken versions.yml file in last/train.

- .github/scripts/conda_env_sorter.py
- .pre-commit-config.yaml
- modules/nf-core/basicpy/environment.yml
- modules/nf-core/bowtie/align/environment.yml
- modules/nf-core/cellrangeratac/count/environment.yml
- modules/nf-core/cellrangeratac/mkfastq/environment.yml
- modules/nf-core/cellrangeratac/mkref/environment.yml
- modules/nf-core/ensemblvep/environment.yml
- modules/nf-core/fastk/histex/environment.yml
- modules/nf-core/fastk/merge/environment.yml
- modules/nf-core/fcs/fcsgx/environment.yml
- modules/nf-core/gatk4/variantstotable/environment.yml
- modules/nf-core/genescopefk/environment.yml
- modules/nf-core/hlala/preparegraph/environment.yml
- modules/nf-core/ilastik/multicut/environment.yml
- modules/nf-core/ilastik/pixelclassification/environment.yml
- modules/nf-core/merquryfk/katcomp/environment.yml
- modules/nf-core/merquryfk/katgc/environment.yml
- modules/nf-core/regtools/junctionsextract/environment.yml
- modules/nf-core/snpeff/environment.yml
- modules/nf-core/trgt/merge/environment.yml
- modules/nf-core/trgt/plot/environment.yml
- modules/nf-core/universc/environment.yml
This fixes an issue with the Seqera containers naming.
The Seqera containers site doesn't care about the context of what module the
image is for. It just sorts the dependencies.
This avoids having multiple containers with a bunch of different names.
Should probably handle that on the wave-cli side.
> style: Sort environment.yml dependencies

- modules/nf-core/last/dotplot/main.nf
- modules/nf-core/last/dotplot/meta.yml
- modules/nf-core/last/dotplot/tests/main.nf.test
- modules/nf-core/last/dotplot/tests/main.nf.test.snap
This uses the `maf-filter` tool distributed together with `last-dotplot` in the LAST suite.
The genome alignments that are plotted can be very large, even after the filtering step.  Therefore I implemented it with a pipe command rather than creating a separate module, which would consume a lot of disk space.
- For modules:
> Optional filtering of the alignments input to `last/dotplot`.

- modules/nf-core/mafft/guidetree/main.nf
- modules/nf-core/mafft/guidetree/tests/main.nf.test.snap
MAFFT adds some weird prefix, this line removes it. Without ^ it was removing also stuff that was not the prefix.
> fix tiny thing

- modules/nf-core/ampcombi2/parsetables/main.nf
This changes all output files per sample created by ampcombi2/parsetables to 'Optional' to allow for empty sample files in case of no AMPs detected. Which is creating a problem in nf-core/funcscan  https://github.com/nf-core/funcscan/issues/444
- For modules:
> Fix ampcombi2/parsetables output declarations

- modules/nf-core/cellpose/main.nf
This PR adds environment variables to limit the amount of cpu that Cellpose can access. Currently, the Pytorch implementation of Cellpose doesn't have guardrails and will greedily use all the cpus available, which can cause to performance issues on executors like AWS batch.
- For modules:
> Add cpu limit for Pytorch to cellpose.

- modules/nf-core/tcoffee/align/main.nf
> Update Docker container tcoffee (was wrong before)

- modules/nf-core/csvtk/concat/environment.yml
- modules/nf-core/csvtk/join/environment.yml
- modules/nf-core/csvtk/split/environment.yml
- modules/nf-core/mafft/align/environment.yml
- modules/nf-core/mafft/guidetree/environment.yml
Because now there is ane entry of csvkt and mafft in conda-forge, it will throw an error becuse the channels order in environment.yml is inverted compared to what we state in the dependencies:
I want the bioconda entry of mafft so bioconda needs to be first in the channels. 
- For modules:
> Update conda channels priority in csvtk and mafft

- modules/nf-core/hmmer/hmmpress/environment.yml
- modules/nf-core/hmmer/hmmpress/main.nf
- modules/nf-core/hmmer/hmmpress/meta.yml
- modules/nf-core/hmmer/hmmpress/tests/main.nf.test
- modules/nf-core/hmmer/hmmpress/tests/main.nf.test.snap
- For modules:
PR adds new tool hmmpress from HMMER package. It indexes and compressed hmm flatfiles to prepare input database for hmmscan. 
Anticipating possible quesstions about pattern of the input file in meta.yml
The input file is supposed to be `*.hmm`, but file can have no extension for better looking output names
Even in the manual author suggests using input filename without extension:
> **Step 2: compress and index the flatfile with hmmpress**
> hmmscan has to read a lot of profiles in a hurry, and HMMER’s text
> flatfiles are bulky. To accelerate this, hmmscan depends on binary compression and indexing of the flatfiles. First you compress and index
> your profile database with the …
> new module: `hmmer/hmmpress`

- modules/nf-core/verifybamid/verifybamid2/main.nf
single quotes cause ${meta.id} to be evaluated as a string literal rather than a variable
PR checklist skipped as this is a minor change not requiring tests.
> fixing tag in verifybamid2 module

- modules/nf-core/calder2/main.nf
single quotes cause $meta.id to be evaluated as a string literal rather than a variable. 
Relates to https://github.com/nf-core/modules/pull/7734
checklist skipped as this is a minimal syntax edit
> fixing tag in calder2 module

- modules/nf-core/ngscheckmate/fastq/environment.yml
- modules/nf-core/ngscheckmate/fastq/main.nf
- modules/nf-core/ngscheckmate/ncm/environment.yml
- modules/nf-core/ngscheckmate/ncm/main.nf
- modules/nf-core/ngscheckmate/ncm/tests/main.nf.test.snap
- modules/nf-core/ngscheckmate/patterngenerator/environment.yml
- modules/nf-core/ngscheckmate/patterngenerator/main.nf
- modules/nf-core/ngscheckmate/vafncm/environment.yml
- modules/nf-core/ngscheckmate/vafncm/main.nf
- modules/nf-core/ngscheckmate/vafncm/tests/main.nf.test.snap
ngscheckmate test depends on GAWK, which I am updating here: https://github.com/nf-core/modules/pull/7738
This pins the version of bcftools in conda to the same version in the biocontainer - the test for ngscheckmate/vafncm fails with newer versions of bcftools which are pulled in by conda.
Closes #XXX 
- For modules:
> Pin bcftools in ngscheckmate conda YAML to same version as biocontainer

- modules/nf-core/galah/tests/main.nf.test
- modules/nf-core/gawk/main.nf
- modules/nf-core/gawk/meta.yml
- modules/nf-core/gawk/tests/main.nf.test
- modules/nf-core/gawk/tests/main.nf.test.snap
- modules/nf-core/ngscheckmate/fastq/tests/main.nf.test
- modules/nf-core/ngscheckmate/vafncm/tests/main.nf.test
- modules/nf-core/plink/exclude/tests/main.nf.test
- modules/nf-core/quilt/quilt/tests/main.nf.test
- subworkflows/nf-core/bam_subsampledepth_samtools/main.nf
- subworkflows/nf-core/bam_subsampledepth_samtools/tests/main.nf.test
There are a couple of handy features in awk that are not currently completely usable in the GAWK module:
- Awk file redirection: You can redirect awk output to a file using ">" within an awk program, which allows you to do handy things like split a file into multiple files. This PR adds an option to disable shell redirection, allowing use of the awk redirect without creating an empty file.
- (GNU awk specific) BEGINFILE and ENDFILE rules: GNU awk provides the [BEGINFILE and ENDFILE rules](https://www.gnu.org/software/gawk/manual/html_node/BEGINFILE_002fENDFILE.html), which work like BEGIN and END but are repeated each time a new file is read. The old method for processing gzipped input concatenated all files together in a single `zcat`, eliding the ability to use this feature on gzipped …
> Gawk: decompress files individually, and allow disabling of shell redirect

- modules/nf-core/gawk/main.nf
- modules/nf-core/gawk/meta.yml
Missed one little thing in the last PR: https://github.com/nf-core/modules/pull/7738
If you can write multiple output files, the process needs to be able to catch them!
Closes #XXX 
- For modules:
> GAWK: Fix output specification

- modules/nf-core/splitubam/main.nf
- modules/nf-core/splitubam/tests/main.nf.test.snap
The newline caused `END_VERSIONS` to end up in versions.yml failing stub runs within pipelines. 
Closes #XXX 
- For modules:
> Fix splitubam stub

- modules/nf-core/bwa/index/main.nf
- modules/nf-core/bwamem2/index/main.nf
Kept having bwamem2 index tasks that ran forever and failed. 
Updated bwamem2 to use 28.B of memory per byte of fasta. Issue for reference: https://github.com/bwa-mem2/bwa-mem2/issues/9
Also tracked down the required memory for bwa index while I was at it. Doesn't seem to fail because most of the genome requirements are under the necessary memory.
Not the first place where people have run into this https://github.com/nf-core/modules/pull/6628
> Set BWA and bwamem2 index memory dynamically

- modules/nf-core/tabix/bgzip/main.nf
- modules/nf-core/tabix/bgzip/meta.yml
The regular expressions to detect arguments in line 29 were not working when multiple arguments were passed  (e.g. `-r -i`). This is because `.matches()` checks for matches to the entire string, not just a match to a part. Instead of updating the regex, I found it easier to split by spaces and check for arguments that way. 
Also, the name of the `gzi` output is not always `${output}.gzi` (e.g. if the `-I` parameter is used), so I changed that to look for any `.gzi` file.
- For modules:
> Update tabix/bgzip to make index file parameter detection more robust

- modules/nf-core/gatk4/variantfiltration/main.nf
- modules/nf-core/gatk4/variantfiltration/meta.yml
- modules/nf-core/gatk4/variantfiltration/tests/main.nf.test
- modules/nf-core/gatk4/variantfiltration/tests/main.nf.test.snap
- modules/nf-core/tabix/bgzip/main.nf
- modules/nf-core/tabix/bgzip/meta.yml
This allows for the use of compressed reference genome files, but does introduce an extra argument, so will break existing pipelines unfortunately. However, the extra parameter is optional it is an easy fix to add `, []` to fix any affected pipelines. I can do a search for use of the module in nf-core pipeline and open a PR to fix this if that would be helpful.
Resolves #3621 and #3622
- For modules:
> Allow for gziped reference files in gatk4/variantfiltration

- modules/nf-core/graphtyper/vcfconcatenate/environment.yml
- modules/nf-core/graphtyper/vcfconcatenate/main.nf
- modules/nf-core/graphtyper/vcfconcatenate/meta.yml
- modules/nf-core/graphtyper/vcfconcatenate/tests/main.nf.test
- modules/nf-core/graphtyper/vcfconcatenate/tests/main.nf.test.snap
For very large datasets (>300 samples) the number of VCFs produced by `graphtyper/genotype` can be so many that the shell cannot execute the command. This adds batching to avoid this error but does not change the input or output. This also updates the conda/docker dependencies.
> Update `graphtyper/vcfconcatenate`: Add batching to avoid long command line error

- modules/nf-core/bedtools/shuffle/environment.yml
- modules/nf-core/bedtools/shuffle/main.nf
- modules/nf-core/bedtools/shuffle/meta.yml
- modules/nf-core/bedtools/shuffle/tests/main.nf.test
- modules/nf-core/bedtools/shuffle/tests/main.nf.test.snap
- modules/nf-core/bedtools/shuffle/tests/nextflow.config
> Add bedtools/shuffle module

- modules/nf-core/seqtk/sample/main.nf
While reviewing a PR pulling down the seqtk sample module, we noticed a regex in some of the argument parsing logic that could cause troubles by being too inspecific.
It is on [this line](https://github.com/nf-core/modules/blob/7f88aae/modules/nf-core/seqtk/sample/main.nf#L23)
I have tested the current pattern against a number of imaginary contents of the arg variable in the `nextflow console`, and one can see that the pattern:
1. Misses cases where there is a space between `-s` and the number.
2. Erroneously matches against filenames containing `-s[0-9]` as part of the filename.
With the fixed regex, that adds a space before the `-s` flag, and an optional space after it, both of these are fixed:
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite …
> Make arg parsing regex in seaqtk sample more specific avoiding spurious matches

- modules/nf-core/cellrangeratac/mkfastq/main.nf
- Changed from using `touch` to `echo "" | gzip > .gz` to create `.gz` file in stub
Closes #7899 
- For modules:
> Fixing cellrangeratac/mkfastq stub gz

- modules/nf-core/multiqc/environment.yml
- modules/nf-core/multiqc/main.nf
- modules/nf-core/multiqc/tests/main.nf.test.snap
Update MultiQC to latest version
Fixes nf-core/seqinspector#102
- For modules:
> Bump multiqc to 1.28

- modules/nf-core/deeptools/bamcoverage/main.nf
- modules/nf-core/deeptools/bamcoverage/tests/main.nf.test.snap
Make it return `prefix.extension` to be consistent with what is expected from the actual run
- For modules:
> deeptools_bamcoverage - Minor fix to stub script

- modules/nf-core/seqkit/concat/main.nf
- modules/nf-core/seqkit/seq/main.nf
- modules/nf-core/seqkit/stats/main.nf
- modules/nf-core/seqkit/translate/main.nf
and Nextflow extension language server autformatting - no other changes!
Closes #XXX 
- For modules:
> Add threads parameter for all seqkit modules missing 

- modules/nf-core/mindagap/duplicatefinder/environment.yml
- modules/nf-core/mindagap/duplicatefinder/main.nf
- modules/nf-core/mindagap/duplicatefinder/tests/main.nf.test
- modules/nf-core/mindagap/duplicatefinder/tests/main.nf.test.snap
- modules/nf-core/mindagap/mindagap/main.nf
- modules/nf-core/mindagap/mindagap/tests/main.nf.test
- modules/nf-core/mindagap/mindagap/tests/main.nf.test.snap
In this PR I've:
* added a stub section to MINDAGAP/DUPLICATEFINDER
* updated tests for both MINDAGAP/DUPLICATEFINDER and MINDAGAP/MINDAGAP modules to use `params.modules_testdata_base_path`
* fixed the numpy version for duplicatefinder in the env because a newer version was causing the conda outputs to not match 
- For modules:
> Mindagap stub and test updates

- modules/nf-core/bandage/image/main.nf
- modules/nf-core/bandage/image/tests/main.nf.test.snap
While testing the updated module on `nf-core/viralrecon`, I encountered a Nextflow syntax error related to the `versions.yml` generation. Upon inspection, I noticed that the version command being executed was:
```bash
docker run -i --cpu-shares 2048 --memory 12288m \
-e "NXF_TASK_WORKDIR" \
-e "NXF_DEBUG=${NXF_DEBUG:=0}" \
-v /home/smonzon/Documents/desarrollo/viralrecon:/home/smonzon/Documents/desarrollo/viralrecon \
-w $PWD -u $(id -u):$(id -g) \
quay.io/biocontainers/bandage:0.9.0--h9948957_0 \
Bandage --version
```
This led to the following error output:
```
qt.qpa.xcb: could not connect to display
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized.
```
The issue …
> fixed bug in bandage/image module, wrong versions.yml outputted

- subworkflows/nf-core/fastq_qc_trim_filter_setstrandedness/main.nf
#7881 was half-baked, this is the fix. This step needs to both use and write the ch_filtered_reads channel.
Closes #XXX 
- For modules:
> Fix to rnaseq preprocessing linting fix

- modules/nf-core/gtdbtk/classifywf/main.nf
In doing some (slightly odd) things to my locally patched version of this module, I found a couple of sources of potential errors.
- Quote pplacer_scratch variable to avoid `.command.sh: line 3: [: !=: unary operator expected` warning
- Update Biocontainer to latest revision
- Update version string handling to redirect warnings to `/dev/null`, as these end up in the versions.yml file and break downstream processing
@jfy133 sorry for finding these right after your last PR 🤦‍♂️
Waiting for a local test to finish before merging
Closes #XXX 
- For modules:
> Update GTDB-TK: Update container version and fix a couple of error sources [do not merge - waiting on local test]

- modules/nf-core/gtdbtk/classifywf/main.nf
Tested locally, works
Closes #XXX 
- For modules:
> Fix errant bash comment in gtdbtk/classifywf

- modules/nf-core/fusioncatcher/fusioncatcher/environment.yml
- modules/nf-core/fusioncatcher/fusioncatcher/main.nf
- modules/nf-core/fusioncatcher/fusioncatcher/meta.yml
- modules/nf-core/fusioncatcher/fusioncatcher/tests/main.nf.test
- modules/nf-core/fusioncatcher/fusioncatcher/tests/main.nf.test.snap
> new module: fusioncatcher/fusioncatcher

- modules/nf-core/vsearch/usearchglobal/main.nf
The `switch` block in this module doesnt follow nextflow's _strict syntax_, the block is replaced here with if/else to make the module future proof.
- For modules:
> Update vsearch/usearchglobal to strict syntax

- modules/nf-core/krakenuniq/preloadedkrakenuniq/main.nf
The `args` argument passes additional arguments to krakenuniq from `task.ext.args`.  Placing this argument last on the command line, and in particular, after `--preload-size $ram_chunk_size` allows this option to be overridden through the `task.ext.args`.
This change was suggested [here](https://github.com/nf-core/taxprofiler/issues/603).  In the context of [nf-core/taxprofiler](https://github.com/nf-core/taxprofiler), this PR enables the `ram_chunk_size` option to be passed in the input `database.csv` file.  Krakenuniq can be run: multiple times with a single database, with different `ram_chunk_size` values;  as suggested by @jfy133, using a different value of `ram_chunk_size` with each database.
Closes #XXX 
- Ensure …
> Move extended arguments to end of krakenuniq command line.

- modules/nf-core/nanocomp/environment.yml
Only one `:` instead of two - not sure how this made it in!
Removed the `bioconda::` prefix entirely, as I don't think it's needed.
Used in the scnanoseq pipeline.
Closes #XXX 
- For modules:
> Fix typo in conda environment.yml

- modules/nf-core/links/tests/main.nf.test
- modules/nf-core/links/tests/main.nf.test.snap
Following [some discussion on slack](https://nfcore.slack.com/archives/C02L5UB4Y9G/p1745578136387789), `scaffolding/` should be removed from `test-datasets/data/genomics/`. This module now uses sarscov2 data for testing.
> change links test-data to sarscov

- modules/nf-core/mlst/tests/main.nf.test
- modules/nf-core/mlst/tests/main.nf.test.snap
This PR fixes failing tests for MLST by updating to a new input file. The previous file had been [deleted from the test-datasets repository](https://github.com/nf-core/test-datasets/commit/e3b282c2c401e28117ccb8ce17eadcd51aaaa4ae).
Closes #8152 
- [ x ] This comment contains a description of changes (with reason).
- [ x ] If you've fixed a bug or added code that should be tested, add tests!
- For modules:
- [ x ] `nf-core modules test <MODULE> --profile docker`
- [ x ] `nf-core modules test <MODULE> --profile singularity`
- [ x ] `nf-core modules test <MODULE> --profile conda`
> Update files for MLST tests

- subworkflows/nf-core/bam_markduplicates_picard/main.nf
This pull request updates the input channel definitions in the `BAM_MARKDUPLICATES_PICARD` workflow to include metadata for the `ch_fasta` and `ch_fai` channels. 
* [`subworkflows/nf-core/bam_markduplicates_picard/main.nf`](diffhunk://#diff-f860eca129d5e81ddd4fe2c0d56a7c3a8eae51d9beb2d78e944f636041f651b3L13-R14): Modified the `ch_fasta` and `ch_fai` channels to include `val(meta)` in addition to `path(fasta)` and `path(fai)` respectively. This ensures metadata is passed along with the file paths.
- For modules:
> Update BAM_MARKDUPLICATES_PICARD take docs

- modules/nf-core/samtools/bgzip/main.nf
- modules/nf-core/samtools/bgzip/tests/main.nf.test
- modules/nf-core/samtools/bgzip/tests/main.nf.test.snap
We know that the input is always a FASTA file.  This fix makes sure that the output name ends in `fasta.gz` without the user having to change the prefix or the meta.id.
- For modules:
> `samtools/bgzip`: default to `fasta.gz` as file suffix.

- modules/nf-core/bcftools/norm/main.nf
This PR updates the bcftools norm stub section to write the index that would actually be written by the tool.
For example, even if you have `--write-index=tbi`, the tool will output a csi index if you have `--output-type b` or `--output-type u`. 
Closes #XXX 
- For modules:
> Fix bcftools norm stub

- modules/nf-core/bcftools/concat/main.nf
- modules/nf-core/bcftools/concat/tests/main.nf.test
- modules/nf-core/bcftools/concat/tests/main.nf.test.snap
- subworkflows/nf-core/vcf_annotate_ensemblvep_snpeff/tests/main.nf.test.snap
Ensure bcftools concatenation always occurs in the same order, no matter what order the vcf files arrive in the channel.
> Ensure concatenation is always in the same order

- modules/nf-core/catpack/bins/main.nf
- modules/nf-core/catpack/bins/meta.yml
- modules/nf-core/catpack/bins/tests/main.nf.test
- modules/nf-core/catpack/summarise/tests/main.nf.test
This PR exposes the parameter `--bin_suffix` / `-s` as input in catpack/bins.
This parameter is used when the `bins` parameter is a directory. The application default (`.fna`) it's not suitable for common binning tools, which generates the bin files with `.fa` extension.
Closes #XXX 
- For modules:
> catpack/bins: Add bin_suffix as input

- subworkflows/nf-core/bam_dedup_umi/main.nf
Genome BAM deduplication log (`UMI_DEDUP_GENOME.out.deduplog`) is being reused for transcriptome deduplication, leading to a duplicate log in `ch_dedup_log` and input file name collisions downstream.
> Fix genome BAM dedup log reused for transcriptome dedup

- modules/nf-core/last/split/main.nf
- modules/nf-core/last/split/meta.yml
- modules/nf-core/last/split/tests/main.nf.test.snap
I am sorry @mashehu; I forgot that `last/split` also computes identity scores.  Can I ask you for a quick check on this one too?  :bow: The AWK code is identical to the one in PR #8480 after I applied your suggestions.
- For modules:
> Also compute ungapped percent identity scores in `last/split`.

- modules/nf-core/catpack/download/main.nf
Adds a missing line break to the command.
- For modules:
> Fix catpack/download command

- modules/nf-core/gatk4/baserecalibrator/meta.yml
Closes #XXX  
In the module, the inputs, known_sites and known_sites_tbi, are indicated as optional. However, according to the GATK4 tool manual these inputs are required.
> Update meta.yml input optional

- modules/nf-core/catpack/download/main.nf
- modules/nf-core/catpack/download/meta.yml
- modules/nf-core/catpack/download/tests/main.nf.test.snap
Exposes individual output files generated by `catpack/download` to improve integration with `catpack/prepare`, which expects each input file to be separate.
- For modules:
> Improve catpack/download output structure

- subworkflows/nf-core/fastq_trim_fastp_fastqc/meta.yml
This just corrects a typo in the meta.yml. the input `val_discard_trimmed_pass` was called `val_discard_trimmed`. I also re-ordered it to match the main.nf.
> make the meta.yml match the name and order of the main.nf input

- subworkflows/nf-core/fastq_fastqc_umitools_trimgalore/main.nf
This PR updates the `getTrimGaloreReadsAfterFiltering` function in  `FASTQ_FASTQC_UMITOOLS_TRIMGALORE` to correctly parse the number of reads removed due to being shorter than the minimum length cutoff in TrimGalore logs.
The original regex used to extract the number of filtered reads expected exactly one standard space after the colon in the line. However, in actual TrimGalore logs, the whitespace after the colon can be a tab or multiple/non-standard spaces, which caused the regex to fail silently. As a result, filtered_reads was not matched, and the function returned the total number of reads processed — giving a misleading count of reads that passed filtering.
Updated the regex to:
`/shorter than the length cutoff[^:]+:\s*([\d\.]+)/`
This keeps the original colon handling but changes …
> update regex in `FASTQ_FASTQC_UMITOOLS_TRIMGALORE` subworkflow, closes #8576

- .github/workflows/nf-test.yml
Until we can work out a better "skip" if the build is failing mechanism.
Currently, all of the tests that fail are resulting in a large number of "failed" build requests on the wave side, instead of just passing an already made container.
> ci: Turn arm64 tests off

- modules/nf-core/rtgtools/format/meta.yml
- modules/nf-core/rtgtools/pedfilter/meta.yml
- modules/nf-core/rtgtools/rocplot/meta.yml
- modules/nf-core/rtgtools/vcfeval/meta.yml
Changed `documentation` links in `meta.yml` files to point to more informative pages in the [rtg tools documentation site](https://realtimegenomics.github.io/rtg-tools/index.html) rather than the [github page](https://github.com/RealTimeGenomics/rtg-tools)
- rocplot
- pedfilter
- format
- vcfeval
part of:
- #7995
- #7996
- #7997
- #7998
- For modules:
> Update the documentation links in meta.yml files for rtg tools

- modules/nf-core/nanoq/main.nf
- modules/nf-core/nanoq/meta.yml
Fix the output path of the process.
Currently, `*_filtered` is hardcoded. If the prefix is configured to something else, the output file it not matched.
- For modules:
> nanoq: fix output path

- modules/nf-core/doubletdetection/environment.yml
- modules/nf-core/doubletdetection/main.nf
- modules/nf-core/doubletdetection/templates/doubletdetection.py
- modules/nf-core/doubletdetection/tests/main.nf.test
- modules/nf-core/doubletdetection/tests/main.nf.test.snap
This updates the tool version, adds the pyyaml dependency to prevent boiler plate code und switches to using smaller test data
> Update doubletdetection module

- modules/nf-core/deacon/index/environment.yml
- modules/nf-core/deacon/index/main.nf
- modules/nf-core/deacon/index/meta.yml
- modules/nf-core/deacon/index/tests/main.nf.test
- modules/nf-core/deacon/index/tests/main.nf.test.snap
The container seems to have issues on apple silicon, so I tested this locally using conda.
- For modules:
> Add the deacon/index tool.

- modules/nf-core/parabricks/minimap2/main.nf
- modules/nf-core/parabricks/minimap2/meta.yml
- modules/nf-core/parabricks/minimap2/tests/main.nf.test
- modules/nf-core/parabricks/minimap2/tests/main.nf.test.snap
- modules/nf-core/parabricks/minimap2/tests/nextflow.config
> Add parabricks-minimap2 module

- modules/meta-schema.json
Close tools issue https://github.com/nf-core/tools/issues/3444
Required for tools PR https://github.com/nf-core/tools/pull/3451
Related to website PR https://github.com/nf-core/website/issues/3041
> Add extra_args to modules meta-schema.json

- .github/skip_nf_test.json
- modules/nf-core/force/tileextent/Dockerfile
- modules/nf-core/force/tileextent/main.nf
- modules/nf-core/force/tileextent/meta.yml
- modules/nf-core/force/tileextent/tests/main.nf.test
- modules/nf-core/force/tileextent/tests/main.nf.test.snap
- modules/nf-core/force/tileextent/tests/nextflow.shp.config
Earth science module that computes a list of allowed FORCE tiles for a given datacube and geometry.
- For modules:
> Add force-tile-extent module

- modules/nf-core/force/cube/Dockerfile
Following a [discussion on Slack](https://nfcore.slack.com/archives/CJRH30T6V/p1750332391291719) we decided that Dockerfiles should hold a reference to the original images 
- For modules:
> Add original image in Dockerfile

- modules/nf-core/pydamage/filter/main.nf
Moves `args` call to before `filter` subcommand, as this is where the parameter options for [`-t` filter  parameter](https://pydamage.readthedocs.io/en/latest/CLI.html#pydamage) goes (and there are no further arguments that come [after](https://pydamage.readthedocs.io/en/latest/CLI.html#pydamage-filter)
Closes #XXX 
- For modules:
> PYDAMAGE_FILTER: Move args to compatible place

- modules/nf-core/bwameth/align/main.nf
- modules/nf-core/bwameth/index/main.nf
Closes https://github.com/nf-core/methylseq/issues/550
bwa-mem2 is supported by bwameth, but the current module container does not have the executable installed. The most recent container on biocontainers adds support for this.
> Bumping container versions

- modules/nf-core/hmmcopy/gccounter/main.nf
- modules/nf-core/hmmcopy/gccounter/tests/main.nf.test
- modules/nf-core/hmmcopy/gccounter/tests/main.nf.test.snap
- modules/nf-core/hmmcopy/generatemap/main.nf
- modules/nf-core/hmmcopy/generatemap/tests/main.nf.test
- modules/nf-core/hmmcopy/generatemap/tests/main.nf.test.snap
- modules/nf-core/hmmcopy/mapcounter/main.nf
- modules/nf-core/hmmcopy/mapcounter/tests/main.nf.test
- modules/nf-core/hmmcopy/mapcounter/tests/main.nf.test.snap
- modules/nf-core/hmmcopy/readcounter/environment.yml
- modules/nf-core/hmmcopy/readcounter/main.nf
- modules/nf-core/hmmcopy/readcounter/meta.yml
- modules/nf-core/hmmcopy/readcounter/tests/main.nf.test
- modules/nf-core/hmmcopy/readcounter/tests/main.nf.test.snap
Adding cram support in hmmcopy/readcounter. Unfortunately this seems to require making a temporary bam file, I tried streaming the input directly but that gave me an error.
Also adding stubs to the other 3 submodules while here.
> Allow cram in hmmcopy/readcounter and add stubs

- modules/nf-core/last/mafconvert/main.nf
- modules/nf-core/last/mafconvert/meta.yml
- modules/nf-core/last/mafconvert/tests/main.nf.test
Exporting the `fasta` genome file was only needed because I could not find a way to discover the path to the genome file during the module's regression tests.  However, this caused race conditions in _nf-core/pairgenomealign_ when the module would output many identical genome files to the pipeline's results folder, causing it to crash when the genome file was large.  So I spent more time thinking and found a much simpler way to access the genome file during tests…
`nf-core lint` reports that `samtools` and `last` are outdated. I will fix that in a separate PR.
- For modules:
> `last/maf-convert`: stop exporting `fasta` when converting to `cram`.

- modules/nf-core/yahs/environment.yml
- modules/nf-core/yahs/main.nf
- modules/nf-core/yahs/meta.yml
- modules/nf-core/yahs/tests/main.nf.test
- modules/nf-core/yahs/tests/main.nf.test.snap
- modules/nf-core/yahs/tests/nextflow.config
YaHS inputs are conceptually linked - the mapped hic reads correspond to a specific fasta file - so I've put everything in a single input tuple. This makes it easier to run YaHS on multiple assemblies. I don't think there are any official nf-core pipelines using this module yet so hopefully this isn't too troubling.
Also adds a stub test as I noticed that was missing, and moves the args into a param.
Closes #XXX 
- For modules:
> Move YaHS inputs to single tuple

- modules/nf-core/bwameth/align/tests/main.nf.test
- modules/nf-core/bwameth/align/tests/main.nf.test.snap
bwameth supports bwa-mem2 but no test has been added to use bwa-mem2 indexes. This uses the recent update to bwameth/index that allows bwameth index to build bwa-mem2 indexes and generates a test bam files using them (https://github.com/nf-core/modules/pull/8838).
Requested by @mashehu in this thread: https://github.com/nf-core/modules/pull/8793
- For modules:
> Adding bwa-mem2 mode test to bwameth/align

- modules/nf-core/krakentools/combinekreports/environment.yml
- modules/nf-core/krakentools/combinekreports/main.nf
- modules/nf-core/krakentools/combinekreports/tests/main.nf.test.snap
- modules/nf-core/krakentools/extractkrakenreads/environment.yml
- modules/nf-core/krakentools/extractkrakenreads/main.nf
- modules/nf-core/krakentools/extractkrakenreads/tests/main.nf.test.snap
- modules/nf-core/krakentools/kreport2krona/environment.yml
- modules/nf-core/krakentools/kreport2krona/main.nf
- modules/nf-core/krakentools/kreport2krona/tests/main.nf.test.snap
- subworkflows/nf-core/fastq_extract_kraken_krakentools/tests/main.nf.test.snap
- version bump in all modules
- updated snapshot files in all modules and subwfs using krakentools
- makes #8851 obsolete
- For modules:
> update krakentools version 1.2.1

- subworkflows/nf-core/fasta_index_bismark_bwameth/main.nf
- subworkflows/nf-core/fasta_index_bismark_bwameth/meta.yml
- subworkflows/nf-core/fasta_index_bismark_bwameth/tests/main.nf.test
- subworkflows/nf-core/fasta_index_bismark_bwameth/tests/main.nf.test.snap
Following recent updates to bwameth modules to support bwa-mem2, support for mem2 is being added to the nf-core/methylseq pipeline. This subworkflow update allows mem2 indexes to be generated if no bwameth_index path is passed, with mem2 index tests added as well.
> Adding mem2 switch to fasta_index_bismark_bwameth subworkflow

- modules/nf-core/scanpy/hashsolo/main.nf
- modules/nf-core/scanpy/hashsolo/meta.yml
- modules/nf-core/scanpy/hashsolo/templates/hashsolo.py
- modules/nf-core/scanpy/hashsolo/tests/main.nf.test.snap
- `SCANPY_HASHSOLO.out.assignment` returned a list of `[assignment, params]` because the pattern wasn't clearly.
- This small PR removes this duplicate file pattern
> Update duplicate file pattern

- modules/nf-core/checkm2/databasedownload/main.nf
- modules/nf-core/galah/tests/nextflow.config
This PR attempts to solve the following error:
```
Server returned HTTP response code: 406 for URL: https://zenodo.org/api/records/14897628 -- Check script 'modules/nf-core/checkm2/databasedownload/main.nf' at line: 22
```
This seems to happen becase the Zenodo API expects the `application/json` content type, but `file()` doesn't set it.
The solution implemented here creates the HTTP request manually, setting the neccesary header.
- For modules:
> Fix CheckM2 database download

- .github/workflows/nf-test.yml
- modules/nf-core/scvitools/scar/environment.yml
- modules/nf-core/scvitools/scar/main.nf
- modules/nf-core/scvitools/scar/meta.yml
- modules/nf-core/scvitools/scar/templates/scar.py
- modules/nf-core/scvitools/scar/tests/main.nf.test
- modules/nf-core/scvitools/scar/tests/main.nf.test.snap
- modules/nf-core/scvitools/scar/tests/nextflow.config
- modules/nf-core/scvitools/solo/environment.yml
- modules/nf-core/scvitools/solo/main.nf
- modules/nf-core/scvitools/solo/meta.yml
- modules/nf-core/scvitools/solo/templates/solo.py
- modules/nf-core/scvitools/solo/tests/main.nf.test
- modules/nf-core/scvitools/solo/tests/main.nf.test.snap
- modules/nf-core/scvitools/solo/tests/nextflow.config
Updates scvitools tools to the latest versions, removes exotic `task.ext` fields usage, and adds more tests
> Update scvitools modules

- modules/nf-core/seq2hla/environment.yml
- modules/nf-core/seq2hla/main.nf
- modules/nf-core/seq2hla/meta.yml
- modules/nf-core/seq2hla/tests/main.nf.test
- modules/nf-core/seq2hla/tests/main.nf.test.snap
Adding the seq2HLA module to call hlatypes from RNA sequencing data
Closes #XXX 
- For modules:
> Adds seq2hla

- modules/nf-core/snapaligner/index/main.nf
- modules/nf-core/snapaligner/index/tests/main.nf.test
- modules/nf-core/snapaligner/index/tests/main.nf.test.snap
Trying to use the `path(process.out.versions[0]).yaml` on the stub test here gave:
`com.fasterxml.jackson.dataformat.yaml.snakeyaml.error.MarkedYAMLException: while scanning a quoted scalar`.
> Fix version in snapaligner/index stub

- modules/nf-core/blobtk/plot/main.nf
- modules/nf-core/blobtk/plot/tests/main.nf.test.snap
Correction to version information in blobtk_plots
A tab got introduced into the version array, which doesn't kill linting but does kill the version collection in a pipeline.
> Update to correct malformed version

- modules/nf-core/gtdbtk/classifywf/main.nf
- modules/nf-core/gtdbtk/classifywf/meta.yml
- modules/nf-core/gtdbtk/classifywf/tests/main.nf.test
- modules/nf-core/gtdbtk/gtdbtoncbimajorityvote/tests/main.nf.test
This input type has been deprecated in the latest GTDB-Tk release.
Closes #XXX 
- For modules:
> Deprecate mash_db argument in gtdbtk/classifywf

- modules/nf-core/sawfish/discover/main.nf
- modules/nf-core/sawfish/discover/meta.yml
Fix nextflow language server error: `expected_cn/cnv_exclude_regions` is already declared. 
Closes #XXX 
- For modules:
> Fix sawfish discover

- modules/nf-core/basicpy/main.nf
- modules/nf-core/basicpy/tests/main.nf.test.snap
This doesn't change the version of the wrapped basicpy package itself, rather it just points to a new, rebuilt container image with updated dependencies to handle reading a wider variety of image file formats.
Required for nf-core/mcmicro#84.
- For modules:
> Bump basicpy container revision
