- modules/nf-core/cnvkit/batch/main.nf
- modules/nf-core/cnvkit/batch/meta.yml
- modules/nf-core/gatk4/annotateintervals/main.nf
- modules/nf-core/gatk4/annotateintervals/meta.yml
- modules/nf-core/gatk4/filterintervals/main.nf
- modules/nf-core/gatk4/filterintervals/meta.yml
- tests/modules/nf-core/cnvkit/batch/main.nf
- tests/modules/nf-core/gatk4/annotateintervals/main.nf
- tests/modules/nf-core/gatk4/filterintervals/main.nf
This PR adds extra meta fields to the following modules,
1. gatk4/annotateintervals
2. gatk4/filterintervals
3. cnvkit/batch
> update GATK's annotateintervals and filterintervals, and CNVkit's batch with extra meta fields

- modules/nf-core/gtdbtk/classifywf/main.nf
- modules/nf-core/gtdbtk/classifywf/meta.yml
- tests/modules/nf-core/gtdbtk/classifywf/main.nf
- tests/modules/nf-core/gtdbtk/classifywf/test.yml
Update to the latest GTDB-tk version.
Notable changes: 
- output files are in subdirectories (`identify`, `classify`) are are now `mv` to the current working directory.
- The latest version can make use of mash database to speedup ANI placement. See here: https://ecogenomics.github.io/GTDBTk/commands/classify_wf.html#mutually%20exclusive%20required%20arguments_repeat1
- 
> update GTDB-tk to 2.3.2

- modules/nf-core/taxpasta/merge/main.nf
- modules/nf-core/taxpasta/standardise/main.nf
Update the version of `taxpasta` into `0.6.0`
> Update taxpasta version to 0.6.0

- modules/nf-core/metaphlan/mergemetaphlantables/main.nf
> Update the biocontainer link

- modules/nf-core/shinyngs/app/main.nf
- modules/nf-core/shinyngs/staticdifferential/main.nf
- modules/nf-core/shinyngs/staticexploratory/main.nf
- modules/nf-core/shinyngs/validatefomcomponents/main.nf
Just a bump to underlying shinyngs.
> bump shinyngs

- modules/nf-core/controlfreec/assesssignificance/main.nf
- modules/nf-core/controlfreec/freec/main.nf
- modules/nf-core/controlfreec/freec2bed/main.nf
- modules/nf-core/controlfreec/freec2circos/main.nf
- modules/nf-core/controlfreec/makegraph/main.nf
> update version controlfreec

- modules/nf-core/seqtk/seq/main.nf
- modules/nf-core/seqtk/seq/meta.yml
Closes #XXX 
- [] If you've fixed a bug or added code that should be tested, add tests!
- [] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [] If necessary, include test data in your PR.
- [] Remove all TODO statements.
- [] Emit the `versions.yml` file.
- [] Follow the naming conventions.
- [] Follow the parameters requirements.
- [] Follow the input/output options guidelines.
- [] Add a resource `label`
- [] Use BioConda and BioContainers if possible to fulfil software requirements.
- [] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd …
> Seqtk seq 1.4

- subworkflows/nf-core/initialise/main.nf
- subworkflows/nf-core/initialise/meta.yml
- tests/config/pytest_modules.yml
- tests/subworkflows/nf-core/initialise/main.nf
- tests/subworkflows/nf-core/initialise/nextflow.config
- tests/subworkflows/nf-core/initialise/nextflow_schema.json
- tests/subworkflows/nf-core/initialise/test.yml
Adds an INTIALISE subworkflow.
This could, in theory, take over many of the functions in `WorkflowMain.initialise()` and make it simpler to maintain a pipeline.
It performs the basic functions:
- Runs --version
- Runs --help
- Checks profiles
- Checks Conda channels
> Add INITIALISE subworkflow for starting nf-core pipelines

- subworkflows/nf-core/initialise/meta.yml
- subworkflows/yaml-schema.json
needed to update the json schema to allow empty components/modules
> Fix initialise linting

- modules/nf-core/cellranger/count/templates/cellranger_count.py
> Add license to cellranger count renaming script. 

- modules/nf-core/seqkit/sliding/main.nf
Adding the stub for SeqKit Sliding
> Update main.nf to include stub

- tests/modules/nf-core/blast/blastn/test.yml
- tests/modules/nf-core/blast/blastp/main.nf
- tests/modules/nf-core/blast/blastp/test.yml
- tests/modules/nf-core/blast/makeblastdb/test.yml
- tests/modules/nf-core/blast/tblastn/test.yml
> Blast - updated blastp test to use proteome instead of genome + checking versions.yml file exist for all modules of blast suite

- modules/nf-core/gatk4/markduplicates/main.nf
- modules/nf-core/stitch/main.nf
- tests/modules/nf-core/gatk4/markduplicates/main.nf
- tests/modules/nf-core/gatk4/markduplicates/test.yml
Closes https://github.com/nf-core/modules/issues/3902
> add stub to gatk4 markduplicates

- modules/nf-core/fastqc/tests/main.nf.test
- modules/nf-core/fastqc/tests/main.nf.test.snap
- nf-test.config
- tests/config/nf-test.config
> fastqc-nf-test : mv outputdir param to test file and add snapshot

- modules/nf-core/spring/decompress/main.nf
- modules/nf-core/spring/decompress/meta.yml
- tests/config/pytest_modules.yml
- tests/modules/nf-core/spring/decompress/main.nf
- tests/modules/nf-core/spring/decompress/nextflow.config
- tests/modules/nf-core/spring/decompress/test.yml
> Add spring/decompress module

- modules/nf-core/purgedups/histplot/main.nf
- modules/nf-core/purgedups/histplot/meta.yml
- tests/config/pytest_modules.yml
- tests/modules/nf-core/purgedups/histplot/main.nf
- tests/modules/nf-core/purgedups/histplot/nextflow.config
- tests/modules/nf-core/purgedups/histplot/test.yml
Adds the tool hist_plot from the purge_dups package.
Closes #3915  
> Add purgedups histplot

- modules/nf-core/umicollapse/main.nf
After some experience with this module I realise it needs the highest resources (RAM heavy)
Closes #XXX 
- [-] This comment contains a description of changes (with reason).
> update umicollapse from process_medium to process_high

- modules/nf-core/taxpasta/merge/main.nf
- modules/nf-core/taxpasta/standardise/main.nf
> update taxpasta version

- modules/nf-core/dshbio/exportsegments/main.nf
- modules/nf-core/dshbio/exportsegments/meta.yml
- modules/nf-core/dshbio/filterbed/main.nf
- modules/nf-core/dshbio/filterbed/meta.yml
- modules/nf-core/dshbio/filtergff3/main.nf
- modules/nf-core/dshbio/filtergff3/meta.yml
- modules/nf-core/dshbio/splitbed/main.nf
- modules/nf-core/dshbio/splitbed/meta.yml
- modules/nf-core/dshbio/splitgff3/main.nf
- modules/nf-core/dshbio/splitgff3/meta.yml
> Update dsh-bio modules to version 2.3

- modules/nf-core/mitohifi/findmitoreference/main.nf
- modules/nf-core/mitohifi/findmitoreference/meta.yml
- tests/modules/nf-core/mitohifi/findmitoreference/main.nf
- tests/modules/nf-core/mitohifi/findmitoreference/test.yml
The findreference module currently has optional inputs as mandatory. These are removed.
The code is updated to use the same container as mitohifi/mitohifi.
Some other small issues are also fixed.
Closes #XXX 
> Update mitohifi findreference

- modules/nf-core/emboss/revseq/main.nf
- modules/nf-core/emboss/revseq/meta.yml
- tests/config/pytest_modules.yml
- tests/modules/nf-core/emboss/revseq/main.nf
- tests/modules/nf-core/emboss/revseq/nextflow.config
- tests/modules/nf-core/emboss/revseq/test.yml
Closes #XXX 
I added the Emboos tool `revseq` that reverse complements a nucleotide sequence.
> Emboss revseq

- modules/nf-core/sratools/prefetch/tests/main.nf.test
- modules/nf-core/sratools/prefetch/tests/main.nf.test.snap
> Improve tests for sratools/prefetch

- .gitattributes
> add syntax highlighting for .nf.test scripts

- subworkflows/nf-core/initialise/main.nf
> INITIALISE subworkflow corrected scoping and parameters are made more consistent

- .github/workflows/test.yml
Gonna remove the space commit, but I think this worked.
@adamrtalbot Any thoughts on the Setup Singularity steps with the `$NXF_SINGULARITY_CACHEDIR` and what not?
Also, not sure if there are other apptainer/singularity things going on, the singularity setup action we were using just said to start using the apptainer setup action. So if anyone knows more about it, chime in!
> ci: Try setup-apptainer

- modules/nf-core/custom/dumpsoftwareversions/tests/main.nf.test
- modules/nf-core/custom/dumpsoftwareversions/tests/main.nf.test.snap
> simpler test for custom/dumpsoftwareversions

- modules/nf-core/zip/main.nf
- modules/nf-core/zip/meta.yml
- tests/config/pytest_modules.yml
- tests/modules/nf-core/zip/main.nf
- tests/modules/nf-core/zip/nextflow.config
- tests/modules/nf-core/zip/test.yml
Adds the missing 'zip' module counterpart to 'unzip'. 
> Add file zipping module

- modules/nf-core/zip/main.nf
This module is currently not doing the right thing, since symlinks aren't being resolved for the input files, and files in the output zip then just have the symlink paths. 
We can use the `-l` switch in 7z to resolve symlinks.
> Add flag to zip for following symlinks

- .github/modules.yml
- .github/workflows/test.yml
- subworkflows/nf-core/fastq_download_prefetch_fasterqdump_sratools/tests/main.nf.test
- subworkflows/nf-core/fastq_download_prefetch_fasterqdump_sratools/tests/main.nf.test.snap
- tests/config/pytest_modules.yml
> nf-test for fastq_download_prefetch_fasterqdump_sratools

- modules/nf-core/gfatools/stat/main.nf
- modules/nf-core/gfatools/stat/meta.yml
- tests/config/pytest_modules.yml
- tests/modules/nf-core/gfatools/stat/main.nf
- tests/modules/nf-core/gfatools/stat/nextflow.config
- tests/modules/nf-core/gfatools/stat/test.yml
Adds the tool GFATOOLS/STAT
Closes #3958 
> Add gfatools stat

- tests/modules/nf-core/gfastats/main.nf
- tests/modules/nf-core/gfastats/test.yml
Adds a test to GFASTATS, testing gfa to fasta conversion.
Closes #XXX 
> Add gfastats test

- modules/nf-core/custom/dumpsoftwareversions/tests/main.nf.test
- modules/nf-core/custom/sratoolsncbisettings/tests/main.nf.test
- modules/nf-core/fastqc/tests/main.nf.test
- modules/nf-core/snakemake/tests/main.nf.test
- modules/nf-core/sratools/fasterqdump/tests/main.nf.test
- modules/nf-core/sratools/prefetch/tests/main.nf.test
- modules/nf-core/sratools/prefetch/tests/main.nf.test.snap
- subworkflows/nf-core/fastq_download_prefetch_fasterqdump_sratools/tests/main.nf.test
Changes:
- nf-test uses relative import for main.nf scripts (e.g. ../main.nf)
- Every nf-test includes modules and modules_nfcore tag
> nf-test consistency enforcing

- .github/modules.yml
- subworkflows/nf-core/nfvalidation_plugin_utils/main.nf
- subworkflows/nf-core/nfvalidation_plugin_utils/meta.yml
- subworkflows/nf-core/nfvalidation_plugin_utils/tests/main.nf.test
- subworkflows/nf-core/nfvalidation_plugin_utils/tests/main.nf.test.snap
- subworkflows/nf-core/nfvalidation_plugin_utils/tests/nextflow_schema.json
- tests/subworkflows/nf-core/nfvalidationpluginutils/main.nf
- tests/subworkflows/nf-core/nfvalidationpluginutils/nextflow.config
- tests/subworkflows/nf-core/nfvalidationpluginutils/test.yml
> Add NFVALIDATION_PLUGIN_SUBWORKFLOW for starting pipeline

- .github/workflows/test.yml
- tests/config/nextflow.config
> switch test.yml to self hosted runners on AWS

- .github/workflows/test.yml
- subworkflows/nf-core/nextflowpipelineutils/tests/main.functions.nf.test
- subworkflows/nf-core/nextflowpipelineutils/tests/main.functions.nf.test.snap
- subworkflows/nf-core/nextflowpipelineutils/tests/nextflow.config
Changes:
- Use specific config for subworkflow nextflowpipelineutils so the version and data does not vary
Closes #XXX 
> nextflowpipelineutils: strict tests

- modules/nf-core/sourmash/compare/main.nf
- modules/nf-core/sourmash/gather/main.nf
- modules/nf-core/sourmash/index/main.nf
- modules/nf-core/sourmash/sketch/main.nf
- modules/nf-core/sourmash/taxannotate/main.nf
This PR updates 5 modules related with sourmash (`sourmash/compare`, `sourmash/gather`, `sourmash/index`, `sourmash/sketch`, and `sourmash/taxannotate`)
> Update `sourmash` modules to 4.8.4

- modules/nf-core/tcoffee/align/main.nf
Bumps T-Coffee to version 13.46
Closes #3995
> bump T-Coffee version

- modules/nf-core/muscle5/super5/main.nf
- modules/nf-core/muscle5/super5/meta.yml
- tests/config/pytest_modules.yml
- tests/modules/nf-core/muscle5/super5/main.nf
- tests/modules/nf-core/muscle5/super5/nextflow.config
- tests/modules/nf-core/muscle5/super5/test.yml
> added Muscle5 super5 module

- .github/CODEOWNERS
Should request a Code review from nf-test people. I have it set to "load balance" the reviews. 
We should probably recruit more people.
> Auto Request review from nf-test people on anything related to nf-test

- modules/nf-core/hisat2/align/tests/main.nf.test
- modules/nf-core/hisat2/build/tests/main.nf.test
- modules/nf-core/hisat2/extractsplicesites/tests/main.nf.test
> add missing modules tag for nf-tests

- modules/nf-core/rasusa/tests/main.nf.test
- modules/nf-core/rasusa/tests/main.nf.test.snap
- modules/nf-core/rasusa/tests/tags.yml
- tests/config/pytest_modules.yml
> Rasusa nf test

- modules/nf-core/glimpse/chunk/tests/main.nf.test
- modules/nf-core/glimpse/chunk/tests/main.nf.test.snap
- modules/nf-core/glimpse/chunk/tests/nextflow.config
- modules/nf-core/glimpse/chunk/tests/tags.yml
- tests/config/pytest_modules.yml
nf-test for glimpse_chunk, the other will follow.
Closes #XXX 
> Glimpse chunk nftest

- modules/nf-core/glimpse/ligate/tests/main.nf.test
- modules/nf-core/glimpse/ligate/tests/main.nf.test.snap
- modules/nf-core/glimpse/ligate/tests/tags.yml
- tests/config/pytest_modules.yml
Add nf-test for glimpse_ligate
Closes #XXX 
> Glimpse ligate nftest

- modules/nf-core/sourmash/sketch/tests/main.nf.test
- modules/nf-core/sourmash/sketch/tests/main.nf.test.snap
- modules/nf-core/sourmash/sketch/tests/tags.yml
- tests/config/pytest_modules.yml
nf-test for sourmash sketch
Closes #4100  
> nf-test for module sourmash/sketch

- modules/nf-core/trimgalore/tests/main.nf.test
- modules/nf-core/trimgalore/tests/main.nf.test.snap
- modules/nf-core/trimgalore/tests/tags.yml
- tests/config/pytest_modules.yml
> Feat/trimgalore nf-test

- modules/nf-core/samtools/sort/tests/main.nf.test
- modules/nf-core/samtools/sort/tests/main.nf.test.snap
- modules/nf-core/samtools/sort/tests/nextflow.config
- modules/nf-core/samtools/sort/tests/tags.yml
- tests/config/pytest_modules.yml
> nf-test migration

- modules/nf-core/shinyngs/app/main.nf
- modules/nf-core/shinyngs/staticdifferential/main.nf
- modules/nf-core/shinyngs/staticexploratory/main.nf
- modules/nf-core/shinyngs/validatefomcomponents/main.nf
> Bump shinyngs modules to pull in recent updates

- .github/CODEOWNERS
- .github/generate_codeowners.sh
> Generate codeowners

- .github/CODEOWNERS
- .github/generate_codeowners.sh
- .github/manual_CODEOWNERS
- .gitignore
- modules/nf-core/arriba/arriba/meta.yml
- modules/nf-core/fqtk/meta.yml
- modules/nf-core/sgdemux/meta.yml
Also fixes a little issue with @samfulcrum
> Make Codeowners Deterministic

- modules/nf-core/assemblyscan/tests/main.nf.test
- modules/nf-core/assemblyscan/tests/main.nf.test.snap
- modules/nf-core/assemblyscan/tests/tags.yml
- tests/config/pytest_modules.yml
add nf-test to assemblyscan
Closes #4162  
> Complete nf-test for assemblyscan

- subworkflows/nf-core/bam_sort_stats_samtools/tests/main.nf.test
- subworkflows/nf-core/bam_sort_stats_samtools/tests/main.nf.test.snap
- subworkflows/nf-core/bam_sort_stats_samtools/tests/tags.yml
- tests/config/pytest_modules.yml
> Feat/bam_sort_stats_samtools nf-test

- modules/nf-core/samtools/import/main.nf
> fix PE inputs

- modules/nf-core/chopper/tests/main.nf.test
- modules/nf-core/chopper/tests/main.nf.test.snap
- modules/nf-core/chopper/tests/tags.yml
- tests/config/pytest_modules.yml
Add nf-test to module chopper
Closes #4180 
> chopper: add nf-test

- tests/config/test_data.config
> proteome_fasta_gz test data added

- .github/workflows/fix-linting.yml
- .github/workflows/test.yml
> updated github actions dependencies

- modules/nf-core/ataqv/ataqv/environment.yml
- modules/nf-core/ataqv/mkarv/environment.yml
- modules/nf-core/rseqc/bamstat/environment.yml
- modules/nf-core/rseqc/inferexperiment/environment.yml
- modules/nf-core/rseqc/innerdistance/environment.yml
- modules/nf-core/rseqc/junctionannotation/environment.yml
- modules/nf-core/rseqc/junctionsaturation/environment.yml
- modules/nf-core/rseqc/readdistribution/environment.yml
- modules/nf-core/rseqc/readduplication/environment.yml
- modules/nf-core/rseqc/tin/environment.yml
- style: Run prettier
- style: Clean up conda package names
Follow up to https://github.com/nf-core/modules/pull/4079
> Run prettier on conda envs

- modules/nf-core/openms/idfilter/main.nf
- modules/nf-core/openms/idfilter/meta.yml
- tests/config/pytest_modules.yml
- tests/modules/nf-core/openms/idfilter/main.nf
- tests/modules/nf-core/openms/idfilter/nextflow.config
- tests/modules/nf-core/openms/idfilter/test.yml
Closes #3993 
Implements another OpenMS module [IDFilter](https://abibuilder.cs.uni-tuebingen.de/archive/openms/Documentation/nightly/html/TOPP_IDFilter.html). The module has an optional filter file as input as well as variable filter criteria (see docs). I needed to set a default filter criterion for the optional filter file.
> New module openms/idfilter

- modules/nf-core/seqkit/fx2tab/environment.yml
- modules/nf-core/seqkit/fx2tab/main.nf
> Update seqkit/fx2tab to version 2.5.1

- modules/nf-core/custom/dumpsoftwareversions/environment.yml
- modules/nf-core/custom/dumpsoftwareversions/main.nf
- modules/nf-core/custom/dumpsoftwareversions/tests/main.nf.test.snap
> update multiqc to 1.17 in custom/dumpsoftwareversions

- .github/renovate-bot.json5
- .github/renovate.json5
- modules/nf-core/bowtie2/build/environment.yml
- modules/nf-core/bowtie2/build/main.nf
- modules/nf-core/htseq/count/environment.yml
- modules/nf-core/htseq/count/main.nf
- chore(deps): Bump htseq conda env #4266
- chore(deps): Update bowtie2 conda env #4212
- ci(renovate): Assign CodeOwners to PRs
- ci(renovate): Move gitAuthor to main config
> Update missed renovate environments

- modules/nf-core/bwa/mem/environment.yml
- modules/nf-core/bwamem2/mem/environment.yml
- modules/nf-core/dragmap/align/environment.yml
- modules/nf-core/mosdepth/environment.yml
- modules/nf-core/svdb/merge/environment.yml
Should close(or atleast the conda env the mulled containers need to be bumped):
#4289
#4288
#4287
#4286
#4277
#4276
> build: Add renovate comments to conda packages

- .github/renovate.json5
- modules/nf-core/bwa/mem/environment.yml
- modules/nf-core/bwamem2/mem/environment.yml
- modules/nf-core/dragmap/align/environment.yml
- modules/nf-core/mosdepth/environment.yml
- modules/nf-core/svdb/merge/environment.yml
- ci(renovate): Remove docker hub
- ci(renovate): Update environment.yml regex
- ci(renovate): Copy regex from anaconda
- ci(renovate): Toss in pypi while we're here
- chore: Try adding :'s
- ci(renovate): Finally figured it out
For real this time.
Random links along the way:
https://github.com/anaconda/renovate-config/blob/176696853379d878a87575ba03b1b12fd29d24ac/default.json#L64-L71
https://github.com/anaconda/renovate-config/blob/176696853379d878a87575ba03b1b12fd29d24ac/docs/conda-environment.md?plain=1#L24
https://github.com/search?q=renovate%3A+datasource%3Dconda&type=code
> Fix conda and renovate

- .github/workflows/pre-commit.yml
- .pre-commit-config.yaml
- ci(renovate): Add pre-commit hook
- ci: Add a pre-commit GitHub action workflow
> Add renovate config check

- .github/renovate.json5
Don't know how this got in there...
> ci(renovate): Fix merge conflict

- tests/config/test_data.config
> test data config pdb update

- modules/nf-core/kallisto/quant/main.nf
- modules/nf-core/kallisto/quant/meta.yml
- modules/nf-core/kallisto/quant/tests/main.nf.test
- modules/nf-core/kallisto/quant/tests/single_end.config
- tests/modules/nf-core/kallisto/quant/main.nf
- tests/modules/nf-core/kallisto/quant/nextflow.config
In this PR:
- Fragment length parameters are mandatory for Kallisto in single-end, so move them to channels. 
- Put a strandedness into meta and use to determine strandedness parameters, as requested by @drpatelh , to avoid logic like [this](https://github.com/nf-core/rnaseq/blob/58bbc278ad3fd39bc0b28d63caec07ac8d83b162/conf/modules.config#L1164).
This is also consistent with the equivalent [Salmon module](https://github.com/nf-core/modules/blob/master/modules/nf-core/salmon/quant/main.nf).
Closes #XXX 
> Kallisto fragment length params to channels, strand to meta

- modules/nf-core/ensemblvep/download/environment.yml
- modules/nf-core/ensemblvep/download/meta.yml
- modules/nf-core/ensemblvep/filtervep/meta.yml
- modules/nf-core/ensemblvep/vep/environment.yml
- modules/nf-core/ensemblvep/vep/meta.yml
- modules/nf-core/multiqc/environment.yml
- modules/nf-core/multiqc/meta.yml
- modules/nf-core/sentieon/datametrics/meta.yml
- modules/nf-core/sentieon/dnamodelapply/meta.yml
- modules/nf-core/sentieon/gvcftyper/meta.yml
- modules/nf-core/sentieon/tnfilter/environment.yml
- modules/nf-core/sentieon/wgsmetrics/meta.yml
- modules/nf-core/snpeff/download/environment.yml
- modules/nf-core/snpeff/download/meta.yml
- modules/nf-core/snpeff/snpeff/environment.yml
- modules/nf-core/snpeff/snpeff/meta.yml
- tests/modules/nf-core/sentieon/dnamodelapply/main.nf
> update meta.yml files

- modules/nf-core/seqkit/fx2tab/environment.yml
- modules/nf-core/seqkit/fx2tab/main.nf
- modules/nf-core/seqkit/tab2fx/environment.yml
- modules/nf-core/seqkit/tab2fx/main.nf
> Update seqkit/tab2fx seqkit/fx2tab to version 2.6.0

- modules/nf-core/mitohifi/findmitoreference/environment.yml
- modules/nf-core/mitohifi/findmitoreference/main.nf
- tests/modules/nf-core/mitohifi/findmitoreference/main.nf
Adds meta map to mitohifi/findmitoreference.
Closes #XXX 
> Add meta map and update process label to mitohifi/findmitoreference

- modules/nf-core/mudskipper/bulk/environment.yml
- modules/nf-core/mudskipper/bulk/main.nf
- modules/nf-core/mudskipper/bulk/meta.yml
- modules/nf-core/mudskipper/index/environment.yml
- modules/nf-core/mudskipper/index/main.nf
- modules/nf-core/mudskipper/index/meta.yml
- tests/config/pytest_modules.yml
- tests/modules/nf-core/mudskipper/bulk/main.nf
- tests/modules/nf-core/mudskipper/bulk/nextflow.config
- tests/modules/nf-core/mudskipper/bulk/test.yml
- tests/modules/nf-core/mudskipper/index/main.nf
- tests/modules/nf-core/mudskipper/index/nextflow.config
- tests/modules/nf-core/mudskipper/index/test.yml
Adding tools from mudskipper
Closes #4344 
> add mudskipper/index and mudskipper/bulk

- .github/workflows/test.yml
- modules/nf-core/sratools/fasterqdump/tests/main.nf.test
- nf-test.config
> .nf-test -> nf-test

- modules/nf-core/mafft/main.nf
- modules/nf-core/mafft/meta.yml
- modules/nf-core/mafft/tests/main.nf.test
- modules/nf-core/mafft/tests/main.nf.test.snap
- modules/nf-core/mafft/tests/nextflow_addfragments.config
- modules/nf-core/mafft/tests/tags.yml
- tests/config/pytest_modules.yml
> Update MAFFT module with new arguments and tests

- modules/nf-core/sentieon/applyvarcal/environment.yml
- modules/nf-core/sentieon/applyvarcal/main.nf
- modules/nf-core/sentieon/bwaindex/environment.yml
- modules/nf-core/sentieon/bwaindex/main.nf
- modules/nf-core/sentieon/bwamem/main.nf
- modules/nf-core/sentieon/datametrics/environment.yml
- modules/nf-core/sentieon/datametrics/main.nf
- modules/nf-core/sentieon/dedup/environment.yml
- modules/nf-core/sentieon/dedup/main.nf
- modules/nf-core/sentieon/dnamodelapply/environment.yml
- modules/nf-core/sentieon/dnamodelapply/main.nf
- modules/nf-core/sentieon/dnascope/environment.yml
- modules/nf-core/sentieon/dnascope/main.nf
- modules/nf-core/sentieon/gvcftyper/environment.yml
- modules/nf-core/sentieon/gvcftyper/main.nf
- modules/nf-core/sentieon/haplotyper/environment.yml
- modules/nf-core/sentieon/haplotyper/main.nf
- modules/nf-core/sentieon/readwriter/environment.yml
- modules/nf-core/sentieon/readwriter/main.nf
- modules/nf-core/sentieon/setup.md
- modules/nf-core/sentieon/tnfilter/environment.yml
- modules/nf-core/sentieon/tnfilter/main.nf
- modules/nf-core/sentieon/tnhaplotyper2/environment.yml
- modules/nf-core/sentieon/tnhaplotyper2/main.nf
- modules/nf-core/sentieon/tnscope/environment.yml
- modules/nf-core/sentieon/tnscope/main.nf
- modules/nf-core/sentieon/varcal/environment.yml
- modules/nf-core/sentieon/varcal/main.nf
- modules/nf-core/sentieon/wgsmetrics/environment.yml
- modules/nf-core/sentieon/wgsmetrics/main.nf
> More bioconda sentieon

- modules/nf-core/rsem/calculateexpression/tests/main.nf.test
- modules/nf-core/rsem/calculateexpression/tests/main.nf.test.snap
- modules/nf-core/rsem/calculateexpression/tests/nextflow.config
- modules/nf-core/rsem/calculateexpression/tests/tags.yml
- modules/nf-core/rsem/preparereference/tests/main.nf.test
- modules/nf-core/rsem/preparereference/tests/main.nf.test.snap
- modules/nf-core/rsem/preparereference/tests/tags.yml
- tests/config/pytest_modules.yml
> add nf-tests for rsem/calculateexpression and rsem/preparereference

- modules/nf-core/salmon/index/tests/main.nf.test
- modules/nf-core/salmon/index/tests/main.nf.test.snap
- modules/nf-core/salmon/index/tests/tags.yml
- modules/nf-core/salmon/quant/tests/main.nf.test
- modules/nf-core/salmon/quant/tests/main.nf.test.snap
- modules/nf-core/salmon/quant/tests/nextflow.config
- modules/nf-core/salmon/quant/tests/tags.yml
- tests/config/pytest_modules.yml
> nf-test for salmon

- .github/workflows/test.yml
Making a new PR to follow this.
Fixes a Few issues:
- Commenting on every push
- Jobs failing when the PR comes from a fork
> Deprecation comment

- modules/nf-core/gt/gff3/environment.yml
- modules/nf-core/gt/gff3/main.nf
- modules/nf-core/gt/gff3/meta.yml
- modules/nf-core/gt/gff3/tests/main.nf.test
- modules/nf-core/gt/gff3/tests/main.nf.test.snap
- modules/nf-core/gt/gff3/tests/nextflow.config
- modules/nf-core/gt/gff3/tests/tags.yml
> Added gt/gff3

- .github/workflows/test.yml
until the jobs get picked up again
> switch back to github based runners for now

- modules/nf-core/ngscheckmate/vafncm/main.nf
- modules/nf-core/pretextmap/main.nf
- modules/nf-core/pretextmap/meta.yml
- modules/nf-core/samtools/calmd/meta.yml
- modules/nf-core/samtools/collate/meta.yml
- modules/nf-core/samtools/fasta/main.nf
- modules/nf-core/samtools/fasta/meta.yml
- modules/nf-core/samtools/markdup/main.nf
- modules/nf-core/samtools/markdup/meta.yml
> samtools/fasta: remove the extra bracket ( from the version string

- modules/nf-core/multiqc/tests/main.nf.test
- tests/config/test_data.config
Update the MultiQC module to pull static test data rather than generating it with FastQC, removing a dependency for consuming workflows wanting to test this module. 
Closes #XXX 
> Pull multiqc static multiqc test data

- modules/nf-core/pretextsnapshot/main.nf
- modules/nf-core/pretextsnapshot/meta.yml
- tests/modules/nf-core/pretextsnapshot/test.yml
> Add dot in the end of prefix for output file

- modules/nf-core/blast/blastn/tests/main.nf.test
- modules/nf-core/blast/blastn/tests/main.nf.test.snap
> blastn snapshot for versions added

- modules/nf-core/cat/cat/main.nf
- modules/nf-core/cat/cat/tests/main.nf.test
> Now generating a more informative error message

- modules/nf-core/xz/compress/main.nf
- modules/nf-core/xz/compress/meta.yml
- modules/nf-core/xz/compress/tests/main.nf.test
- modules/nf-core/xz/compress/tests/main.nf.test.snap
This PR adds stub and stub test, improves tests and meta.yml for module xz/compress
> xz/compress: adds stub and stub test, improves tests and meta.yml

- modules/nf-core/xz/decompress/main.nf
- modules/nf-core/xz/decompress/meta.yml
- modules/nf-core/xz/decompress/tests/main.nf.test
- modules/nf-core/xz/decompress/tests/main.nf.test.snap
This PR adds stub and stub test, improves tests and meta.yml for module xz/decompress
> xz/decompress: adds stub and stub test, improves tests and meta.yml

- modules/nf-core/abricate/run/meta.yml
Came across a typo in the meta.yml
> Fix Typo in abricate

- modules/nf-core/ncbigenomedownload/environment.yml
- modules/nf-core/ncbigenomedownload/main.nf
- modules/nf-core/ncbigenomedownload/meta.yml
- tests/modules/nf-core/ncbigenomedownload/main.nf
- tests/modules/nf-core/ncbigenomedownload/nextflow.config
- tests/modules/nf-core/ncbigenomedownload/test.yml
I updated the container version, because I was getting a bug with the previous version.
I added the taxids as a path input so the user has the option of using a text file with taxids
I added a groups input because that's a mandatory parameter
I also added "-p $task.cpus \\" so that multiple cpus can be used
> ncbigenomedownload updated container and added input parameters

- modules/nf-core/cellranger/mkvdjref/environment.yml
- modules/nf-core/cellranger/mkvdjref/main.nf
- modules/nf-core/cellranger/mkvdjref/meta.yml
- tests/modules/nf-core/cellranger/mkvdjref/main.nf
- tests/modules/nf-core/cellranger/mkvdjref/test.yml
Hi,
the old module was not usable for every possible configuration. 
It contained flags that were not required and made other configurations impossible to run.
The current form 
`
cellranger \
mkvdjref \
--genome=$reference_name \
--fasta=$fasta \
--genes=$gtf \
$args
`
contains `--fasta` and `--genes` which are not required.
The current format makes running the other configuration impossible
`
cellranger \
mkvdjref \
--genome=$reference_name \
--seqs=$seqs 
`
which is necesary e.g. when trying to specify the IMGT reference for the `cellranger vdj` command.
So, I would suggest to remove the unrequired ones from the module and rather add them in the respective config file of the pipelines. 
See also [here](https://support.10xgenomics.com/single-cell-vdj/software/pipelines/latest/advanced/re …
> usable with every configuration

- .github/workflows/test.yml
same to what we use in nf-core tools
> get nicer diff outputs for nf-tests

- modules/nf-core/custom/tabulartogseacls/main.nf
In this PR, the GSEA .cls file is corrected, so that if a class from a sample sheet is empty, the 'empty' string is used instead, which produces the correct output. 
Closes #XXX 
> Deal properly with empty classes in GSEA preparation

- modules/nf-core/tidk/search/environment.yml
- modules/nf-core/tidk/search/main.nf
- modules/nf-core/tidk/search/meta.yml
- modules/nf-core/tidk/search/tests/main.nf.test
- modules/nf-core/tidk/search/tests/main.nf.test.snap
- modules/nf-core/tidk/search/tests/nextflow.config
- modules/nf-core/tidk/search/tests/tags.yml
> Added tidk/search

- modules/nf-core/tidk/explore/environment.yml
- modules/nf-core/tidk/explore/main.nf
- modules/nf-core/tidk/explore/meta.yml
- modules/nf-core/tidk/explore/tests/main.nf.test
- modules/nf-core/tidk/explore/tests/main.nf.test.snap
- modules/nf-core/tidk/explore/tests/nextflow.config
- modules/nf-core/tidk/explore/tests/tags.yml
> Added tidk/explore

- modules/nf-core/tidk/plot/environment.yml
- modules/nf-core/tidk/plot/main.nf
- modules/nf-core/tidk/plot/meta.yml
- modules/nf-core/tidk/plot/tests/main.nf.test
- modules/nf-core/tidk/plot/tests/main.nf.test.snap
- modules/nf-core/tidk/plot/tests/tags.yml
> Added tidk/plot

- modules/nf-core/seqkit/sort/environment.yml
- modules/nf-core/seqkit/sort/main.nf
- modules/nf-core/seqkit/sort/meta.yml
- modules/nf-core/seqkit/sort/tests/main.nf.test
- modules/nf-core/seqkit/sort/tests/main.nf.test.snap
- modules/nf-core/seqkit/sort/tests/nextflow.config
- modules/nf-core/seqkit/sort/tests/tags.yml
> Added seqkit/sort

- modules/nf-core/narfmap/align/environment.yml
- modules/nf-core/narfmap/align/main.nf
- modules/nf-core/narfmap/align/meta.yml
- modules/nf-core/narfmap/align/tests/main.nf.test
- modules/nf-core/narfmap/align/tests/main.nf.test.snap
- modules/nf-core/narfmap/align/tests/tags.yml
- modules/nf-core/narfmap/hashtable/environment.yml
- modules/nf-core/narfmap/hashtable/main.nf
- modules/nf-core/narfmap/hashtable/meta.yml
- modules/nf-core/narfmap/hashtable/tests/main.nf.test
- modules/nf-core/narfmap/hashtable/tests/main.nf.test.snap
- modules/nf-core/narfmap/hashtable/tests/tags.yml
I couldn't be bothered to make a mulled container so I made it with auto-wave 😬
> Create new NARFMAP modules

- modules/nf-core/seqkit/seq/environment.yml
- modules/nf-core/seqkit/seq/main.nf
- modules/nf-core/seqkit/seq/meta.yml
- modules/nf-core/seqkit/seq/tests/main.nf.test
- modules/nf-core/seqkit/seq/tests/main.nf.test.snap
- modules/nf-core/seqkit/seq/tests/nextflow.config
- modules/nf-core/seqkit/seq/tests/tags.yml
> Added seqkit/seq

- modules/nf-core/sortmerna/environment.yml
- modules/nf-core/sortmerna/main.nf
- modules/nf-core/sortmerna/tests/main.nf.test
- modules/nf-core/sortmerna/tests/main.nf.test.snap
Closes #XXX 
Removed snapshot for empty output zipped files and instead added an assertion on the log.
> Added stub and bumped version to 4.3.6

- modules/nf-core/fastp/main.nf
- modules/nf-core/fastp/tests/main.nf.test
- modules/nf-core/fastp/tests/main.nf.test.snap
> Added stub for fastp and tests

- modules/nf-core/fastqc/tests/main.nf.test
- modules/nf-core/fastqc/tests/main.nf.test.snap
migrating existing pytests but, would be gr8 to have more specific assertions for each test
> fix fastqc tests n snap

- modules/nf-core/pharokka/installdatabases/environment.yml
- modules/nf-core/pharokka/installdatabases/main.nf
- modules/nf-core/pharokka/installdatabases/meta.yml
- modules/nf-core/pharokka/installdatabases/tests/main.nf.test
- modules/nf-core/pharokka/installdatabases/tests/main.nf.test.snap
- modules/nf-core/pharokka/installdatabases/tests/tags.yml
- modules/nf-core/pharokka/pharokka/environment.yml
- modules/nf-core/pharokka/pharokka/main.nf
- modules/nf-core/pharokka/pharokka/meta.yml
- modules/nf-core/pharokka/pharokka/tests/main.nf.test
- modules/nf-core/pharokka/pharokka/tests/main.nf.test.snap
- modules/nf-core/pharokka/pharokka/tests/nextflow.config
- modules/nf-core/pharokka/pharokka/tests/tags.yml
> NEW MODULES: pharokka/installdatabases & pharokka/pharokka

- modules/nf-core/openms/idripper/environment.yml
- modules/nf-core/openms/idripper/main.nf
- modules/nf-core/openms/idripper/meta.yml
- modules/nf-core/openms/idripper/tests/main.nf.test
- modules/nf-core/openms/idripper/tests/main.nf.test.snap
- modules/nf-core/openms/idripper/tests/nextflow.config
- modules/nf-core/openms/idripper/tests/tags.yml
> Add new module openms/idripper

- modules/nf-core/custom/dumpsoftwareversions/tests/main.nf.test
- modules/nf-core/custom/dumpsoftwareversions/tests/main.nf.test.snap
> Fixed custom/dumpsoftwareversions nf-tests

- modules/nf-core/openms/idscoreswitcher/environment.yml
- modules/nf-core/openms/idscoreswitcher/main.nf
- modules/nf-core/openms/idscoreswitcher/meta.yml
- modules/nf-core/openms/idscoreswitcher/tests/main.nf.test
- modules/nf-core/openms/idscoreswitcher/tests/main.nf.test.snap
- modules/nf-core/openms/idscoreswitcher/tests/nextflow.config
- modules/nf-core/openms/idscoreswitcher/tests/tags.yml
> Add new module openms/idscoreswitcher

- modules/nf-core/custom/tabulartogseacls/main.nf
See https://github.com/nf-core/differentialabundance/issues/218 ([@fruce-ki](https://github.com/fruce-ki))
> Fix field matching in GSEA cls building

- modules/nf-core/custom/dumpsoftwareversions/environment.yml
- modules/nf-core/custom/dumpsoftwareversions/main.nf
- modules/nf-core/custom/dumpsoftwareversions/tests/main.nf.test.snap
- modules/nf-core/multiqc/environment.yml
- modules/nf-core/multiqc/main.nf
- modules/nf-core/multiqc/tests/main.nf.test.snap
> Bump MultiQC version to 1.19

- modules/nf-core/kraken2/kraken2/tests/main.nf.test
Originally by @drpatelh in #4702 
Closes #XXX 
> Fix tags for kraken2

- modules/nf-core/fqtk/meta.yml
- tests/modules/nf-core/fqtk/main.nf
Originally by @drpatelh
Closes #XXX 
> Update fqtk module

- modules/nf-core/foldcomp/decompress/environment.yml
- modules/nf-core/foldcomp/decompress/main.nf
- modules/nf-core/foldcomp/decompress/meta.yml
- modules/nf-core/foldcomp/decompress/tests/main.nf.test
- modules/nf-core/foldcomp/decompress/tests/main.nf.test.snap
- modules/nf-core/foldcomp/decompress/tests/tags.yml
> foldcomp decompress

- subworkflows/nf-core/fasta_explore_search_plot_tidk/main.nf
- subworkflows/nf-core/fasta_explore_search_plot_tidk/meta.yml
- subworkflows/nf-core/fasta_explore_search_plot_tidk/tests/main.nf.test
- subworkflows/nf-core/fasta_explore_search_plot_tidk/tests/main.nf.test.snap
- subworkflows/nf-core/fasta_explore_search_plot_tidk/tests/nextflow.config
- subworkflows/nf-core/fasta_explore_search_plot_tidk/tests/tags.yml
> Added fasta_explore_search_plot_tidk subworkflow

- .github/workflows/test.yml
- nf-test.config
> NXF_TEST_DIR -> NFT_WORKDIR

- .github/workflows/test.yml
- modules/nf-core/qualimap/bamqc/tests/main.nf.test
> Sort test.yml file

- modules/nf-core/qualimap/bamqc/tests/main.nf.test
- modules/nf-core/qualimap/bamqc/tests/main.nf.test.snap
- modules/nf-core/qualimap/bamqccram/tests/main.nf.test
- modules/nf-core/qualimap/bamqccram/tests/main.nf.test.snap
- modules/nf-core/qualimap/rnaseq/tests/main.nf.test
- modules/nf-core/qualimap/rnaseq/tests/main.nf.test.snap
> Better tests for qualimap

- modules/nf-core/blast/makeblastdb/environment.yml
- modules/nf-core/blast/makeblastdb/main.nf
update tool version 
Closes #XXX 
> update version of nf-core module blast/makeblastdb

- modules/nf-core/gt/suffixerator/environment.yml
- modules/nf-core/gt/suffixerator/main.nf
- modules/nf-core/gt/suffixerator/meta.yml
- modules/nf-core/gt/suffixerator/tests/main.nf.test
- modules/nf-core/gt/suffixerator/tests/main.nf.test.snap
- modules/nf-core/gt/suffixerator/tests/nextflow.config
- modules/nf-core/gt/suffixerator/tests/tags.yml
> Added gt/suffixerator

- .github/workflows/test.yml
should fix newer linting error for the `devcontainer.json`
> pin prettier version

- modules/nf-core/gffread/tests/main.nf.test
> CHORES: update gffread tests with new data organisation

- modules/nf-core/gunzip/tests/main.nf.test
> CHORES: update gunzip tests with new data organisation

- modules/nf-core/gt/ltrharvest/environment.yml
- modules/nf-core/gt/ltrharvest/main.nf
- modules/nf-core/gt/ltrharvest/meta.yml
- modules/nf-core/gt/ltrharvest/tests/main.nf.test
- modules/nf-core/gt/ltrharvest/tests/main.nf.test.snap
- modules/nf-core/gt/ltrharvest/tests/nextflow.config
- modules/nf-core/gt/ltrharvest/tests/nextflow.extended.config
- modules/nf-core/gt/ltrharvest/tests/nextflow.extended.custom.config
- modules/nf-core/gt/ltrharvest/tests/tags.yml
> Added gt/ltrharvest

- modules/nf-core/ltrretriever/environment.yml
- modules/nf-core/ltrretriever/main.nf
- modules/nf-core/ltrretriever/meta.yml
- modules/nf-core/ltrretriever/tests/main.nf.test
- modules/nf-core/ltrretriever/tests/main.nf.test.snap
- modules/nf-core/ltrretriever/tests/nextflow.config
- modules/nf-core/ltrretriever/tests/tags.yml
> Added ltrretriever

- subworkflows/nf-core/utils_nextflow_pipeline/tests/main.function.nf.test
- subworkflows/nf-core/utils_nextflow_pipeline/tests/main.workflow.nf.test
- subworkflows/nf-core/utils_nfcore_pipeline/tests/main.function.nf.test
- subworkflows/nf-core/utils_nfcore_pipeline/tests/main.workflow.nf.test
- subworkflows/nf-core/utils_nfvalidation_plugin/tests/main.nf.test
> nicer assertions in utils subworkflows

- modules/nf-core/trinity/main.nf
- modules/nf-core/trinity/meta.yml
- modules/nf-core/trinity/tests/main.nf.test
> Trinity: Now handling multiple reads

- modules/nf-core/ltrfinder/environment.yml
- modules/nf-core/ltrfinder/main.nf
- modules/nf-core/ltrfinder/meta.yml
- modules/nf-core/ltrfinder/tests/main.nf.test
- modules/nf-core/ltrfinder/tests/main.nf.test.snap
- modules/nf-core/ltrfinder/tests/tags.yml
> Added ltrfinder

- modules/nf-core/eggnogmapper/environment.yml
- modules/nf-core/eggnogmapper/meta.yml
- modules/nf-core/eggnogmapper/tests/main.nf.test
> DIAMOND_MAKEDB updated

- modules/nf-core/gffread/tests/main.nf.test
- modules/nf-core/gffread/tests/main.nf.test.snap
No differences in logic really, just modified the tests to simplify the snapshot- helped me to debug use of this module in a workflow testing environment. 
> Updating gffread tests

- modules/nf-core/deepcell/mesmer/tests/main.nf.test
Removed annoying leftover TODO from my previous PR for this module.
Closes #XXX 
> removed leftover todo

- modules/nf-core/survivor/stats/main.nf
- modules/nf-core/survivor/stats/tests/main.nf.test.snap
> survivor stats needs unzipped vcf

- modules/nf-core/umicollapse/main.nf
- modules/nf-core/umicollapse/meta.yml
- modules/nf-core/umicollapse/tests/main.nf.test
- modules/nf-core/umicollapse/tests/main.nf.test.snap
> Add umicollapse capability to run with fastq

- subworkflows/nf-core/preprocess_rnaseq/tests/main.nf.test
- subworkflows/nf-core/preprocess_rnaseq/tests/nextflow.config
Just remove issues picked up in workflow-level linting that weren't picked up in linting here for some reason.
> Fix some linting issues in rnaseq_preprocessing workflow

- modules/nf-core/bclconvert/Dockerfile
- modules/nf-core/bclconvert/README.md
https://github.com/nf-core/modules/pull/4823/commits/8249312f334a9f60750d4a654db0d707113ccf70 explains most of it
Less manual steps the better
Inspired by #4818
> bclconvert: Add version arg and move download to Dockerfile

- modules/nf-core/wfmash/environment.yml
- modules/nf-core/wfmash/main.nf
> update wfmash to v0.12.6

- modules/nf-core/gsea/gsea/main.nf
- modules/nf-core/gsea/gsea/meta.yml
See https://github.com/nf-core/differentialabundance/issues/143
Closes #XXX 
> Made GSEA butterfly plot optional

- modules/nf-core/umitools/extract/tests/main.nf.test
> CHORE: Update UMITOOLS_EXTRACT test data path

- modules/nf-core/sentieon/applyvarcal/main.nf
- modules/nf-core/sentieon/bwaindex/main.nf
- modules/nf-core/sentieon/bwamem/main.nf
- modules/nf-core/sentieon/datametrics/main.nf
- modules/nf-core/sentieon/dedup/main.nf
- modules/nf-core/sentieon/dnamodelapply/main.nf
- modules/nf-core/sentieon/dnascope/main.nf
- modules/nf-core/sentieon/gvcftyper/main.nf
- modules/nf-core/sentieon/haplotyper/main.nf
- modules/nf-core/sentieon/readwriter/main.nf
- modules/nf-core/sentieon/tnfilter/main.nf
- modules/nf-core/sentieon/tnhaplotyper2/main.nf
- modules/nf-core/sentieon/tnscope/main.nf
- modules/nf-core/sentieon/varcal/main.nf
- modules/nf-core/sentieon/wgsmetrics/main.nf
Trying to fix this problem:
https://github.com/nf-core/sarek/issues/1399#issuecomment-1935253384
> Adding support for apptainer in Sentieon modules

- modules/nf-core/rseqc/tin/tests/main.nf.test
- modules/nf-core/rseqc/tin/tests/main.nf.test.snap
> CHORES: Update rseqc/tin to use path rather than map

- modules/nf-core/salmon/index/tests/main.nf.test
- modules/nf-core/salmon/index/tests/main.nf.test.snap
- modules/nf-core/salmon/quant/tests/main.nf.test
- modules/nf-core/salmon/quant/tests/main.nf.test.snap
> CHORES: Update salmon modules to use path rather than map

- modules/nf-core/subread/featurecounts/tests/main.nf.test
> CHORES: Update SUBREAD_FEATURECOUNTS module to use path rather than map

- modules/nf-core/trimgalore/tests/main.nf.test
> CHORES: Update TRIMGALORE module to use path rather than map

- modules/nf-core/pyrodigal/environment.yml
- modules/nf-core/pyrodigal/main.nf
- modules/nf-core/pyrodigal/tests/main.nf.test.snap
This updates pyrodigal to version 3.3.0 incl. new mulled containers.
> Update pyrodigal to 3.3.0

- modules/nf-core/samtools/fastq/tests/main.nf.test
- modules/nf-core/samtools/fastq/tests/main.nf.test.snap
- modules/nf-core/samtools/fixmate/tests/main.nf.test
- modules/nf-core/samtools/fixmate/tests/main.nf.test.snap
- modules/nf-core/samtools/flagstat/tests/main.nf.test
- modules/nf-core/samtools/flagstat/tests/main.nf.test.snap
- modules/nf-core/samtools/idxstats/tests/main.nf.test
- modules/nf-core/samtools/idxstats/tests/main.nf.test.snap
- modules/nf-core/samtools/index/tests/main.nf.test
- modules/nf-core/samtools/index/tests/main.nf.test.snap
- modules/nf-core/samtools/merge/tests/main.nf.test
- modules/nf-core/samtools/merge/tests/main.nf.test.snap
- modules/nf-core/samtools/mpileup/tests/main.nf.test
- modules/nf-core/samtools/mpileup/tests/main.nf.test.snap
- modules/nf-core/samtools/sort/tests/main.nf.test
- modules/nf-core/samtools/sort/tests/main.nf.test.snap
- modules/nf-core/samtools/stats/tests/main.nf.test
- modules/nf-core/samtools/stats/tests/main.nf.test.snap
- modules/nf-core/samtools/view/tests/main.nf.test
- modules/nf-core/samtools/view/tests/main.nf.test.snap
> CHORES: update samtools tests with new data organisation

- modules/nf-core/seqkit/fx2tab/environment.yml
- modules/nf-core/seqkit/fx2tab/main.nf
- modules/nf-core/seqkit/tab2fx/environment.yml
- modules/nf-core/seqkit/tab2fx/main.nf
> Update seqkit to 2.7.0

- modules/nf-core/custom/dumpsoftwareversions/environment.yml
- modules/nf-core/custom/dumpsoftwareversions/main.nf
> Bump software versions

- modules/nf-core/samtools/view/tests/main.nf.test
> Forgot samtools view stub tests in data path conversion

- modules/nf-core/samblaster/environment.yml
- modules/nf-core/samblaster/main.nf
- tests/modules/nf-core/samblaster/test.yml
Keeping samblaster at v0.1.26 while updating samtools from v1.16.1 to v1.19.2
Confirmed container-name like this:
```
$ docker run --rm -it quay.io/biocontainers/mulled-v2-19fa9f1a5c3966b63a24166365e81da35738c5ab:60ebac4ad9c6530c0d7bf6844f52ec6916e1e0b1-0 /bin/sh
Unable to find image 'quay.io/biocontainers/mulled-v2-19fa9f1a5c3966b63a24166365e81da35738c5ab:60ebac4ad9c6530c0d7bf6844f52ec6916e1e0b1-0' locally
60ebac4ad9c6530c0d7bf6844f52ec6916e1e0b1-0: Pulling from biocontainers/mulled-v2-19fa9f1a5c3966b63a24166365e81da35738c5ab
fa7e54f17dc0: Already exists
4ca545ee6d5d: Already exists
dba71cae7ba0: Pull complete
Digest: sha256:c0c7aca3aeafc8fd39e26777193f78932ccf0be891cb358c4ade829f4e4b1379
Status: Downloaded newer image for quay.io/biocontainers/mulled-v2-19fa9f1a5c3966b63a24166365e81da357 …
```
> Updating samtools in samblaster-module

- modules/nf-core/svdb/merge/environment.yml
- modules/nf-core/svdb/merge/main.nf
> Updating samtools in svdb module

- subworkflows/nf-core/fastq_align_star/main.nf
- subworkflows/nf-core/fastq_align_star/tests/main.nf.test
- subworkflows/nf-core/fastq_align_star/tests/main.nf.test.snap
In my last PR on this subworkflow after review changes I left the following mistakes:
- Trailing newlines to annoy linting at the workflow level
- transcriptome fasta inconsistent with genome fastq input.
- RSEM_PREPAREREFERENCE not used correctly in test where transcriptome supplied.
I fixed those things here.
Closes #XXX 
> Tidy up new bits of fastq_align_star

- modules/nf-core/svdb/merge/meta.yml
- modules/nf-core/svdb/merge/tests/main.nf.test
Just fixing paths to testdata.
And updating meta.yml. (The substring `_sv_merge`  is no longer part of the suffix for the output-vcf-files.)
> Svdb merge fixing path to testdata

- modules/nf-core/bwamem2/mem/environment.yml
- modules/nf-core/bwamem2/mem/main.nf
- modules/nf-core/bwamem2/mem/tests/main.nf.test.snap
Updating module BWAMEM2/MEM to samtools v1.19.2
> Updating module BWAMEM2/MEM to samtools v1.19.2

- modules/nf-core/pairtools/dedup/main.nf
- modules/nf-core/pairtools/dedup/meta.yml
> pairtools/dedup: handle the warning for containers

- modules/nf-core/pairtools/merge/main.nf
> pairtools/merge: handle the warning for containers

- modules/nf-core/pairtools/select/main.nf
- modules/nf-core/pairtools/select/meta.yml
> pairtools/select: handle the warning for containers

- modules/nf-core/pairtools/sort/main.nf
> pairtools/sort: handle the warning for containers

- modules/nf-core/pairtools/flip/main.nf
- modules/nf-core/pairtools/flip/meta.yml
> pairtools/flip: handle the warning for containers

- modules/nf-core/pairtools/restrict/main.nf
- modules/nf-core/pairtools/restrict/meta.yml
> pairtools/restrict: handle the warning for containers

- modules/nf-core/pairtools/parse/main.nf
- modules/nf-core/pairtools/parse/meta.yml
> pairtools/parse: handle the warning for containers

- modules/nf-core/pairtools/stats/main.nf
> pairtools/stats: handle the warning for containers

- modules/nf-core/gatk4/cnnscorevariants/environment.yml
- modules/nf-core/gatk4/cnnscorevariants/main.nf
- modules/nf-core/gatk4/determinegermlinecontigploidy/environment.yml
- modules/nf-core/gatk4/determinegermlinecontigploidy/main.nf
- modules/nf-core/gatk4/germlinecnvcaller/environment.yml
- modules/nf-core/gatk4/germlinecnvcaller/main.nf
- modules/nf-core/gatk4/postprocessgermlinecnvcalls/environment.yml
- modules/nf-core/gatk4/postprocessgermlinecnvcalls/main.nf
> tentative fix for gatk broad image issues

- modules/nf-core/gawk/main.nf
- modules/nf-core/gawk/meta.yml
> fix tiny bug in gawk module

- modules/nf-core/gfaffix/main.nf
> Update gfaffix to 0.1.5b

- modules/nf-core/custom/catadditionalfasta/tests/main.nf.test
> update data path for modules custom/catadditionalfasta

- modules/nf-core/bwa/aln/tests/main.nf.test
- modules/nf-core/bwa/index/tests/main.nf.test
Needed to make nf-test work in Sarek.
> bwa/index : modules_testdata_base_path instead of test_data in nf-test

- modules/nf-core/bwa/aln/tests/main.nf.test
- modules/nf-core/bwa/mem/tests/main.nf.test
> bwa/mem : Using modules_testdata_base_path instead of test_data in nf-test

- modules/nf-core/custom/tx2gene/tests/main.nf.test
- modules/nf-core/custom/tx2gene/tests/main.nf.test.snap
> update data path for modules custom/tx2gene

- modules/nf-core/dragmap/align/tests/main.nf.test
> dragmap/align : modules_testdata_base_path instead of test_data in nf-test

- subworkflows/nf-core/preprocess_rnaseq/main.nf
Minor fix to https://github.com/nf-core/modules/pull/4998- fix for provided sortmerna index to preprocessing.
Closes #XXX 
- For modules:
> Fix sortmerna indexing

- .github/workflows/test.yml
- modules/nf-core/multiqc/environment.yml
- modules/nf-core/multiqc/main.nf
- modules/nf-core/multiqc/tests/main.nf.test.snap
> Update MQC container

- modules/nf-core/samtools/sormadup/environment.yml
- modules/nf-core/samtools/sormadup/main.nf
- modules/nf-core/samtools/sormadup/meta.yml
- modules/nf-core/samtools/sormadup/tests/main.nf.test
- modules/nf-core/samtools/sormadup/tests/main.nf.test.snap
- modules/nf-core/samtools/sormadup/tests/tags.yml
Second try at a samtools meta module
xref #3310 
xref #4571 
Speak now or forever hold your peace
Closes #XXX 
- For modules:
> New module samtools/sormadup

- subworkflows/nf-core/fastq_fastqc_umitools_trimgalore/tests/main.nf.test
- subworkflows/nf-core/fastq_fastqc_umitools_trimgalore/tests/main.nf.test.snap
> update subworkflows/fastq_fastqc_umitools_trimgalore tests

- .github/CODEOWNERS
> Update CODEOWNERS for ewels

- modules/nf-core/gffread/tests/main.nf.test
- modules/nf-core/gffread/tests/nextflow-gff3.config
- modules/nf-core/stringtie/stringtie/tests/main.nf.test
- modules/nf-core/stringtie/stringtie/tests/nextflow.config
> add an extra config for gffread gff3 and stringtie_stringtie tests

- modules/nf-core/svync/main.nf
- modules/nf-core/svync/meta.yml
- modules/nf-core/svync/tests/main.nf.test
> svync update

- modules/nf-core/geofetch/environment.yml
- modules/nf-core/geofetch/main.nf
- modules/nf-core/geofetch/meta.yml
- modules/nf-core/geofetch/tests/main.nf.test
- modules/nf-core/geofetch/tests/main.nf.test.snap
- modules/nf-core/geofetch/tests/tags.yml
- nextflow.config
Add a module for `geofetch`
- For modules:
> Add geofetch module

- modules/nf-core/umitools/dedup/tests/main.nf.test
- modules/nf-core/umitools/dedup/tests/main.nf.test.snap
- modules/nf-core/umitools/dedup/tests/nextflow.config
> rewrite umitools/dedup tests

- modules/nf-core/samtools/sormadup/main.nf
- modules/nf-core/samtools/sormadup/meta.yml
I promise this is the last fix 😊 
Closes #XXX 
- For modules:
> samtools sormadup: clean up meta, fix args

- modules/nf-core/bedtools/genomecov/tests/main.nf.test
> Fix test data paths in bedtools/genomecov

- modules/nf-core/bbmap/bbsplit/main.nf
> remove debugging line from bbmap/bbsplit

- modules/nf-core/bedtools/genomecov/main.nf
- modules/nf-core/bedtools/genomecov/tests/main.nf.test
> Genomecov test path - missed one

- modules/nf-core/cutadapt/environment.yml
- modules/nf-core/cutadapt/main.nf
- modules/nf-core/cutadapt/tests/main.nf.test.snap
Update cutadapt to version v4.6
> Update cutadapt to v4.6

- modules/nf-core/dupradar/environment.yml
- modules/nf-core/dupradar/main.nf
- modules/nf-core/dupradar/meta.yml
- modules/nf-core/dupradar/templates/dupradar.r
- modules/nf-core/dupradar/tests/main.nf.test
- modules/nf-core/dupradar/tests/main.nf.test.snap
- modules/nf-core/dupradar/tests/nextflow.config
- modules/nf-core/dupradar/tests/tags.yml
Migrated from https://github.com/nf-core/rnaseq/blob/master/modules/local/dupradar/main.nf
Closes #XXX 
- For modules:
> Add new dupradar module with tests

- modules/nf-core/cellrangerarc/count/main.nf
> Small little fix to cellrangerarc main count

- modules/nf-core/ribotricer/prepareorfs/environment.yml
- modules/nf-core/ribotricer/prepareorfs/main.nf
- modules/nf-core/ribotricer/prepareorfs/meta.yml
- modules/nf-core/ribotricer/prepareorfs/tests/main.nf.test
- modules/nf-core/ribotricer/prepareorfs/tests/main.nf.test.snap
- modules/nf-core/ribotricer/prepareorfs/tests/tags.yml
> Add ribotricer/prepareorfs

- modules/nf-core/summarizedexperiment/summarizedexperiment/main.nf
- modules/nf-core/summarizedexperiment/summarizedexperiment/templates/summarizedexperiment.r
- modules/nf-core/summarizedexperiment/summarizedexperiment/tests/main.nf.test.snap
> Don't drop dimensions when selecting from matrix-like objects in summarizedexperiment

- modules/nf-core/summarizedexperiment/summarizedexperiment/templates/summarizedexperiment.r
Be better in matching dimension metadata to dimension names from matrices in summarized experiment. Also remove some pointless lines that were hanging around from previous.
- For modules:
> Subset meta as required for summarizedexperiment

- modules/nf-core/svanalyzer/svbenchmark/main.nf
- modules/nf-core/svanalyzer/svbenchmark/meta.yml
- modules/nf-core/svanalyzer/svbenchmark/tests/main.nf.test
- modules/nf-core/svanalyzer/svbenchmark/tests/main.nf.test.snap
> svanalyzer updated

- modules/nf-core/ribotish/predict/main.nf
> fix sytax error in ribotish/predict

- modules/nf-core/tximeta/tximport/main.nf
- modules/nf-core/tximeta/tximport/templates/tximport.r
- modules/nf-core/tximeta/tximport/tests/main.nf.test.snap
> No r version in tximport snapshots

- .github/workflows/test.yml
the caching actually is only for the package downloads, not installs 😞
> don't skip installation steps

- modules/nf-core/glimpse2/phase/main.nf
- modules/nf-core/glimpse2/phase/meta.yml
- modules/nf-core/glimpse2/phase/tests/main.nf.test
- modules/nf-core/glimpse2/phase/tests/main.nf.test.snap
- modules/nf-core/glimpse2/phase/tests/tags.yml
Add nf-test to glimpse2/phase
- For modules:
> Glimpse2 phase: move to nf-test

- modules/nf-core/ribotish/predict/tests/main.nf.test
- modules/nf-core/ribotish/predict/tests/main.nf.test.snap
- modules/nf-core/ribotish/quality/tests/main.nf.test.snap
I needed to [update the riboseq test bams](https://github.com/nf-core/test-datasets/pull/1120) for ribotricer, so we need to update the tests here. 
- For modules:
> Update tests for ribotish after test data changes

- modules/nf-core/trimgalore/environment.yml
Hoping to fix tests on https://github.com/nf-core/tools/pull/2816
> run nf-core lint on trimgalore

- modules/nf-core/kallistobustools/count/main.nf
- modules/nf-core/kallistobustools/count/meta.yml
- modules/nf-core/kallistobustools/count/tests/main.nf.test.snap
Update relates to requirement for PR in `nf-core/scrnaseq`: https://github.com/nf-core/scrnaseq/pull/301
> update kallistobustools count output list

- modules/nf-core/gatk4/splitncigarreads/main.nf
- modules/nf-core/gatk4/splitncigarreads/meta.yml
- modules/nf-core/gatk4/splitncigarreads/tests/main.nf.test
> splitncigarreads added meta for references

- .github/workflows/test.yml
- modules/nf-core/angsd/gl/environment.yml
- modules/nf-core/angsd/gl/main.nf
- modules/nf-core/angsd/gl/meta.yml
- modules/nf-core/angsd/gl/tests/config_gl_1.conf
- modules/nf-core/angsd/gl/tests/config_gl_2.conf
- modules/nf-core/angsd/gl/tests/config_gl_3.conf
- modules/nf-core/angsd/gl/tests/config_gl_4.conf
- modules/nf-core/angsd/gl/tests/main.nf.test
- modules/nf-core/angsd/gl/tests/main.nf.test.snap
- modules/nf-core/angsd/gl/tests/tags.yml
Adds ANGSD Genotype Likelihood calculation
> Add module: ANGSD_GL

- modules/nf-core/liftoff/environment.yml
- modules/nf-core/liftoff/main.nf
- modules/nf-core/liftoff/meta.yml
- modules/nf-core/liftoff/tests/main.nf.test
- modules/nf-core/liftoff/tests/main.nf.test.snap
- modules/nf-core/liftoff/tests/nextflow.config
- modules/nf-core/liftoff/tests/tags.yml
> Added liftoff

- modules/nf-core/gt/gff3validator/environment.yml
- modules/nf-core/gt/gff3validator/main.nf
- modules/nf-core/gt/gff3validator/meta.yml
- modules/nf-core/gt/gff3validator/tests/main.nf.test
- modules/nf-core/gt/gff3validator/tests/main.nf.test.snap
- modules/nf-core/gt/gff3validator/tests/nextflow.config
- modules/nf-core/gt/gff3validator/tests/tags.yml
> Added gt/gff3validator

- modules/nf-core/ensemblvep/vep/tests/main.nf.test
> update paths for VEP

- modules/nf-core/kallistobustools/count/main.nf
- modules/nf-core/kallistobustools/count/meta.yml
- modules/nf-core/kallistobustools/count/tests/main.nf.test.snap
> Revert "update kallistobustools count output list"

- modules/nf-core/dragmap/align/main.nf
- modules/nf-core/dragmap/align/meta.yml
- modules/nf-core/dragmap/align/tests/main.nf.test
- modules/nf-core/dragmap/align/tests/main.nf.test.snap
- subworkflows/nf-core/fastq_align_dna/main.nf
- add cram and index output support to dragmap
- update dependent subworkflows
Closes #XXX 
- For modules:
> add cram/index support to dragmap

- modules/nf-core/openms/idmerger/meta.yml
- modules/nf-core/openms/idmerger/tests/main.nf.test
- modules/nf-core/openms/idmerger/tests/main.nf.test.snap
> Idmerger nf test closes #5157

- modules/nf-core/ashlar/main.nf
* $meta.id is not correctly interpolated into the tag string
* version output string no longer includes extraneous python warnings
- For modules:
> Fix ashlar tag string and version string output

- modules/nf-core/rgi/cardannotation/main.nf
- modules/nf-core/rgi/main/main.nf
This fixes a dependency version of RGI (Details see in its [Bioconda issue](https://github.com/bioconda/bioconda-recipes/issues/46581)).
- For modules:
> Update modules: rgi

- modules/nf-core/gatk4/asereadcounter/main.nf
- modules/nf-core/gatk4/asereadcounter/main.nf.test
- modules/nf-core/gatk4/asereadcounter/meta.yml
> corrected bug in asereadcounter

- subworkflows/nf-core/bam_create_som_pon_gatk/tests/main.nf.test
> update paths in bam_create_som_pon_gatk subworkflows

- modules/nf-core/summarizedexperiment/summarizedexperiment/templates/summarizedexperiment.r
Currently this module fails if input sample metadata has any all-NA columns due an aggregation operation designed to collapse e.g. tech reps. I propose we just remove such columns before the aggregation.
- For modules:
> summarizedexperiment: don't aggregate na cols

- modules/nf-core/minimap2/align/environment.yml
- modules/nf-core/minimap2/align/main.nf
- modules/nf-core/minimap2/align/tests/main.nf.test
- modules/nf-core/minimap2/align/tests/main.nf.test.snap
- modules/nf-core/minimap2/index/environment.yml
- modules/nf-core/minimap2/index/main.nf
- modules/nf-core/minimap2/index/tests/main.nf.test.snap
> Update minimap2 and output optional csi

- modules/nf-core/dragmap/hashtable/tests/main.nf.test
> ci(nf-test): update path for dragmap/hashtable tests

- modules/nf-core/samtools/faidx/tests/main.nf.test
> ci(nf-test): update paths for samtools/faidx tests

- modules/nf-core/anota2seq/anota2seqrun/meta.yml
> Fix anota2seq patterns

- modules/nf-core/arriba/arriba/main.nf
- tests/modules/nf-core/arriba/arriba/test.yml
update arriba stub to write correct version
- For modules:
> update arriba stub to write correct version

- modules/nf-core/htsnimtools/vcfcheck/environment.yml
- modules/nf-core/htsnimtools/vcfcheck/main.nf
- modules/nf-core/htsnimtools/vcfcheck/meta.yml
- modules/nf-core/htsnimtools/vcfcheck/tests/main.nf.test
- modules/nf-core/htsnimtools/vcfcheck/tests/main.nf.test.snap
- modules/nf-core/htsnimtools/vcfcheck/tests/nextflow.config
- modules/nf-core/htsnimtools/vcfcheck/tests/tags.yml
> new module htsnimtools/vcfcheck

- modules/nf-core/seqkit/fx2tab/environment.yml
- modules/nf-core/seqkit/fx2tab/main.nf
- modules/nf-core/seqkit/tab2fx/environment.yml
- modules/nf-core/seqkit/tab2fx/main.nf
> Update seqkit to 2.8.1

- modules/nf-core/agat/convertspgxf2gxf/environment.yml
- modules/nf-core/agat/convertspgxf2gxf/main.nf
- modules/nf-core/agat/convertspgxf2gxf/meta.yml
- modules/nf-core/agat/convertspgxf2gxf/tests/main.nf.test.snap
> agat/convertspgxf2gxf: Version bumped to 1.4.0

- tests/config/test_data.config
New entries added in test_data.config following merge of https://github.com/nf-core/test-datasets/pull/1175
> Update test_data.config with plink2 popgen data

- modules/nf-core/cellranger/multi/main.nf
- modules/nf-core/cellranger/multi/templates/cellranger_multi.py
- modules/nf-core/cellranger/multi/tests/main.nf.test.snap
- modules/nf-core/cellranger/multi/tests/nextflow.config
> Add fixes for handling `FFPE` data.

- subworkflows/nf-core/fasta_build_add_kraken2/main.nf
- subworkflows/nf-core/fasta_build_add_kraken2/meta.yml
- subworkflows/nf-core/fasta_build_add_kraken2/tests/main.nf.test
- subworkflows/nf-core/fasta_build_add_kraken2/tests/main.nf.test.snap
- subworkflows/nf-core/fasta_build_add_kraken2_bracken/main.nf
- subworkflows/nf-core/fasta_build_add_kraken2_bracken/meta.yml
- subworkflows/nf-core/fasta_build_add_kraken2_bracken/tests/main.nf.test
- subworkflows/nf-core/fasta_build_add_kraken2_bracken/tests/main.nf.test.snap
- subworkflows/nf-core/fasta_build_add_kraken2_bracken/tests/tags.yml
> Add bracken build module in fasta_build_add_kraken2 subworkflow

- modules/nf-core/wisecondorx/convert/main.nf
- modules/nf-core/wisecondorx/convert/tests/main.nf.test.snap
- modules/nf-core/wisecondorx/gender/main.nf
- modules/nf-core/wisecondorx/gender/tests/main.nf.test.snap
- modules/nf-core/wisecondorx/newref/main.nf
- modules/nf-core/wisecondorx/newref/tests/main.nf.test.snap
- modules/nf-core/wisecondorx/predict/main.nf
- modules/nf-core/wisecondorx/predict/tests/main.nf.test.snap
> bump wisecondorx modules

- modules/nf-core/gawk/main.nf
> fix gawk stubs

- modules/nf-core/wisecondorx/convert/main.nf
- modules/nf-core/wisecondorx/convert/tests/main.nf.test.snap
- modules/nf-core/wisecondorx/gender/main.nf
- modules/nf-core/wisecondorx/gender/tests/main.nf.test.snap
- modules/nf-core/wisecondorx/newref/main.nf
- modules/nf-core/wisecondorx/newref/tests/main.nf.test.snap
- modules/nf-core/wisecondorx/predict/main.nf
- modules/nf-core/wisecondorx/predict/tests/main.nf.test.snap
> bump wisecondorx to v1.2.7

- .github/workflows/clean-up.yml
It's just throwing an error. Not sure if y'all know why that would be happening...
https://github.com/nf-core/modules/actions/workflows/clean-up.yml
> Fix stale action

- modules/nf-core/gffread/environment.yml
- modules/nf-core/gffread/main.nf
- modules/nf-core/gffread/meta.yml
- modules/nf-core/gffread/tests/main.nf.test
- modules/nf-core/gffread/tests/main.nf.test.snap
- modules/nf-core/gffread/tests/nextflow-fasta.config
> GFFREAD: updated to 0.12.7, added meta and fasta input/output

- tests/config/pytest_modules.yml
> re delete gatk4/bedtointervallist from pytest_modules.yml after it was added again (see #5251)

- modules/nf-core/mosdepth/environment.yml
- modules/nf-core/mosdepth/main.nf
- modules/nf-core/mosdepth/tests/main.nf.test.snap
Just updating mosdepth to 0.3.8
Closes #XXX 
- For modules:
> Update mosdepth to 0.3.8

- modules/nf-core/repeatmodeler/repeatmodeler/environment.yml
- modules/nf-core/repeatmodeler/repeatmodeler/main.nf
- modules/nf-core/repeatmodeler/repeatmodeler/meta.yml
- modules/nf-core/repeatmodeler/repeatmodeler/tests/main.nf.test
- modules/nf-core/repeatmodeler/repeatmodeler/tests/main.nf.test.snap
- modules/nf-core/repeatmodeler/repeatmodeler/tests/tags.yml
> Added repeatmodeler/repeatmodeler

- modules/nf-core/cellranger/multi/main.nf
- modules/nf-core/cellranger/multi/tests/main.nf.test
This work relates to requirements and bugs identified during  https://github.com/nf-core/scrnaseq/pull/276
It relates to allowing module to use FFPE data and to properly parse optional files for config generation.
> add updates in nf-core/cellrangermulti module script

- modules/nf-core/bedgovcf/environment.yml
- modules/nf-core/bedgovcf/main.nf
- modules/nf-core/bedgovcf/tests/main.nf.test.snap
> update bedgovcf to v0.1.1

- .github/workflows/test.yml
- modules/nf-core/krakenuniq/preloadedkrakenuniq/main.nf
- modules/nf-core/krakenuniq/preloadedkrakenuniq/meta.yml
- modules/nf-core/krakenuniq/preloadedkrakenuniq/tests/main.nf.test
- modules/nf-core/krakenuniq/preloadedkrakenuniq/tests/main.nf.test.snap
* base reads output file format on input format
* expand tests beyond stubs
* parallelize compression
Currently dependent on https://github.com/nf-core/test-datasets/pull/1192
Closes https://github.com/nf-core/taxprofiler/issues/474
> Fix krakenuniq

- modules/nf-core/agat/convertspgff2gtf/environment.yml
- modules/nf-core/agat/convertspgff2gtf/main.nf
- modules/nf-core/agat/convertspgff2gtf/meta.yml
- modules/nf-core/agat/convertspgff2gtf/tests/main.nf.test.snap
- modules/nf-core/agat/convertspgff2tsv/environment.yml
- modules/nf-core/agat/convertspgff2tsv/main.nf
- modules/nf-core/agat/convertspgff2tsv/meta.yml
- modules/nf-core/agat/convertspgff2tsv/tests/main.nf.test
- modules/nf-core/agat/convertspgff2tsv/tests/main.nf.test.snap
- modules/nf-core/agat/spaddintrons/environment.yml
- modules/nf-core/agat/spaddintrons/main.nf
- modules/nf-core/agat/spaddintrons/meta.yml
- modules/nf-core/agat/spaddintrons/tests/main.nf.test.snap
- modules/nf-core/agat/spstatistics/environment.yml
- modules/nf-core/agat/spstatistics/main.nf
- modules/nf-core/agat/spstatistics/meta.yml
- modules/nf-core/agat/spstatistics/tests/main.nf.test.snap
- modules/nf-core/agat/sqstatbasic/environment.yml
- modules/nf-core/agat/sqstatbasic/main.nf
- modules/nf-core/agat/sqstatbasic/meta.yml
- modules/nf-core/agat/sqstatbasic/tests/main.nf.test.snap
> Updated agat modules

- modules/nf-core/gt/stat/environment.yml
- modules/nf-core/gt/stat/main.nf
- modules/nf-core/gt/stat/meta.yml
- modules/nf-core/gt/stat/tests/main.nf.test
- modules/nf-core/gt/stat/tests/main.nf.test.snap
- modules/nf-core/gt/stat/tests/tags.yml
> Added gt/stat

- modules/nf-core/vcflib/vcffixup/environment.yml
- modules/nf-core/vcflib/vcffixup/main.nf
- modules/nf-core/vcflib/vcffixup/meta.yml
- modules/nf-core/vcflib/vcffixup/tests/main.nf.test
- modules/nf-core/vcflib/vcffixup/tests/main.nf.test.snap
- modules/nf-core/vcflib/vcffixup/tests/tags.yml
> add module vcffixup

- modules/nf-core/tximeta/tximport/main.nf
- modules/nf-core/tximeta/tximport/tests/main.nf.test
- modules/nf-core/tximeta/tximport/tests/main.nf.test.snap
Partly addressing https://github.com/nf-core/rnaseq/issues/1188
- For modules:
> Add missing tximport outputs

- subworkflows/nf-core/quantify_pseudo_alignment/main.nf
- subworkflows/nf-core/quantify_pseudo_alignment/tests/main.nf.test
- subworkflows/nf-core/quantify_pseudo_alignment/tests/main.nf.test.snap
> Update subworkflow for missing tximport outputs

- modules/nf-core/basicpy/main.nf
- modules/nf-core/basicpy/meta.yml
- tests/modules/nf-core/basicpy/nextflow.config
The new container version no longer requires overriding the entrypoint.
Closes #XXX 
- For modules:
> basicpy version bump

- modules/nf-core/sratools/fasterqdump/main.nf
- modules/nf-core/sratools/fasterqdump/meta.yml
- modules/nf-core/sratools/fasterqdump/tests/main.nf.test
- modules/nf-core/sratools/fasterqdump/tests/main.nf.test.snap
- modules/nf-core/sratools/fasterqdump/tests/nextflow.config
- modules/nf-core/sratools/prefetch/main.nf
- modules/nf-core/sratools/prefetch/meta.yml
- modules/nf-core/sratools/prefetch/tests/main.nf.test
- modules/nf-core/sratools/prefetch/tests/main.nf.test.snap
> Added stub for sratools

- modules/nf-core/bwa/aln/environment.yml
- modules/nf-core/bwa/aln/main.nf
- modules/nf-core/bwa/aln/meta.yml
- modules/nf-core/bwa/aln/tests/main.nf.test.snap
- modules/nf-core/bwa/index/environment.yml
- modules/nf-core/bwa/index/main.nf
- modules/nf-core/bwa/index/meta.yml
- modules/nf-core/bwa/index/tests/main.nf.test.snap
- modules/nf-core/bwa/mem/tests/main.nf.test
- modules/nf-core/bwa/mem/tests/main.nf.test.snap
- subworkflows/nf-core/fastq_align_dna/tests/main.nf.test
- subworkflows/nf-core/fastq_align_dna/tests/main.nf.test.snap
> Version bumped bwa/index and bwa/aln

- modules/nf-core/meryl/count/main.nf
- modules/nf-core/meryl/count/meta.yml
- modules/nf-core/meryl/count/tests/main.nf.test.snap
- modules/nf-core/meryl/histogram/main.nf
- modules/nf-core/meryl/histogram/meta.yml
- modules/nf-core/meryl/unionsum/main.nf
- modules/nf-core/meryl/unionsum/meta.yml
- modules/nf-core/meryl/unionsum/tests/main.nf.test.snap
> Added task.memory to meryl modules and .meryl ext for outputs

- modules/nf-core/seqkit/rmdup/environment.yml
- modules/nf-core/seqkit/rmdup/main.nf
- modules/nf-core/seqkit/rmdup/meta.yml
- modules/nf-core/seqkit/rmdup/tests/main.nf.test
- modules/nf-core/seqkit/rmdup/tests/main.nf.test.snap
- modules/nf-core/seqkit/rmdup/tests/tags.yml
> Added seqkit/rmdup

- modules/nf-core/bowtie2/align/main.nf
- modules/nf-core/bowtie2/align/meta.yml
Updates meta.yml that was missed in https://github.com/nf-core/modules/pull/5180
Closes #XXX 
- For modules:
> Update Bowtie2 meta.yml

- modules/nf-core/tsebra/environment.yml
- modules/nf-core/tsebra/main.nf
- modules/nf-core/tsebra/meta.yml
- modules/nf-core/tsebra/tests/main.nf.test
- modules/nf-core/tsebra/tests/main.nf.test.snap
- modules/nf-core/tsebra/tests/tags.yml
- tests/config/test_data.config
> Added tsebra

- modules/nf-core/mtmalign/align/main.nf
Update ouptut format (not in a directory!)
- For modules:
> Update mTMalign/align output format

- modules/nf-core/tcoffee/seqreformat/main.nf
> Update seqreformat stub

- nf-test.config
> Bump nft-bam to v0.2.0

- modules/nf-core/bases2fastq/main.nf
- modules/nf-core/bases2fastq/tests/main.nf.test
- modules/nf-core/bases2fastq/tests/main.nf.test.snap
We're a couple of versions behind 😬 
@blajoie
> Bump bases2fastq

- modules/nf-core/nonpareil/curve/meta.yml
- modules/nf-core/nonpareil/curve/tests/main.nf.test
- modules/nf-core/nonpareil/curve/tests/main.nf.test.snap
- modules/nf-core/nonpareil/curve/tests/nextflow.config
- modules/nf-core/nonpareil/nonpareil/tests/main.nf.test
- modules/nf-core/nonpareil/nonpareil/tests/main.nf.test.snap
- modules/nf-core/nonpareil/set/meta.yml
- modules/nf-core/nonpareil/set/tests/main.nf.test
- modules/nf-core/nonpareil/set/tests/main.nf.test.snap
- modules/nf-core/nonpareil/set/tests/nextflow.config
Tests for nonpareil seem to be [failing currently]((https://github.com/nf-core/modules/actions/runs/9427296179/job/25971253841?pr=2703), not sure why they are running on that), as does the linting, so lets fix that up.
> Update nonpareil tests and linting

- modules/nf-core/blast/blastn/environment.yml
- modules/nf-core/blast/blastn/main.nf
- modules/nf-core/blast/blastn/tests/main.nf.test.snap
- modules/nf-core/blast/blastp/environment.yml
- modules/nf-core/blast/blastp/main.nf
- modules/nf-core/blast/blastp/meta.yml
- modules/nf-core/blast/blastp/tests/main.nf.test
- modules/nf-core/blast/blastp/tests/main.nf.test.snap
- modules/nf-core/blast/tblastn/environment.yml
- modules/nf-core/blast/tblastn/main.nf
- modules/nf-core/blast/tblastn/tests/main.nf.test
- modules/nf-core/blast/tblastn/tests/main.nf.test.snap
Bumped up the version of the blast modules to 2.15 and fixed some nf-test tests at the same time.
Closes #XXX 
- For modules:
> Bumped up blast to 2.15.0

- modules/nf-core/cnvkit/reference/tests/main.nf.test
- modules/nf-core/cnvkit/reference/tests/main.nf.test.snap
Closes #XXX 
- For modules:
Related to [this comment](https://github.com/nf-core/modules/pull/5595#issuecomment-2152744218)
> change test for cnvkit/reference to be more generalized

- modules/nf-core/cnvkit/antitarget/tests/main.nf.test
- modules/nf-core/cnvkit/antitarget/tests/main.nf.test.snap
> change test for cnvkit/antitarget to be more general

- modules/nf-core/dshbio/exportsegments/environment.yml
- modules/nf-core/dshbio/exportsegments/main.nf
- modules/nf-core/dshbio/filterbed/environment.yml
- modules/nf-core/dshbio/filterbed/main.nf
- modules/nf-core/dshbio/filtergff3/environment.yml
- modules/nf-core/dshbio/filtergff3/main.nf
- modules/nf-core/dshbio/splitbed/environment.yml
- modules/nf-core/dshbio/splitbed/main.nf
- modules/nf-core/dshbio/splitgff3/environment.yml
- modules/nf-core/dshbio/splitgff3/main.nf
> Update dsh-bio to 2.4

- modules/nf-core/meryl/count/main.nf
This module uses a lot of memory and it often has to be increased, so the label has been changed to `process_high`
- For modules:
> Change meryl count from process medium to process high

- modules/nf-core/bcftools/annotate/main.nf
- modules/nf-core/bcftools/annotate/tests/bcf.config
- modules/nf-core/bcftools/annotate/tests/main.nf.test
- modules/nf-core/bcftools/annotate/tests/main.nf.test.snap
- modules/nf-core/bcftools/annotate/tests/vcf.config
- modules/nf-core/bcftools/annotate/tests/vcf_gz_index.config
- modules/nf-core/bcftools/annotate/tests/vcf_gz_index_csi.config
- modules/nf-core/bcftools/annotate/tests/vcf_gz_index_tbi.config
> BCFTOOLS_ANNOTATE : move annotation to its own input / update tests

- modules/nf-core/checkm2/databasedownload/environment.yml
- modules/nf-core/checkm2/databasedownload/main.nf
- modules/nf-core/checkm2/databasedownload/tests/main.nf.test.snap
- modules/nf-core/checkm2/predict/environment.yml
- modules/nf-core/checkm2/predict/main.nf
- modules/nf-core/checkm2/predict/meta.yml
- modules/nf-core/checkm2/predict/tests/main.nf.test
- modules/nf-core/checkm2/predict/tests/main.nf.test.snap
> Update ChekmM2 to 1.0.2

- tests/config/test_data.config
adds key to test_data.config for sage proteomics module
> updated test datasets to include sage proteomics base parameter file

- modules/nf-core/survivor/bedpetovcf/environment.yml
- modules/nf-core/survivor/bedpetovcf/main.nf
- modules/nf-core/survivor/bedpetovcf/meta.yml
- modules/nf-core/survivor/bedpetovcf/tests/main.nf.test
- modules/nf-core/survivor/bedpetovcf/tests/main.nf.test.snap
- modules/nf-core/survivor/bedpetovcf/tests/tags.yml
> new-module survivor bedpetovcf

- modules/nf-core/happy/ftxpy/environment.yml
- modules/nf-core/happy/ftxpy/main.nf
- modules/nf-core/happy/ftxpy/meta.yml
- modules/nf-core/happy/ftxpy/tests/feature.config
- modules/nf-core/happy/ftxpy/tests/main.nf.test
- modules/nf-core/happy/ftxpy/tests/main.nf.test.snap
- modules/nf-core/happy/ftxpy/tests/tags.yml
> new_module_happy_ftxpy

- modules/nf-core/deepcell/mesmer/main.nf
Updated the deepcell/mesmer module to use quay.io registry to fetch container instead of personal one.
> Updated docker container to quay.io registry.

- modules/nf-core/merquryfk/ploidyplot/environment.yml
- modules/nf-core/merquryfk/ploidyplot/main.nf
- modules/nf-core/merquryfk/ploidyplot/meta.yml
Fixes typo's in the channel names and linting
Closes #XXX 
- For modules:
> Patch merqury/ploidyplot channel names

- modules/nf-core/wittyer/Dockerfile
- modules/nf-core/wittyer/README.md
- modules/nf-core/wittyer/main.nf
- modules/nf-core/wittyer/meta.yml
- modules/nf-core/wittyer/tests/main.nf.test
- modules/nf-core/wittyer/tests/main.nf.test.snap
- modules/nf-core/wittyer/tests/test.config
> wittyer input fix and version update

- modules/nf-core/bbmap/bbsplit/main.nf
- modules/nf-core/bbmap/bbsplit/tests/main.nf.test
- modules/nf-core/bbmap/bbsplit/tests/main.nf.test.snap
- modules/nf-core/custom/catadditionalfasta/main.nf
- modules/nf-core/custom/catadditionalfasta/tests/main.nf.test
- modules/nf-core/custom/catadditionalfasta/tests/main.nf.test.snap
- modules/nf-core/fq/subsample/main.nf
- modules/nf-core/fq/subsample/tests/main.nf.test
- modules/nf-core/fq/subsample/tests/main.nf.test.snap
- modules/nf-core/hisat2/align/main.nf
- modules/nf-core/hisat2/align/tests/main.nf.test
- modules/nf-core/hisat2/align/tests/main.nf.test.snap
- modules/nf-core/hisat2/build/main.nf
- modules/nf-core/hisat2/build/tests/main.nf.test
- modules/nf-core/hisat2/build/tests/main.nf.test.snap
- modules/nf-core/hisat2/extractsplicesites/main.nf
- modules/nf-core/hisat2/extractsplicesites/tests/main.nf.test
- modules/nf-core/hisat2/extractsplicesites/tests/main.nf.test.snap
- modules/nf-core/preseq/lcextrap/main.nf
- modules/nf-core/preseq/lcextrap/tests/main.nf.test
- modules/nf-core/preseq/lcextrap/tests/main.nf.test.snap
- subworkflows/nf-core/fastq_align_hisat2/tests/main.nf.test.snap
> stubs and test for rnaseq modules - part I

- modules/nf-core/multiqc/environment.yml
- modules/nf-core/multiqc/main.nf
- modules/nf-core/multiqc/tests/main.nf.test.snap
> bump MultiQC version

- .github/workflows/test.yml
- modules/nf-core/fargene/tests/main.nf.test
- modules/nf-core/gunzip/main.nf
- modules/nf-core/gunzip/meta.yml
- modules/nf-core/gunzip/tests/main.nf.test
- modules/nf-core/gunzip/tests/main.nf.test.snap
- modules/nf-core/gunzip/tests/nextflow.config
- modules/nf-core/leviosam2/lift/tests/main.nf.test
- modules/nf-core/leviosam2/lift/tests/main.nf.test.snap
- modules/nf-core/liftoff/environment.yml
- modules/nf-core/liftoff/main.nf
> Added prefix to gunzip and while keeping the default name as `archive.toString() - '.gz'` 

- modules/nf-core/interproscan/main.nf
Fix for using Seqera containers container. `pkgs/` folder is still present meaning `find` returns more than one file, of which only the one in `share/` is correct.
Closes #XXX 
- For modules:
> Add share to find path

- modules/nf-core/agat/spfilterfeaturefromkilllist/environment.yml
- modules/nf-core/agat/spfilterfeaturefromkilllist/main.nf
- modules/nf-core/agat/spfilterfeaturefromkilllist/meta.yml
- modules/nf-core/agat/spfilterfeaturefromkilllist/tests/main.nf.test
- modules/nf-core/agat/spfilterfeaturefromkilllist/tests/main.nf.test.snap
- modules/nf-core/agat/spfilterfeaturefromkilllist/tests/tags.yml
- tests/config/test_data.config
> Added agat/spfilterfeaturefromkilllist

- modules/nf-core/stranger/environment.yml
- modules/nf-core/stranger/main.nf
- modules/nf-core/stranger/tests/main.nf.test.snap
> bump stranger to 0.9.1

- nf-test.config
> Update nft-bam to v0.3.0

- subworkflows/nf-core/fastq_fastqc_umitools_fastp/tests/main.nf.test
- subworkflows/nf-core/fastq_fastqc_umitools_fastp/tests/main.nf.test.snap
- subworkflows/nf-core/fastq_fastqc_umitools_trimgalore/tests/main.nf.test
- subworkflows/nf-core/fastq_fastqc_umitools_trimgalore/tests/main.nf.test.snap
Continuing on #5913
Removed snapshot output for tests that are skipping trimming as output is the same as input:
- `fastq_fastqc_umitools_fastp`
- `fastq_fastqc_umitools_trimgalore`
Closes #XXX 
- For modules:
> Add stubs for rnaseq subworkflows - part III

- subworkflows/nf-core/fastq_fastqc_umitools_fastp/tests/main.nf.test
- subworkflows/nf-core/fastq_fastqc_umitools_fastp/tests/main.nf.test.snap
Continuing on https://github.com/nf-core/modules/pull/5921:
- Finally fix stub for subworkflow fastq_fastqc_umitools_fastp
Closes #XXX 
- For modules:
> Add stubs for rnaseq subworkflows - part IV

- modules/nf-core/bioawk/main.nf
> Add same file clash check to bioawk

- .github/workflows/test.yml
> disable conda setup when not using a conda profile

- modules/nf-core/narfmap/align/environment.yml
- modules/nf-core/narfmap/align/main.nf
- modules/nf-core/narfmap/align/tests/main.nf.test
- modules/nf-core/narfmap/align/tests/main.nf.test.snap
- modules/nf-core/narfmap/align/tests/segfault.nf.test
- modules/nf-core/narfmap/align/tests/segfault.nf.test.snap
- modules/nf-core/narfmap/hashtable/environment.yml
- modules/nf-core/narfmap/hashtable/main.nf
- modules/nf-core/narfmap/hashtable/tests/main.nf.test.snap
- tests/config/nf-test.config
For some reason this fails in nascent, but not here...
> NARFMAP segfault

- modules/nf-core/narfmap/align/tests/main.nf.test
- modules/nf-core/narfmap/align/tests/main.nf.test.snap
- modules/nf-core/narfmap/align/tests/segfault.nf.test
- modules/nf-core/narfmap/align/tests/segfault.nf.test.snap
> narfmap cleanup

- modules/nf-core/narfmap/align/main.nf
- modules/nf-core/narfmap/align/tests/main.nf.test
- modules/nf-core/narfmap/align/tests/main.nf.test.snap
- modules/nf-core/narfmap/align/tests/segfault.nf.test
- **feat: Add cram/index support to narfmap**
- **chore: Remove singularity image comment**
- **test: Update tests for CRAM**
> Add CRAM/index support to NARFMAP

- modules/nf-core/multiqc/environment.yml
- modules/nf-core/multiqc/main.nf
- modules/nf-core/multiqc/tests/main.nf.test.snap
> bump multiqc

- modules/nf-core/nanoq/main.nf
- modules/nf-core/nanoq/meta.yml
- modules/nf-core/nanoq/tests/main.nf.test.snap
Add `${args}` to the script. 
- For modules:
> Update the module: nanoq

- modules/nf-core/dupradar/main.nf
- modules/nf-core/dupradar/tests/main.nf.test.snap
https://github.com/nf-core/modules/pull/5943 didn't trigger the module nf-tests (we should look into that), and the snapshot needed updating due to the changes.
Closes #XXX 
- For modules:
> Update dupradar test snapshot

- modules/nf-core/custom/gtffilter/environment.yml
- modules/nf-core/custom/gtffilter/main.nf
- modules/nf-core/custom/gtffilter/meta.yml
- modules/nf-core/custom/gtffilter/templates/gtffilter.py
- modules/nf-core/custom/gtffilter/tests/main.nf.test
- modules/nf-core/custom/gtffilter/tests/main.nf.test.snap
- modules/nf-core/custom/gtffilter/tests/tags.yml
The functionality has already been implemented in [rnaseq](https://github.com/nf-core/rnaseq/tree/master/modules/local/gtf_filter) and [scrnaseq](https://github.com/nf-core/scrnaseq/blob/master/modules/local/gtf_gene_filter.nf)
As I am planning to implement the same functionality in #circrna, I think it makes sense to extract this to a proper nf-core module
Closes #5963  
- For modules:
> new module: custom_gtffilter

- modules/nf-core/agat/spmergeannotations/environment.yml
- modules/nf-core/agat/spmergeannotations/main.nf
- modules/nf-core/agat/spmergeannotations/meta.yml
- modules/nf-core/agat/spmergeannotations/tests/main.nf.test
- modules/nf-core/agat/spmergeannotations/tests/main.nf.test.snap
- modules/nf-core/agat/spmergeannotations/tests/tags.yml
> Added agat/spmergeannotations

- modules/nf-core/propr/propr/templates/propr.R
> modify valCutoff funtion in propr.R

- subworkflows/nf-core/fastq_qc_trim_filter_setstrandedness/main.nf
Just porting a fix [previously discussed in rnaseq](https://github.com/nf-core/rnaseq/pull/1317) to this subworkflow. 
Closes #XXX 
- For modules:
> Remove problematic ifEmpty() from rnaseq preprocessing

- modules/nf-core/ltrharvest/tests/main.nf.test
- modules/nf-core/ltrharvest/tests/main.nf.test.snap
- modules/nf-core/ltrharvest/tests/tags.yml
> ltrharvest: Added test to verify graceful handling of no ltr input

- modules/nf-core/sniffles/meta.yml
> Fix keyword meta

- modules/nf-core/macs3/callpeak/environment.yml
- modules/nf-core/macs3/callpeak/main.nf
- modules/nf-core/macs3/callpeak/meta.yml
- modules/nf-core/macs3/callpeak/tests/bam.config
- modules/nf-core/macs3/callpeak/tests/bed.config
- modules/nf-core/macs3/callpeak/tests/main.nf.test
- modules/nf-core/macs3/callpeak/tests/main.nf.test.snap
> Add macs3/callpeak module

- modules/nf-core/ltrretriever/lai/tests/main.nf.test
- tests/config/test_data.config
> ltrretriever/lai: Fixed test data path

- modules/nf-core/cat/cat/tests/main.nf.test
- modules/nf-core/cat/cat/tests/main.nf.test.snap
> Added versions to snapshot to pass nf-core lint

- modules/nf-core/ltrretriever/ltrretriever/main.nf
> Created a local writable copy of the genome to avoid ltrretriever die

- modules/nf-core/longphase/phase/environment.yml
- modules/nf-core/longphase/phase/main.nf
- modules/nf-core/longphase/phase/meta.yml
- modules/nf-core/longphase/phase/tests/main.nf.test
- modules/nf-core/longphase/phase/tests/main.nf.test.snap
- modules/nf-core/longphase/phase/tests/nextflow.config
- modules/nf-core/longphase/phase/tests/tags.yml
> Add longphase/phase

- modules/nf-core/splitubam/environment.yml
- modules/nf-core/splitubam/main.nf
- modules/nf-core/splitubam/meta.yml
- modules/nf-core/splitubam/tests/main.nf.test
- modules/nf-core/splitubam/tests/main.nf.test.snap
- modules/nf-core/splitubam/tests/nextflow.config
- modules/nf-core/splitubam/tests/tags.yml
> New module splitubam

- modules/nf-core/cellranger/mkfastq/main.nf
This PR addresses this issue: https://github.com/nf-core/demultiplex/issues/211
Closes #XXX 
- For modules:
> Added resource setting arguments

- modules/nf-core/sentieon/dedup/main.nf
- modules/nf-core/sentieon/dedup/tests/main.nf.test.snap
> add task cpus to sentieon driver

- modules/nf-core/busco/busco/tests/main.nf.test
- modules/nf-core/busco/generateplot/tests/main.nf.test
> Updated test data paths for busco/busco

- modules/nf-core/samblaster/tests/main.nf.test
- modules/nf-core/samblaster/tests/main.nf.test.snap
> Used nft-bam for samblaster tests

- modules/nf-core/checkqc/environment.yml
- modules/nf-core/checkqc/main.nf
- modules/nf-core/checkqc/meta.yml
- modules/nf-core/checkqc/tests/main.nf.test
- modules/nf-core/checkqc/tests/main.nf.test.snap
Updated checkqc to 4.0.3. It is important to note that while version 4.0.4 is available in bioconda, it does not work due to some missing dependencies. Therefore, we need to use the latest pip version, which is 4.0.3.
Added more nf-tests.
Changed design so that output can be inspected when running a pipeline, even when failing. Related to https://github.com/nf-core/demultiplex/pull/210
Closes #XXX 
- For modules:
> Update checkqc to 4.0.3

- modules/nf-core/bclconvert/tests/main.nf.test
- modules/nf-core/biscuit/align/tests/main.nf.test
- modules/nf-core/biscuit/bsconv/tests/main.nf.test
- modules/nf-core/mash/screen/tests/main.nf.test
- modules/nf-core/mash/sketch/tests/main.nf.test
- modules/nf-core/presto/filterseq/tests/main.nf.test
- modules/nf-core/svdb/query/tests/main.nf.test
- modules/nf-core/windowmasker/convert/tests/main.nf.test
- modules/nf-core/windowmasker/mkcounts/tests/main.nf.test
- modules/nf-core/windowmasker/ustat/tests/main.nf.test
> Updated test data paths batch 3

- modules/nf-core/last/dotplot/tests/main.nf.test
- modules/nf-core/last/lastal/tests/main.nf.test
- modules/nf-core/last/lastdb/tests/main.nf.test
- modules/nf-core/last/mafconvert/tests/main.nf.test
- modules/nf-core/last/mafswap/tests/main.nf.test
- modules/nf-core/last/postmask/tests/main.nf.test
- modules/nf-core/last/split/tests/main.nf.test
- modules/nf-core/last/train/tests/main.nf.test
- modules/nf-core/mapad/map/tests/main.nf.test
- modules/nf-core/prokka/tests/main.nf.test
- modules/nf-core/prokka/tests/main.nf.test.snap
> Updated test data paths batch 5

- modules/nf-core/staramr/search/environment.yml
- modules/nf-core/staramr/search/tests/main.nf.test
> staramr/search: Locked numpy version from container

- modules/nf-core/happy/ftxpy/tests/main.nf.test
- modules/nf-core/happy/prepy/tests/main.nf.test
- modules/nf-core/nanofilt/tests/main.nf.test
- modules/nf-core/pairtools/split/tests/main.nf.test
- modules/nf-core/pigz/compress/tests/main.nf.test
- modules/nf-core/pigz/compress/tests/main.nf.test.snap
- modules/nf-core/pigz/uncompress/tests/main.nf.test
- modules/nf-core/pyrodigal/tests/main.nf.test
- modules/nf-core/pyrodigal/tests/main.nf.test.snap
- modules/nf-core/smoothxg/tests/main.nf.test
- modules/nf-core/survivor/bedpetovcf/tests/main.nf.test
- modules/nf-core/survivor/stats/tests/main.nf.test
> Updated test data paths batch 4

- modules/nf-core/antismash/antismashlite/tests/main.nf.test
- modules/nf-core/fastani/tests/main.nf.test
- modules/nf-core/lima/tests/main.nf.test
- modules/nf-core/pear/tests/main.nf.test
- modules/nf-core/picard/collecthsmetrics/tests/main.nf.test
- modules/nf-core/picard/crosscheckfingerprints/tests/main.nf.test
- modules/nf-core/picard/extractfingerprint/tests/main.nf.test
- modules/nf-core/staramr/search/tests/main.nf.test
- modules/nf-core/tabix/bgzip/tests/main.nf.test
- modules/nf-core/tiddit/cov/tests/main.nf.test
- modules/nf-core/tiddit/cov/tests/main.nf.test.snap
> Updated test data paths batch2

- modules/nf-core/kalign/align/tests/main.nf.test
- modules/nf-core/metamaps/classify/tests/main.nf.test
- modules/nf-core/metamaps/mapdirectly/tests/main.nf.test
- modules/nf-core/plink/epistasis/main.nf
- modules/nf-core/plink/epistasis/tests/main.nf.test
- modules/nf-core/plink/epistasis/tests/main.nf.test.snap
- modules/nf-core/plink/fastepistasis/main.nf
- modules/nf-core/plink/fastepistasis/tests/main.nf.test
- modules/nf-core/plink/fastepistasis/tests/main.nf.test.snap
- modules/nf-core/plink/gwas/tests/main.nf.test
- modules/nf-core/plink/gwas/tests/main.nf.test.snap
- modules/nf-core/plink/hwe/main.nf
- modules/nf-core/plink/hwe/tests/main.nf.test
- modules/nf-core/plink/hwe/tests/main.nf.test.snap
- modules/nf-core/plink/ld/tests/main.nf.test
- modules/nf-core/plink/ld/tests/main.nf.test.snap
- modules/nf-core/scimap/spatiallda/tests/main.nf.test
- modules/nf-core/vardictjava/tests/main.nf.test
> Updated test data paths batch 7

- modules/nf-core/agat/convertspgff2gtf/tests/main.nf.test
- modules/nf-core/agat/convertspgff2tsv/tests/main.nf.test
- modules/nf-core/agat/convertspgxf2gxf/tests/main.nf.test
- modules/nf-core/agat/spaddintrons/tests/main.nf.test
- modules/nf-core/agat/spstatistics/tests/main.nf.test
- modules/nf-core/agat/sqstatbasic/tests/main.nf.test
- modules/nf-core/barrnap/tests/main.nf.test
- modules/nf-core/smoove/call/tests/main.nf.test
> Updated test data paths batch 9

- modules/nf-core/admixture/meta.yml
- modules/nf-core/admixture/tests/main.nf.test
- modules/nf-core/ale/tests/main.nf.test
- modules/nf-core/gem3/gem3mapper/tests/main.nf.test
- modules/nf-core/genomad/endtoend/meta.yml
- modules/nf-core/genomad/endtoend/tests/main.nf.test
- modules/nf-core/openms/decoydatabase/meta.yml
- modules/nf-core/openms/decoydatabase/tests/main.nf.test
- modules/nf-core/president/meta.yml
- modules/nf-core/president/tests/main.nf.test
- modules/nf-core/resfinder/run/tests/main.nf.test
- modules/nf-core/spaceranger/count/tests/main.nf.test
- modules/nf-core/spaceranger/mkgtf/tests/main.nf.test
- modules/nf-core/spaceranger/mkref/tests/main.nf.test
- modules/nf-core/spaceranger/mkref/tests/main.nf.test.snap
> Updated test data paths batch 15

- modules/nf-core/art/illumina/main.nf
- modules/nf-core/art/illumina/meta.yml
- modules/nf-core/art/illumina/tests/main.nf.test
- modules/nf-core/art/illumina/tests/main.nf.test.snap
- modules/nf-core/bcftools/annotate/tests/main.nf.test
- modules/nf-core/bcftools/concat/tests/main.nf.test
- modules/nf-core/bcftools/mpileup/tests/main.nf.test
- modules/nf-core/bcftools/reheader/tests/main.nf.test
- modules/nf-core/bcftools/sort/tests/main.nf.test
- modules/nf-core/bismark/coverage2cytosine/meta.yml
- modules/nf-core/bismark/coverage2cytosine/tests/main.nf.test
- modules/nf-core/bismark/coverage2cytosine/tests/main.nf.test.snap
- modules/nf-core/bismark/methylationextractor/tests/main.nf.test
- modules/nf-core/bismark/methylationextractor/tests/main.nf.test.snap
- modules/nf-core/bismark/report/meta.yml
- modules/nf-core/bismark/report/tests/main.nf.test
- modules/nf-core/bismark/summary/tests/main.nf.test
- modules/nf-core/foldcomp/compress/tests/main.nf.test
- modules/nf-core/foldcomp/decompress/tests/main.nf.test
- modules/nf-core/svync/tests/main.nf.test
- modules/nf-core/vcf2cytosure/tests/main.nf.test
> Updated test data paths batch 12

- modules/nf-core/bwa/mem/tests/main.nf.test
- modules/nf-core/bwa/mem/tests/main.nf.test.snap
- modules/nf-core/bwamem2/mem/tests/main.nf.test
- modules/nf-core/bwamem2/mem/tests/main.nf.test.snap
- modules/nf-core/bwameme/mem/tests/main.nf.test
- modules/nf-core/bwameme/mem/tests/main.nf.test.snap
> swap to nf-test assertions to nft-bam for bwa modules

- modules/nf-core/bismark/align/meta.yml
- modules/nf-core/bismark/align/tests/main.nf.test
- modules/nf-core/bismark/align/tests/main.nf.test.snap
- modules/nf-core/bismark/coverage2cytosine/tests/main.nf.test
- modules/nf-core/bismark/deduplicate/tests/main.nf.test
- modules/nf-core/bismark/deduplicate/tests/main.nf.test.snap
- modules/nf-core/bismark/genomepreparation/meta.yml
- modules/nf-core/bismark/genomepreparation/tests/main.nf.test
- modules/nf-core/bismark/methylationextractor/tests/main.nf.test
- modules/nf-core/bismark/report/tests/main.nf.test
- modules/nf-core/bismark/summary/tests/main.nf.test
- modules/nf-core/merqury/hapmers/tests/main.nf.test
- modules/nf-core/xengsort/index/tests/main.nf.test
> Updated test data paths batch 14

- modules/nf-core/bamstats/generalstats/tests/main.nf.test
- modules/nf-core/circularmapper/circulargenerator/tests/main.nf.test
- modules/nf-core/circularmapper/realignsamfile/tests/main.nf.test
- modules/nf-core/ganon/report/tests/main.nf.test
- modules/nf-core/ganon/table/tests/main.nf.test
- modules/nf-core/mudskipper/bulk/meta.yml
- modules/nf-core/mudskipper/bulk/tests/main.nf.test
- modules/nf-core/vsearch/cluster/environment.yml
- modules/nf-core/vsearch/cluster/tests/main.nf.test
- modules/nf-core/vsearch/sort/tests/main.nf.test
> Updated test data paths batch 20

- modules/nf-core/abricate/run/tests/main.nf.test
- modules/nf-core/abricate/summary/meta.yml
- modules/nf-core/abricate/summary/tests/main.nf.test
- modules/nf-core/angsd/gl/tests/main.nf.test
- modules/nf-core/bacphlip/tests/main.nf.test
- modules/nf-core/cellpose/tests/main.nf.test
- modules/nf-core/hamronization/abricate/tests/main.nf.test
- modules/nf-core/hamronization/deeparg/tests/main.nf.test
- modules/nf-core/hamronization/fargene/tests/main.nf.test
- modules/nf-core/hamronization/summarize/tests/main.nf.test
> Updated test data paths batch 16

- modules/nf-core/panacus/histgrowth/tests/main.nf.test
- modules/nf-core/panacus/visualize/tests/main.nf.test
- modules/nf-core/plink2/extract/tests/main.nf.test
- modules/nf-core/plink2/score/tests/main.nf.test
- modules/nf-core/plink2/vcf/meta.yml
- modules/nf-core/plink2/vcf/tests/main.nf.test
- modules/nf-core/rrnatranscripts/tests/main.nf.test
- modules/nf-core/seqtk/cutn/tests/main.nf.test
- modules/nf-core/seqtk/seq/meta.yml
- modules/nf-core/seqtk/seq/tests/main.nf.test
- modules/nf-core/seqtk/seq/tests/main.nf.test.snap
- modules/nf-core/seqtk/trim/tests/main.nf.test
> Updated test data paths batch 17

- modules/nf-core/amplify/predict/tests/main.nf.test
- modules/nf-core/evigene/tr2aacds/tests/main.nf.test
- modules/nf-core/instrain/compare/environment.yml
- modules/nf-core/instrain/compare/meta.yml
- modules/nf-core/instrain/compare/tests/main.nf.test
- modules/nf-core/instrain/profile/environment.yml
- modules/nf-core/instrain/profile/meta.yml
- modules/nf-core/instrain/profile/tests/main.nf.test
- modules/nf-core/ngscheckmate/ncm/tests/main.nf.test
- modules/nf-core/ngscheckmate/ncm/tests/main.nf.test.snap
- modules/nf-core/seqtk/rename/tests/main.nf.test
- modules/nf-core/seqtk/sample/tests/main.nf.test
- modules/nf-core/seqtk/subseq/meta.yml
- modules/nf-core/seqtk/subseq/tests/main.nf.test
- modules/nf-core/vcf2db/tests/main.nf.test
- modules/nf-core/vcf2db/tests/main.nf.test.snap
> Updated test data paths batch 18

- modules/nf-core/eggnogmapper/meta.yml
- modules/nf-core/eggnogmapper/tests/main.nf.test
- modules/nf-core/filtlong/tests/main.nf.test
- modules/nf-core/filtlong/tests/main.nf.test.snap
- modules/nf-core/liftoff/tests/main.nf.test
- modules/nf-core/multivcfanalyzer/tests/main.nf.test
- modules/nf-core/shovill/tests/main.nf.test
- modules/nf-core/sourmash/index/meta.yml
- modules/nf-core/sourmash/index/tests/main.nf.test
- modules/nf-core/sourmash/sketch/tests/main.nf.test
> Updated test data paths batch 19

- modules/nf-core/krakentools/combinekreports/tests/main.nf.test
- modules/nf-core/krakentools/combinekreports/tests/main.nf.test.snap
- modules/nf-core/krakentools/combinekreports/tests/tags.yml
Add nf-test to the module krakentools/combinekreports, related to this issue https://github.com/nf-core/taxprofiler/issues/403
- For modules:
> Add nf-test to krakentools/combinekreports

- modules/nf-core/bakta/bakta/tests/main.nf.test
- modules/nf-core/celesta/tests/main.nf.test
- modules/nf-core/openms/idripper/tests/main.nf.test
- modules/nf-core/openms/idscoreswitcher/tests/main.nf.test
- modules/nf-core/repeatmodeler/builddatabase/tests/main.nf.test
- modules/nf-core/repeatmodeler/repeatmodeler/tests/main.nf.test
> Updated test data paths batch 21

- modules/nf-core/bwa/sampe/environment.yml
- modules/nf-core/bwa/sampe/tests/main.nf.test
- modules/nf-core/hmmcopy/gccounter/tests/main.nf.test
- modules/nf-core/hmmcopy/generatemap/tests/main.nf.test
- modules/nf-core/hmmcopy/mapcounter/tests/main.nf.test
- modules/nf-core/hmmcopy/readcounter/tests/main.nf.test
- modules/nf-core/ngscheckmate/patterngenerator/tests/main.nf.test
- modules/nf-core/xz/decompress/tests/main.nf.test
- modules/nf-core/xz/decompress/tests/main.nf.test.snap
> Updated test data paths batch 23

- modules/nf-core/bioawk/main.nf
- modules/nf-core/nonpareil/curve/environment.yml
- modules/nf-core/nonpareil/curve/main.nf
- modules/nf-core/nonpareil/curve/tests/main.nf.test
- modules/nf-core/nonpareil/curve/tests/main.nf.test.snap
- modules/nf-core/nonpareil/nonpareil/environment.yml
- modules/nf-core/nonpareil/nonpareil/main.nf
- modules/nf-core/nonpareil/nonpareil/tests/main.nf.test
- modules/nf-core/nonpareil/nonpareil/tests/main.nf.test.snap
- modules/nf-core/nonpareil/set/environment.yml
- modules/nf-core/nonpareil/set/main.nf
- modules/nf-core/nonpareil/set/tests/main.nf.test
- modules/nf-core/nonpareil/set/tests/main.nf.test.snap
This also removes the manual FASTQ file decompression, as this is handled internally by the tool now.
Closes #XXX 
- For modules:
> Update Nonpareil to latest version, add stub tests

- modules/nf-core/bowtie/build/tests/main.nf.test
- modules/nf-core/bwa/aln/tests/main.nf.test
- modules/nf-core/bwa/samse/environment.yml
- modules/nf-core/bwa/samse/tests/main.nf.test
- modules/nf-core/flash/tests/main.nf.test
- modules/nf-core/flash/tests/main.nf.test.snap
- modules/nf-core/nanoplot/tests/main.nf.test
- modules/nf-core/nanoplot/tests/main.nf.test.snap
- modules/nf-core/ngsbits/samplegender/tests/main.nf.test
- modules/nf-core/star/starsolo/tests/main.nf.test
- modules/nf-core/trimmomatic/tests/main.nf.test
- modules/nf-core/zip/tests/main.nf.test
> Updated test data paths batch 24

- modules/nf-core/backsub/tests/main.nf.test
- modules/nf-core/cnvkit/batch/environment.yml
- modules/nf-core/cnvkit/batch/tests/main.nf.test
- modules/nf-core/cnvkit/batch/tests/main.nf.test.snap
- modules/nf-core/cobs/classicconstruct/main.nf
- modules/nf-core/cobs/classicconstruct/tests/main.nf.test
- modules/nf-core/cobs/classicconstruct/tests/main.nf.test.snap
- modules/nf-core/cobs/compactconstruct/tests/main.nf.test
- modules/nf-core/interproscan/tests/main.nf.test
- modules/nf-core/mcquant/tests/main.nf.test
- modules/nf-core/truvari/consistency/tests/main.nf.test
- modules/nf-core/truvari/segment/tests/main.nf.test
- modules/nf-core/xz/compress/tests/main.nf.test
- modules/nf-core/xz/compress/tests/main.nf.test.snap
> Updated test data paths batch 22

- modules/nf-core/chopper/meta.yml
- modules/nf-core/chopper/tests/main.nf.test
- modules/nf-core/clame/tests/main.nf.test
- modules/nf-core/htseq/count/tests/main.nf.test
- modules/nf-core/tidk/explore/tests/main.nf.test
- modules/nf-core/tidk/explore/tests/main.nf.test.snap
- modules/nf-core/tidk/plot/tests/main.nf.test
- modules/nf-core/tidk/plot/tests/main.nf.test.snap
- modules/nf-core/tidk/search/tests/main.nf.test
- modules/nf-core/tidk/search/tests/main.nf.test.snap
- modules/nf-core/trust4/tests/main.nf.test
> Updated test data paths batch 25

- subworkflows/nf-core/bam_tumor_normal_somatic_variant_calling_strelka/main.nf
- subworkflows/nf-core/bam_tumor_normal_somatic_variant_calling_strelka/meta.yml
- subworkflows/nf-core/bam_tumor_normal_somatic_variant_calling_strelka/tests/main.nf.test
- subworkflows/nf-core/bam_tumor_normal_somatic_variant_calling_strelka/tests/main.nf.test.snap
- subworkflows/nf-core/bam_tumor_normal_somatic_variant_calling_strelka/tests/tags.yml
> port strelka-somatic subwf from sarek

- modules/nf-core/nonpareil/curve/meta.yml
- modules/nf-core/nonpareil/nonpareilcurvesr/environment.yml
- modules/nf-core/nonpareil/nonpareilcurvesr/main.nf
- modules/nf-core/nonpareil/nonpareilcurvesr/meta.yml
- modules/nf-core/nonpareil/nonpareilcurvesr/tests/main.nf.test
- modules/nf-core/nonpareil/nonpareilcurvesr/tests/main.nf.test.snap
- modules/nf-core/nonpareil/nonpareilcurvesr/tests/tags.yml
- modules/nf-core/nonpareil/set/meta.yml
> Add nonpareil/nonpareilcurvesr

- subworkflows/nf-core/fastq_qc_trim_filter_setstrandedness/main.nf
Fix this function definition so that it can be included.
Closes #XXX 
- For modules:
> fix function definition in fastq_qc_trim_filter_setstrandedness

- modules/nf-core/bedtools/bamtobed/tests/main.nf.test
- modules/nf-core/bedtools/closest/tests/main.nf.test
- modules/nf-core/bedtools/complement/tests/main.nf.test
- modules/nf-core/bedtools/coverage/tests/main.nf.test
- modules/nf-core/bedtools/getfasta/tests/main.nf.test
- modules/nf-core/bedtools/map/tests/main.nf.test
- modules/nf-core/bedtools/merge/tests/main.nf.test
> Updated test data paths batch 26

- modules/nf-core/cellbender/merge/environment.yml
- modules/nf-core/cellbender/merge/main.nf
- modules/nf-core/cellbender/merge/meta.yml
- modules/nf-core/cellbender/merge/templates/merge.py
- modules/nf-core/cellbender/merge/tests/main.nf.test
- modules/nf-core/cellbender/merge/tests/main.nf.test.snap
- modules/nf-core/cellbender/merge/tests/tags.yml
- modules/nf-core/cellbender/removebackground/environment.yml
- modules/nf-core/cellbender/removebackground/main.nf
- modules/nf-core/cellbender/removebackground/meta.yml
- modules/nf-core/cellbender/removebackground/tests/epochs.config
- modules/nf-core/cellbender/removebackground/tests/main.nf.test
- modules/nf-core/cellbender/removebackground/tests/main.nf.test.snap
- modules/nf-core/cellbender/removebackground/tests/tags.yml
Adds cellbender for ambient RNA removal in single cell transcriptomics. Is supposed to be used in both #scrnaseq and #scdownstream.
- For modules:
> Add cellbender modules

- modules/nf-core/blast/blastn/tests/main.nf.test
- modules/nf-core/blast/blastp/tests/main.nf.test
- modules/nf-core/blast/makeblastdb/tests/main.nf.test
- modules/nf-core/blast/makeblastdb/tests/main.nf.test.snap
- modules/nf-core/blast/tblastn/tests/main.nf.test
- modules/nf-core/cdhit/cdhit/tests/main.nf.test
- modules/nf-core/porechop/porechop/tests/main.nf.test
- modules/nf-core/wfmash/tests/main.nf.test
> Updated test data paths batch 30

- modules/nf-core/eklipse/tests/main.nf.test
- modules/nf-core/famsa/align/tests/main.nf.test
- modules/nf-core/famsa/guidetree/tests/main.nf.test
- modules/nf-core/odgi/layout/tests/main.nf.test
- modules/nf-core/odgi/sort/tests/main.nf.test
- modules/nf-core/odgi/sort/tests/main.nf.test.snap
- modules/nf-core/odgi/unchop/tests/main.nf.test
- modules/nf-core/odgi/unchop/tests/main.nf.test.snap
- modules/nf-core/odgi/viz/tests/main.nf.test
- modules/nf-core/pharokka/installdatabases/environment.yml
- modules/nf-core/pharokka/installdatabases/main.nf
- modules/nf-core/pharokka/installdatabases/tests/main.nf.test.snap
- modules/nf-core/pharokka/pharokka/environment.yml
- modules/nf-core/pharokka/pharokka/main.nf
- modules/nf-core/pharokka/pharokka/tests/main.nf.test
- modules/nf-core/pharokka/pharokka/tests/main.nf.test.snap
- modules/nf-core/salsa2/tests/main.nf.test
- modules/nf-core/svanalyzer/svbenchmark/tests/main.nf.test
> Updated test data paths batch 27

- modules/nf-core/agrvate/tests/main.nf.test
- modules/nf-core/fastqscan/tests/main.nf.test
- modules/nf-core/genmod/compound/tests/main.nf.test
- modules/nf-core/krakentools/extractkrakenreads/tests/main.nf.test
- modules/nf-core/mmseqs/createdb/tests/main.nf.test
- modules/nf-core/mmseqs/createdb/tests/main.nf.test.snap
- modules/nf-core/mmseqs/createindex/tests/main.nf.test
- modules/nf-core/mmseqs/createtsv/tests/main.nf.test
- modules/nf-core/mmseqs/linclust/tests/main.nf.test
- modules/nf-core/mmseqs/linclust/tests/main.nf.test.snap
- modules/nf-core/mmseqs/taxonomy/tests/main.nf.test
- modules/nf-core/mmseqs/taxonomy/tests/main.nf.test.snap
> Updated test data paths batch 29

- modules/nf-core/sentieon/qualcal/main.nf
- modules/nf-core/sentieon/qualcal/tests/main.nf.test
- modules/nf-core/sentieon/qualcal/tests/main.nf.test.snap
Handles multiple input bams/crams by turning them into a list of `-i bam1 -i bam2` etc. 
Closes #XXX 
- For modules:
> Sentieon Qualcal can merge bams provided as list

- modules/nf-core/seqkit/concat/meta.yml
- modules/nf-core/seqkit/concat/tests/main.nf.test
- modules/nf-core/seqkit/fq2fa/tests/main.nf.test
- modules/nf-core/seqkit/fx2tab/tests/main.nf.test
- modules/nf-core/seqkit/grep/tests/main.nf.test
- modules/nf-core/seqkit/seq/tests/main.nf.test
- modules/nf-core/seqkit/sliding/tests/main.nf.test
- modules/nf-core/seqkit/sort/tests/main.nf.test
- modules/nf-core/seqkit/split2/tests/main.nf.test
- modules/nf-core/seqkit/tab2fx/tests/main.nf.test
- modules/nf-core/tcoffee/align/tests/main.nf.test
> Updated test data paths batch37

- modules/nf-core/sentieon/haplotyper/main.nf
- modules/nf-core/sentieon/haplotyper/tests/main.nf.test
- modules/nf-core/sentieon/haplotyper/tests/main.nf.test.snap
The existing implementation did not support multiple BAM files as inputs. I've added it while preserving backwards compatibility (as you can see from the snapshots).
Also, tidies the module a bit.
- For modules:
> Update to Sentieon Haplotyper to support multiple BAM files

- modules/nf-core/bedgovcf/tests/main.nf.test
- modules/nf-core/freebayes/tests/main.nf.test
- modules/nf-core/freebayes/tests/main.nf.test.snap
- modules/nf-core/gtfsort/tests/main.nf.test
- modules/nf-core/igvreports/tests/main.nf.test
- modules/nf-core/seqkit/pair/tests/main.nf.test
- modules/nf-core/seqkit/replace/tests/main.nf.test
- modules/nf-core/seqkit/stats/tests/main.nf.test
- modules/nf-core/umicollapse/tests/main.nf.test
> Updated test data paths batch38

- modules/nf-core/deepcell/mesmer/tests/main.nf.test
- modules/nf-core/expansionhunter/tests/main.nf.test
- modules/nf-core/fargene/tests/main.nf.test
- modules/nf-core/fastk/fastk/tests/main.nf.test
- modules/nf-core/nanoq/tests/main.nf.test
- modules/nf-core/prodigal/tests/main.nf.test
> Updated test data paths batch39

- modules/nf-core/sentieon/bwamem/main.nf
- modules/nf-core/sentieon/bwamem/tests/main.nf.test
- modules/nf-core/sentieon/bwamem/tests/main.nf.test.snap
- modules/nf-core/sentieon/bwamem/tests/nextflow_out_cram.config
amending how the output and prefix are treated of BWAMEM to enable CRAM publication directly
Closes #XXX 
- For modules:
> Sentieon BWAMEM can publish CRAM files

- modules/nf-core/assemblyscan/meta.yml
- modules/nf-core/assemblyscan/tests/main.nf.test
- modules/nf-core/gatk4/indexfeaturefile/tests/main.nf.test
- modules/nf-core/nonpareil/curve/tests/main.nf.test
- modules/nf-core/nonpareil/nonpareil/tests/main.nf.test
- modules/nf-core/nonpareil/nonpareilcurvesr/tests/main.nf.test
- modules/nf-core/nonpareil/set/tests/main.nf.test
> Updated test data paths batch35

- modules/nf-core/cellranger/mkfastq/main.nf
- modules/nf-core/cellranger/mkfastq/tests/main.nf.test
- modules/nf-core/cellranger/mkfastq/tests/main.nf.test.snap
Addressing this issue:
https://github.com/nf-core/modules/issues/6189
Closes #XXX 
- For modules:
> Added output for fastq and undetermined fastq

- subworkflows/nf-core/bam_dedup_stats_samtools_umicollapse/tests/main.nf.test
- subworkflows/nf-core/bam_qc_picard/tests/main.nf.test
- subworkflows/nf-core/fasta_explore_search_plot_tidk/tests/main.nf.test
- subworkflows/nf-core/fastq_align_mapad/tests/main.nf.test
- subworkflows/nf-core/mmseqs_contig_taxonomy/tests/main.nf.test
> Updated test data paths batch40

- subworkflows/nf-core/fastq_align_bowtie2/tests/main.nf.test
- subworkflows/nf-core/fastq_align_bwa/tests/main.nf.test
- subworkflows/nf-core/fastq_align_dna/tests/main.nf.test
> Updated test data paths batch41

- modules/nf-core/gatk4/denoisereadcounts/tests/main.nf.test
- modules/nf-core/gatk4/denoisereadcounts/tests/main.nf.test.snap
- modules/nf-core/gatk4/reblockgvcf/tests/main.nf.test
- modules/nf-core/gatk4/reblockgvcf/tests/main.nf.test.snap
- modules/nf-core/gatk4/splitncigarreads/tests/main.nf.test
- modules/nf-core/gatk4/splitncigarreads/tests/main.nf.test.snap
- modules/nf-core/gatk4/svannotate/tests/main.nf.test
- modules/nf-core/gatk4/svannotate/tests/main.nf.test.snap
- modules/nf-core/gatk4/svcluster/tests/main.nf.test
- modules/nf-core/gatk4/svcluster/tests/main.nf.test.snap
- modules/nf-core/mageck/mle/tests/main.nf.test
> Updated test data paths batch42

- modules/nf-core/samtools/stats/tests/main.nf.test
> fix samtools_stats tests

- modules/nf-core/multiqc/main.nf
The multiqc module currently lacks a prefix functionality, just adding it in.
Closes #XXX 
- For modules:
> Add prefix functionality to multiqc module

- modules/nf-core/multiqc/environment.yml
- modules/nf-core/multiqc/main.nf
- modules/nf-core/multiqc/tests/main.nf.test.snap
> Bump MultiQC to 1.24.1

- modules/nf-core/multiqc/tests/main.nf.test
- modules/nf-core/multiqc/tests/nextflow.config
Just setting a prefix for mutliqc in testing. Makes it behave when testing in a pipeline context where this prefix is set and would need to be overridden to maintain validity of the .snap.
Closes #XXX 
- For modules:
> Lock prefix config for multiqc

- modules/environment-schema.json
Update linting of `envrionment.yml` file, remove `defaults` channel. https://github.com/nf-core/tools/pull/3029
> don't require defaults in the environment.yml channels

- subworkflows/nf-core/bcl_demultiplex/main.nf
Because Ben said so
Closes #XXX 
- For modules:
> Update bcl_demultiplex syntax

- subworkflows/nf-core/utils_nfcore_pipeline/main.nf
Ben's been giving me a lot to do 🤷🏻 
Closes #XXX 
- For modules:
> fix syntax for utils_nfcore_pipeline

- subworkflows/nf-core/utils_nextflow_pipeline/main.nf
> remove defaults from utils_nextflow_pipeline (again)

- .github/ISSUE_TEMPLATE/new_module.yml
Closes #1591 (If I understood it correctly :D) 
- For modules:
> New sections for further module info

- modules/nf-core/multiqc/main.nf
> remove slashy strings from multiqc

- modules/nf-core/tximeta/tximport/templates/tximport.r
As discussed in this issue: https://github.com/nf-core/rnaseq/issues/1365
gene_info is derived from transcript_info, which only contains the columns "gene_id", "gene_name", but not "tx". Thus, the rownames assignment was not doing anything. Fortunately, the row names were not needed downstream regardless.
Thanks for the confirmation, @pinin4fjords !
(Incidentally, I was glad to see that the commit prior to mine removed some of the redundant output files; I was wondering about those too.)
Closes #XXX 
- For modules:
> Remove redundant rowname assignment

- modules/nf-core/bcftools/reheader/main.nf
- modules/nf-core/bcftools/reheader/meta.yml
- modules/nf-core/bcftools/reheader/tests/main.nf.test
- modules/nf-core/bcftools/reheader/tests/main.nf.test.snap
- modules/nf-core/bcftools/reheader/tests/vcf_gz_index.config
- modules/nf-core/bcftools/reheader/tests/vcf_gz_index_csi.config
- modules/nf-core/bcftools/reheader/tests/vcf_gz_index_tbi.config
> Add index output to bcftools reheader

- modules/environment-schema.json
> Fix wrong array definition in env schema

- modules/nf-core/bcftools/merge/main.nf
- modules/nf-core/bcftools/merge/tests/main.nf.test
- modules/nf-core/bcftools/merge/tests/main.nf.test.snap
- modules/nf-core/bcftools/merge/tests/nextflow.config
Can't sort one input file.
- For modules:
> Fix bcftools merge for one sample

- modules/nf-core/krona/ktupdatetaxonomy/environment.yml
- modules/nf-core/krona/ktupdatetaxonomy/main.nf
- modules/nf-core/krona/ktupdatetaxonomy/tests/main.nf.test
- modules/nf-core/krona/ktupdatetaxonomy/tests/main.nf.test.snap
- tests/config/pytest_modules.yml
- tests/modules/nf-core/krona/ktupdatetaxonomy/main.nf
- tests/modules/nf-core/krona/ktupdatetaxonomy/nextflow.config
- tests/modules/nf-core/krona/ktupdatetaxonomy/test.yml
Added nf-test for krona/ktupdatetaxonomy with #6226
> Added nf-test for krona/ktupdatetaxonomy

- modules/environment-schema.json
> Add support for pip dependencies and force version pinning in conda

- modules/nf-core/spades/main.nf
- modules/nf-core/spades/tests/main.nf.test.snap
> Add PREFIX to SPADES warnings log

- modules/nf-core/seqcluster/collapse/main.nf
- modules/nf-core/seqcluster/collapse/tests/main.nf.test
- modules/nf-core/seqcluster/collapse/tests/main.nf.test.snap
This PR updates the recent addition of `seqcluster` to nf-core modules by 
- Changing the test data to a smrnaseq dataset
- Fixing a small issue with fastq capturing
Closes #XXX 
- For modules:
> Fix `seqcluster` 

- modules/nf-core/mirtrace/qc/main.nf
- modules/nf-core/mirtrace/qc/meta.yml
- modules/nf-core/mirtrace/qc/tests/main.nf.test
- modules/nf-core/mirtrace/qc/tests/main.nf.test.snap
Related to: https://github.com/nf-core/smrnaseq/issues/419
Closes #XXX 
- For modules:
> Add optional config mode in `mirtrace/qc`

- modules/nf-core/mirtop/counts/tests/main.nf.test
- modules/nf-core/mirtop/export/tests/main.nf.test
- modules/nf-core/mirtop/export/tests/main.nf.test.snap
- modules/nf-core/mirtop/gff/main.nf
- modules/nf-core/mirtop/gff/meta.yml
- modules/nf-core/mirtop/gff/tests/main.nf.test
- modules/nf-core/mirtop/gff/tests/main.nf.test.snap
- modules/nf-core/mirtop/stats/meta.yml
- modules/nf-core/mirtop/stats/tests/main.nf.test
- subworkflows/nf-core/bam_stats_mirna_mirtop/main.nf
- subworkflows/nf-core/bam_stats_mirna_mirtop/tests/main.nf.test
- subworkflows/nf-core/bam_stats_mirna_mirtop/tests/main.nf.test.snap
This PR adds the '`arity`' option in `mirtop/gff` which allows for the use of one or multiple bam files as input. In addition, some minor changes were introduced such as:
- Named outputs using `${prefix}`
- Outputs from process or workflows were renamed to add clarity (e.g. rawdata -> "isomirs", tsv -> "counts", mirtop_gff -> "gff")
Closes #XXX 
- For modules:
> Update mirtop modules and subworkflow

- modules/nf-core/summarizedexperiment/summarizedexperiment/templates/summarizedexperiment.r
- modules/nf-core/tximeta/tximport/templates/tximport.r
This PR fixes some errors introduced as I factored these R modules out of nf-core/rnaseq. Namely, I wasn't careful enough to nobble R's innate desire to mangle names in column headers. 
Closes #XXX 
- For modules:
> Fix tximport summarizedexperiment

- modules/nf-core/sratools/prefetch/main.nf
> Update output to use type dir for compatibility with tes.

- subworkflows/nf-core/fastq_qc_trim_filter_setstrandedness/main.nf
This PR just fixes up some channel wrangling in this subworkflow so the trim failures are properly returned. Also removed an un-needed map.
Closes #XXX 
- For modules:
> minor changes to fastq preprocessing

- modules/nf-core/gtdbtk/classifywf/main.nf
- modules/nf-core/gtdbtk/classifywf/tests/main.nf.test.snap
> Fix GTDBTK version calling in stub test

- modules/nf-core/multiqc/environment.yml
- modules/nf-core/multiqc/main.nf
- modules/nf-core/multiqc/tests/main.nf.test.snap
> Bump MQC to 1.25

- modules/nf-core/svdb/build/environment.yml
- modules/nf-core/svdb/build/main.nf
- modules/nf-core/svdb/build/meta.yml
- modules/nf-core/svdb/build/tests/main.nf.test
- modules/nf-core/svdb/build/tests/main.nf.test.snap
- modules/nf-core/svdb/build/tests/tags.yml
Closes #6656 
Closes #XXX 
- For modules:
> Add SVDB build

- modules/nf-core/snpeff/download/main.nf
- modules/nf-core/snpeff/download/tests/main.nf.test
- modules/nf-core/snpeff/download/tests/main.nf.test.snap
- modules/nf-core/snpeff/snpeff/tests/main.nf.test
- modules/nf-core/snpeff/snpeff/tests/nextflow.config
Retiring `snpeff_genome`. So going forward `${snpeff_db}` will be equivalent to what was previously ${snpeff_genome}.${snpeff_db}`.
Change needed [here](https://github.com/nf-core/sarek/pull/1656).
Closes #XXX 
- For modules:
> Adjusting SnpEff modules

- modules/nf-core/kalign/align/main.nf
- modules/nf-core/kalign/align/tests/main.nf.test.snap
Removes characters in echo statement that break msa pipeline
- For modules:
> KALIGN - fix bug in error catching: remove new lines

- modules/nf-core/mtmalign/align/main.nf
- modules/nf-core/mtmalign/align/tests/main.nf.test
- modules/nf-core/mtmalign/align/tests/main.nf.test.snap
The module was missing one test and was doing an extra operation (mv) that was useless and caused issues in AWS.
Closes #XXX 
- For modules:
> mtmalign/align - clean tests and fix output

- modules/nf-core/wisecondorx/predict/main.nf
- modules/nf-core/wisecondorx/predict/meta.yml
- modules/nf-core/wisecondorx/predict/tests/main.nf.test.snap
> update wisecondorx predict output

- modules/nf-core/tabix/bgziptabix/main.nf
- modules/nf-core/tabix/bgziptabix/tests/main.nf.test
- modules/nf-core/tabix/bgziptabix/tests/main.nf.test.snap
> update stubs for tabix/bgziptabix

- modules/nf-core/bcftools/concat/main.nf
- modules/nf-core/bcftools/concat/meta.yml
- modules/nf-core/bcftools/concat/tests/main.nf.test
- modules/nf-core/bcftools/concat/tests/main.nf.test.snap
> create indices when missing

- modules/nf-core/cellranger/mkfastq/main.nf
- modules/nf-core/cellranger/mkfastq/tests/main.nf.test.snap
> Updated stub mkfastq

- modules/nf-core/bedtools/genomecov/main.nf
> bedtools/genomecov - Update main.nf to use https over oras

- modules/nf-core/multiqc/environment.yml
- modules/nf-core/multiqc/main.nf
- modules/nf-core/multiqc/tests/main.nf.test.snap
> Bumped MQC to 1.25.1

- modules/nf-core/bcftools/pluginsetgt/environment.yml
- modules/nf-core/bcftools/pluginsetgt/main.nf
- modules/nf-core/bcftools/pluginsetgt/meta.yml
- modules/nf-core/bcftools/pluginsetgt/tests/main.nf.test
- modules/nf-core/bcftools/pluginsetgt/tests/main.nf.test.snap
- modules/nf-core/bcftools/pluginsetgt/tests/nextflow.config
- modules/nf-core/bcftools/pluginsetgt/tests/vcf_gz_index.config
- modules/nf-core/bcftools/pluginsetgt/tests/vcf_gz_index_csi.config
- modules/nf-core/bcftools/pluginsetgt/tests/vcf_gz_index_tbi.config
> Add bcftools/pluginsetgt

- .github/scripts/wave_singularity.py
- modules/nf-core/pints/caller/environment.yml
- modules/nf-core/pints/caller/main.nf
- modules/nf-core/pints/caller/tests/main.nf.test
- modules/nf-core/pints/caller/tests/main.nf.test.snap
The bioconda builds aren't getting updated, and the biocontainers
containers aren't getting updated. They're publishing to PyPI
consistently, so we'll meet them where they're at.
Using Seqera Containers because this isn't possible with biocontainers that I know of to use pypi packages.
https://github.com/nf-core/modules/issues/5814 is the issue with the linting.
> pints 1.1.13

- modules/nf-core/longphase/haplotag/main.nf
- modules/nf-core/longphase/haplotag/tests/main.nf.test.snap
- modules/nf-core/longphase/phase/main.nf
- modules/nf-core/longphase/phase/tests/main.nf.test.snap
It should not be there. Now, extra input files work as expected. 
Closes #XXX 
- For modules:
> Remove `params` from longphase

- modules/nf-core/genmod/annotate/environment.yml
- modules/nf-core/genmod/annotate/main.nf
- modules/nf-core/genmod/compound/environment.yml
- modules/nf-core/genmod/compound/main.nf
- modules/nf-core/genmod/models/environment.yml
- modules/nf-core/genmod/models/main.nf
- modules/nf-core/genmod/score/environment.yml
- modules/nf-core/genmod/score/main.nf
Updated genmod to version 3.8.3 in `genmod/{annotate,compound,model,score}`
- For modules:
> Update Genmod to 3.8.3

- modules/nf-core/bcftools/filter/main.nf
- modules/nf-core/bcftools/filter/meta.yml
- modules/nf-core/bcftools/filter/tests/main.nf.test
- modules/nf-core/bcftools/filter/tests/main.nf.test.snap
- modules/nf-core/bcftools/filter/tests/region_filter.config
> add index to bcftools filter input to enable region filtering

- modules/nf-core/samtools/sort/main.nf
- modules/nf-core/samtools/sort/tests/main.nf.test
- modules/nf-core/samtools/sort/tests/main.nf.test.snap
> add tests for multiple input files

- subworkflows/nf-core/fastq_fastqc_umitools_trimgalore/tests/main.nf.test.snap
> FIX: fastq_fastqc_umitools_trimgalore - update snapshot

- subworkflows/nf-core/fastq_qc_trim_filter_setstrandedness/main.nf
Fixing an error reported in https://github.com/nf-core/rnaseq/issues/1390, caused by a mistake in variable naming. 
Closes #XXX 
- For modules:
> Fix badly named variable

- modules/nf-core/star/align/meta.yml
- subworkflows/nf-core/utils_nextflow_pipeline/main.nf
Applying suggestion from https://github.com/nf-core/modules/pull/6755#discussion_r1793642254
> use multi-line string for warning

- modules/nf-core/multiqc/main.nf
> multiqc_plots is a folder not a file

- modules/nf-core/tar/environment.yml
- modules/nf-core/tar/main.nf
- modules/nf-core/tar/meta.yml
- modules/nf-core/tar/tests/main.nf.test
- modules/nf-core/tar/tests/main.nf.test.snap
> Add TAR module

- .github/workflows/test.yml
- modules/nf-core/deepvariant/vcfstatsreport/main.nf
- modules/nf-core/deepvariant/vcfstatsreport/meta.yml
- modules/nf-core/deepvariant/vcfstatsreport/tests/main.nf.test
- modules/nf-core/deepvariant/vcfstatsreport/tests/main.nf.test.snap
- modules/nf-core/deepvariant/vcfstatsreport/tests/tags.yml
> New module: deepvariant/vcfstatsreport

- subworkflows/nf-core/fastq_qc_trim_filter_setstrandedness/main.nf
I was too hasty on https://github.com/nf-core/modules/pull/6781- we shouldn't be skipping the whole subworkflows there. 
Closes #XXX 
- For modules:
> Don't skip whole trimming workflows

- modules/nf-core/proovframe/map/environment.yml
- modules/nf-core/proovframe/map/main.nf
- modules/nf-core/proovframe/map/meta.yml
- modules/nf-core/proovframe/map/tests/main.nf.test
- modules/nf-core/proovframe/map/tests/main.nf.test.snap
> proovframe map init push

- modules/nf-core/bedtools/nuc/environment.yml
- modules/nf-core/bedtools/nuc/main.nf
- modules/nf-core/bedtools/nuc/meta.yml
- modules/nf-core/bedtools/nuc/tests/main.nf.test
- modules/nf-core/bedtools/nuc/tests/main.nf.test.snap
Closes #6783 
Was originally submitted as PR #6784, but I rebased it and the other PR got closed. I also added a check that is found in other bedtools subcommands, so there will be a warning if the input bed is the same file as the output bed file.
- For modules:
> new module: bedtools/nuc

- modules/nf-core/bcftools/annotate/main.nf
- modules/nf-core/bedtools/split/main.nf
> Some syntax updates

- modules/nf-core/elprep/fastatoelfasta/environment.yml
- modules/nf-core/elprep/fastatoelfasta/main.nf
- modules/nf-core/elprep/fastatoelfasta/meta.yml
- modules/nf-core/elprep/fastatoelfasta/tests/main.nf.test
- modules/nf-core/elprep/fastatoelfasta/tests/main.nf.test.snap
> new module elprep/fastatoelfasta

- modules/nf-core/bismark/coverage2cytosine/main.nf
- modules/nf-core/cooler/balance/main.nf
> Remove moving of input

- modules/nf-core/megahit/main.nf
> MEGAHIT: Replace ORAS with HTTPS URL for Seqera Container

- modules/nf-core/trimgalore/environment.yml
- modules/nf-core/trimgalore/main.nf
- modules/nf-core/trimgalore/tests/main.nf.test.snap
- subworkflows/nf-core/fastq_fastqc_umitools_trimgalore/tests/main.nf.test.snap
cutadapt 4.2 does not have arm-compatible conda builds, 4.9 does. So just bumped the build to pull in that newer dep. 
Closes #XXX 
- For modules:
> Bump trimgalore build for newer cutadapt

- modules/nf-core/quilt/quilt/main.nf
- modules/nf-core/quilt/quilt/meta.yml
- modules/nf-core/quilt/quilt/tests/main.nf.test
- modules/nf-core/quilt/quilt/tests/main.nf.test.snap
This PR add the bamlist file option in the input tuple for the QUILT software.
- For modules:
> Add bamlist to quilt

- modules/nf-core/svdb/build/environment.yml
- modules/nf-core/svdb/build/main.nf
- modules/nf-core/svdb/build/tests/main.nf.test.snap
- modules/nf-core/svdb/merge/environment.yml
- modules/nf-core/svdb/merge/main.nf
- modules/nf-core/svdb/merge/meta.yml
- modules/nf-core/svdb/merge/tests/main.nf.test
- modules/nf-core/svdb/merge/tests/main.nf.test.snap
- modules/nf-core/svdb/merge/tests/nextflow.config
- modules/nf-core/svdb/query/environment.yml
- modules/nf-core/svdb/query/main.nf
- modules/nf-core/svdb/query/tests/main.nf.test.snap
- Updates SVDB from 2.8.1 to 2.8.2
- Replaced bgzip with bcftools to allow for indexing 
- Fixed a bug introduced in https://github.com/nf-core/modules/pull/6794, where the --priority list would be sorted together with the vcf:prioritytag, changing the priority order. 
- Added a check for the expected priority string in the tests.
E.g. when sorting, 
```
['tiddit', 'cnvnator'] and [test2.vcf, test.vcf]
``` 
would be input as 
```
--priority cnvnantor,tiddit --vcf test.vcf:cnvnator, test2.vcf:tiddit
```
even though --priority should still be `--priority tiddit,cnvnator`.
- For modules:
> Fix and update SVDB

- subworkflows/nf-core/utils_nfschema_plugin/tests/main.nf.test
Closes https://github.com/nf-core/sarek/issues/1698 
- For modules:
> fails with lenient mode

- modules/nf-core/svdb/merge/main.nf
> Add args2 and revert default output format back to vcf.gz for SVDB merge

- modules/nf-core/mcstaging/phenoimager2mc/tests/main.nf.test
The tif test-files are now staged in a directory. This directory is passed as input to the tests.
Closes #6859 
- For modules:
> mcstaging/phenoimager2mc update nf-test file staging

- .github/workflows/test.yml
- subworkflows/nf-core/fasta_newick_epang_gappa/main.nf
- subworkflows/nf-core/fasta_newick_epang_gappa/tests/main.nf.test
Closes #XXX 
- For modules:
There was a join that assumed meta only had the `id` entry. I removed this assumption.
> Fix a join bug

- modules/nf-core/parabricks/fq2bam/main.nf
- modules/nf-core/parabricks/fq2bam/meta.yml
- modules/nf-core/parabricks/fq2bam/tests/main.nf.test
> adjust io of fq2bam to be consistent

- modules/nf-core/genmod/models/main.nf
- modules/nf-core/genmod/models/meta.yml
- modules/nf-core/genmod/models/tests/main.nf.test
- modules/nf-core/genmod/score/main.nf
- modules/nf-core/genmod/score/meta.yml
- modules/nf-core/genmod/score/tests/main.nf.test
Since the ped file required for genmod is tightly linked with the input VCF (i.e., genmod fails if there are individuals in the PED file not in the input VCF), I believe inputing them together simplifies workflows. 
- For modules:
> Change inputs for genmod

- modules/nf-core/svdb/merge/main.nf
SVDB is single-threaded and should not request more cores by default. 
Closes #XXX 
- For modules:
> Update SVDB merge label

- modules/nf-core/limma/differential/templates/limma_de.R
Just suggested tweaks for @KamilMaliszArdigen 's PR:
1. Use conditionals to avoid duplicating the `duplicateCorrelation` call
2. Check for conflicts between things we add to the model (fixed effects), and things we supply to e.g. `lmFit` via `block` (random effects).
Closes #XXX 
- For modules:
> 325 mixed model in limma jon

- modules/nf-core/quast/main.nf
This is a more recent version of the quast container, which comes with bwa in the path. See also here https://github.com/bioconda/bioconda-recipes/pull/36236
> Update quast container

- .github/scripts/wave_singularity.py
Tidy up script and make it more of a CLI tool.
Should be good to run within a GitHub Actions workflow now.
> Tidy up Python script to fetch Singularity HTTPS image URLs

- modules/nf-core/fcsgx/fetchdb/environment.yml
- modules/nf-core/fcsgx/fetchdb/main.nf
- modules/nf-core/fcsgx/fetchdb/meta.yml
- modules/nf-core/fcsgx/fetchdb/tests/main.nf.test
- modules/nf-core/fcsgx/fetchdb/tests/main.nf.test.snap
Adds a fetch db module for fcs-gx. rungx and clean to come. 
Closes #XXX 
- For modules:
> Add FCSGX_FETCHDB

- .github/workflows/wave.yml
- modules/nf-core/ale/environment.yml
That'll keep the job from running 🫠
> ci: Use correct job name

- .vscode/extensions.json
- .vscode/settings.json
https://github.com/nf-core/modules/pull/6937/files#r1829178269
This should be turned on for all nf-core repos by default now.
Snuck in some recommended extensions since the Nextflow extension should do a lot of heavy lifting now.
> Enable Harshil Alignment

- modules/nf-core/coverm/contig/environment.yml
- modules/nf-core/coverm/contig/main.nf
- modules/nf-core/coverm/contig/meta.yml
- modules/nf-core/coverm/contig/tests/main.nf.test
- modules/nf-core/coverm/contig/tests/main.nf.test.snap
Adds coverm contigs module. Closes #6950
- For modules:
> Add Coverm contigs module

- modules/nf-core/happy/sompy/main.nf
- modules/nf-core/happy/sompy/tests/main.nf.test.snap
> happy/sompy change -f to -R

- .github/workflows/wave.yml
- **ci: Allow continue on error for wave jobs for now**
- **ci: Update the event to be the PR head**
> Ignore wave being flakey

- .github/workflows/wave.yml
- modules/nf-core/fgbio/sortbam/environment.yml
https://github.com/karlhorky/github-tricks/blob/a3e5122b64e80029a5bd4706ccbdc3a1f6058fe8/readme.md?plain=1#L284-L285
> ci(wave): Get the syntax right

- modules/nf-core/trgt/genotype/environment.yml
- modules/nf-core/trgt/genotype/main.nf
- modules/nf-core/trgt/genotype/meta.yml
- modules/nf-core/trgt/genotype/tests/main.nf.test
- modules/nf-core/trgt/genotype/tests/main.nf.test.snap
Added module `trgt/genotype`. 
(Partially) closes #6984  
- For modules:
> Added module trgt/genotype

- modules/nf-core/vcf2db/environment.yml
- modules/nf-core/vcf2db/main.nf
> migrate vcf2db to wave

- .github/renovate.json5
- .github/workflows/gpu-tests.yml
- .github/workflows/nf-test.yml
- .github/workflows/pytest-workflow.yml
- .github/workflows/wave.yml
- **ci(renovate): Allow _VERSION or _VER**
- **ci: VERSION => VER**
> Fix Renovate CI versions

- .github/workflows/gpu-tests.yml
- **Purge the workspace for the self-hosted runners**
- **Purge the workspace for the GPU self-hosted runners**
Closes #XXX 
- For modules:
> Purge CI workspace before running using GPU

- modules/nf-core/regtools/junctionsextract/environment.yml
- modules/nf-core/regtools/junctionsextract/main.nf
- modules/nf-core/regtools/junctionsextract/tests/main.nf.test.snap
bump version for regtools module
- For modules:
> bump regtools version

- tests/modules/nf-core/nextclade/run/nextflow.config
During a previous PR the `nextflow.config` file in the `NEXTCLADE_RUN` process pytest was left in the folder.
- For modules:
> Remove lone nextflow.config in `NEXTCLADE_RUN` old pytest

- modules/nf-core/datavzrd/main.nf
Change from using `oras://` to `https://` in line with https://nfcore.slack.com/archives/CJRH30T6V/p1727558952383079
Closes #XXX 
- For modules:
> update datavrzd containers

- modules/nf-core/trgt/merge/main.nf
Stub honors requested output type now
- For modules:
> trgt/merge: Made extension of stub test configurable

- modules/nf-core/tcoffee/consensus/main.nf
- modules/nf-core/tcoffee/consensus/meta.yml
- For modules:
- [] `nf-core modules test <MODULE> --profile singularity`
> Fix output channel of TCOFFEE/CONSENSUS

- modules/nf-core/mafft/guidetree/meta.yml
Fix prettier MAFFT 
- For modules:
> Fix prettier mafft 

- modules/nf-core/trinity/environment.yml
- modules/nf-core/trinity/main.nf
- modules/nf-core/trinity/meta.yml
- modules/nf-core/trinity/tests/main.nf.test.snap
Updated from version 2.15.1 to 2.15.2.
Closes #XXX 
- For modules:
> Update trinity version

- modules/nf-core/samshee/environment.yml
- modules/nf-core/samshee/main.nf
- modules/nf-core/samshee/tests/main.nf.test.snap
> Attempt at fixing samshee module with latest release

- modules/nf-core/sylph/sketch/tests/main.nf.test
The lack of this is causing errors in local testing like:
```
Error: java.lang.NullPointerException: Cannot invoke "String.toLowerCase()" because the return value of "com.askimed.nf.test.core.ITaggable.getName()" is null 
```
Closes #XXX 
- For modules:
> Add name to SYLPH_SKETCH module tests

- modules/nf-core/subread/featurecounts/main.nf
- modules/nf-core/subread/featurecounts/meta.yml
- modules/nf-core/subread/featurecounts/tests/main.nf.test.snap
The examples in the docs all use txt, but I feel that's false advertising. I think this is opinated but will work out of the box with differentialabundance(I think).
> Switch featureCounts to TSV

- modules/nf-core/fq/lint/main.nf
- subworkflows/nf-core/fastq_qc_trim_filter_setstrandedness/main.nf
Two fixes to this subworkflow:
- correct badly named include alias
- move first linting until after cat'ing tech reps (otherwise arranging pairs for linting was fiddly)
Also added a missing stub to the fq/lint module itself.
Closes #XXX 
- For modules:
> Minor fixes to linting in prepro

- subworkflows/nf-core/utils_nfcore_pipeline/main.nf
Closes https://github.com/nf-core/modules/issues/7147
Closes #XXX 
- For modules:
> Convert exception obj to string

- modules/nf-core/pretextmap/main.nf
- modules/nf-core/pretextmap/tests/main.nf.test.snap
Adds `args2` for `samtools view` options since `args` is used for PretextMap and `samtools` is only optionally executed.
Closes #XXX 
- For modules:
> Add args2 to samtools view inside pretextmap

- modules/nf-core/samtools/mpileup/main.nf
> add stub test for samtools/mpileup

- subworkflows/nf-core/bam_dedup_umi/main.nf
Fixing install errors like:
```
ERROR    Module 'bam/dedup/stats/samtools/umicollapse' not found in available modules      
```
Closes #XXX 
- For modules:
> Fix subworkflow imports for bam_dedup_umi

- .github/workflows/pytest-workflow.yml
- tests/config/nextflow.config
Use same conda install and conda config from nf-test for pytest, as done in #7215 
Closes #XXX 
- For modules:
> Fix conda pytests cf #7215

- modules/nf-core/homer/findpeaks/tests/main.nf.test
- modules/nf-core/homer/findpeaks/tests/main.nf.test.snap
- subworkflows/nf-core/homer_groseq/tests/main.nf.test
- subworkflows/nf-core/homer_groseq/tests/main.nf.test.snap
- **test(homer): Add uniqmap module test**
- **test: Add snapshot for readLines**
- **test(homer): Add subworkflow uniqmap test**
- **fix: Get rid of tuple error**
> Add HOMER Uniqmap tests

- modules/nf-core/metamdbg/asm/environment.yml
- modules/nf-core/metamdbg/asm/main.nf
- modules/nf-core/metamdbg/asm/tests/main.nf.test.snap
> Bump metamdbg version and update snapshot

- modules/nf-core/deseq2/differential/templates/deseq2_differential.R
Related to https://github.com/nf-core/website/pull/2888
- For modules:
> DESeq2 R script make r.version export more readable

- modules/nf-core/flye/main.nf
This PR switches the ORAS container to http and updates the docker container as well, as the tag seemed outdated when building the container with Seqera.
- For modules:
> Change flye oras container

- subworkflows/nf-core/fastq_fastqc_umitools_fastp/tests/main.nf.test.snap
Somehow the tests for this subworkflow got broken in place (i think as part of https://github.com/nf-core/modules/pull/7207)- I'm just refreshing them here. 
Closes #XXX 
- For modules:
> Refresh test snap for fastq_fastqc_umitools_fastp

- modules/nf-core/checkm2/predict/tests/main.nf.test
- modules/nf-core/checkm2/predict/tests/main.nf.test.snap
- tests/config/nf-test.config
replaces #7271 
reverting to the old settings hoping this will fix the error:
```
touch: cannot touch '.command.trace': Permission denied
```
> Fix docker ownserhip issue and remove userEmulation

- modules/nf-core/star/align/main.nf
> fix star align language server errors

- .github/workflows/gpu-tests.yml
to have a more fine-grained rules for status checks
> differentiate between different confirm-pass actions

- modules/nf-core/hifiasm/environment.yml
- modules/nf-core/hifiasm/main.nf
- modules/nf-core/hifiasm/tests/main.nf.test.snap
Update hifiasm from 0.21 to 0.24 
* bump hifiasm version
* snap
* all 7 tests passed (via docker)
> bump hifiasm version to 0.24.0-r702

- modules/nf-core/lima/environment.yml
- modules/nf-core/lima/main.nf
- modules/nf-core/lima/tests/main.nf.test
- modules/nf-core/lima/tests/main.nf.test.snap
> Bumped lima to 2.12.0

- modules/nf-core/agat/convertspgff2gtf/environment.yml
- modules/nf-core/agat/convertspgff2gtf/main.nf
- modules/nf-core/agat/convertspgff2gtf/tests/main.nf.test.snap
- modules/nf-core/agat/convertspgff2tsv/environment.yml
- modules/nf-core/agat/convertspgff2tsv/main.nf
- modules/nf-core/agat/convertspgff2tsv/tests/main.nf.test.snap
- modules/nf-core/agat/convertspgxf2gxf/environment.yml
- modules/nf-core/agat/convertspgxf2gxf/main.nf
- modules/nf-core/agat/convertspgxf2gxf/tests/main.nf.test.snap
- modules/nf-core/agat/spaddintrons/environment.yml
- modules/nf-core/agat/spaddintrons/main.nf
- modules/nf-core/agat/spaddintrons/tests/main.nf.test.snap
- modules/nf-core/agat/spfilterfeaturefromkilllist/environment.yml
- modules/nf-core/agat/spfilterfeaturefromkilllist/main.nf
- modules/nf-core/agat/spfilterfeaturefromkilllist/tests/main.nf.test
- modules/nf-core/agat/spfilterfeaturefromkilllist/tests/main.nf.test.snap
- modules/nf-core/agat/spmergeannotations/environment.yml
- modules/nf-core/agat/spmergeannotations/main.nf
- modules/nf-core/agat/spmergeannotations/tests/main.nf.test
- modules/nf-core/agat/spmergeannotations/tests/main.nf.test.snap
- modules/nf-core/agat/spstatistics/environment.yml
- modules/nf-core/agat/spstatistics/main.nf
- modules/nf-core/agat/spstatistics/tests/main.nf.test.snap
- modules/nf-core/agat/sqstatbasic/environment.yml
- modules/nf-core/agat/sqstatbasic/main.nf
- modules/nf-core/agat/sqstatbasic/tests/main.nf.test.snap
> Bumped agat modules

- modules/nf-core/shinyngs/staticdifferential/main.nf
- modules/nf-core/shinyngs/staticdifferential/tests/main.nf.test.snap
- modules/nf-core/shinyngs/validatefomcomponents/main.nf
- modules/nf-core/shinyngs/validatefomcomponents/tests/main.nf.test.snap
> Removed r-base from versions.yml

- .github/actions/get-shards/action.yml
- .github/actions/nf-test-action/action.yml
- .github/workflows/nf-test.yml
Successfully tested in https://github.com/nf-core/modules/pull/7274
> fix filter value for nf-test dry-run

- modules/nf-core/last/dotplot/environment.yml
- modules/nf-core/last/dotplot/main.nf
- modules/nf-core/last/dotplot/tests/main.nf.test.snap
- modules/nf-core/last/lastal/environment.yml
- modules/nf-core/last/lastal/main.nf
- modules/nf-core/last/lastal/tests/main.nf.test.snap
- modules/nf-core/last/lastdb/environment.yml
- modules/nf-core/last/lastdb/main.nf
- modules/nf-core/last/lastdb/tests/main.nf.test.snap
- modules/nf-core/last/mafconvert/environment.yml
- modules/nf-core/last/mafconvert/main.nf
- modules/nf-core/last/mafconvert/tests/main.nf.test.snap
- modules/nf-core/last/mafswap/environment.yml
- modules/nf-core/last/mafswap/main.nf
- modules/nf-core/last/mafswap/tests/main.nf.test
- modules/nf-core/last/mafswap/tests/main.nf.test.snap
- modules/nf-core/last/postmask/environment.yml
- modules/nf-core/last/postmask/main.nf
- modules/nf-core/last/postmask/tests/main.nf.test.snap
- modules/nf-core/last/split/environment.yml
- modules/nf-core/last/split/main.nf
- modules/nf-core/last/split/tests/main.nf.test.snap
- modules/nf-core/last/train/environment.yml
- modules/nf-core/last/train/main.nf
- modules/nf-core/last/train/tests/main.nf.test.snap
This version will be needed for the use of the new `maf-linked` tool later.
- For modules:
> Update to LAST version 1608 using sequera containers.

- modules/nf-core/catpack/bins/environment.yml
- modules/nf-core/catpack/bins/main.nf
- modules/nf-core/catpack/bins/meta.yml
- modules/nf-core/catpack/bins/tests/main.nf.test
- modules/nf-core/catpack/bins/tests/main.nf.test.snap
- modules/nf-core/catpack/bins/tests/nextflow.config
CONTIGS and BINS are pretty much the same command but with slightly different input.
When making BINS I realised  I missed a couple of optional inputs for CONTIGS, so I've included them here.
Closes #5588 
- For modules:
> Add CATPACK_BINS (add missing optional input files CATPACK_CONTIGS)

- .devcontainer/devcontainer.json
> Use the correct syntax for devcontainer features

- modules/nf-core/trgt/genotype/environment.yml
- modules/nf-core/trgt/genotype/main.nf
- modules/nf-core/trgt/genotype/tests/main.nf.test.snap
- modules/nf-core/trgt/merge/environment.yml
- modules/nf-core/trgt/merge/main.nf
- modules/nf-core/trgt/merge/tests/main.nf.test.snap
- modules/nf-core/trgt/plot/environment.yml
- modules/nf-core/trgt/plot/main.nf
- modules/nf-core/trgt/plot/tests/main.nf.test.snap
> Bump TRGT to 1.5.0

- modules/nf-core/gatk4/baserecalibrator/main.nf
- modules/nf-core/gatk4/baserecalibrator/meta.yml
- modules/nf-core/gatk4/baserecalibrator/tests/main.nf.test
- modules/nf-core/gatk4/baserecalibrator/tests/main.nf.test.snap
> FEAT: add meta to gatk4/baserecalibrator

- modules/nf-core/dastool/dastool/main.nf
- modules/nf-core/dastool/fastatocontig2bin/main.nf
Old image still depends on `defaults` - bump to new container.
Closes #XXX 
- For modules:
> Bump DAS_Tool container version

- modules/nf-core/ensemblvep/vep/main.nf
- modules/nf-core/ensemblvep/vep/meta.yml
- modules/nf-core/ensemblvep/vep/tests/main.nf.test
- modules/nf-core/ensemblvep/vep/tests/main.nf.test.snap
> tabix vep output

- modules/nf-core/ensemblvep/vep/main.nf
> fix issue in tabix VEP PR

- modules/nf-core/paraphase/environment.yml
- modules/nf-core/paraphase/main.nf
- modules/nf-core/paraphase/tests/main.nf.test
- modules/nf-core/paraphase/tests/main.nf.test.snap
> Bump paraphase to 3.2.0

- modules/nf-core/bcftools/concat/main.nf
- modules/nf-core/bcftools/concat/meta.yml
- modules/nf-core/bcftools/concat/tests/main.nf.test.snap
- Don't try to tabix if the index exists as csi
- Output filename based on `--output-type`. 
- For modules:
> Fix bcftools concat

- modules/nf-core/haplogrep3/classify/environment.yml
- modules/nf-core/haplogrep3/classify/main.nf
- modules/nf-core/haplogrep3/classify/meta.yml
- modules/nf-core/haplogrep3/classify/tests/main.nf.test
- modules/nf-core/haplogrep3/classify/tests/main.nf.test.snap
- modules/nf-core/haplogrep3/classify/tests/nextflow.config
> Add haplogrep3

- modules/nf-core/find/unpigz/main.nf
- modules/nf-core/find/unpigz/tests/main.nf.test
- modules/nf-core/find/unpigz/tests/main.nf.test.snap
> Fix find/unpigz input arity, currently it crashes on single files

- modules/nf-core/anota2seq/anota2seqrun/templates/anota2seqrun.r
See https://github.com/nf-core/riboseq/pull/88
Closes #XXX 
- For modules:
> Update anota2seqrun.r for minor order fix

- modules/nf-core/antismash/antismashlite/tests/main.nf.test
> ANTISMASH/ANTISMASHLITE: Remove debug tag from tests

- modules/nf-core/anota2seq/anota2seqrun/templates/anota2seqrun.r
> readded backslashes

- modules/nf-core/liftoff/main.nf
- modules/nf-core/liftoff/meta.yml
- modules/nf-core/liftoff/tests/main.nf.test
This PR implements #7342. I have updated the script and meta.yml
> liftoff: allow gzipped fasta inputs

- subworkflows/nf-core/differential_functional_enrichment/meta.yml
- subworkflows/nf-core/differential_functional_enrichment/tests/main.nf.test
> [linting] fix linting for differential_functional_enrichment subworkflow

- subworkflows/nf-core/bam_dedup_umi/tests/main.nf.test
- subworkflows/nf-core/fastq_qc_trim_filter_setstrandedness/meta.yml
- subworkflows/nf-core/fastq_qc_trim_filter_setstrandedness/tests/main.nf.test
> Fix some subworkflow linting issues

- modules/nf-core/cellpose/main.nf
Aims to replace hardcoded version with extract of `cellpose --version`.
Closes #7420 
- For modules:
> update module: CELLPOSE

- tests/config/test_data.config
> Update test_data.config with streptococcus_agalactiae

- modules/nf-core/find/unpigz/main.nf
- modules/nf-core/find/unpigz/meta.yml
- modules/nf-core/find/unpigz/tests/main.nf.test
- modules/nf-core/find/unpigz/tests/main.nf.test.snap
> Fix find/unpigz add more test assertions

- modules/nf-core/learnmsa/align/tests/nextflow.config
Add comment to LearnMSA explaining why we have overwritten the container
- For modules:
> Add comment to LearnMSA

- modules/nf-core/metamdbg/asm/main.nf
> Remove switch statement from metamdbg/asm for language server compatibility

- modules/nf-core/samtools/sormadup/main.nf
- modules/nf-core/samtools/sormadup/tests/bam.config
- modules/nf-core/samtools/sormadup/tests/cram.config
- modules/nf-core/samtools/sormadup/tests/main.nf.test
- modules/nf-core/samtools/sormadup/tests/main.nf.test.snap
> enable cram output for samtools_sormadup

- modules/nf-core/svtools/vcftobedpe/environment.yml
- modules/nf-core/svtools/vcftobedpe/main.nf
- modules/nf-core/svtools/vcftobedpe/meta.yml
- modules/nf-core/svtools/vcftobedpe/tests/main.nf.test
- modules/nf-core/svtools/vcftobedpe/tests/main.nf.test.snap
> new module svtools/vcftobedpe

- modules/nf-core/fastp/meta.yml
Fixes the description string in the meta.yml of Fastp.
- For modules:
> Fix description string in Yaml

- modules/nf-core/simpleaf/index/environment.yml
- modules/nf-core/simpleaf/index/main.nf
- modules/nf-core/simpleaf/index/tests/main.nf.test.snap
- modules/nf-core/simpleaf/quant/environment.yml
- modules/nf-core/simpleaf/quant/main.nf
- modules/nf-core/simpleaf/quant/tests/main.nf.test.snap
Upgrade simpleaf to 0.19.2 for gene id to name mapping conversion.
- For modules:
> Upgrade to simpleaf 0.19.2

- modules/nf-core/paraphase/environment.yml
- modules/nf-core/paraphase/main.nf
- modules/nf-core/paraphase/tests/main.nf.test.snap
> Bump Paraphase

- modules/nf-core/upp/align/environment.yml
- modules/nf-core/upp/align/main.nf
- modules/nf-core/upp/align/tests/main.nf.test.snap
Update UPP container
The previous container was not working properly, see [here](https://github.com/nf-core/multiplesequencealign/issues/194). 
We tried to contact the owner of the repo to fix the bioconda recipe but we currently have no answer. At the moment we created a Docker container to have at least docker and singularity functional and as soon as the tool is in bioconda we will update the module.
- For modules:
> Update UPP container

- modules/nf-core/bcftools/call/main.nf
- modules/nf-core/bcftools/mpileup/main.nf
- modules/nf-core/bcftools/pluginimputeinfo/main.nf
- modules/nf-core/bcftools/pluginsetgt/main.nf
- modules/nf-core/bcftools/plugintag2tag/main.nf
- modules/nf-core/bcftools/view/main.nf
> fix: language server related issue with bcftools

- modules/nf-core/delly/call/environment.yml
- modules/nf-core/delly/call/main.nf
- modules/nf-core/delly/call/tests/main.nf.test.snap
> bump delly to 1.3.3

- modules/nf-core/custom/tabulartogseacls/environment.yml
- modules/nf-core/custom/tabulartogseagct/environment.yml
- modules/nf-core/gprofiler2/gost/main.nf
- modules/nf-core/gprofiler2/gost/templates/gprofiler2_gost.R
- modules/nf-core/gprofiler2/gost/tests/main.nf.test.snap
- subworkflows/nf-core/differential_functional_enrichment/tests/main.nf.test.snap
Addressing comments from this PR in differentialabundance https://github.com/nf-core/differentialabundance/pull/420
- For modules:
> Updates  to differentialabundance modules

- modules/nf-core/tcoffee/align/environment.yml
- modules/nf-core/tcoffee/align/main.nf
- modules/nf-core/tcoffee/regressive/main.nf
Add tmalign to tcoffee/align 
Once the next bioconda build is fixed, we will update all the modules 
- For modules:
> Add tmalign to tcoffee/align 

- modules/nf-core/tagbam/environment.yml
- modules/nf-core/tagbam/main.nf
- modules/nf-core/tagbam/meta.yml
- modules/nf-core/tagbam/tests/main.nf.test
- modules/nf-core/tagbam/tests/main.nf.test.snap
- modules/nf-core/tagbam/tests/nextflow.config
- modules/nf-core/tagbam/tests/tags.yml
> Add new module tagbam

- modules/nf-core/pigz/uncompress/main.nf
- modules/nf-core/pigz/uncompress/tests/main.nf.test.snap
> extra parenthesis removed

- modules/nf-core/pigz/uncompress/main.nf
> put tag back into module

- modules/nf-core/clipkit/environment.yml
- modules/nf-core/clipkit/main.nf
- modules/nf-core/clipkit/meta.yml
- modules/nf-core/clipkit/tests/main.nf.test
- modules/nf-core/clipkit/tests/main.nf.test.snap
- modules/nf-core/clipkit/tests/nextflow.config
(conda tests will pass as soon as update 2.4.1 is live)
New version allows trimming MSAs only at the ends.
Added log file output.
Added input option to change the output format.
Added alternative mode test, with gap threshold and trim ends only flag
- For modules:
> Version update clipkit (2.4.1)

- modules/nf-core/clipkit/meta.yml
log output description text fix
> log descr fix

- subworkflows/nf-core/abundance_differential_filter/main.nf
> somehow this change is removed from the previous pr. put it back here

- modules/nf-core/fqtk/environment.yml
- modules/nf-core/fqtk/main.nf
> Update fqtk to 0.3.1

- modules/nf-core/quilt/quilt/meta.yml
Remove extra space in the meta.yml of `QUILT`
- For modules:
> `QUILT` Remove extra space in meta.yml

- modules/nf-core/star/indexversion/meta.yml
> Fix linting error in `star/indexversion`

- modules/nf-core/blat/environment.yml
- modules/nf-core/blat/main.nf
- modules/nf-core/blat/tests/main.nf.test.snap
> Update blat to use ucsc-blat recipe(s)

- .github/workflows/nf-test-gpu.yml
follow up on https://github.com/nf-core/modules/pull/7406
Closes #XXX 
- For modules:
> don't run GPU nf-test if only meta.yml was changed

- .github/workflows/skipped-nf-test-gpu.yml
- .github/workflows/skipped-nf-test.yml
Replace https://github.com/nf-core/modules/pull/7528
> add GHA to pass required tests when skipped

- subworkflows/nf-core/vcf_impute_glimpse/tests/main.nf.test
- subworkflows/nf-core/vcf_impute_glimpse/tests/main.nf.test.snap
Closes #6186
We moved the path to hum_data as we also now use dog_data in phaseimpute pipeline.
- For modules:
> Fix `VCF_IMPUTE_GLIMPSE` nf-test

- README.md
> Add bluesky link

- modules/nf-core/svdb/merge/main.nf
> Fix language server issues in SVDB/merge

- modules/nf-core/longphase/phase/main.nf
> Fix language server issues for longphase/phase

- subworkflows/nf-core/abundance_differential_filter/meta.yml
How did it get through linting like that?
> Add missing metadata values

- modules/nf-core/hifiasm/main.nf
- modules/nf-core/hifiasm/tests/main.nf.test
- modules/nf-core/hifiasm/tests/main.nf.test.snap
Hifiasm supports multiple input files from the same sample, but it seems like the output files are different depending on the order of the input files. This PR sorts the inputs.
Closes #XXX 
- For modules:
> Sort hifiasm inputs

- modules/nf-core/simpleaf/index/environment.yml
- modules/nf-core/simpleaf/index/main.nf
- modules/nf-core/simpleaf/index/tests/main.nf.test
- modules/nf-core/simpleaf/index/tests/main.nf.test.snap
- modules/nf-core/simpleaf/quant/environment.yml
- modules/nf-core/simpleaf/quant/main.nf
- modules/nf-core/simpleaf/quant/tests/main.nf.test
- modules/nf-core/simpleaf/quant/tests/main.nf.test.snap
Closes #XXX 
- [] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- For modules:
> update simpleaf version to 0.19.3

- modules/nf-core/sylph/profile/main.nf
- modules/nf-core/sylph/profile/tests/main.nf.test
- modules/nf-core/sylph/profile/tests/main.nf.test.snap
- modules/nf-core/sylphtax/taxprof/tests/main.nf.test
- modules/nf-core/sylphtax/taxprof/tests/main.nf.test.snap
This PR updates the order in input arguments for `sylph profile` module.
- For modules:
> Update order in input for sylph profile

- modules/nf-core/stranger/environment.yml
- modules/nf-core/stranger/main.nf
- modules/nf-core/stranger/tests/main.nf.test.snap
> Bump stranger

- modules/nf-core/snpeff/snpeff/main.nf
- modules/nf-core/snpeff/snpeff/tests/main.nf.test
- modules/nf-core/snpeff/snpeff/tests/main.nf.test.snap
> fix snpeff stub

- modules/nf-core/samtools/fastq/main.nf
- modules/nf-core/samtools/fastq/tests/main.nf.test
- modules/nf-core/samtools/fastq/tests/main.nf.test.snap
> Add stubs to samtools/fastq

- modules/nf-core/stranger/main.nf
- modules/nf-core/stranger/tests/main.nf.test.snap
Closes #7751 
Closes #XXX 
- For modules:
> Fix stranger version

- modules/nf-core/last/dotplot/environment.yml
- modules/nf-core/last/dotplot/main.nf
- modules/nf-core/last/dotplot/tests/main.nf.test.snap
- modules/nf-core/last/lastal/environment.yml
- modules/nf-core/last/lastal/main.nf
- modules/nf-core/last/lastal/tests/main.nf.test.snap
- modules/nf-core/last/lastdb/environment.yml
- modules/nf-core/last/lastdb/main.nf
- modules/nf-core/last/lastdb/tests/main.nf.test.snap
- modules/nf-core/last/mafconvert/environment.yml
- modules/nf-core/last/mafconvert/main.nf
- modules/nf-core/last/mafconvert/tests/main.nf.test.snap
- modules/nf-core/last/mafswap/environment.yml
- modules/nf-core/last/mafswap/main.nf
- modules/nf-core/last/mafswap/tests/main.nf.test.snap
- modules/nf-core/last/postmask/environment.yml
- modules/nf-core/last/postmask/main.nf
- modules/nf-core/last/postmask/tests/main.nf.test.snap
- modules/nf-core/last/split/environment.yml
- modules/nf-core/last/split/main.nf
- modules/nf-core/last/split/tests/main.nf.test.snap
- modules/nf-core/last/train/environment.yml
- modules/nf-core/last/train/main.nf
- modules/nf-core/last/train/tests/main.nf.test.snap
For `last/mafconvert`, this is an important update that fixes a bug where long hard-clipping lengths in CIGAR lines would go over the maximal limit of 268435455 for BAM and CRAM files.
Other modules are also updated for the sake of consistency but there should be no difference other than MD5 sums changing in files that contain the version number.
Closes #XXX 
- For modules:
> Update `last/*` modules to version 1611 from version 1608.

- modules/nf-core/stranger/main.nf
Closes #5873 
Closes #XXX 
- For modules:
> Stranger name collision warning

- modules/nf-core/severus/main.nf
- modules/nf-core/severus/meta.yml
- modules/nf-core/severus/tests/main.nf.test.snap
Closes #XXX 
- For modules:
File name for severus_somatic vcf was wrong leading to it not being put in output correctly
> Change file name for severus_somatic.vcf

- modules/nf-core/samtools/convert/main.nf
- modules/nf-core/samtools/convert/tests/main.nf.test.snap
> fix samtools/convert stub

- modules/nf-core/salmon/quant/main.nf
> Fix language server error in salmon/quant

- modules/nf-core/arriba/arriba/main.nf
> Fix language server errors in arriba/arriba

- modules/nf-core/dshbio/exportsegments/environment.yml
- modules/nf-core/dshbio/exportsegments/main.nf
- modules/nf-core/dshbio/exportsegments/tests/main.nf.test.snap
- modules/nf-core/dshbio/filterbed/environment.yml
- modules/nf-core/dshbio/filterbed/main.nf
- modules/nf-core/dshbio/filterbed/tests/main.nf.test
- modules/nf-core/dshbio/filterbed/tests/main.nf.test.snap
- modules/nf-core/dshbio/filterbed/tests/nextflow.config
- modules/nf-core/dshbio/filtergff3/environment.yml
- modules/nf-core/dshbio/filtergff3/main.nf
- modules/nf-core/dshbio/filtergff3/tests/main.nf.test.snap
- modules/nf-core/dshbio/splitbed/environment.yml
- modules/nf-core/dshbio/splitbed/main.nf
- modules/nf-core/dshbio/splitbed/tests/main.nf.test
- modules/nf-core/dshbio/splitbed/tests/main.nf.test.snap
- modules/nf-core/dshbio/splitgff3/environment.yml
- modules/nf-core/dshbio/splitgff3/main.nf
- modules/nf-core/dshbio/splitgff3/tests/main.nf.test.snap
> Update dsh-bio to 3.0

- modules/nf-core/ivar/consensus/environment.yml
- modules/nf-core/ivar/consensus/main.nf
- modules/nf-core/ivar/consensus/tests/main.nf.test
- modules/nf-core/ivar/consensus/tests/main.nf.test.snap
- modules/nf-core/ivar/trim/environment.yml
- modules/nf-core/ivar/trim/main.nf
- modules/nf-core/ivar/trim/tests/main.nf.test
- modules/nf-core/ivar/trim/tests/main.nf.test.snap
- modules/nf-core/ivar/variants/environment.yml
- modules/nf-core/ivar/variants/main.nf
- modules/nf-core/ivar/variants/tests/main.nf.test.snap
`ivar version` returns:
```
iVar version 1.4.3
Please raise issues and bug reports at https://github.com/andersen-lab/ivar/
```
Second line has to be removed to get `[process IVAR_VARIANTS:[ivar:1.4.3]]` properly. This was already fixed in [ivar trim module](https://github.com/nf-core/modules/blob/ce475295fb2edd3264ca8481fa9324a9c90753a5/modules/nf-core/ivar/trim/main.nf#L48). Using that fix for other ivar modules.
Snapshots have being simplified for ivar trim and consensus to make them the same as ivar variants. 
Snapshots have been updated accordingly.
Closes #XXX 
- For modules:
> Fixed ivar modules

- modules/nf-core/deepvariant/makeexamples/main.nf
- modules/nf-core/deepvariant/rundeepvariant/main.nf
Closes [#7900](https://github.com/nf-core/modules/issues/7900)
It seems that empty .gz files generated by simply touch .gz break the snapshot functionality of nf-test by causing an EOFException because the files are not actually compressed.
A fix is to replace the touch command with echo "" | gzip > <filename>.gz
> Updated deevariant to avoid failing nf-test

- modules/nf-core/tabix/bgzip/tests/main.nf.test
- modules/nf-core/tabix/bgziptabix/tests/main.nf.test
- modules/nf-core/tabix/tabix/tests/main.nf.test
> fix path to TABIX

- modules/nf-core/windowmasker/convert/tests/convert_binary.config
- modules/nf-core/windowmasker/convert/tests/convert_oascii.config
- modules/nf-core/windowmasker/convert/tests/main.nf.test
- modules/nf-core/windowmasker/convert/tests/nextflow.config
Unifies the windowmasker config to follow module guidelines: https://nf-co.re/docs/guidelines/components/modules#configuration-of-extargs-in-tests
- For modules:
> Unify windowmasker config

- modules/nf-core/angsd/gl/tests/config_gl_2.conf
- modules/nf-core/angsd/gl/tests/config_gl_3.conf
- modules/nf-core/angsd/gl/tests/config_gl_4.conf
- modules/nf-core/angsd/gl/tests/main.nf.test
- modules/nf-core/angsd/gl/tests/nextflow.config
Unifies the configs following the guidelines https://nf-co.re/docs/guidelines/components/modules#configuration-of-extargs-in-tests
- For modules:
> unify angsd gl configs

- .github/CODEOWNERS
> Add @pinin4fjords as codeowner on key contributions

- modules/nf-core/bbmap/bbduk/main.nf
> Fixed `bbduk/bbmap` versions.yml line

- modules/nf-core/annosine/environment.yml
- modules/nf-core/annosine/main.nf
- modules/nf-core/annosine/meta.yml
- modules/nf-core/annosine/tests/main.nf.test
- modules/nf-core/annosine/tests/main.nf.test.snap
- modules/nf-core/annosine/tests/nextflow.config
> Added annosine

- modules/nf-core/nanoplot/environment.yml
- modules/nf-core/nanoplot/main.nf
- modules/nf-core/nanoplot/tests/main.nf.test.snap
Related to https://github.com/nf-core/viralrecon/issues/466  
- For modules:
> update nanoplot to latest available version

- modules/nf-core/gatk/unifiedgenotyper/main.nf
Reverts nf-core/modules#8156
Nevermind it breaks nf-core/eager downstream
> Revert "Update UnifiedGenotyper"

- modules/nf-core/helitronscanner/scan/environment.yml
- modules/nf-core/helitronscanner/scan/main.nf
- modules/nf-core/helitronscanner/scan/meta.yml
- modules/nf-core/helitronscanner/scan/tests/main.nf.test
- modules/nf-core/helitronscanner/scan/tests/main.nf.test.snap
> Added helitronscanner/scan

- modules/nf-core/fastp/environment.yml
- modules/nf-core/fastp/main.nf
- modules/nf-core/fastp/tests/main.nf.test.snap
- subworkflows/nf-core/fastq_fastqc_umitools_fastp/tests/main.nf.test.snap
- subworkflows/nf-core/fastq_trim_fastp_fastqc/tests/main.nf.test.snap
> update fastp to latest version, snapshots updated

- modules/nf-core/cutadapt/environment.yml
- modules/nf-core/cutadapt/main.nf
- modules/nf-core/cutadapt/tests/main.nf.test.snap
> update cutadapt module to latest version

- modules/nf-core/blast/blastdbcmd/environment.yml
- modules/nf-core/blast/blastdbcmd/main.nf
- modules/nf-core/blast/blastdbcmd/tests/main.nf.test.snap
- modules/nf-core/blast/blastn/environment.yml
- modules/nf-core/blast/blastn/main.nf
- modules/nf-core/blast/blastn/tests/main.nf.test.snap
- modules/nf-core/blast/blastp/environment.yml
- modules/nf-core/blast/blastp/main.nf
- modules/nf-core/blast/blastp/tests/main.nf.test.snap
- modules/nf-core/blast/makeblastdb/environment.yml
- modules/nf-core/blast/makeblastdb/main.nf
- modules/nf-core/blast/makeblastdb/tests/main.nf.test.snap
- modules/nf-core/blast/tblastn/environment.yml
- modules/nf-core/blast/tblastn/main.nf
- modules/nf-core/blast/tblastn/tests/main.nf.test.snap
update_blastdb couldn't be updated, tests failed after update.
- For modules:
> Update blast modules to latest version

- modules/nf-core/blast/updateblastdb/environment.yml
- modules/nf-core/blast/updateblastdb/main.nf
- modules/nf-core/blast/updateblastdb/tests/main.nf.test.snap
Updating the missing module from #8179
> Update version for updateblastdb

- modules/nf-core/fastqc/main.nf
> Change FastQC memory parameter from float to int

- modules/nf-core/bandage/image/environment.yml
- modules/nf-core/bandage/image/main.nf
- modules/nf-core/bandage/image/tests/main.nf.test.snap
> updated bandage image to latest version

- modules/nf-core/freyja/boot/environment.yml
- modules/nf-core/freyja/boot/main.nf
- modules/nf-core/freyja/boot/tests/main.nf.test.snap
- modules/nf-core/freyja/demix/environment.yml
- modules/nf-core/freyja/demix/main.nf
- modules/nf-core/freyja/demix/tests/main.nf.test.snap
- modules/nf-core/freyja/update/environment.yml
- modules/nf-core/freyja/update/main.nf
- modules/nf-core/freyja/update/meta.yml
- modules/nf-core/freyja/update/tests/main.nf.test.snap
- modules/nf-core/freyja/variants/environment.yml
- modules/nf-core/freyja/variants/main.nf
- modules/nf-core/freyja/variants/tests/main.nf.test.snap
- subworkflows/nf-core/bam_variant_demix_boot_freyja/tests/main.nf.test.snap
- **updated freyja update to latest version**
- **updated freyja variants to latest version**
- **updated freyja boot to latest release**
- **updated freyja demix to latest release**
- **fix freyja update and variants with fixed bioconda recipe**
- **updated snapshot for subworkflow after freyja update**
Bioconda recipe was fixed in the process to fix dependency errors: 
https://github.com/bioconda/bioconda-recipes/pull/55002
Related to  https://github.com/nf-core/viralrecon/issues/466 
- For modules:
> update freyja module to latest version

- modules/nf-core/artic/guppyplex/environment.yml
- modules/nf-core/artic/guppyplex/main.nf
- modules/nf-core/artic/guppyplex/tests/main.nf.test.snap
- modules/nf-core/artic/minion/environment.yml
- modules/nf-core/artic/minion/main.nf
- modules/nf-core/artic/minion/tests/main.nf.test.snap
> updated artic to latest version

- modules/nf-core/shinyngs/app/environment.yml
- modules/nf-core/shinyngs/app/main.nf
- modules/nf-core/shinyngs/app/tests/main.nf.test.snap
- modules/nf-core/shinyngs/staticdifferential/environment.yml
- modules/nf-core/shinyngs/staticdifferential/main.nf
- modules/nf-core/shinyngs/staticdifferential/tests/main.nf.test.snap
- modules/nf-core/shinyngs/staticexploratory/environment.yml
- modules/nf-core/shinyngs/staticexploratory/main.nf
- modules/nf-core/shinyngs/staticexploratory/tests/main.nf.test.snap
- modules/nf-core/shinyngs/validatefomcomponents/environment.yml
- modules/nf-core/shinyngs/validatefomcomponents/main.nf
- modules/nf-core/shinyngs/validatefomcomponents/tests/main.nf.test.snap
> Update shinyngs modules

- .github/actions/nf-test-action/action.yml
- .github/workflows/update-gpu-snapshot.yml
untested, but I basically tried to copy the logic from the linter action. Be aware that the comment format is 
`@nf-core-bot update gpu snapshot path: $PATH` otherwise nothing will happen.
> add gpu snapshot updater action

- .github/workflows/nf-test-gpu.yml
- .github/workflows/update-gpu-snapshot.yml
should fix https://github.com/nf-core/modules/actions/runs/14240420610/job/39908852967#step:13:754
> run update snapshot on gpu runners

- .github/skip_nf_test.json
- modules/nf-core/ensemblvep/download/environment.yml
- modules/nf-core/ensemblvep/download/main.nf
- modules/nf-core/ensemblvep/filtervep/environment.yml
- modules/nf-core/ensemblvep/filtervep/main.nf
- modules/nf-core/ensemblvep/vep/environment.yml
- modules/nf-core/ensemblvep/vep/main.nf
> update vep to 113.4 and redo conda tests

- modules/nf-core/ragtag/patch/main.nf
I forgot to re-enable logging after testing if killing tail helps with the CI job getting stuck.
> Uncomment logging.

- modules/nf-core/dragmap/hashtable/tests/main.nf.test
- modules/nf-core/dragmap/hashtable/tests/main.nf.test.snap
> dragmap hashtable - snapshot versions

- modules/nf-core/porechop/abi/meta.yml
> Fix prettier porechop meta

- modules/nf-core/hmmer/jackhmmer/environment.yml
- modules/nf-core/hmmer/jackhmmer/main.nf
- modules/nf-core/hmmer/jackhmmer/meta.yml
- modules/nf-core/hmmer/jackhmmer/tests/main.nf.test
- modules/nf-core/hmmer/jackhmmer/tests/main.nf.test.snap
> add hmmer/jackhmmer module

- modules/nf-core/strdust/environment.yml
- modules/nf-core/strdust/main.nf
- modules/nf-core/strdust/tests/main.nf.test.snap
> Bump STRdust to 0.11.4

- modules/nf-core/modkit/pileup/environment.yml
- modules/nf-core/modkit/pileup/main.nf
- modules/nf-core/modkit/pileup/tests/main.nf.test.snap
> Bump modkit to 0.4.4

- modules/nf-core/severus/environment.yml
- modules/nf-core/severus/main.nf
- modules/nf-core/severus/tests/main.nf.test.snap
> Bump Severus to 1.5

- modules/nf-core/trgt/genotype/environment.yml
- modules/nf-core/trgt/genotype/main.nf
- modules/nf-core/trgt/genotype/tests/main.nf.test
- modules/nf-core/trgt/genotype/tests/main.nf.test.snap
- modules/nf-core/trgt/merge/environment.yml
- modules/nf-core/trgt/merge/main.nf
- modules/nf-core/trgt/merge/tests/main.nf.test
- modules/nf-core/trgt/merge/tests/main.nf.test.snap
- modules/nf-core/trgt/plot/environment.yml
- modules/nf-core/trgt/plot/main.nf
- modules/nf-core/trgt/plot/tests/main.nf.test
- modules/nf-core/trgt/plot/tests/main.nf.test.snap
> Bump TRGT to 2.0.0

- modules/nf-core/hifiasm/environment.yml
- modules/nf-core/hifiasm/main.nf
- modules/nf-core/hifiasm/tests/main.nf.test.snap
> Bump hifiasm to 0.25.0

- modules/nf-core/genmod/annotate/environment.yml
- modules/nf-core/genmod/annotate/main.nf
- modules/nf-core/genmod/annotate/tests/main.nf.test.snap
- modules/nf-core/genmod/compound/environment.yml
- modules/nf-core/genmod/compound/main.nf
- modules/nf-core/genmod/compound/tests/main.nf.test.snap
- modules/nf-core/genmod/models/environment.yml
- modules/nf-core/genmod/models/main.nf
- modules/nf-core/genmod/models/tests/main.nf.test.snap
- modules/nf-core/genmod/score/environment.yml
- modules/nf-core/genmod/score/main.nf
- modules/nf-core/genmod/score/tests/main.nf.test.snap
> Bump genmod to 3.10.1

- modules/nf-core/argnorm/environment.yml
- modules/nf-core/argnorm/main.nf
- modules/nf-core/argnorm/tests/argnorm_hamronized.config
- modules/nf-core/argnorm/tests/main.nf.test
- modules/nf-core/argnorm/tests/main.nf.test.snap
Removes dedicated harmnization tests as it is a dedicated subcommand not a flag now 
- For modules:
> Bump versiuon ARGNORM and add native --version flag

- subworkflows/nf-core/fasta_index_bismark_bwameth/main.nf
- subworkflows/nf-core/fasta_index_bismark_bwameth/tests/main.nf.test
- subworkflows/nf-core/fasta_index_bismark_bwameth/tests/main.nf.test.snap
> fasta_index scope for run_picard_collecthsmetrics

- modules/nf-core/hifiasm/main.nf
- modules/nf-core/hifiasm/tests/main.nf.test.snap
> fix hifiasm stub

- modules/nf-core/fgbio/copyumifromreadname/environment.yml
- modules/nf-core/fgbio/copyumifromreadname/main.nf
- modules/nf-core/fgbio/copyumifromreadname/meta.yml
- modules/nf-core/fgbio/copyumifromreadname/tests/main.nf.test
- modules/nf-core/fgbio/copyumifromreadname/tests/main.nf.test.snap
- modules/nf-core/fgbio/copyumifromreadname/tests/nextflow.config
Add the fgbio subtool CopyUmiFromReadName
> Add fgbio/copyumifromreadname

- modules/nf-core/variancepartition/dream/templates/dream.R
> feat: improve handling of nulls in module

- modules/nf-core/minimap2/align/environment.yml
- modules/nf-core/minimap2/align/main.nf
- modules/nf-core/minimap2/align/tests/main.nf.test.snap
- modules/nf-core/minimap2/index/environment.yml
- modules/nf-core/minimap2/index/main.nf
- modules/nf-core/minimap2/index/tests/main.nf.test.snap
- modules/nf-core/paraphase/environment.yml
- modules/nf-core/paraphase/main.nf
- modules/nf-core/paraphase/tests/main.nf.test.snap
> Bump minimap2 to 2.29

- modules/nf-core/trgt/genotype/environment.yml
- modules/nf-core/trgt/genotype/main.nf
- modules/nf-core/trgt/genotype/tests/main.nf.test.snap
- modules/nf-core/trgt/merge/environment.yml
- modules/nf-core/trgt/merge/main.nf
- modules/nf-core/trgt/merge/tests/main.nf.test.snap
- modules/nf-core/trgt/plot/environment.yml
- modules/nf-core/trgt/plot/main.nf
- modules/nf-core/trgt/plot/tests/main.nf.test.snap
> Bump TRGT to 2.1.0

- modules/nf-core/amulety/antiberty/environment.yml
- modules/nf-core/amulety/antiberty/main.nf
- modules/nf-core/amulety/antiberty/meta.yml
- modules/nf-core/amulety/antiberty/tests/gpu.nf.test.snap
- modules/nf-core/amulety/antiberty/tests/main.nf.test.snap
- bump amulety version
- update snaps
Closes #XXX 
- For modules:
> Bump versions amulety antiberty

- modules/nf-core/picard/collectinsertsizemetrics/main.nf
> Deduplicate args in picard/collectinsertsizemetrics

- modules/nf-core/amulety/balmpaired/environment.yml
- modules/nf-core/amulety/balmpaired/main.nf
- modules/nf-core/amulety/balmpaired/meta.yml
- modules/nf-core/amulety/balmpaired/tests/gpu.nf.test
- modules/nf-core/amulety/balmpaired/tests/gpu.nf.test.snap
- modules/nf-core/amulety/balmpaired/tests/main.nf.test
- modules/nf-core/amulety/balmpaired/tests/main.nf.test.snap
- modules/nf-core/amulety/balmpaired/tests/nextflow.config
- add balmpaired
- add snapshot
Closes #XXX 
- For modules:
> Add module amulety/balmpaired

- subworkflows/nf-core/fastq_align_dedup_bwameth/main.nf
- subworkflows/nf-core/fastq_align_dedup_bwameth/meta.yml
- subworkflows/nf-core/fastq_align_dedup_bwameth/tests/gpu.nf.test
- subworkflows/nf-core/fastq_align_dedup_bwameth/tests/main.nf.test
…/workflow parameters
Closes #XXX 
- For modules:
> Replaced params.use_gpu with a workflow variable 

- modules/nf-core/trust4/main.nf
- modules/nf-core/trust4/meta.yml
- modules/nf-core/trust4/tests/main.nf.test
> add barcodewhitelist option

- modules/nf-core/mapad/index/environment.yml
- modules/nf-core/mapad/index/main.nf
- modules/nf-core/mapad/index/tests/main.nf.test.snap
- modules/nf-core/mapad/map/environment.yml
- modules/nf-core/mapad/map/main.nf
- modules/nf-core/mapad/map/tests/main.nf.test.snap
- subworkflows/nf-core/fastq_align_mapad/tests/main.nf.test.snap
Bump mapAD version from `v0.44.1` to `v0.45.0`
> Update mapAD to v0.45.0

- modules/nf-core/trust4/environment.yml
- modules/nf-core/trust4/main.nf
- modules/nf-core/trust4/meta.yml
- modules/nf-core/trust4/tests/main.nf.test
- modules/nf-core/trust4/tests/main.nf.test.snap
- simplify trust4 bump version
- update meta and tests
Closes #XXX 
- For modules:
> Bump and fix trust4

- modules/nf-core/tesorter/environment.yml
- modules/nf-core/tesorter/main.nf
- modules/nf-core/tesorter/meta.yml
- modules/nf-core/tesorter/tests/main.nf.test
- modules/nf-core/tesorter/tests/main.nf.test.snap
- modules/nf-core/tesorter/tests/nextflow.config
> Added tesorter

- modules/nf-core/gatk4/markduplicates/environment.yml
- modules/nf-core/gatk4/markduplicates/main.nf
- modules/nf-core/gatk4/markduplicates/tests/main.nf.test.snap
- modules/nf-core/gatk4/unmarkduplicates/environment.yml
- modules/nf-core/gatk4/unmarkduplicates/main.nf
- modules/nf-core/gatk4/unmarkduplicates/tests/main.nf.test.snap
> gatk4 leftovers from 6917

- modules/nf-core/verifybamid/verifybamid2/main.nf
- modules/nf-core/verifybamid/verifybamid2/tests/main.nf.test
- modules/nf-core/verifybamid/verifybamid2/tests/main.nf.test.snap
> add stubs for verifybamid2

- modules/nf-core/gatk4/intervallisttobed/main.nf
- modules/nf-core/gatk4/intervallisttobed/meta.yml
>  gatk4 leftovers from 8401 

- modules/nf-core/s4pred/runmodel/main.nf
- modules/nf-core/s4pred/runmodel/tests/main.nf.test.snap
> removed buggy def from prefix

- modules/nf-core/ngsbits/bedcoverage/environment.yml
- modules/nf-core/ngsbits/bedcoverage/main.nf
- modules/nf-core/ngsbits/bedcoverage/meta.yml
- modules/nf-core/ngsbits/bedcoverage/tests/main.nf.test
- modules/nf-core/ngsbits/bedcoverage/tests/main.nf.test.snap
- modules/nf-core/ngsbits/bedcoverage/tests/nextflow.config
> new module ngsbits/bedcoverage

- modules/nf-core/ngsbits/bedannotategc/environment.yml
- modules/nf-core/ngsbits/bedannotategc/main.nf
- modules/nf-core/ngsbits/bedannotategc/meta.yml
- modules/nf-core/ngsbits/bedannotategc/tests/main.nf.test
- modules/nf-core/ngsbits/bedannotategc/tests/main.nf.test.snap
- modules/nf-core/ngsbits/bedannotategc/tests/nextflow.config
> new module: ngsbits/bedannotategc

- modules/nf-core/openms/decoydatabase/environment.yml
- modules/nf-core/openms/decoydatabase/main.nf
- modules/nf-core/openms/decoydatabase/tests/main.nf.test.snap
- modules/nf-core/openms/filefilter/environment.yml
- modules/nf-core/openms/filefilter/main.nf
- modules/nf-core/openms/filefilter/tests/main.nf.test.snap
- modules/nf-core/openms/idfilter/environment.yml
- modules/nf-core/openms/idfilter/main.nf
- modules/nf-core/openms/idfilter/tests/main.nf.test.snap
- modules/nf-core/openms/idmassaccuracy/environment.yml
- modules/nf-core/openms/idmassaccuracy/main.nf
- modules/nf-core/openms/idmassaccuracy/tests/main.nf.test.snap
- modules/nf-core/openms/idmerger/environment.yml
- modules/nf-core/openms/idmerger/main.nf
- modules/nf-core/openms/idmerger/tests/main.nf.test.snap
- modules/nf-core/openms/idripper/environment.yml
- modules/nf-core/openms/idripper/main.nf
- modules/nf-core/openms/idripper/tests/main.nf.test.snap
- modules/nf-core/openms/idscoreswitcher/environment.yml
- modules/nf-core/openms/idscoreswitcher/main.nf
- modules/nf-core/openms/idscoreswitcher/tests/main.nf.test.snap
- modules/nf-core/openms/peakpickerhires/environment.yml
- modules/nf-core/openms/peakpickerhires/main.nf
- modules/nf-core/openms/peakpickerhires/tests/main.nf.test.snap
- modules/nf-core/openms/peptideindexer/environment.yml
- modules/nf-core/openms/peptideindexer/main.nf
- modules/nf-core/openms/peptideindexer/tests/main.nf.test.snap
- modules/nf-core/openmsthirdparty/cometadapter/environment.yml
- modules/nf-core/openmsthirdparty/cometadapter/main.nf
- modules/nf-core/openmsthirdparty/cometadapter/tests/main.nf.test.snap
> Bump OpenMS version, update snapshots

- modules/nf-core/rtn/tni/environment.yml
- modules/nf-core/rtn/tni/main.nf
> Update RTN version and use Seqera Containers

- modules/nf-core/samtools/collatefastq/meta.yml
> fix samtools collatefastq meta

- modules/nf-core/fcs/fcsadaptor/environment.yml
- modules/nf-core/fcs/fcsadaptor/main.nf
- modules/nf-core/fcs/fcsadaptor/meta.yml
- modules/nf-core/fcs/fcsadaptor/tests/main.nf.test.snap
> Sanitized fasta before passing to av_screen to avoid permanentFail

- modules/nf-core/stranger/environment.yml
- modules/nf-core/stranger/main.nf
- modules/nf-core/stranger/meta.yml
- modules/nf-core/stranger/tests/main.nf.test.snap
> Bgzip and tabix stranger

- .github/actions/nf-test-action/action.yml
Succesfully tested in https://github.com/nf-core/modules/actions/runs/15136298389/job/42563714600?pr=8515#step:6:1046
> revert manual pdiff install

- modules/nf-core/shinyngs/staticexploratory/main.nf
- modules/nf-core/shinyngs/staticexploratory/meta.yml
- modules/nf-core/shinyngs/staticexploratory/tests/main.nf.test
I wrote this module before I knew any better and used `meta.id` as the input for a contrast variable in this module, clearly very silly, though it might have been before the current standard of non-file mandatory arguments being passed via channels.
Anywho, move that input to an actual channel.
Closes #XXX 
- For modules:
> Don't use meta.id as contrast var

- modules/nf-core/parabricks/fq2bammeth/main.nf
> Fixed an issue where fq2bammeth failed on aws batch

- modules/nf-core/abricate/run/main.nf
> More permissive ABRICATE_RUN file symlinking

- modules/nf-core/sortmerna/main.nf
After https://github.com/conda-forge/sortmerna-feedstock/pull/3, I build new images to pull in the good build.
Used a Wave command like:
```
wave \                                                                                                  
--conda-package conda-forge::sortmerna=4.3.7=py313h71a826f_1 \
--platform linux/amd64 \
--freeze --await --singularity
```
Seqera containers web UI couldn't be used because you can't specify build (it just cached the old one).
Closes #XXX 
- For modules:
> pull in good conda build for sortmerna

- modules/nf-core/metacache/build/environment.yml
- modules/nf-core/metacache/build/main.nf
- modules/nf-core/metacache/build/meta.yml
- modules/nf-core/metacache/build/tests/main.nf.test
- modules/nf-core/metacache/build/tests/main.nf.test.snap
> New module metacache/build

- modules/nf-core/samtools/idxstats/main.nf
Closes #XXX 
Samtools/idxstats has the label `process_single` which means it's assigned 1 cpu. However the code block uses `${task.cpus-1}` meaning it assigns 0 threads to the process.
- For modules:
> Update samtools idxstats thread count

- modules/nf-core/fusioncatcher/fusioncatcher/main.nf
> update memory definition

- modules/nf-core/bwa/sampe/meta.yml
- modules/nf-core/bwa/samse/meta.yml
Replaced two meta.yml files in the modules bwa/sampe and bwa/sampe which make linting fail, fixed with prettier
Closes #XXX 
- For modules:
> Fix prettier sampe samse meta.yml

- modules/nf-core/diamond/blastp/environment.yml
- modules/nf-core/diamond/blastp/main.nf
- modules/nf-core/diamond/blastp/tests/main.nf.test.snap
- modules/nf-core/diamond/blastx/environment.yml
- modules/nf-core/diamond/blastx/main.nf
- modules/nf-core/diamond/blastx/tests/main.nf.test.snap
- modules/nf-core/diamond/cluster/environment.yml
- modules/nf-core/diamond/cluster/main.nf
- modules/nf-core/diamond/cluster/tests/main.nf.test.snap
- modules/nf-core/diamond/makedb/environment.yml
- modules/nf-core/diamond/makedb/main.nf
- modules/nf-core/diamond/makedb/tests/main.nf.test.snap
> Bump DIAMOND versions

- modules/nf-core/mgikit/demultiplex/environment.yml
- modules/nf-core/mgikit/demultiplex/main.nf
- modules/nf-core/mgikit/demultiplex/tests/main.nf.test.snap
Update mgikit version to 2.0.0
- For modules:
> Update mgikit version

- modules/nf-core/trust4/main.nf
- modules/nf-core/trust4/meta.yml
- modules/nf-core/trust4/tests/main.nf.test
> read_format should be an input

- modules/nf-core/vclust/prefilter/environment.yml
- modules/nf-core/vclust/prefilter/main.nf
- modules/nf-core/vclust/prefilter/meta.yml
- modules/nf-core/vclust/prefilter/tests/main.nf.test
- modules/nf-core/vclust/prefilter/tests/main.nf.test.snap
> New Module: vclust/prefilter

- modules/nf-core/checkv/downloaddatabase/environment.yml
- modules/nf-core/checkv/downloaddatabase/main.nf
- modules/nf-core/checkv/downloaddatabase/tests/main.nf.test.snap
- modules/nf-core/checkv/endtoend/environment.yml
- modules/nf-core/checkv/endtoend/main.nf
- modules/nf-core/checkv/endtoend/tests/main.nf.test.snap
- modules/nf-core/checkv/updatedatabase/environment.yml
- modules/nf-core/checkv/updatedatabase/main.nf
- modules/nf-core/checkv/updatedatabase/tests/main.nf.test.snap
> Checkv version bump

- modules/nf-core/perbase/main.nf
- modules/nf-core/perbase/meta.yml
- modules/nf-core/perbase/tests/main.nf.test
- modules/nf-core/perbase/tests/main.nf.test.snap
> updated module:perbase to include (optional) bed file to analyse only regions of interest

- modules/nf-core/hostile/clean/environment.yml
- modules/nf-core/hostile/clean/main.nf
- modules/nf-core/hostile/clean/meta.yml
- modules/nf-core/hostile/clean/tests/main.nf.test
- modules/nf-core/hostile/clean/tests/main.nf.test.snap
- modules/nf-core/hostile/fetch/environment.yml
- modules/nf-core/hostile/fetch/main.nf
- modules/nf-core/hostile/fetch/meta.yml
- modules/nf-core/hostile/fetch/tests/main.nf.test
- modules/nf-core/hostile/fetch/tests/main.nf.test.snap
- modules/nf-core/hostile/fetch/tests/nextflow.config
Bump hostile version to v2.0.1 in hostile modules
Closes #XXX 
- For modules:
> Update hostile modules

- modules/nf-core/stare/environment.yml
- modules/nf-core/stare/main.nf
- modules/nf-core/stare/meta.yml
- modules/nf-core/stare/tests/main.nf.test
- modules/nf-core/stare/tests/main.nf.test.snap
Transferring module from: https://github.com/nf-core/tfactivity/tree/dev/modules/local/stare
Closes #XXX 
- For modules:
> Add module: STARE

- modules/nf-core/nail/search/environment.yml
- modules/nf-core/nail/search/main.nf
- modules/nf-core/nail/search/tests/main.nf.test.snap
> version-bump

- modules/nf-core/cellpose/main.nf
- modules/nf-core/cellpose/tests/main.nf.test.snap
Simple PR to upgrade container version for Cellpose from 3.0.1 to 3.1.0.
> Update Cellpose to 3.1.0

- modules/nf-core/tabix/bgzip/environment.yml
- modules/nf-core/tabix/bgziptabix/environment.yml
- modules/nf-core/tabix/tabix/environment.yml
Tabix and BGzip binaries are now part of the HTSlib project. And tabix-1.11 in Bioconda doesn't contain anything.
We can keep dependencies: bioconda::htslib=1.21 only (remove the tabix-1.11) to avoid potential errors in setting up local dependencies?
> Update module/tabix environment.yml

- modules/nf-core/seqtk/sample/meta.yml
- modules/nf-core/seqtk/sample/tests/main.nf.test
- modules/nf-core/seqtk/sample/tests/main.nf.test.snap
Currently only sampling for a defined number of reads is enabled for this module. This PR enables relative sampling that is built-in to `seqtk sample` where you can specify a fraction (<1.0) of your fastq to keep. 
Closes #XXX 
- For modules:
> seqtk sample - enable fractional sampling

- modules/nf-core/fusionreport/download/environment.yml
> prettier for fusionreport

- modules/nf-core/rbt/vcfsplit/environment.yml
- modules/nf-core/rbt/vcfsplit/main.nf
- modules/nf-core/rbt/vcfsplit/meta.yml
- modules/nf-core/rbt/vcfsplit/tests/main.nf.test
- modules/nf-core/rbt/vcfsplit/tests/main.nf.test.snap
> Add new module rbt/vcfsplit

- .gitignore
- modules/nf-core/cellranger/multi/main.nf
- modules/nf-core/cellranger/multi/meta.yml
- modules/nf-core/cellranger/multi/templates/cellranger_multi.py
- modules/nf-core/cellranger/multi/tests/main.nf.test
> Include ocm barcoding handler in cellranger/multi module

- modules/nf-core/varscan/somatic/environment.yml
- modules/nf-core/varscan/somatic/main.nf
- modules/nf-core/varscan/somatic/meta.yml
- modules/nf-core/varscan/somatic/tests/main.nf.test
- modules/nf-core/varscan/somatic/tests/main.nf.test.snap
- modules/nf-core/varscan/somatic/tests/nextflow.config
I have added new variant calling tool Varscan with subtool somatic.
Closes #8713 
- For modules:
> Add new module varscan/somatic

- modules/nf-core/gprofiler2/gost/main.nf
- modules/nf-core/gprofiler2/gost/templates/gprofiler2_gost.R
- modules/nf-core/gprofiler2/gost/tests/main.nf.test
- modules/nf-core/gprofiler2/gost/tests/main.nf.test.snap
- subworkflows/nf-core/differential_functional_enrichment/tests/main.nf.test.snap
This PR fixes a bug where sources were split twice, which led to Gprofiler not filtering properly by sources.
It includes modifications to the versions.yml to keep the data version of the file stored in versions.yml (since the data version changes continuously)
It modifies the snapshot accordingly
It also adds a completely new test to makes sure that sources works as expected.
Closes #8701 
- For modules:
> Gprofiler sources fixes

- modules/nf-core/varscan/processsomatic/environment.yml
- modules/nf-core/varscan/processsomatic/main.nf
- modules/nf-core/varscan/processsomatic/meta.yml
- modules/nf-core/varscan/processsomatic/tests/main.nf.test
- modules/nf-core/varscan/processsomatic/tests/main.nf.test.snap
- modules/nf-core/varscan/processsomatic/tests/nextflow.config
I have added new variant calling tool Varscan with subtool processSomatic.
Closes #8713  
- For modules:
> Add new module varscan/processsomatic

- modules/nf-core/clipkit/meta.yml
> clipkit keywords

- modules/nf-core/varscan/fpfilter/environment.yml
- modules/nf-core/varscan/fpfilter/main.nf
- modules/nf-core/varscan/fpfilter/meta.yml
- modules/nf-core/varscan/fpfilter/tests/main.nf.test
- modules/nf-core/varscan/fpfilter/tests/main.nf.test.snap
- modules/nf-core/varscan/fpfilter/tests/nextflow.config
I have added new variant calling tool Varscan with subtool fpfilter.
Closes #8713  
- For modules:
> Add new module varscan/fpfilter

- modules/nf-core/perbase/environment.yml
- modules/nf-core/perbase/main.nf
- modules/nf-core/perbase/meta.yml
- modules/nf-core/perbase/tests/main.nf.test.snap
Closes #8853 by bumping perbase version to 1.0.0  
- For modules:
> update module: PERBASE

- modules/nf-core/multiqc/main.nf
> bump mqc build version

- modules/nf-core/cnvkit/access/main.nf
- modules/nf-core/cnvkit/antitarget/main.nf
- modules/nf-core/cnvkit/batch/environment.yml
- modules/nf-core/cnvkit/batch/main.nf
- modules/nf-core/cnvkit/batch/tests/main.nf.test
- modules/nf-core/cnvkit/batch/tests/main.nf.test.snap
- modules/nf-core/cnvkit/call/main.nf
- modules/nf-core/cnvkit/export/main.nf
- modules/nf-core/cnvkit/export/tests/main.nf.test.snap
- modules/nf-core/cnvkit/genemetrics/main.nf
- modules/nf-core/cnvkit/reference/main.nf
- modules/nf-core/cnvkit/target/main.nf
> cnvkit: nextflow lint + minor polish + update of cnvkit/batch

- modules/nf-core/gatk4spark/applybqsr/main.nf
- modules/nf-core/gatk4spark/applybqsr/meta.yml
- modules/nf-core/gatk4spark/applybqsr/tests/main.nf.test
- modules/nf-core/gatk4spark/applybqsr/tests/main.nf.test.snap
- modules/nf-core/gatk4spark/applybqsr/tests/nextflow_bam.config
- modules/nf-core/gatk4spark/applybqsr/tests/nextflow_cram.config
Following #8461
Closes #XXX 
- For modules:
> fix gatkspark/applybqsr

- .pre-commit-config.yaml
- modules/nf-core/coverm/contig/meta.yml
- modules/nf-core/coverm/genome/environment.yml
- modules/nf-core/coverm/genome/main.nf
- modules/nf-core/coverm/genome/meta.yml
- modules/nf-core/coverm/genome/tests/main.nf.test
- modules/nf-core/coverm/genome/tests/main.nf.test.snap
- modules/nf-core/coverm/genome/tests/nextflow.config
Work towards nf-core/mag#587. Based off of #6959. 
- For modules:
> Add coverm/genome

- modules/nf-core/ngscheckmate/ncm/main.nf
> lint + code polish ngscheckmate/ncm

- .github/workflows/update-sentieon-snapshot.yml
Continuing on:
- https://github.com/nf-core/modules/pull/8928
- https://github.com/nf-core/modules/pull/8929
Closes #XXX 
- For modules:
> add secrets

- subworkflows/nf-core/mmseqs_fasta_cluster/meta.yml
prettier fix that escaped linting
- For modules:
> small push

- modules/nf-core/dupradar/environment.yml
- modules/nf-core/dupradar/main.nf
- modules/nf-core/dupradar/tests/main.nf.test
- modules/nf-core/dupradar/tests/main.nf.test.snap
> Bump dupRadar version

- modules/nf-core/hasheddrops/main.nf
- modules/nf-core/hasheddrops/meta.yml
- modules/nf-core/hasheddrops/templates/HashedDrops.R
- modules/nf-core/hasheddrops/tests/main.nf.test.snap
add `*_id_to_hash.csv` as output
> Add another csv file as output

- modules/nf-core/nanoplot/environment.yml
- modules/nf-core/nanoplot/main.nf
- modules/nf-core/nanoplot/meta.yml
- modules/nf-core/nanoplot/tests/main.nf.test
- modules/nf-core/nanoplot/tests/main.nf.test.snap
Closes #8831  
- For modules:
This PR updates the nanoplot module version. The test validation has been updated to check for log file existence instead of specific content, as the new version generates empty log files.
> Update nanoplot to 1.46.1

- modules/nf-core/modkit/bedmethyltobigwig/environment.yml
- modules/nf-core/modkit/bedmethyltobigwig/main.nf
- modules/nf-core/modkit/bedmethyltobigwig/meta.yml
- modules/nf-core/modkit/bedmethyltobigwig/tests/main.nf.test
- modules/nf-core/modkit/bedmethyltobigwig/tests/main.nf.test.snap
- modules/nf-core/modkit/bedmethyltobigwig/tests/tags.yml
> New module: modkit/bedmethyltobigwig

- modules/nf-core/abra2/environment.yml
- modules/nf-core/abra2/main.nf
- modules/nf-core/abra2/meta.yml
- modules/nf-core/abra2/tests/main.nf.test
- modules/nf-core/abra2/tests/main.nf.test.snap
- modules/nf-core/abra2/tests/nextflow.config
Adds new module for [Abra2](https://github.com/mozack/abra2)
To do:
Closes #2186
- For modules:
> module: Abra2 for INDEL realignment

- modules/nf-core/abra2/main.nf
- modules/nf-core/abra2/tests/main.nf.test
- modules/nf-core/abra2/tests/main.nf.test.snap
stub was broken and regular was capturing null on docker
following:
- https://github.com/nf-core/modules/pull/8986
Closes #XXX 
- For modules:
> Fix abra2 versions snapshot

- modules/nf-core/bcftools/annotate/main.nf
- modules/nf-core/bcftools/annotate/meta.yml
- modules/nf-core/bcftools/annotate/tests/main.nf.test
- modules/nf-core/bcftools/annotate/tests/main.nf.test.snap
> Add --columns-file argument to bcftools annotate

- modules/nf-core/picard/collecthsmetrics/main.nf
> Remove unnecessary spaces from `picard` module

- modules/nf-core/pear/main.nf
- modules/nf-core/pear/tests/main.nf.test
- modules/nf-core/pear/tests/main.nf.test.snap
> add stub to pear

- modules/nf-core/tinc/meta.yml
- modules/nf-core/tinc/templates/main_script.R
Update module `tinc` with:
- add description of the module in `meta.yml`
- add a new line of code in the main script, to filter out some mutations
- add explicit package call for Packages in the main script
- For modules:
> Update module tinc

- subworkflows/nf-core/differential_functional_enrichment/meta.yml
> Fix: fix meta.yml file

- modules/nf-core/metamdbg/asm/environment.yml
- modules/nf-core/metamdbg/asm/main.nf
- modules/nf-core/metamdbg/asm/tests/main.nf.test.snap
> Bump metamdbg version

- modules/nf-core/gtdbtk/classifywf/environment.yml
- modules/nf-core/gtdbtk/classifywf/main.nf
- modules/nf-core/gtdbtk/classifywf/meta.yml
- modules/nf-core/gtdbtk/classifywf/tests/main.nf.test.snap
- modules/nf-core/gtdbtk/gtdbtoncbimajorityvote/environment.yml
- modules/nf-core/gtdbtk/gtdbtoncbimajorityvote/main.nf
Fixes issue with Conda pulling in incompatible version of Numpy.
Closes #XXX 
- For modules:
> Bump GTDB-Tk to v2.5.2

- modules/nf-core/beagle5/beagle/environment.yml
- modules/nf-core/beagle5/beagle/main.nf
- modules/nf-core/beagle5/beagle/meta.yml
- modules/nf-core/beagle5/beagle/tests/main.nf.test.snap
> Update to Beagle 5.5

- modules/nf-core/rastair/mbias_parser/environment.yml
- modules/nf-core/rastair/methylkit/environment.yml
- modules/nf-core/rastair/methylkit/main.nf
- modules/nf-core/rastair/methylkit/meta.yml
- modules/nf-core/rastair/methylkit/tests/main.nf.test
- subworkflows/nf-core/bam_taps_conversion/main.nf
- subworkflows/nf-core/bam_taps_conversion/meta.yml
- subworkflows/nf-core/bam_taps_conversion/tests/main.nf.test
- subworkflows/nf-core/bam_taps_conversion/tests/main.nf.test.snap
This PR adds a subworkflow called 'bam_taps_conversion' to assess DNA methylation for bam files from samples generated using TAPS protocol.
Closes #XXX 
- For modules:
> Added bam_taps_conversion subworkflow

- modules/nf-core/metaeuk/easypredict/main.nf
- modules/nf-core/metaeuk/easypredict/tests/main.nf.test.snap
Hopefully this doesn't require snapshot updates...
Closes #XXX 
- For modules:
> fix(metaeuk/easypredict): add threads argument to command

- subworkflows/nf-core/faa_seqfu_seqkit/main.nf
- subworkflows/nf-core/faa_seqfu_seqkit/meta.yml
- subworkflows/nf-core/faa_seqfu_seqkit/tests/main.nf.test
- subworkflows/nf-core/faa_seqfu_seqkit/tests/main.nf.test.snap
- subworkflows/nf-core/faa_seqfu_seqkit/tests/nextflow.config
Produces statistics of the input sequences, re-formats (i.e., to upper case, removing gaps) and validates them, filters by user-defined min and max length thresholds (defaults [30, 5000]), removes duplicate sequences by name, and finally produces another QC statistics report after pre-processing.
- For modules:
> New nf-core subworkflow - faa seqfu seqkit

- modules/nf-core/csvtk/sort/environment.yml
- modules/nf-core/csvtk/sort/main.nf
- modules/nf-core/csvtk/sort/meta.yml
- modules/nf-core/csvtk/sort/tests/main.nf.test
- modules/nf-core/csvtk/sort/tests/main.nf.test.snap
> Add module csvtk/sort

- modules/meta-schema.json
Keywords in the meta.yml file must be unique and can't contain the keyword "example".
Close https://github.com/nf-core/tools/issues/3690
> Add validation of meta.yml keywords
